In [1]:
##
# Measure clustering effect 
# - final function-loop version for the book
#

import pandas as pd
import numpy as np
import scipy as sp
import sklearn
import importlib
import databox as db
import joblib
from hashlib import md5
# import sample_group_stats as sgst
from sklearn.mixture import BayesianGaussianMixture
from sklearn.decomposition import FastICA
import extools as ex
import scipy.stats as st
import scipy.special as sp

OK -- read the ontology db (19571, 4)
Restored 303734 tags and 191240 tokens. Run update_corpus_tagdata() to update.
-- loaded the skipgram model tank/fasttext_8.model --

Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

In [2]:
ica_data_df = pd.read_parquet("data/q_sep/CE-ICA_data_8-dim.pq")

tf_df = pd.read_parquet("data/q_sep/token_features.pq")

ica8 = joblib.load("data/q_sep/CE-ICA_transformer_w_8-dim.pkl")

In [56]:
print("=========================")


feat_freq_df = pd.DataFrame(tf_df.reset_index().drop_duplicates().\
                            groupby(['category','arcpath']).lemma.value_counts())
feat_freq_df = feat_freq_df[feat_freq_df['count']>1].copy()
print("feat_freq_df.shape", feat_freq_df.shape)

print("=========================")


feat_idx = feat_freq_df.index.droplevel(0).unique()

# feat_idx is the n>1 features in the data set, that we evaluate

print("feat_idx: the set of features in the data to evaluate")
print(len(feat_idx))

print("=========================")

feat_vectors =\
  [ex.compute_feat_vec(arcpath,lemma,ica8).round(3) for (arcpath,lemma) in feat_idx]
feat_vectors_df = pd.DataFrame(feat_vectors,dtype=np.float16,index=feat_idx)

print("feat_vectors_df.shape",feat_vectors_df.shape)
feat_tokens = tf_df[['arcpath','lemma']].reset_index()[['token','arcpath','lemma']].\
  drop_duplicates().set_index(['arcpath','lemma'])

print("=========================")

print("check counts: feat_freq_df.groupby('category')")
print([df.sort_values('count').tail() for g,df in feat_freq_df.groupby('category')])

print("=========================")

tf_df = tf_df[(tf_df.reset_index().set_index(['category','arcpath','lemma']).index.isin(feat_freq_df.index))]
tf_df=tf_df[['arcpath','lemma']]
tf_df.head(5)

=========================
feat_freq_df.shape (56151, 1)
=========================
feat_idx: the set of features in the data to evaluate
45214
=========================
feat_vectors_df.shape (45214, 8)
=========================
check counts: feat_freq_df.groupby('category')
[                             count
category   arcpath    lemma
adaptation conj>cc>   and      204
           nmod>case> of       207
           det>       the      222
           case>      of       232
           cop>       be       430,                               count
category arcpath       lemma
location compound<det> the      177
         conj>cc>      and      194
         amod<         bear     304
         case>         in       311
         det>          the      404,                             count
category   arcpath   lemma
taxongroup cc>       and      476
           amod>     other    490
           nmod<det> the      494
           case>     of      1219
           det>      the     1533,                               count
category arcpath       lemma
topic    conj<conj>cc> and     2809
         cc>           and     2904
         conj>cc>      and     3002
         case>         of      4186
         det>          the     7045]
=========================

                                                 arcpath lemma
category   token                    widx
adaptation Aar-5e58_102_predators-8 5               obl<  warn
                                    6           obl<obj>    it
                                    7              case>    of
                                    22    appos>conj>cc>   and
           Aar-5e58_110_nocturnal-4 1         nsubj>det>   the

In [45]:
import joblib
import os

n_clust = 10

def get_BGMM(my_cat : str):
    

    my_ica_data = ica_data_df.loc[my_cat]
    
    bgm_pkl_fname = os.path.join('data/q_cluster','BGM_full_covar_'+my_cat+'.pkl')
    print("checking for %s" % bgm_pkl_fname)
    if os.path.exists(bgm_pkl_fname):
        bgm = joblib.load(bgm_pkl_fname)
        print("BGM loaded")
        # print(str(bgm.__dict__))
    else:
    
        bgm = BayesianGaussianMixture(n_components=n_clust,tol=0.001,max_iter=500,
                                              random_state=42,
                                              covariance_type='full')
        bgm.fit(my_ica_data)
        
        joblib.dump(bgm,bgm_pkl_fname)
        print("BGM saved: %s" % bgm_pkl_fname)
        
    return bgm

In [46]:
bgm_ada = get_BGMM('adaptation')

checking for data/q_cluster/BGM_full_covar_adaptation.pkl
BGM loaded

In [317]:
def analyze_category(my_cat, int_struct = False, debug = False):
    # my_cat = 'location'
    # how many picks from each cluster
    global bgm, my_ica_data   
  
    result = {}
    my_tfs = tf_df.loc[my_cat]
    my_ica_data = ica_data_df.loc[my_cat]
    
    bgm = get_BGMM(my_cat)
    
    
    # check fit
    
    print("bgm.predict(my_ica_data)).value_counts()")
    print(pd.Series(bgm.predict(my_ica_data)).value_counts())
    
    my_clust = pd.DataFrame({'cluster':bgm.predict(my_ica_data)},index=my_ica_data.index)
    feat_bag = my_tfs.reset_index()[['arcpath','lemma','token']]
    clust_feats = my_clust.merge(feat_bag,left_index=True,right_on='token').drop_duplicates().groupby(['cluster','arcpath']).lemma.value_counts()

    clust_feats = pd.DataFrame(clust_feats).reset_index().rename(columns={'count':'freq'}).\
        sort_values('freq',ascending=False).set_index(['arcpath','lemma'])
    
    print("clust_feats",clust_feats.shape)
    print(clust_feats.head())
    
    print("=========================")
    
    
    clust_f_df = clust_feats.pivot(columns='cluster').fillna(0).astype(int)
    print("clust_f_df pivot table",clust_f_df.shape)
    
    clust_p_df = pd.DataFrame(np.array(clust_f_df) / (np.array(clust_f_df).sum(axis=0)),index=clust_f_df.index)
    print("clust_p_df is the probability distribution cluster-wise")
    print(clust_p_df.head(5))
    print("=========================")


    print("Elementwise relative entropy by clusters, feature-wise")

    clust_q = clust_p_df.sum(axis=1)
    clust_q /= clust_q.sum()
    clust_el_kldiv = pd.concat([sp.rel_entr(clust_p_df[c],clust_q) for c in clust_p_df.columns],axis=1)
    
    print(clust_el_kldiv.loc[clust_q.sort_values(ascending=False).index[0:5]])
    
    
    print("========== clust_featdx_df ===============")


    clust_featdx_df = pd.concat([pd.DataFrame(clust_el_kldiv[c].sort_values(ascending=False))\
                           .assign(cluster=c).rename(columns={c:'Dx'})
                             for c in clust_el_kldiv.columns]).reset_index().\
                            set_index(['cluster','arcpath','lemma'])


    clust_featdx_df = clust_featdx_df.merge(clust_feats.reset_index().set_index(['cluster','arcpath','lemma'])\
                                .rename(columns={'freq':'N'}),left_index=True,right_index=True)


    clust_featdx_df_short = clust_featdx_df.groupby('cluster').head(5) # table sketch for the book
    print(clust_featdx_df_short.sample(5))
    result['clust_featdx_df_short']=clust_featdx_df_short
    result['clust_featdx_df']=clust_featdx_df

    print("=========================")

    print("pred_feats")
    
    global pred_feats
    
    feats100 = feat_freq_df.loc[my_cat].sort_values('count').tail(100).index    
    
    pred_feats = clust_featdx_df.reset_index().set_index(['arcpath','lemma']).index.unique()
    pred_feats  = pred_feats[pred_feats.isin(feat_idx)].copy()    
    pred_feats_c = pred_feats[pred_feats.isin(feats100)].copy()        
    pred_feats_all = pred_feats
    
    pred_feats = pred_feats_c # cluster prediction
    
    feat_v = feat_vectors_df.loc[pred_feats].sort_index()

    print("feat_v")
    print(feat_v.round(3).head(5))

    mean_norm = (bgm.means_.T/np.sqrt((bgm.means_**2).sum(axis=1))).T.round(2)
    print("mean_norm")
    print(mean_norm)

    cos_predict = pd.DataFrame(np.inner(mean_norm,np.array(feat_v)).T,index=pred_feats)
    print("cos_predict.head(5)")
    print(cos_predict.head(5))
    
    score_predict = pd.DataFrame(bgm.predict_proba(feat_v).round(3),index=pred_feats)
    print("score_predict.head(5)")
    print(score_predict.head(5))

    prob_sheet = clust_p_df.loc[pred_feats]
    print(prob_sheet.head(5))

    cos_pred_stats   = [st.spearmanr(prob_sheet.loc[i],cos_predict.loc[i])   for i in pred_feats]
    score_pred_stats = [st.spearmanr(prob_sheet.loc[i],score_predict.loc[i]) for i in pred_feats]
    
    df = pd.concat([pd.DataFrame(cos_pred_stats,index=pred_feats),
              pd.DataFrame(score_pred_stats,index=pred_feats)],axis=1)
    df.columns=['cos_stat','cos_pvalue','score_stat','score_pvalue']
    
    result["cos_pvalue"]=df.sort_values('cos_pvalue')
    result["score_pvalue"]=df.sort_values('score_pvalue')
    
    
    pred_feats = pred_feats_all
    feat_v = feat_vectors_df.loc[pred_feats].sort_index()

    
    
    if int_struct:    
        print("=========== Internal structure in cluster==============")
        for cl_id in range(n_clust):        
            print("cluster ====>",cl_id)
            cres = {}

            cov = bgm.covariances_[cl_id]        
            import scipy
            (eigvals, eigvecs) = scipy.linalg.eigh(bgm.covariances_[cl_id])
            print("np.sqrt(eigvals)")
            print(np.sqrt(eigvals))

            cl_elong_a = np.sqrt(eigvals[-1]/eigvals[-2])
            cl_elong_v = eigvecs[-1]
            print("cl_elong_a, cl_elong_v.round(2)")
            print(cl_elong_a, cl_elong_v.round(2))  


            cres["cl_elong_a"] = cl_elong_a
            cres["cl_elong_v"] = cl_elong_v
            cres["cl_elong_var"] = eigvals[-1]
            cres["cl_mean"] = bgm.means_[cl_id]

            print("cluster data sample, mean shift")

            cl_ica_data = my_ica_data[bgm.predict(my_ica_data)==cl_id] - bgm.means_[cl_id]
            cl_ica_data=cl_ica_data[~cl_ica_data.index.duplicated(keep='first')]
            print(cl_ica_data.shape, cl_ica_data.head(3))

            print("cluster data elongation along main axis")        
            # global token_elong
            token_elong = pd.Series(np.inner(cl_ica_data,cl_elong_v),name='x',index=cl_ica_data.index)
            token_elong.head(3)

            # Compute each feature's effect on the projected axis


            cl_feat_elong_ip = pd.Series(np.inner(feat_v,cl_elong_v),
                                         index=feat_v.index,
                                         name='effect').loc[clust_featdx_df.loc[cl_id].index].sort_values(ascending=False)

            cl_feat_elong_df = pd.concat([cl_feat_elong_ip,clust_featdx_df.loc[cl_id]],axis=1)
            cl_feat_elong_df['eff2']=cl_feat_elong_df.effect**2

            cl_feat_elong_top = cl_feat_elong_df.sort_values('eff2',ascending=False).head(10)
            print(cl_feat_elong_top)

            print("Compute the feature-associated token x1 positions (ftok) on the projected axis")
            
            # global ftok

            ftok = feat_tokens.loc[cl_feat_elong_top.index]
            ftok = ftok.merge(token_elong,left_on='token',right_index=True).sort_index()
            ftok = ftok.reset_index().drop_duplicates().set_index(['arcpath','lemma'])
            print("ftok")
            print(ftok)


            print("Evaluate the feature-associated token positions on the projected axis")
            print("Compare to the group of tokens not associated with the feature (X0)")

            res = []
            feat_index = ftok.index.unique()
            
            print('feat_index',feat_index.shape)
            print('token_elong',token_elong.shape)
            print('ftok',ftok.shape)            
            
            
            for feat_i in feat_index:
                #print ('feat_i',feat_i)
                x1 = ftok.loc[[feat_i]].x
                tokens_in = ftok.loc[[feat_i]].token
                
                #print('tokens_in',tokens_in)
                #print('x1',x1)                
                
                
                x0 = token_elong[~token_elong.index.isin(tokens_in)]

                print('x0',x0)                

                n1 = len(x1)                
                n0 = len(x0)
                dx = np.round(x1.mean()-x0.mean(),3)

                stat=st.ttest_ind(x1, x0)

                res.append({'test_pvalue':np.round(stat.pvalue,5),
                            'test_dX':dx,'test_Nx':n1,'test_N':n1+n0,'test_st':np.round(stat.statistic,2)})
                    
            if len(res):


                feat_tests = pd.DataFrame(res,index = feat_index)
                print("Spearman results")
                print("feat_tests")
                print(feat_tests)

                book_cl_elong = pd.concat([cl_feat_elong_top,feat_tests],axis=1)        
                book_cl_elong = book_cl_elong[book_cl_elong.test_dX * book_cl_elong.effect > 0]
                print("book_cl_elong")
                print(book_cl_elong)

                cres["cl_ica_data"] = cl_ica_data
                cres["cl_feat_elong_top"] = cl_feat_elong_top
                cres["book_cl_elong"] = book_cl_elong
                cres["token_elong"] = token_elong


                result['C%d'%cl_id] = cres
    
    print("===========  end ==============")
    
    
    return result

In [318]:
cresTax = analyze_category('taxongroup',True)

checking for data/q_cluster/BGM_full_covar_taxongroup.pkl
BGM loaded
bgm.predict(my_ica_data)).value_counts()
9    2472
2    2429
6    1400
0     842
8     552
4     282
1     233
7     134
3      12
5       5
Name: count, dtype: int64
clust_feats (19040, 2)
                 cluster  freq
arcpath   lemma
case>     of           6   818
det>      the          2   613
          the          9   441
nmod<det> the          6   379
case>     of           2   346
=========================
clust_f_df pivot table (10866, 10)
clust_p_df is the probability distribution cluster-wise
                              0    1         2    3    4    5    6    7    8  \
arcpath              lemma
acl:relcl<case>      of     0.0  0.0  0.000096  0.0  0.0  0.0  0.0  0.0  0.0
acl:relcl<det>       the    0.0  0.0  0.000192  0.0  0.0  0.0  0.0  0.0  0.0
acl:relcl<obl<cop>   be     0.0  0.0  0.000096  0.0  0.0  0.0  0.0  0.0  0.0
acl:relcl<obl<nsubj> it     0.0  0.0  0.000096  0.0  0.0  0.0  0.0  0.0  0.0
acl:relcl>           be     0.0  0.0  0.000096  0.0  0.0  0.0  0.0  0.0  0.0

                                   9
arcpath              lemma
acl:relcl<case>      of     0.000000
acl:relcl<det>       the    0.000000
acl:relcl<obl<cop>   be     0.000000
acl:relcl<obl<nsubj> it     0.000000
acl:relcl>           be     0.000145
=========================
Elementwise relative entropy by clusters, feature-wise
                             0         1         2    3         4    5  \
arcpath        lemma
det>           the   -0.001607  0.007449  0.019732  0.0 -0.000204  0.0
case>          of    -0.002400 -0.003662  0.004788  0.0 -0.003980  0.0
cc>            and    0.000000  0.002718 -0.001966  0.0 -0.002310  0.0
amod>          other  0.000000  0.019691  0.006058  0.0 -0.002219  0.0
compound<case> of     0.109052  0.000000 -0.000748  0.0  0.000000  0.0

                             6         7         8         9
arcpath        lemma
det>           the    0.035031 -0.005187 -0.005351  0.023938
case>          of     0.187530 -0.004298 -0.001521 -0.002849
cc>            and    0.000000  0.002712  0.030488  0.020603
amod>          other  0.001924 -0.000865  0.005733  0.000332
compound<case> of    -0.000440  0.000000  0.000000 -0.000947
========== clust_featdx_df ===============
                                Dx    N
cluster arcpath    lemma
7       nmod>case> such   0.007683   16
8       conj<det>  the    0.022788   88
9       det>       the    0.023938  441
2       nmod>det>  the    0.016782  283
4       conj>det>  the    0.010155   20
=========================
pred_feats
feat_v
                                0         1         2         3         4  \
arcpath          lemma
acl:relcl>nsubj> that   -0.062988 -0.031006 -0.225952  0.068970 -0.026001
                 which  -0.026993 -0.062988 -0.218018  0.080017  0.065979
acl>obl>det>     the     0.145020 -0.152954 -0.185059  0.146973  0.284912
amod>            common  0.469971  0.033997 -0.514160  0.641113  0.316895
                 large   0.499023 -0.064026 -0.609863  0.694824  0.412109

                                5         6         7
arcpath          lemma
acl:relcl>nsubj> that   -0.140991  0.068970 -0.194946
                 which  -0.091980  0.182983 -0.238037
acl>obl>det>     the     0.091980 -0.151978 -0.040985
amod>            common -0.314941  0.091980  0.020996
                 large  -0.080994 -0.144043 -0.040009
mean_norm
[[-0.28 -0.25  0.74  0.28 -0.24 -0.28 -0.11  0.3 ]
 [ 0.65  0.41 -0.23  0.3  -0.19  0.29 -0.14  0.35]
 [ 0.83  0.05 -0.24 -0.14  0.21 -0.09 -0.15 -0.4 ]
 [ 0.01 -0.27 -0.03  0.   -0.01  0.96  0.08 -0.06]
 [ 0.29 -0.34 -0.27 -0.01  0.13  0.07  0.03 -0.84]
 [ 0.03 -0.29 -0.18 -0.87 -0.23 -0.24  0.09  0.11]
 [-0.17 -0.04  0.06 -0.16  0.95  0.02 -0.1   0.19]
 [ 0.53 -0.21 -0.59 -0.26 -0.32 -0.21  0.16  0.29]
 [-0.09  0.01 -0.29  0.1  -0.06  0.08  0.94  0.05]
 [-0.28 -0.18 -0.34  0.26 -0.69 -0.07 -0.34  0.33]]
cos_predict.head(5)
                                    0         1         2         3         4  \
arcpath             lemma
compound<case>      of      -0.142858 -0.094829  0.065604 -0.103357  0.205167
compound<det>       the     -0.197243 -0.117362  0.105470 -0.036762  0.279232
compound<appos<det> the     -0.187869  0.097680  0.227300  0.124052  0.215901
compound<           species -0.332748  0.472939  0.498115 -0.288469  0.261418
compound<nmod<det>  the     -0.452854  0.551205  0.591522 -0.050425  0.401391

                                    5         6         7         8         9
arcpath             lemma
compound<case>      of       0.012351 -0.084102  0.080936  0.123147  0.058002
compound<det>       the     -0.015730 -0.021460  0.065196  0.221812 -0.066027
compound<appos<det> the     -0.151640  0.226762  0.033263 -0.100862 -0.076822
compound<           species -0.447692  0.074860  0.364147  0.214562 -0.017163
compound<nmod<det>  the     -0.553895  0.166650  0.307577  0.032184  0.016892
score_predict.head(5)
                               0      1      2    3    4    5      6    7  \
arcpath             lemma
compound<case>      of       0.0  0.000  0.059  0.0  0.0  0.0  0.227  0.0
compound<det>       the      0.0  0.000  0.098  0.0  0.0  0.0  0.219  0.0
compound<appos<det> the      0.0  0.002  0.057  0.0  0.0  0.0  0.635  0.0
compound<           species  0.0  0.008  0.203  0.0  0.0  0.0  0.246  0.0
compound<nmod<det>  the      0.0  0.011  0.219  0.0  0.0  0.0  0.320  0.0

                                 8      9
arcpath             lemma
compound<case>      of       0.002  0.712
compound<det>       the      0.003  0.680
compound<appos<det> the      0.001  0.306
compound<           species  0.004  0.539
compound<nmod<det>  the      0.003  0.447
                                    0         1         2    3         4    5  \
arcpath             lemma
compound<case>      of       0.049309  0.000000  0.000240  0.0  0.000000  0.0
compound<det>       the      0.036406  0.000000  0.000817  0.0  0.000892  0.0
compound<appos<det> the      0.027189  0.000668  0.000096  0.0  0.000000  0.0
compound<           species  0.025346  0.000000  0.000144  0.0  0.000595  0.0
compound<nmod<det>  the      0.021659  0.000000  0.000096  0.0  0.000000  0.0

                                    6    7    8         9
arcpath             lemma
compound<case>      of       0.000114  0.0  0.0  0.004342
compound<det>       the      0.000228  0.0  0.0  0.007671
compound<appos<det> the      0.000000  0.0  0.0  0.000796
compound<           species  0.000114  0.0  0.0  0.004559
compound<nmod<det>  the      0.000000  0.0  0.0  0.001447
=========== Internal structure in cluster==============
cluster ====> 0
np.sqrt(eigvals)
[0.13220147 0.18089723 0.22340393 0.24835196 0.28967368 0.34636284
 0.383435   0.65756759]
cl_elong_a, cl_elong_v.round(2)
1.714938856031669 [-0.13 -0.45  0.21 -0.8   0.01  0.03  0.12 -0.3 ]
cluster data sample, mean shift
(827, 8)                                   0         1         2         3         4  \
token_id
Arc-b4f2_60_Sterna-17      0.269772  0.011575 -0.217613 -0.617702  0.484017
Cir-aed8_182_animal-20    -0.400118  0.421515  0.117231  0.632574  0.089577
Fri-5711_17_Fritillaria-1  0.325610 -0.103719 -0.736775  0.372575 -0.091066

                                  5         6         7
token_id
Arc-b4f2_60_Sterna-17      1.523788 -0.255121  0.493460
Cir-aed8_182_animal-20     0.168482  0.063410  0.163747
Fri-5711_17_Fritillaria-1 -0.750147  0.213261 -0.226958
cluster data elongation along main axis
                        effect        Dx  N      eff2
arcpath     lemma
det>        the       0.728370 -0.001607  1  0.530522
amod>       true     -0.696367  0.000157  1  0.484926
            european -0.640723  0.000163  1  0.410526
            american -0.615469  0.000232  1  0.378803
            bighorn  -0.601725  0.000715  1  0.362073
            red      -0.575242 -0.000189  1  0.330904
            Siberian -0.573746  0.000625  1  0.329185
            bille    -0.569769  0.000900  1  0.324637
            early    -0.556316  0.000837  1  0.309487
appos<case> at        0.553682  0.000648  1  0.306564
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                          token         x
arcpath     lemma
amod>       Siberian    Sal-7dcf_2_salamander-6  0.076941
            american   Cro-0859_276_crocodile-9 -0.073167
            bighorn         Big-0af3_33_sheep-4 -0.567018
            bille       Igu-69c5_9_dinosaurs-25  0.210170
            early     Ani-4d8b_162_chimpanzee-2 -0.679259
            european         Eur-35e8_13_gull-3 -0.376998
            red         Red-a286_70_squirrel-29  0.602987
            true         Dun-cad0_16_beetles-60 -0.569069
appos<case> at          Lep-f8ec_671_Insecta-16  0.528630
det>        the         Sal-7dcf_2_salamander-6  0.076941
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (827,)
ftok (10, 2)
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64

x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
Spearman results
feat_tests
                      test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath     lemma
amod>       Siberian      0.80098    0.073        1     827     0.25
            american      0.79033   -0.077        1     827    -0.27
            bighorn       0.04858   -0.572        1     827    -1.98
            bille         0.47653    0.207        1     827     0.71
            early         0.01822   -0.684        1     827    -2.37
            european      0.18854   -0.381        1     827    -1.32
            red           0.03846    0.600        1     827     2.07
            true          0.04778   -0.574        1     827    -1.98
appos<case> at            0.06992    0.525        1     827     1.81
det>        the           0.80098    0.073        1     827     0.25
book_cl_elong
                        effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath     lemma
det>        the       0.728370 -0.001607  1  0.530522      0.80098    0.073
amod>       true     -0.696367  0.000157  1  0.484926      0.04778   -0.574
            european -0.640723  0.000163  1  0.410526      0.18854   -0.381
            american -0.615469  0.000232  1  0.378803      0.79033   -0.077
            bighorn  -0.601725  0.000715  1  0.362073      0.04858   -0.572
            early    -0.556316  0.000837  1  0.309487      0.01822   -0.684
appos<case> at        0.553682  0.000648  1  0.306564      0.06992    0.525

                      test_Nx  test_N  test_st
arcpath     lemma
det>        the             1     827     0.25
amod>       true            1     827    -1.98
            european        1     827    -1.32
            american        1     827    -0.27
            bighorn         1     827    -1.98
            early           1     827    -2.37
appos<case> at              1     827     1.81
cluster ====> 1
np.sqrt(eigvals)
[0.26171702 0.35119703 0.42300565 0.62206648 0.81641687 0.97901089
 1.25573878 2.80445139]
cl_elong_a, cl_elong_v.round(2)
2.2333079518709735 [ 0.56  0.06  0.78 -0.22  0.04 -0.1  -0.11  0.02]
cluster data sample, mean shift
(199, 8)                                  0         1         2         3         4  \
token_id
Tru-f072_21_animals-7     0.968425 -3.946513 -0.182949  1.656552  1.416039
Din-756f_27_Dinosauria-7  0.259754 -2.546674  0.521633  0.218453  0.434535
Sca-9161_30_Animals-1     0.173958 -2.289524  0.608234  0.203571  0.506868

                                 5         6         7
token_id
Tru-f072_21_animals-7     0.870430 -0.665120  0.560448
Din-756f_27_Dinosauria-7  0.999972 -0.221918 -0.319033
Sca-9161_30_Animals-1    -0.306838  0.046482  0.096311
cluster data elongation along main axis
                        effect        Dx   N      eff2
arcpath    lemma
cc>        and       -0.751177  0.002718  13  0.564267
nmod>case> of         0.729722  0.004417   8  0.532494
nmod>      Hewitson   0.725210  0.001158   1  0.525929
nsubj<     order      0.717932  0.001071   1  0.515427
nmod>case> in         0.702984  0.005788   9  0.494187
cc>        as        -0.698172  0.002902   3  0.487444
nmod>case> for        0.674864  0.004620   4  0.455442
nmod>      Boisduval  0.672279  0.001131   1  0.451959
nmod>case> with       0.668601  0.002075   4  0.447027
           as         0.662159  0.000889   1  0.438454
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                 token         x
arcpath    lemma
cc>        and                 Acc-0f45_128_animals-52 -1.517914
           and                  Art-1308_276_animals-9 -1.311260
           and                  Aus-e5de_84_animals-23  0.258544
           and                   Bur-98f9_35_snakes-23 -0.976707
           and                   Eur-9431_146_birds-36  0.939789
           and                 Gre-8842_263_animals-14 -1.078303
           and                    Hor-8eda_15_wasps-17 -0.262167
           and              Lon-b0af_465_amphibians-16 -0.651788
           and                Neo-e4e0_73_amphibians-7  0.419851
           and              Sal-5617_98_salamanders-11 -0.341240
           and                 Sem-88a0_20_molluscs-24 -0.300912
           and                   Tig-9404_36_sharks-31 -2.328309
           and                 Ulm-cc96_2_jellyfish-18 -0.542769
           as                   Bla-2fe0_156_plants-13 -0.134455
           as                Eur-c955_104_squirrels-19 -0.537578
           as                   Eas-b7c7_26_insects-22 -0.697873
nmod>      Boisduval            Pap-75c9_38_Papilio-14  1.066442
           Hewitson             Pap-75c9_41_Papilio-31  1.194487
nmod>case> as                 Din-756f_246_dinosaurs-3  1.060696
           for                  Art-1308_276_animals-9 -1.311260
           for                   Bai-1860_29_animals-4  1.264953
           for                  Bee-1811_473_insects-3  1.098793
           for                   Hed-8dc6_164_plants-3 -2.107495
           in                  Acc-0f45_128_animals-52 -1.517914
           in                 Neo-e4e0_73_amphibians-7  0.419851
           in               Sal-5617_98_salamanders-11 -0.341240
           in                   Ame-d5c4_209_animals-9  0.785165
           in                   Bla-2fe0_156_plants-13 -0.134455
           in                Eur-c955_104_squirrels-19 -0.537578
           in                 Red-a286_99_squirrels-17  1.182871
           in                   Redab4b_59_squirrels-9  0.742750
           in                     She-572b_18_animal-4  1.525565
           of                     Hor-8eda_15_wasps-17 -0.262167
           of                 All-7078_123_Dinosaurs-7  0.170848
           of                    Ble-2387_2_rodents-19  1.139131
           of            Com-264e_2_Syngnathiformes-18  0.820904
           of                    Har-f3ef_20_animals-6  0.929674
           of                        Kin-034b_9_bird-3  1.322116
           of                     Roe-b5ac_120_deer-22 -0.898712
           of         Tig-9404_17_Carcharhiniformes-10  0.428870
           with                  Eur-9431_146_birds-36  0.939789
           with                Ulm-cc96_2_jellyfish-18 -0.542769
           with                 Blu-3a31_23_animals-24  0.128067
           with                 The-f5b4_187_animals-3  1.533152
nsubj<     order                  Fly-ac51_4_Diptera-1  0.869151
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (199,)
ftok (45, 2)
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 186, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 196, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 198, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 198, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 198, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 195, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 190, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 191, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 195, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 198, dtype: float64
Spearman results
feat_tests
                      test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
cc>        and            0.03505   -0.631       13     199    -2.12
           as             0.44919   -0.462        3     199    -0.76
nmod>      Boisduval      0.30727    1.073        1     199     1.02
           Hewitson       0.25272    1.202        1     199     1.15
nmod>case> as             0.30989    1.068        1     199     1.02
           for            0.61391   -0.268        4     199    -0.51
           in             0.48678    0.249        9     199     0.70
           of             0.20712    0.477        8     199     1.27
           with           0.32006    0.527        4     199     1.00
nsubj<     order          0.40541    0.875        1     199     0.83

book_cl_elong
                        effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath    lemma
cc>        and       -0.751177  0.002718  13  0.564267      0.03505   -0.631
nmod>case> of         0.729722  0.004417   8  0.532494      0.20712    0.477
nmod>      Hewitson   0.725210  0.001158   1  0.525929      0.25272    1.202
nsubj<     order      0.717932  0.001071   1  0.515427      0.40541    0.875
nmod>case> in         0.702984  0.005788   9  0.494187      0.48678    0.249
cc>        as        -0.698172  0.002902   3  0.487444      0.44919   -0.462
nmod>      Boisduval  0.672279  0.001131   1  0.451959      0.30727    1.073
nmod>case> with       0.668601  0.002075   4  0.447027      0.32006    0.527
           as         0.662159  0.000889   1  0.438454      0.30989    1.068

                      test_Nx  test_N  test_st
arcpath    lemma
cc>        and             13     199    -2.12
nmod>case> of               8     199     1.27
nmod>      Hewitson         1     199     1.15
nsubj<     order            1     199     0.83
nmod>case> in               9     199     0.70
cc>        as               3     199    -0.76
nmod>      Boisduval        1     199     1.02
nmod>case> with             4     199     1.00
           as               1     199     1.02
cluster ====> 2
np.sqrt(eigvals)
[0.3960085  0.6456979  0.71041842 0.80835755 0.95695145 1.1191785
 1.22046918 1.34060167]
cl_elong_a, cl_elong_v.round(2)
1.0984314004797417 [-0.02 -0.09  0.58  0.07  0.45  0.35 -0.07  0.56]
cluster data sample, mean shift
(2280, 8)                                     0         1         2         3         4  \
token_id
Bla-b48c_24_animals-6       -1.401316  0.605597  0.515301 -0.230137  0.838484
Sia-b899_44_primates-21      0.164422  0.536239  0.486635 -0.284216 -0.639501
Pha-1383_2_Diprotodontia-38  0.377362  0.023735  1.444552  0.866608 -0.346779

                                    5         6         7
token_id
Bla-b48c_24_animals-6        0.163035 -0.042755 -0.208050
Sia-b899_44_primates-21     -0.223604  0.070850  1.070395
Pha-1383_2_Diprotodontia-38  0.637382 -0.083543  0.325244
cluster data elongation along main axis
                         effect        Dx    N      eff2
arcpath  lemma
conj>cc> rather       -0.635106  0.000221    2  0.403359
         but          -0.629623  0.000721   13  0.396425
         or           -0.606872  0.003933   64  0.368294
         and          -0.584519  0.012895  277  0.341662
         as           -0.571473  0.000220    8  0.326581
conj>    form         -0.556713  0.000332    3  0.309929
         mollusc      -0.554473 -0.000032    1  0.307440
         invertebrate -0.547881  0.000086    2  0.300174
         tortoise     -0.546524  0.000066    1  0.298689
         fish         -0.545626  0.000063    4  0.297708
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                      token         x
arcpath  lemma
conj>    fish         Atl-fb88_25_fishes-15 -3.655930
         fish         Spa-e46a_21_animals-2 -0.698114
         fish      Sea-4a1d_309_reptiles-17  0.151133
         fish        Tam-0d84_13_characin-6 -0.806471
         form        Mos-3d44_144_animals-7 -1.886516
...                                     ...       ...
conj>cc> or           Tho-4613_4_spiders-11 -0.720854
         or         Tyr-9f97_325_lizards-43  0.080017
         or         Wea-8e57_5_Mustelidae-3 -0.705664
         rather  Cni-c1f9_224_cnidarians-33 -1.000411
         rather     Pte-62aa_442_animals-12 -1.728691

[375 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (2280,)
ftok (375, 2)
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2276, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2277, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2278, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2279, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2279, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Bir-ebe4_542_mammals-10        2.548465
Nil-600c_128_animals-14       -0.007033
                                 ...
Blu-41f9_91_animal-7          -0.795735
Com-a681_84_vertebrates-4     -0.793273
Chi-c10a_299_chimpanzees-27    0.210409
Bro-f1dc_290_animal-25        -1.844749
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2003, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2272, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2267, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2216, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2278, dtype: float64
Spearman results
feat_tests
                       test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath  lemma
conj>    fish              0.02494   -1.216        4    2280    -2.24
         form              0.00003   -2.588        3    2280    -4.15
         invertebrate      0.34849   -0.719        2    2280    -0.94
         mollusc           0.02055   -2.511        1    2280    -2.32
         tortoise          0.12666   -1.656        1    2280    -1.53
conj>cc> and               0.00000   -1.120      277    2280   -17.13
         as                0.00002   -1.657        8    2280    -4.33
         but               0.00000   -1.890       13    2280    -6.32
         or                0.00000   -1.049       64    2280    -7.73
         rather            0.08346   -1.327        2    2280    -1.73
book_cl_elong
                         effect        Dx    N      eff2  test_pvalue  \
arcpath  lemma
conj>cc> rather       -0.635106  0.000221    2  0.403359      0.08346
         but          -0.629623  0.000721   13  0.396425      0.00000
         or           -0.606872  0.003933   64  0.368294      0.00000
         and          -0.584519  0.012895  277  0.341662      0.00000
         as           -0.571473  0.000220    8  0.326581      0.00002
conj>    form         -0.556713  0.000332    3  0.309929      0.00003
         mollusc      -0.554473 -0.000032    1  0.307440      0.02055
         invertebrate -0.547881  0.000086    2  0.300174      0.34849
         tortoise     -0.546524  0.000066    1  0.298689      0.12666
         fish         -0.545626  0.000063    4  0.297708      0.02494

                       test_dX  test_Nx  test_N  test_st
arcpath  lemma
conj>cc> rather         -1.327        2    2280    -1.73
         but            -1.890       13    2280    -6.32
         or             -1.049       64    2280    -7.73
         and            -1.120      277    2280   -17.13
         as             -1.657        8    2280    -4.33
conj>    form           -2.588        3    2280    -4.15
         mollusc        -2.511        1    2280    -2.32
         invertebrate   -0.719        2    2280    -0.94
         tortoise       -1.656        1    2280    -1.53
         fish           -1.216        4    2280    -2.24
cluster ====> 3
np.sqrt(eigvals)
[0.21115671 0.22982939 0.24384121 0.24768674 0.26566413 0.27196214
 0.35848478 7.07414045]
cl_elong_a, cl_elong_v.round(2)
19.733447379518083 [-0.08 -0.9   0.14 -0.25  0.06 -0.3   0.06 -0.06]
cluster data sample, mean shift
(12, 8)                              0         1         2         3         4  \
token_id
Sep-9969_11_Sepia-94 -0.109762 -0.722088 -0.089950  0.297656 -0.094313
Sep-9969_11_Sepia-13  0.014948 -0.707135  0.000731 -0.068633 -0.048942
Sep-9969_11_Sepia-8   0.037790 -0.494847 -0.650656  0.633717  0.177464

                             5         6         7
token_id
Sep-9969_11_Sepia-94  2.762769  0.404445 -0.129934
Sep-9969_11_Sepia-13  2.356798  0.135907 -0.174223
Sep-9969_11_Sepia-8   2.657096  0.340549 -0.148887
cluster data elongation along main axis
                                  effect        Dx   N      eff2
arcpath             lemma
compound>           Sepia      -0.268692  0.006471   2  0.072196
flat<flat>compound> Sepia      -0.255541  0.044139  12  0.065301
amod>               cuttlefish -0.238076  0.003235   1  0.056680
compound>           cuttlefish -0.232783  0.002969   1  0.054188
flat<flat>compound> cuttlefish -0.229504  0.040461  11  0.052672
flat<list>amod>     giant      -0.219652  0.044139  12  0.048247
flat<compound>      Sepia       0.193832  0.044139  12  0.037571
flat<compound>amod> cuttlefish  0.158390  0.044139  12  0.025087
flat<list>amod>     common     -0.148139  0.043844  12  0.021945
flat<flat>          Sepia      -0.132598  0.044139  12  0.017582
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                           token         x
arcpath         lemma
amod>           cuttlefish   Sep-9969_11_Sepia-8 -0.579888
compound>       Sepia        Sep-9969_11_Sepia-8 -0.579888
                Sepia       Sep-9969_11_Sepia-94 -0.244920
                cuttlefish  Sep-9969_11_Sepia-30 -0.055540
flat<compound>  Sepia        Sep-9969_11_Sepia-8 -0.579888
...                                          ...       ...
flat<list>amod> giant       Sep-9969_11_Sepia-44 -0.051512
                giant       Sep-9969_11_Sepia-46 -0.051512
                giant       Sep-9969_11_Sepia-48 -0.051512
                giant       Sep-9969_11_Sepia-50 -0.051512
                giant       Sep-9969_11_Sepia-52 -0.051512

[87 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (12,)
ftok (87, 2)
x0 token_id
Sep-9969_11_Sepia-94   -0.244920
Sep-9969_11_Sepia-13   -0.051512
Sep-9969_11_Sepia-48   -0.051512
Sep-9969_11_Sepia-14   -0.051512
Sep-9969_11_Sepia-50   -0.051512
Sep-9969_11_Sepia-52   -0.051512
Sep-9969_11_Sepia-30   -0.055540
Sep-9969_11_Sepia-39   -0.051512
Sep-9969_11_Sepia-46   -0.051512
Sep-9969_11_Sepia-44   -0.051512
Sep-9969_11_Sepia-10   -0.051512
Name: x, dtype: float64
x0 token_id
Sep-9969_11_Sepia-13   -0.051512
Sep-9969_11_Sepia-48   -0.051512
Sep-9969_11_Sepia-14   -0.051512
Sep-9969_11_Sepia-50   -0.051512
Sep-9969_11_Sepia-52   -0.051512
Sep-9969_11_Sepia-30   -0.055540
Sep-9969_11_Sepia-39   -0.051512
Sep-9969_11_Sepia-46   -0.051512
Sep-9969_11_Sepia-44   -0.051512
Sep-9969_11_Sepia-10   -0.051512
Name: x, dtype: float64
x0 token_id
Sep-9969_11_Sepia-94   -0.244920
Sep-9969_11_Sepia-13   -0.051512
Sep-9969_11_Sepia-8    -0.579888
Sep-9969_11_Sepia-48   -0.051512
Sep-9969_11_Sepia-14   -0.051512
Sep-9969_11_Sepia-50   -0.051512
Sep-9969_11_Sepia-52   -0.051512
Sep-9969_11_Sepia-39   -0.051512
Sep-9969_11_Sepia-46   -0.051512
Sep-9969_11_Sepia-44   -0.051512
Sep-9969_11_Sepia-10   -0.051512
Name: x, dtype: float64
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 token_id
Sep-9969_11_Sepia-30   -0.05554
Name: x, dtype: float64
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
Spearman results
feat_tests
                                test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath             lemma
amod>               cuttlefish      0.00001   -0.510        1      12    -8.40
compound>           Sepia           0.00010   -0.360        2      12    -6.21
                    cuttlefish      0.72679    0.062        1      12     0.36
flat<compound>      Sepia               NaN      NaN       12      12      NaN
flat<compound>amod> cuttlefish          NaN      NaN       12      12      NaN
flat<flat>          Sepia               NaN      NaN       12      12      NaN
flat<flat>compound> Sepia               NaN      NaN       12      12      NaN
                    cuttlefish      0.72679   -0.062       11      12    -0.36
flat<list>amod>     common              NaN      NaN       12      12      NaN
                    giant               NaN      NaN       12      12      NaN
book_cl_elong
                                  effect        Dx   N      eff2  test_pvalue  \
arcpath             lemma
compound>           Sepia      -0.268692  0.006471   2  0.072196      0.00010
amod>               cuttlefish -0.238076  0.003235   1  0.056680      0.00001
flat<flat>compound> cuttlefish -0.229504  0.040461  11  0.052672      0.72679

                                test_dX  test_Nx  test_N  test_st
arcpath             lemma
compound>           Sepia        -0.360        2      12    -6.21
amod>               cuttlefish   -0.510        1      12    -8.40
flat<flat>compound> cuttlefish   -0.062       11      12    -0.36
cluster ====> 4
np.sqrt(eigvals)
[0.87541035 1.0956898  1.1771284  1.38286394 1.47621182 1.83913222
 2.7747381  2.8546637 ]
cl_elong_a, cl_elong_v.round(2)
1.0288047371721647 [-0.02  0.1   0.16  0.23 -0.03 -0.16 -0.94 -0.06]
cluster data sample, mean shift
(258, 8)                                0         1         2         3         4  \
token_id
Bla-2fe0_148_plants-9  -1.589118  0.532876 -0.595739  2.765317 -0.979652
Das-ed91_129_animal-33  0.946745 -0.179290  0.062501 -0.988001 -0.497125
Dee-529a_76_deer-4     -0.865783  0.669462  1.146893  1.255307 -0.731483

                               5         6         7
token_id
Bla-2fe0_148_plants-9   0.019344  1.148160 -6.289577
Das-ed91_129_animal-33 -2.015726  1.201258  0.371768
Dee-529a_76_deer-4     -0.709612 -0.873352 -3.147970
cluster data elongation along main axis
                          effect        Dx  N      eff2
arcpath    lemma
conj>      Subfamily    0.667451  0.000640  1  0.445490
conj<conj> shark       -0.664978 -0.000046  2  0.442196
           bat         -0.663527  0.000714  3  0.440269
           flatworm    -0.566637  0.000473  1  0.321078
conj>      Sciurus      0.563619  0.000685  1  0.317666
           family       0.551452  0.000584  1  0.304100
           swallowtail  0.530675  0.001369  2  0.281616
           Blattodea    0.504107  0.000640  1  0.254124
conj<conj> c.          -0.499749  0.000406  1  0.249749
conj>      dinosaur     0.472400  0.001240  2  0.223162
Compute the feature-associated token x1 positions (ftok) on the projected axis

/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)

ftok
                                           token         x
arcpath    lemma
conj<conj> bat              Bat-2d5b_226_bats-34 -2.213637
           bat              Bat-2d5b_226_bats-44 -2.468908
           bat                 Vam-5657_4_bat-24 -1.274221
           c.             Pap-75c9_46_Papilio-92 -0.364505
           flatworm      Ear-b650_253_beetles-22 -1.681358
           shark             Req-2240_3_shark-30 -1.162573
           shark             Req-2240_3_shark-33 -1.119459
conj>      Blattodea          Soc-cc7f_57_ants-9  1.419770
           Sciurus        Sci-501e_9_squirrel-55  0.873694
           Subfamily      Igu-7a3f_52_lizards-12  1.508407
           dinosaur     Had-5500_143_reptiles-23  0.601762
           dinosaur      Rep-aa64_159_reptiles-2  2.034344
           family        Oak-f2b6_135_Fagaceae-2  0.699875
           swallowtail     Pap-75c9_40_Papilio-1  1.875292
           swallowtail     Pap-75c9_60_Papilio-1 -0.124200
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (258,)
ftok (15, 2)
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 255, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 257, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 257, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 256, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 257, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 257, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 257, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Oce-2d88_489_animals-11       -0.038837
Vam-5657_4_bat-24             -1.274221
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 256, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 257, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 256, dtype: float64
Spearman results
feat_tests
                        test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
conj<conj> bat              0.00092   -2.019        3     258    -3.35
           c.               0.72373   -0.376        1     258    -0.35
           flatworm         0.10924   -1.698        1     258    -1.61
           shark            0.12259   -1.160        2     258    -1.55
conj>      Blattodea        0.18198    1.416        1     258     1.34
           Sciurus          0.41395    0.867        1     258     0.82
           Subfamily        0.15593    1.505        1     258     1.42
           dinosaur         0.07891    1.319        2     258     1.76
           family           0.51410    0.693        1     258     0.65
           swallowtail      0.24570    0.873        2     258     1.16
book_cl_elong
                          effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath    lemma
conj>      Subfamily    0.667451  0.000640  1  0.445490      0.15593    1.505
conj<conj> shark       -0.664978 -0.000046  2  0.442196      0.12259   -1.160
           bat         -0.663527  0.000714  3  0.440269      0.00092   -2.019
           flatworm    -0.566637  0.000473  1  0.321078      0.10924   -1.698
conj>      Sciurus      0.563619  0.000685  1  0.317666      0.41395    0.867
           family       0.551452  0.000584  1  0.304100      0.51410    0.693
           swallowtail  0.530675  0.001369  2  0.281616      0.24570    0.873
           Blattodea    0.504107  0.000640  1  0.254124      0.18198    1.416
conj<conj> c.          -0.499749  0.000406  1  0.249749      0.72373   -0.376
conj>      dinosaur     0.472400  0.001240  2  0.223162      0.07891    1.319

                        test_Nx  test_N  test_st
arcpath    lemma
conj>      Subfamily          1     258     1.42
conj<conj> shark              2     258    -1.55
           bat                3     258    -3.35
           flatworm           1     258    -1.61
conj>      Sciurus            1     258     0.82
           family             1     258     0.65
           swallowtail        2     258     1.16
           Blattodea          1     258     1.34
conj<conj> c.                 1     258    -0.35
conj>      dinosaur           2     258     1.76
cluster ====> 5
np.sqrt(eigvals)
[0.26601108 0.29226841 0.30037423 0.31435327 0.31755581 0.34179399
 0.42360761 8.70287425]
cl_elong_a, cl_elong_v.round(2)
20.5446597646298 [-0.08  0.89 -0.09  0.23 -0.35 -0.01 -0.    0.11]
cluster data sample, mean shift
(5, 8)                                   0         1         2         3         4  \
token_id
Sep-9969_11_cuttlefish-72  0.175137 -1.863047 -0.897680 -5.089547 -1.288464
Sep-9969_11_cuttlefish-61  0.131416 -1.717613 -0.936958 -4.846084 -1.459493
Sep-9969_11_Sepia-73       0.200669 -1.654411 -0.962844 -5.214492 -1.214779

                                  5         6         7
token_id
Sep-9969_11_cuttlefish-72 -1.376220  0.433929  0.686780
Sep-9969_11_cuttlefish-61 -1.435134  0.538422  0.448331
Sep-9969_11_Sepia-73      -1.360708  0.542007  0.680597
cluster data elongation along main axis

                                          effect        Dx  N      eff2
arcpath                 lemma
list<compound>amod>     cuttlefish     -0.373938  0.044624  5  0.139830
list<compound<compound< Sepia           0.356669  0.044624  5  0.127212
list<list>compound>     angulata       -0.348545  0.044624  5  0.121484
list<list>              novaehollandia -0.322935  0.044624  5  0.104287
list<flat>              Sepia          -0.311200  0.044624  5  0.096845
list<list>              papuensis      -0.306864  0.044624  5  0.094165
list<list>compound>     Guinean        -0.278939  0.035699  4  0.077807
list<list>              Sepia          -0.276003  0.044624  5  0.076178
                        officinalis    -0.275028  0.044624  5  0.075640
list<flat>              Subgenus       -0.274664  0.044624  5  0.075440
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                            token         x
arcpath                 lemma
list<compound<compound< Sepia                Sep-9969_11_Sepia-62 -2.103412
                        Sepia                Sep-9969_11_Sepia-73 -2.103412
                        Sepia           Sep-9969_11_cuttlefish-43 -1.587440
                        Sepia           Sep-9969_11_cuttlefish-61 -2.008829
                        Sepia           Sep-9969_11_cuttlefish-72 -2.236184
list<compound>amod>     cuttlefish           Sep-9969_11_Sepia-62 -2.103412
                        cuttlefish           Sep-9969_11_Sepia-73 -2.103412
                        cuttlefish      Sep-9969_11_cuttlefish-43 -1.587440
                        cuttlefish      Sep-9969_11_cuttlefish-61 -2.008829
                        cuttlefish      Sep-9969_11_cuttlefish-72 -2.236184
list<flat>              Sepia                Sep-9969_11_Sepia-62 -2.103412
                        Sepia                Sep-9969_11_Sepia-73 -2.103412
                        Sepia           Sep-9969_11_cuttlefish-43 -1.587440
                        Sepia           Sep-9969_11_cuttlefish-61 -2.008829
                        Sepia           Sep-9969_11_cuttlefish-72 -2.236184
                        Subgenus             Sep-9969_11_Sepia-62 -2.103412
                        Subgenus             Sep-9969_11_Sepia-73 -2.103412
                        Subgenus        Sep-9969_11_cuttlefish-43 -1.587440
                        Subgenus        Sep-9969_11_cuttlefish-61 -2.008829
                        Subgenus        Sep-9969_11_cuttlefish-72 -2.236184
list<list>              Sepia                Sep-9969_11_Sepia-62 -2.103412
                        Sepia                Sep-9969_11_Sepia-73 -2.103412
                        Sepia           Sep-9969_11_cuttlefish-43 -1.587440
                        Sepia           Sep-9969_11_cuttlefish-61 -2.008829
                        Sepia           Sep-9969_11_cuttlefish-72 -2.236184
                        novaehollandia       Sep-9969_11_Sepia-62 -2.103412
                        novaehollandia       Sep-9969_11_Sepia-73 -2.103412
                        novaehollandia  Sep-9969_11_cuttlefish-43 -1.587440
                        novaehollandia  Sep-9969_11_cuttlefish-61 -2.008829
                        novaehollandia  Sep-9969_11_cuttlefish-72 -2.236184
                        officinalis          Sep-9969_11_Sepia-62 -2.103412
                        officinalis          Sep-9969_11_Sepia-73 -2.103412
                        officinalis     Sep-9969_11_cuttlefish-43 -1.587440
                        officinalis     Sep-9969_11_cuttlefish-61 -2.008829
                        officinalis     Sep-9969_11_cuttlefish-72 -2.236184
                        papuensis            Sep-9969_11_Sepia-62 -2.103412
                        papuensis            Sep-9969_11_Sepia-73 -2.103412
                        papuensis       Sep-9969_11_cuttlefish-43 -1.587440
                        papuensis       Sep-9969_11_cuttlefish-61 -2.008829
                        papuensis       Sep-9969_11_cuttlefish-72 -2.236184
list<list>compound>     Guinean              Sep-9969_11_Sepia-62 -2.103412
                        Guinean              Sep-9969_11_Sepia-73 -2.103412
                        Guinean         Sep-9969_11_cuttlefish-61 -2.008829
                        Guinean         Sep-9969_11_cuttlefish-72 -2.236184
                        angulata             Sep-9969_11_Sepia-62 -2.103412
                        angulata             Sep-9969_11_Sepia-73 -2.103412
                        angulata        Sep-9969_11_cuttlefish-43 -1.587440
                        angulata        Sep-9969_11_cuttlefish-61 -2.008829
                        angulata        Sep-9969_11_cuttlefish-72 -2.236184
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (5,)
ftok (49, 2)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 token_id
Sep-9969_11_cuttlefish-43   -1.58744
Name: x, dtype: float64
x0 Series([], Name: x, dtype: float64)
Spearman results
feat_tests
                                        test_pvalue  test_dX  test_Nx  test_N  \
arcpath                 lemma
list<compound<compound< Sepia                   NaN      NaN        5       5
list<compound>amod>     cuttlefish              NaN      NaN        5       5
list<flat>              Sepia                   NaN      NaN        5       5
                        Subgenus                NaN      NaN        5       5
list<list>              Sepia                   NaN      NaN        5       5
                        novaehollandia          NaN      NaN        5       5
                        officinalis             NaN      NaN        5       5
                        papuensis               NaN      NaN        5       5
list<list>compound>     Guinean             0.01515   -0.526        4       5
                        angulata                NaN      NaN        5       5

                                        test_st
arcpath                 lemma
list<compound<compound< Sepia               NaN
list<compound>amod>     cuttlefish          NaN
list<flat>              Sepia               NaN
                        Subgenus            NaN
list<list>              Sepia               NaN
                        novaehollandia      NaN
                        officinalis         NaN
                        papuensis           NaN
list<list>compound>     Guinean           -5.03
                        angulata            NaN
book_cl_elong
                               effect        Dx  N      eff2  test_pvalue  \
arcpath             lemma
list<list>compound> Guinean -0.278939  0.035699  4  0.077807      0.01515

                             test_dX  test_Nx  test_N  test_st
arcpath             lemma
list<list>compound> Guinean   -0.526        4       5    -5.03
cluster ====> 6
np.sqrt(eigvals)
[0.24110727 0.31028343 0.37678552 0.50346858 0.52822512 0.61225642
 0.76127814 0.99444923]
cl_elong_a, cl_elong_v.round(2)
1.3062889477770603 [-0.05  0.93  0.33  0.09  0.02  0.12  0.03  0.03]
cluster data sample, mean shift

/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)

(1332, 8)                                    0         1         2         3         4  \
token_id
Hor-ab9c_184_bat-13        -0.438082 -0.355401  0.229085 -1.898982  1.375143
The-1978_215_Saurischia-16  0.246799 -0.374635 -0.626796 -0.283815  0.974614
Com-f222_479_birds-11       0.784924 -0.106542 -0.386290  1.482840  0.764857

                                   5         6         7
token_id
Hor-ab9c_184_bat-13        -0.538853 -0.121674  0.336166
The-1978_215_Saurischia-16  0.048036 -0.296486  0.502807
Com-f222_479_birds-11      -0.594153  0.128833  0.224974
cluster data elongation along main axis
                                    effect        Dx   N      eff2
arcpath              lemma
acl:relcl>           include     -0.771728  0.001694  10  0.595564
                     contain     -0.753686  0.000493   3  0.568042
obl<                 achieve      0.718221  0.000222   1  0.515841
                     use          0.712818  0.000120   3  0.508110
                     unique       0.711457  0.000193   1  0.506170
                     concentrate  0.709540  0.000222   1  0.503446
acl:relcl>           call        -0.709162  0.000222   1  0.502911
                     have        -0.703773  0.000412   3  0.495296
acl>obl>nmod:poss>   its         -0.703625  0.000787   3  0.495088
nmod<nsubj:pass<obl> diet        -0.700473  0.000525   2  0.490663
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                        token         x
arcpath              lemma
acl:relcl>           call              Aur-4fbd_2_jellyfish-6 -0.663944
                     contain             Bla-975a_2_insects-6 -0.582368
                     contain               Latf3e7_1_snakes-8 -0.814585
                     contain          Mer-8390_2_arthropods-7 -1.095138
                     have               Gol-1dbf_201_birds-32 -0.630666
                     have               Ost-8757_2_animals-24 -1.033817
                     have               Tar2870_20_spiders-46 -1.204961
                     include      Amp-436a_182_salamanders-12 -0.523022
                     include            Bos-be23_2_bovines-17 -0.536654
                     include            Bov-d455_2_mammals-13 -0.204985
                     include              Cni33c8_2_animals-7 -1.007654
                     include               Cor-ff2a_2_fungi-7 -1.075492
                     include         Din-756f_431_dinosaurs-5 -0.782951
                     include              Ech86c4_4_animals-6 -0.967408
                     include             Ros-4632_2_plants-16 -0.720216
                     include            Ter-7888_3_Laridae-10 -0.711852
                     include           Ulm-cc96_2_jellyfish-7 -1.053087
acl>obl>nmod:poss>   its                  Har-a313_11_bird-15 -0.916473
                     its                  Nor-d815_14_bird-16 -0.762811
                     its                  Wes-9ef7_14_bird-16 -0.713869
nmod<nsubj:pass<obl> diet                 Com-f222_370_bird-5 -0.548459
                     diet                Eur-bc75_357_snake-5  0.649014
obl<                 achieve             Thi-b492_56_birds-10  0.107676
                     concentrate         Atl-79fc_231_bird-17 -0.093113
                     unique            Ser-d28b_44_mammals-64  0.359230
                     use                 Atl-f357_23_salmon-7  0.663917
                     use                 Bom-c423_293_bees-22  0.531577
                     use               She-572b_21_animals-14  1.277724
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (1332,)
ftok (28, 2)
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1331, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1329, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1329, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1322, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1329, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1330, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1331, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1331, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1331, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1329, dtype: float64
Spearman results
feat_tests
                                  test_pvalue  test_dX  test_Nx  test_N  \
arcpath              lemma
acl:relcl>           call             0.23353   -0.666        1    1332
                     contain          0.00975   -0.835        3    1332
                     have             0.00292   -0.961        3    1332
                     include          0.00001   -0.766       10    1332
acl>obl>nmod:poss>   its              0.01306   -0.801        3    1332
nmod<nsubj:pass<obl> diet             0.90264    0.048        2    1332
obl<                 achieve          0.84999    0.106        1    1332
                     concentrate      0.86501   -0.095        1    1332
                     unique           0.52275    0.358        1    1332
                     use              0.01068    0.824        3    1332

                                  test_st
arcpath              lemma
acl:relcl>           call           -1.19
                     contain        -2.59
                     have           -2.98
                     include        -4.35
acl>obl>nmod:poss>   its            -2.49
nmod<nsubj:pass<obl> diet            0.12
obl<                 achieve         0.19
                     concentrate    -0.17
                     unique          0.64
                     use             2.56
book_cl_elong
                              effect        Dx   N      eff2  test_pvalue  \
arcpath            lemma
acl:relcl>         include -0.771728  0.001694  10  0.595564      0.00001
                   contain -0.753686  0.000493   3  0.568042      0.00975
obl<               achieve  0.718221  0.000222   1  0.515841      0.84999
                   use      0.712818  0.000120   3  0.508110      0.01068
                   unique   0.711457  0.000193   1  0.506170      0.52275
acl:relcl>         call    -0.709162  0.000222   1  0.502911      0.23353
                   have    -0.703773  0.000412   3  0.495296      0.00292
acl>obl>nmod:poss> its     -0.703625  0.000787   3  0.495088      0.01306

                            test_dX  test_Nx  test_N  test_st
arcpath            lemma
acl:relcl>         include   -0.766       10    1332    -4.35
                   contain   -0.835        3    1332    -2.59
obl<               achieve    0.106        1    1332     0.19
                   use        0.824        3    1332     2.56
                   unique     0.358        1    1332     0.64
acl:relcl>         call      -0.666        1    1332    -1.19
                   have      -0.961        3    1332    -2.98
acl>obl>nmod:poss> its       -0.801        3    1332    -2.49
cluster ====> 7
np.sqrt(eigvals)
[0.80997743 1.10038373 1.2566561  1.61377408 1.70595307 2.32934393
 2.44514931 2.70824346]
cl_elong_a, cl_elong_v.round(2)
1.1075983949986414 [-0.86 -0.29 -0.02 -0.25  0.08  0.19 -0.08  0.25]
cluster data sample, mean shift
(128, 8)                                  0         1         2         3         4  \
token_id
Cor-270b_264_Corvus-99    0.295753  3.831563  1.152315 -0.589901 -2.816580
All-7078_390_Dinosaurs-1  1.662505  3.296345  0.640880  3.501885  1.224498
Ham-9078_75_shark-36     -1.810255  2.770594  0.728095  0.416190 -0.749905

                                 5         6         7
token_id
Cor-270b_264_Corvus-99    1.510947 -1.014890 -2.082122
All-7078_390_Dinosaurs-1 -1.591875 -1.931148 -3.403993
Ham-9078_75_shark-36      0.711914  1.071881  0.103578
cluster data elongation along main axis
                         effect        Dx   N      eff2
arcpath    lemma
nmod>case> throughout -0.802088  0.001087   1  0.643345
           include    -0.777388  0.004553   7  0.604332
           such       -0.754215  0.007683  16  0.568840
           of         -0.714008  0.001517   7  0.509808
           within     -0.696511  0.002016   2  0.485128
           from       -0.682020  0.001253   3  0.465151
           to         -0.679576  0.005758   6  0.461824
amod>      gray       -0.676412  0.001067   1  0.457533
           black      -0.674611  0.001452   2  0.455099
nmod>case> in         -0.673234  0.004082  10  0.453244
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                             token         x
arcpath    lemma
amod>      black              Com-3b7c_19_birds-36 -4.716474
           black               Eur-35e8_60_gull-19 -3.349200
           gray             Sci-501e_7_squirrel-17 -0.368754
nmod>case> from             Cir-aed8_63_animals-42 -2.967543
           from                 Arc-b4f2_43_bird-8 -3.705202
           from            Lea-dca1_2_dinosaurs-17 -1.707399
           in                   Roe-b5ac_55_deer-8 -3.978991
           in                 Euo-1402_2_spider-13 -3.421679
           in               Rho-d4a0_238_plants-15 -4.881607
           in                Bur-9073_53_plants-17 -2.615279
           in                   Vio-0709_9_plant-6 -3.684067
           in                  Mar-9b95_2_mammal-8 -4.075736
           in                 Hem-78f3_7_insects-2 -5.043062
           in                   Roo-1bd1_22_bird-7 -3.286340
           in                    Blabf9a_12_ants-9 -3.031495
           in            Jel-28f4_209_jellyfish-54 -0.552635
           include           Agl-fec0_26_plants-12 -0.691474
           include        Bio-20c0_102_cnidaria-46 -0.105190
           include          Bio-20c0_148_animals-3 -3.758210
           include         Cha-1a30_159_animals-19  0.495082
           include            Euo-1402_2_spider-13 -3.421679
           include          Flo-23b8_35_animals-19 -1.803145
           include          Rho-d4a0_238_plants-15 -4.881607
           of               Bio-20c0_148_animals-3 -3.758210
           of               Pin-feaf_2_conifers-23 -4.018128
           of                Bir-154b_106_Birds-40  2.824040
           of               Orb-0601_125_Spiders-1  0.694177
           of                Pas-2c4d_116_birds-67  1.422175
           of                   Vio-0709_9_plant-6 -3.684067
           of                 Wes-9ef7_125_Birds-9  0.078227
           such             Boa-7d46_69_lizards-23 -0.542358
           such              Bur-9073_53_plants-17 -2.615279
           such        Cae-3f0c_154_vertebrates-23  0.054477
           such             Cir-aed8_63_animals-42 -2.967543
           such            Coa-44f0_179_animals-28  0.024571
           such               Com-3b7c_19_birds-36 -4.716474
           such              Gre-0f9b_76_birds-102  1.011578
           such              Ham-9078_75_sharks-23 -2.726671
           such              Mon-1726_257_plants-7 -2.674455
           such              Pap-75c9_7_Papilio-22 -2.110376
           such             Pin-feaf_2_conifers-23 -4.018128
           such              Pla-2751_104_plants-3 -3.010530
           such             Sho-fcec_73_mammals-18 -2.454346
           such            Sno-0a8f_245_mammals-33 -2.118270
           such            Son-520b_65_thrushes-29 -3.357597
           such            Tur-2bce_104_animals-25 -0.416492
           throughout           Roe-b5ac_55_deer-8 -3.978991
           to                 Euo-1402_2_spider-13 -3.421679
           to                   Arc-b4f2_43_bird-8 -3.705202
           to                    Asi-28dd_21_cat-9 -3.731708
           to           Cni-c1f9_228_cnidarians-34 -3.009683
           to                 Hem-78f3_7_insects-2 -5.043062
           to                   Roo-1bd1_22_bird-7 -3.286340
           within              Mar-9b95_2_mammal-8 -4.075736
           within        Sal-5617_108_amphibians-2 -3.673091
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (128,)
ftok (55, 2)
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Mar-9b95_2_mammal-8        -4.075736
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 126, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 127, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 125, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 118, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 121, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 121, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Car-fccf_17_mammals-15     -0.956986
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 112, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 127, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 122, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 126, dtype: float64
Spearman results
feat_tests
                       test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
amod>      black           0.02439   -4.120        2     128    -2.28
           gray            0.87960   -0.394        1     128    -0.15
nmod>case> from            0.05529   -2.884        3     128    -1.93
           in              0.00000   -3.775       10     128    -4.82
           include         0.03026   -2.165        7     128    -2.19
           of              0.32168   -0.997        7     128    -0.99
           such            0.00050   -2.357       16     128    -3.58
           throughout      0.11968   -4.033        1     128    -1.57
           to              0.00022   -3.905        6     128    -3.81
           within          0.03068   -3.959        2     128    -2.19
book_cl_elong
                         effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath    lemma
nmod>case> throughout -0.802088  0.001087   1  0.643345      0.11968   -4.033
           include    -0.777388  0.004553   7  0.604332      0.03026   -2.165
           such       -0.754215  0.007683  16  0.568840      0.00050   -2.357
           of         -0.714008  0.001517   7  0.509808      0.32168   -0.997
           within     -0.696511  0.002016   2  0.485128      0.03068   -3.959
           from       -0.682020  0.001253   3  0.465151      0.05529   -2.884
           to         -0.679576  0.005758   6  0.461824      0.00022   -3.905
amod>      gray       -0.676412  0.001067   1  0.457533      0.87960   -0.394
           black      -0.674611  0.001452   2  0.455099      0.02439   -4.120
nmod>case> in         -0.673234  0.004082  10  0.453244      0.00000   -3.775

                       test_Nx  test_N  test_st
arcpath    lemma
nmod>case> throughout        1     128    -1.57
           include           7     128    -2.19
           such             16     128    -3.58
           of                7     128    -0.99
           within            2     128    -2.19
           from              3     128    -1.93
           to                6     128    -3.81
amod>      gray              1     128    -0.15
           black             2     128    -2.28
nmod>case> in               10     128    -4.82
cluster ====> 8
np.sqrt(eigvals)
[0.56421749 0.67182982 0.74075103 0.76203468 0.9330763  1.01076916
 1.28514622 2.98271395]
cl_elong_a, cl_elong_v.round(2)
2.3209140775452712 [ 0.26  0.65 -0.11 -0.03  0.51  0.25 -0.42 -0.02]
cluster data sample, mean shift
(525, 8)                               0         1         2         3         4  \
token_id
Rep-aa64_410_snakes-9  0.359614  0.230088 -1.278415 -0.134880  0.267500
Pin-a6d8_2_pine-10    -0.463923 -0.120735  1.663284 -1.343133  1.438222
Kin-dc2e_72_snake-26   0.673100  0.144951  1.276909  0.085060 -0.278574

                              5         6         7
token_id
Rep-aa64_410_snakes-9  0.127630 -2.106340 -1.127459
Pin-a6d8_2_pine-10     0.130861  2.684335 -0.576013
Kin-dc2e_72_snake-26   0.937551  4.097514 -0.439989
cluster data elongation along main axis

                        effect        Dx   N      eff2
arcpath    lemma
case>      from       0.512475 -0.000266   1  0.262630
acl:relcl> fly       -0.507750  0.000312   1  0.257810
obl<       higher     0.504366  0.000189   1  0.254385
conj<conj> waterfowl -0.500098  0.000708   2  0.250098
case>      of         0.497451 -0.001521   3  0.247457
conj<conj> marmot    -0.496653  0.001062   3  0.246664
           hedgehog  -0.487617  0.000708   2  0.237771
           squirrel  -0.486893  0.006020  17  0.237065
           seabird   -0.485202  0.000708   2  0.235421
case>      in         0.482628 -0.000417   1  0.232930
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                            token         x
arcpath    lemma
acl:relcl> fly              Com-f222_150_birds-26  0.481457
case>      from              Hor-ab9c_205_bats-17  1.041855
           in              Gro-2286_16_beetles-35  1.751050
           of                Pte-5908_14_animal-6  0.795176
           of               Red-d827_153_Birds-14  1.832718
           of            Rep-aa64_168_reptiles-18  1.327870
conj<conj> hedgehog       Ear-b650_253_beetles-25 -2.608653
           hedgehog        Hib-c4bb_29_rodents-11 -0.704696
           marmot            Eur-9931_185_deer-45 -5.245632
           marmot            Eur-9931_185_deer-48 -5.223102
           marmot         Eur-9931_185_rodents-21 -5.105360
           seabird    Oct-f4f7_270_cephalopods-24 -0.779433
           seabird          Req-2240_29_sharks-32 -2.297404
           squirrel          Eur-9931_185_deer-45 -5.245632
           squirrel          Eur-9931_185_deer-48 -5.223102
           squirrel       Eur-9931_185_rodents-21 -5.105360
           squirrel       Eas-e016_177_rodents-15 -0.106142
           squirrel            Nor-bda1_8_deer-44 -4.415807
           squirrel            Nor-bda1_8_deer-49 -4.189485
           squirrel       Nor-bda1_8_squirrels-15 -4.350743
           squirrel       Nor-bda1_8_squirrels-19 -3.946834
           squirrel        Per-01a0_75_mammals-36  0.036791
           squirrel         Que0eb3_19_mammals-17  0.505580
           squirrel        Rat-4b67_33_animals-18 -0.394119
           squirrel        Sci-501e_7_squirrel-35  0.185842
           squirrel        Sci-501e_7_squirrel-40  0.401226
           squirrel        Sci-501e_7_squirrel-57 -0.670827
           squirrel        Sci-501e_7_squirrel-63 -0.451672
           squirrel        Sci-501e_7_squirrel-68 -0.204199
           squirrel        Sci-501e_9_squirrel-24 -2.066153
           waterfowl        Riv-1495_224_birds-27 -1.182239
           waterfowl        Riv-1495_224_birds-32 -1.057329
obl<       higher          Nor-c9d9_52_rodents-31  2.940471
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (525,)
ftok (33, 2)
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 524, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 524, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 524, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 522, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 523, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 522, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 523, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 508, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 523, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 524, dtype: float64
Spearman results
feat_tests
                      test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
acl:relcl> fly            0.70329    0.561        1     525     0.38
case>      from           0.44611    1.123        1     525     0.76
           in             0.21328    1.833        1     525     1.25
           of             0.09887    1.406        3     525     1.65
conj<conj> hedgehog       0.12864   -1.584        2     525    -1.52
           marmot         0.00000   -5.142        3     525    -6.25
           seabird        0.15991   -1.465        2     525    -1.41
           squirrel       0.00000   -2.061       17     525    -5.86
           waterfowl      0.31645   -1.045        2     525    -1.00
obl<       higher         0.03977    3.025        1     525     2.06
book_cl_elong
                        effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath    lemma
case>      from       0.512475 -0.000266   1  0.262630      0.44611    1.123
obl<       higher     0.504366  0.000189   1  0.254385      0.03977    3.025
conj<conj> waterfowl -0.500098  0.000708   2  0.250098      0.31645   -1.045
case>      of         0.497451 -0.001521   3  0.247457      0.09887    1.406
conj<conj> marmot    -0.496653  0.001062   3  0.246664      0.00000   -5.142
           hedgehog  -0.487617  0.000708   2  0.237771      0.12864   -1.584
           squirrel  -0.486893  0.006020  17  0.237065      0.00000   -2.061
           seabird   -0.485202  0.000708   2  0.235421      0.15991   -1.465
case>      in         0.482628 -0.000417   1  0.232930      0.21328    1.833

                      test_Nx  test_N  test_st
arcpath    lemma
case>      from             1     525     0.76
obl<       higher           1     525     2.06
conj<conj> waterfowl        2     525    -1.00
case>      of               3     525     1.65
conj<conj> marmot           3     525    -6.25
           hedgehog         2     525    -1.52
           squirrel        17     525    -5.86
           seabird          2     525    -1.41
case>      in               1     525     1.25
cluster ====> 9
np.sqrt(eigvals)
[0.34838879 0.47693821 0.51050328 0.53708375 0.61027253 0.69511422
 0.83622693 1.05344033]
cl_elong_a, cl_elong_v.round(2)
1.2597541283848959 [ 0.1   0.02 -0.13  0.77  0.59  0.09  0.07 -0.09]
cluster data sample, mean shift
(2384, 8)                                   0         1         2         3         4  \
token_id
Sci-501e_7_squirrel-5      0.637601 -0.684479  0.628093  0.609925  0.372686
Ven-77c9_97_arthropods-16 -0.247887 -0.332420 -1.739143  1.609059 -0.349564
Ham-9078_102_sharks-13    -1.327506  0.625702  0.435497 -0.671847 -0.273906

                                  5         6         7
token_id
Sci-501e_7_squirrel-5     -1.470967 -0.415595  1.297738
Ven-77c9_97_arthropods-16  0.147505  0.889617  0.159340
Ham-9078_102_sharks-13     0.541869  0.840101  0.022440
cluster data elongation along main axis
                       effect        Dx   N      eff2
arcpath lemma
det>    those       -0.958516  0.000032   1  0.918753
        both        -0.953254  0.000482   4  0.908693
        no          -0.931955  0.000543   4  0.868541
        some        -0.929061  0.001081  23  0.863154
        any         -0.927626  0.000177   8  0.860490
amod>   predatory    0.925152  0.000151   5  0.855906
        terrestrial  0.924368  0.000452   8  0.854456
det>    a           -0.922012  0.001334  63  0.850106
        each        -0.921188  0.000130   1  0.848587
amod>   most         0.920634  0.000369  13  0.847567
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                   token         x
arcpath lemma
amod>   most   Art-1308_168_arthropods-2  0.508565
        most       Bov-d455_162_bovids-2  0.793022
        most      Col-6d94_171_plants-29 -0.619072
        most         Dra-242f_8_plants-4  1.234355
        most        Eur-35e8_138_bird-12  1.027774
...                                  ...       ...
det>    some         Too-567c_25_birds-2 -0.684618
        some       Too-567c_343_birds-33 -0.566455
        some       Too-567c_48_animals-2 -1.721029
        some      Ven-071d_69_lizards-23 -1.025333
        those     Swa-27b4_32_animals-36 -0.862943

[130 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (2384,)
ftok (130, 2)
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Lil-8f8e_2_Liliopsida-1     -0.570984
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2371, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2379, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Cro-0859_276_crocodile-61    0.667533
Pra-7b55_29_Rodentia-2       1.196157
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2376, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2321, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2376, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2380, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2383, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2380, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2361, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2383, dtype: float64
Spearman results
feat_tests
                     test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath lemma
amod>   most             0.00002    0.955       13    2384     4.33
        predatory        0.32219    0.353        5    2384     0.99
        terrestrial      0.02573    0.629        8    2384     2.23
det>    a                0.00002   -0.429       63    2384    -4.23
        any              0.27835   -0.306        8    2384    -1.08
        both             0.04212   -0.810        4    2384    -2.03
        each             0.81657    0.185        1    2384     0.23
        no               0.82672   -0.087        4    2384    -0.22
        some             0.00000   -0.938       23    2384    -5.66
        those            0.29030   -0.843        1    2384    -1.06
book_cl_elong
                       effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath lemma
det>    those       -0.958516  0.000032   1  0.918753      0.29030   -0.843
        both        -0.953254  0.000482   4  0.908693      0.04212   -0.810
        no          -0.931955  0.000543   4  0.868541      0.82672   -0.087
        some        -0.929061  0.001081  23  0.863154      0.00000   -0.938
        any         -0.927626  0.000177   8  0.860490      0.27835   -0.306
amod>   predatory    0.925152  0.000151   5  0.855906      0.32219    0.353
        terrestrial  0.924368  0.000452   8  0.854456      0.02573    0.629
det>    a           -0.922012  0.001334  63  0.850106      0.00002   -0.429
amod>   most         0.920634  0.000369  13  0.847567      0.00002    0.955

                     test_Nx  test_N  test_st
arcpath lemma
det>    those              1    2384    -1.06
        both               4    2384    -2.03
        no                 4    2384    -0.22
        some              23    2384    -5.66
        any                8    2384    -1.08
amod>   predatory          5    2384     0.99
        terrestrial        8    2384     2.23
det>    a                 63    2384    -4.23
amod>   most              13    2384     4.33
===========  end ==============

In [152]:
token_elong

token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2384, dtype: float64

In [80]:
res = analyze_category('adaptation')

checking for data/q_cluster/BGM_full_covar_adaptation.pkl
BGM loaded
bgm.predict(my_ica_data)).value_counts()
1    754
6    631
2    426
3    378
4    321
8    307
9    306
5    269
0    130
7     56
Name: count, dtype: int64
clust_feats (7134, 2)
                  cluster  freq
arcpath    lemma
cop>       be           1   159
           be           9   140
case>      of           8   131
conj>cc>   and          9   100
amod<case> of           6    87
=========================
clust_f_df pivot table (3355, 10)
clust_p_df is the probability distribution cluster-wise
                               0         1         2    3        4    5    6  \
arcpath              lemma
acl:relcl<           theory  0.0  0.000583  0.000000  0.0  0.00000  0.0  0.0
acl:relcl<amod>      other   0.0  0.000000  0.000000  0.0  0.00132  0.0  0.0
acl:relcl<case>      to      0.0  0.000000  0.000000  0.0  0.00066  0.0  0.0
acl:relcl<det>       the     0.0  0.000291  0.000324  0.0  0.00000  0.0  0.0
acl:relcl<nmod>case> of      0.0  0.000000  0.000324  0.0  0.00000  0.0  0.0

                               7    8         9
arcpath              lemma
acl:relcl<           theory  0.0  0.0  0.000000
acl:relcl<amod>      other   0.0  0.0  0.000000
acl:relcl<case>      to      0.0  0.0  0.000388
acl:relcl<det>       the     0.0  0.0  0.001164
acl:relcl<nmod>case> of      0.0  0.0  0.000776
=========================
Elementwise relative entropy by clusters, feature-wise
                           0         1         2         3         4  \
arcpath    lemma
cop>       be       0.000879  0.042825 -0.000224 -0.001966 -0.006378
nmod>case> of      -0.005391 -0.002539  0.005422  0.000000 -0.002103
nsubj<     include -0.003007 -0.004876 -0.001236  0.000000 -0.003179
case>      of       0.000000 -0.001128  0.011436  0.000000 -0.001946
det>       the     -0.002551 -0.002101  0.020928 -0.002747 -0.000365

                           5         6         7         8         9
arcpath    lemma
cop>       be       0.005879 -0.003349  0.000000  0.000000  0.058856
nmod>case> of       0.051056  0.000000  0.093501  0.000000 -0.000064
nsubj<     include  0.004897 -0.002383  0.254891  0.000000  0.000000
case>      of      -0.003103 -0.002343  0.000000  0.196415 -0.004453
det>       the      0.033776 -0.001331  0.000000 -0.003704  0.009852
========== clust_featdx_df ===============
                                    Dx   N
cluster arcpath    lemma
7       nmod>case> of         0.093501  18
3       amod<      structure  0.036440  15
2       nmod>case> in         0.013629  35
8       amod>      human      0.081236  61
2       nmod>case> such       0.019305  42
=========================
pred_feats
feat_v
                                   0         1         2         3         4  \
arcpath          lemma
acl:relcl>nsubj> that      -0.062988 -0.031006 -0.225952  0.068970 -0.026001
advmod>          highly    -0.081970 -0.160034 -0.350098 -0.029999  0.068970
amod<            animal    -0.261963  0.136963 -0.220947  0.061005 -0.080994
                 behavior  -0.159058  0.010002 -0.128052  0.078003 -0.085022
                 behaviour -0.161987 -0.001000 -0.096985  0.062012 -0.099976

                                   5         6         7
arcpath          lemma
acl:relcl>nsubj> that      -0.140991  0.068970 -0.194946
advmod>          highly     0.080017  0.049988  0.122009
amod<            animal     0.139038 -0.175049 -0.150024
                 behavior   0.026993 -0.094971 -0.078979
                 behaviour  0.014999 -0.046997 -0.042999
mean_norm
[[ 0.04  0.08 -0.76  0.28 -0.19  0.32  0.43  0.13]
 [-0.25 -0.24 -0.16  0.6  -0.52 -0.36 -0.18 -0.23]
 [ 0.89 -0.1  -0.22 -0.08  0.29  0.16 -0.14  0.14]
 [-0.45 -0.01  0.61  0.35 -0.42 -0.16 -0.18  0.27]
 [-0.1   0.58  0.44 -0.37  0.45  0.04 -0.1  -0.34]
 [ 0.82  0.2  -0.03  0.28 -0.28  0.04 -0.2   0.3 ]
 [-0.77 -0.25 -0.17  0.13 -0.29  0.02 -0.25  0.39]
 [ 0.11  0.98  0.01  0.01 -0.15 -0.    0.02  0.1 ]
 [-0.23  0.02  0.19  0.01  0.92  0.01 -0.06  0.25]
 [ 0.48 -0.06 -0.28 -0.04 -0.17  0.01  0.03 -0.81]]
cos_predict.head(5)
                            0         1         2         3         4  \
arcpath       lemma
cc>           and    0.150172  0.197423 -0.075814 -0.116608 -0.094578
conj<conj>cc> and    0.291450 -0.004813  0.065358 -0.203398 -0.239811
conj<cop>     be     0.150587  0.162651 -0.200854  0.005861  0.023474
cc>           or     0.087285  0.174408 -0.138729  0.047826 -0.064327
amod>         other  0.082509  0.158398 -0.153726  0.071887 -0.075069

                            5         6         7         8         9
arcpath       lemma
cc>           and   -0.102399  0.015079 -0.053099 -0.106580  0.195120
conj<conj>cc> and   -0.086625  0.175428 -0.166796  0.040589 -0.038769
conj<cop>     be    -0.145465  0.224484  0.097454 -0.078506  0.056893
cc>           or    -0.082558  0.170020 -0.005239 -0.078763  0.031635
amod>         other -0.087664  0.173802 -0.009392 -0.080327 -0.002453
score_predict.head(5)
                         0      1      2    3      4      5      6    7  \
arcpath       lemma
cc>           and    0.001  0.762  0.017  0.0  0.161  0.045  0.004  0.0
conj<conj>cc> and    0.002  0.690  0.039  0.0  0.106  0.122  0.021  0.0
conj<cop>     be     0.001  0.777  0.012  0.0  0.140  0.031  0.033  0.0
cc>           or     0.001  0.743  0.010  0.0  0.170  0.041  0.028  0.0
amod>         other  0.001  0.731  0.010  0.0  0.172  0.044  0.033  0.0

                         8      9
arcpath       lemma
cc>           and    0.001  0.010
conj<conj>cc> and    0.006  0.013
conj<cop>     be     0.001  0.006
cc>           or     0.003  0.005
amod>         other  0.005  0.005
                            0         1         2    3        4         5  \
arcpath       lemma
cc>           and    0.054087  0.004661  0.002268  0.0  0.00000  0.001310
conj<conj>cc> and    0.037260  0.000291  0.000000  0.0  0.00000  0.000000
conj<cop>     be     0.033654  0.001165  0.001620  0.0  0.00000  0.000000
cc>           or     0.010817  0.000291  0.000324  0.0  0.00000  0.000000
amod>         other  0.013221  0.002330  0.004861  0.0  0.00396  0.009168

                            6         7         8         9
arcpath       lemma
cc>           and    0.026119  0.000000  0.000763  0.003879
conj<conj>cc> and    0.000000  0.000000  0.000000  0.001552
conj<cop>     be     0.007048  0.000000  0.000000  0.001164
cc>           or     0.005804  0.000000  0.000000  0.000388
amod>         other  0.001244  0.018315  0.006102  0.002715
===========  end ==============

In [82]:
res['clust_featdx_df_short']

                                          Dx    N
cluster arcpath          lemma
0       cc>              and        0.095173   45
        conj<conj>cc>    and        0.083995   31
        conj<cop>        be         0.067975   28
        conj<det>        the        0.037252   14
                         a          0.026249   10
1       cop>             be         0.042825  159
        conj>cc>         and        0.017637   64
        obj<             have       0.014957   33
        nsubj<cop>       be         0.013444   51
        compound<det>    the        0.013096   33
2       nmod>det>        the        0.021774   61
        det>             the        0.020928   75
        nmod>case>fixed> as         0.019305   42
        nmod>case>       such       0.019305   42
                         in         0.013629   35
3       amod<cc>         and        0.101903   35
        amod<            behavior   0.070457   25
                         behaviour  0.047395   17
        compound<case>   of         0.037640   14
        amod<            structure  0.036440   15
4       obl<aux:pass>    be         0.053872   42
        obl<mark>        to         0.042485   30
        case>            from       0.039231   33
                         as         0.030477   27
                         by         0.026708   22
5       nmod>case>       of         0.051056   72
        nsubj<cop>       be         0.043491   43
        det>             the        0.033776   47
        nsubj<conj>cc>   and        0.031434   36
        nmod>det>        the        0.022905   31
6       amod<case>       of         0.077156   87
        amod<det>        the        0.060507   74
                         a          0.049745   64
        amod<case>       in         0.039302   45
        amod<cop>        be         0.033319   46
7       nsubj<           include    0.254891   33
        nmod>case>       of         0.093501   18
        nsubj<obj>conj>  fox        0.066827    8
                         wolf       0.050606    6
                         bird       0.049961    6
8       case>            of         0.196415  131
        nmod<det>        the        0.125495   80
        amod>            human      0.081236   61
        case>            in         0.063661   47
        nmod<det>        a          0.057369   38
9       conj>cc>         and        0.065120  100
        cop>             be         0.058856  140
        nsubj>det>       the        0.023393   38
        conj>cc>         but        0.016707   21
        conj>nmod>case>  of         0.012190   14

True

In [83]:
cresTop = analyze_category('topic',True)

checking for data/q_cluster/BGM_full_covar_topic.pkl
BGM loaded
bgm.predict(my_ica_data)).value_counts()
4    8896
0    6276
5    5179
8    5004
1    4837
9    3572
6    2254
7    1892
3    1364
2     259
Name: count, dtype: int64
clust_feats (80022, 2)
                  cluster  freq
arcpath    lemma
case>      of           5  2803
det>       the          4  2236
cc>        and          9  1723
nsubj<cop> be           4  1693
conj>cc>   and          0  1583
=========================
clust_f_df pivot table (39715, 10)
clust_p_df is the probability distribution cluster-wise
                                0         1    2    3         4    5  \
arcpath         lemma
acl:relcl<      animal   0.000041  0.000022  0.0  0.0  0.000000  0.0
acl:relcl<case> in       0.000020  0.000000  0.0  0.0  0.000000  0.0
                include  0.000041  0.000000  0.0  0.0  0.000000  0.0
                of       0.000061  0.000044  0.0  0.0  0.000018  0.0
                with     0.000041  0.000000  0.0  0.0  0.000000  0.0

                                6    7    8    9
arcpath         lemma
acl:relcl<      animal   0.000000  0.0  0.0  0.0
acl:relcl<case> in       0.000035  0.0  0.0  0.0
                include  0.000000  0.0  0.0  0.0
                of       0.000000  0.0  0.0  0.0
                with     0.000000  0.0  0.0  0.0
=========================
Elementwise relative entropy by clusters, feature-wise
                            0         1         2         3         4  \
arcpath       lemma
det>          the    0.010605  0.018945 -0.006144  0.000000  0.033138
case>         of     0.002828 -0.001154 -0.002765  0.000000 -0.001857
cc>           and   -0.000607 -0.001740 -0.003679  0.000000 -0.003533
conj<conj>cc> and   -0.000464 -0.001159  0.003259  0.000000 -0.000476
conj>cc>      and    0.045635 -0.002840 -0.002810 -0.002055 -0.002602

                            5         6         7         8         9
arcpath       lemma
det>          the    0.020697  0.009021 -0.005791 -0.003572 -0.006132
case>         of     0.158360 -0.003672 -0.000619 -0.001101  0.000000
cc>           and    0.000000 -0.003413  0.006159 -0.000537  0.123504
conj<conj>cc> and    0.000000 -0.002567  0.065665  0.000000  0.054071
conj>cc>      and   -0.002335  0.051015 -0.001236 -0.002215 -0.000810
========== clust_featdx_df ===============
                                              Dx     N
cluster arcpath              lemma
1       det>                 the        0.018945  1425
5       case>                of         0.158360  2803
3       appos>               reference  0.072228    64
6       cop>                 be         0.012789   262
1       nsubj:pass<aux:pass> be         0.027698   769
=========================
pred_feats
feat_v
                                  0         1         2         3         4  \
arcpath          lemma
acl:relcl>nsubj> that     -0.062988 -0.031006 -0.225952  0.068970 -0.026001
                 which    -0.026993 -0.062988 -0.218018  0.080017  0.065979
amod>            african   0.415039  0.003000 -0.490967  0.591797  0.271973
                 common    0.469971  0.033997 -0.514160  0.641113  0.316895
                 european  0.458008  0.032990 -0.497070  0.551758  0.262939

                                  5         6         7
arcpath          lemma
acl:relcl>nsubj> that     -0.140991  0.068970 -0.194946
                 which    -0.091980  0.182983 -0.238037
amod>            african  -0.340088  0.029999 -0.014000
                 common   -0.314941  0.091980  0.020996
                 european -0.368896  0.104004  0.093994
mean_norm
[[-0.12  0.21  0.2  -0.26  0.25 -0.23 -0.17 -0.83]
 [ 0.72 -0.13 -0.35 -0.07 -0.07  0.45 -0.23  0.28]
 [ 0.15 -0.2  -0.01 -0.21 -0.15  0.03  0.93 -0.01]
 [-0.46  0.08  0.69  0.23 -0.35 -0.08 -0.22  0.28]
 [-0.12 -0.04 -0.15 -0.07 -0.66  0.03 -0.51  0.52]
 [-0.26 -0.03  0.2  -0.24  0.88  0.01 -0.11  0.22]
 [ 0.22 -0.16 -0.38 -0.16  0.05 -0.08 -0.08 -0.86]
 [-0.1  -0.   -0.12  0.05 -0.1   0.07  0.98  0.02]
 [-0.35 -0.15  0.64  0.34 -0.33 -0.37 -0.15  0.26]
 [-0.49  0.1  -0.38  0.18 -0.46  0.22  0.49  0.28]]
cos_predict.head(5)
                            0         1         2         3         4  \
arcpath       lemma
conj>cc>      and    0.113933 -0.099139  0.050291 -0.162928 -0.085752
obl<cop>      be     0.129717 -0.095287  0.153824 -0.247292 -0.230546
obl<aux:pass> be    -0.148502  0.245953 -0.080672 -0.471835 -0.229989
case>         to    -0.200182  0.289855 -0.037447 -0.520856 -0.280101
det>          the   -0.236019  0.278817 -0.003519 -0.483198 -0.209115

                            5         6         7         8         9
arcpath       lemma
conj>cc>      and   -0.119202  0.238046  0.093284 -0.094747  0.086193
obl<cop>      be    -0.069254  0.274914  0.194389 -0.170507  0.076603
obl<aux:pass> be    -0.118670  0.233154  0.025117 -0.230780 -0.099126
case>         to    -0.109692  0.206382  0.083583 -0.277058 -0.080214
det>          the   -0.114972  0.149592  0.093123 -0.237219 -0.057751
score_predict.head(5)
                         0      1    2    3      4      5      6      7    8  \
arcpath       lemma
conj>cc>      and    0.586  0.046  0.0  0.0  0.316  0.040  0.002  0.002  0.0
obl<cop>      be     0.737  0.063  0.0  0.0  0.157  0.026  0.004  0.004  0.0
obl<aux:pass> be     0.634  0.107  0.0  0.0  0.236  0.015  0.004  0.002  0.0
case>         to     0.662  0.142  0.0  0.0  0.175  0.010  0.005  0.003  0.0
det>          the    0.632  0.130  0.0  0.0  0.216  0.011  0.005  0.003  0.0

                         9
arcpath       lemma
conj>cc>      and    0.007
obl<cop>      be     0.008
obl<aux:pass> be     0.001
case>         to     0.001
det>          the    0.002
                            0         1         2         3         4  \
arcpath       lemma
conj>cc>      and    0.032282  0.002374  0.003589  0.000995  0.001702
obl<cop>      be     0.008279  0.001154  0.000000  0.000000  0.000123
obl<aux:pass> be     0.008341  0.007099  0.000538  0.000000  0.000456
case>         to     0.007749  0.002592  0.000000  0.000000  0.000228
det>          the    0.025532  0.031033  0.005384  0.000000  0.039227

                            5         6         7         8         9
arcpath       lemma
conj>cc>      and    0.001296  0.034480  0.000423  0.001156  0.000229
obl<cop>      be     0.000086  0.001919  0.000000  0.000000  0.000000
obl<aux:pass> be     0.000259  0.002652  0.000000  0.000000  0.000000
case>         to     0.006048  0.001989  0.000000  0.000000  0.000038
det>          the    0.032109  0.024394  0.004089  0.001461  0.005307
=========== Internal structure in cluster==============
cluster ====> 0
np.sqrt(eigvals)
[0.32799058 0.45370549 0.54230341 0.60692332 0.69363321 0.82727651
 0.90444641 1.08223637]
cl_elong_a, cl_elong_v.round(2)
1.1965732430453417 [-0.01  0.04 -0.28 -0.07  0.18  0.32 -0.8  -0.37]
cluster data sample, mean shift
(6258, 8)                               0         1         2         3         4  \
token_id
Cli-c809_26_animal-15 -0.308392 -0.707459  0.401081  1.654279  0.020958
Kag-2289_76_worms-15   0.758170  0.477786  0.229863 -0.785759  0.062551
Boi-e3d6_40_humans-23  0.276220  0.414552  1.083768 -0.495066  0.089636

                              5         6         7
token_id
Cli-c809_26_animal-15 -0.358530  0.153425  0.260352
Kag-2289_76_worms-15   1.438481 -0.628320 -1.463834
Boi-e3d6_40_humans-23  0.390080  0.150188  0.598176
cluster data elongation along main axis
                           effect            Dx  N      eff2
arcpath    lemma
conj<conj> martin       -0.814134  2.544002e-05  1  0.662814
           Gallai       -0.796491  2.661539e-05  1  0.634399
           eagle        -0.783533 -5.591858e-05  1  0.613924
           capuching    -0.738240  2.661539e-05  1  0.544998
conj>      Cricetidae    0.733911  9.391215e-05  2  0.538625
           nigricollis   0.732839  9.391215e-05  2  0.537052
           Ornithischia  0.724404  6.869657e-05  2  0.524761
           Reptilia      0.723743  4.107193e-07  1  0.523803
           Stegosauria   0.723654  7.823675e-05  3  0.523675
           Saurischia    0.723031  1.876529e-05  1  0.522774
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                                token         x
arcpath    lemma
conj<conj> Gallai                 Gir-cc25_27_Rook-83 -1.532002
           capuching          Ceb-b443_19_capuchin-18 -1.070245
           eagle               Nor-4d51_285_eagles-16 -0.514836
           martin              Coma03b_19_swallows-18 -1.121982
conj>      Cricetidae          New-caad_18_Rodentia-5  0.755989
           Cricetidae          Shr-2a0f_11_Muridae-14  1.026054
           Ornithischia     Pte-62aa_25_Saurischia-33  1.014217
           Ornithischia      Sau-6bc5_51_Theropoda-20  0.693645
           Reptilia           Cro-9102_581_Amphibia-5  0.314303
           Saurischia    Orn-f740_113_Ornithischia-35  1.327374
           Stegosauria     Thy-db39_14_Ankylosauria-8  0.449961
           Stegosauria    Thy-db39_56_Ankylosauria-28  1.071223
           Stegosauria      Thy-db39_6_Ankylosauria-9  0.736581
           nigricollis            Har-f3ef_43_hare-61  0.467802
           nigricollis            Lep-7440_49_hare-61  0.467802
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
Spearman results
feat_tests
                         test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
conj<conj> Gallai            0.00677   -1.574        1    6258    -2.71
           capuching         0.05578   -1.112        1    6258    -1.91
           eagle             0.33864   -0.556        1    6258    -0.96
           martin            0.04531   -1.163        1    6258    -2.00
conj>      Cricetidae        0.03862    0.850        2    6258     2.07
           Ornithischia      0.04793    0.813        2    6258     1.98
           Reptilia          0.63849    0.273        1    6258     0.47
           Saurischia        0.02687    1.286        1    6258     2.21
           Stegosauria       0.03395    0.712        3    6258     2.12
           nigricollis       0.29925    0.427        2    6258     1.04
book_cl_elong
                           effect            Dx  N      eff2  test_pvalue  \
arcpath    lemma
conj<conj> martin       -0.814134  2.544002e-05  1  0.662814      0.04531
           Gallai       -0.796491  2.661539e-05  1  0.634399      0.00677
           eagle        -0.783533 -5.591858e-05  1  0.613924      0.33864
           capuching    -0.738240  2.661539e-05  1  0.544998      0.05578
conj>      Cricetidae    0.733911  9.391215e-05  2  0.538625      0.03862
           nigricollis   0.732839  9.391215e-05  2  0.537052      0.29925
           Ornithischia  0.724404  6.869657e-05  2  0.524761      0.04793
           Reptilia      0.723743  4.107193e-07  1  0.523803      0.63849
           Stegosauria   0.723654  7.823675e-05  3  0.523675      0.03395
           Saurischia    0.723031  1.876529e-05  1  0.522774      0.02687

                         test_dX  test_Nx  test_N  test_st
arcpath    lemma
conj<conj> martin         -1.163        1    6258    -2.00
           Gallai         -1.574        1    6258    -2.71
           eagle          -0.556        1    6258    -0.96
           capuching      -1.112        1    6258    -1.91
conj>      Cricetidae      0.850        2    6258     2.07
           nigricollis     0.427        2    6258     1.04
           Ornithischia    0.813        2    6258     1.98
           Reptilia        0.273        1    6258     0.47
           Stegosauria     0.712        3    6258     2.12
           Saurischia      1.286        1    6258     2.21
cluster ====> 1
np.sqrt(eigvals)
[0.35763613 0.56465091 0.6729666  0.73558597 0.91585212 1.0168548
 1.1775666  1.33196632]
cl_elong_a, cl_elong_v.round(2)
1.1311176096064157 [ 0.1  -0.98 -0.08  0.16 -0.01  0.01 -0.05  0.05]
cluster data sample, mean shift
(4805, 8)                                0         1         2         3         4  \
token_id
Min-e696_95_deer-24     1.101398 -0.217850  0.300074  1.408250  0.664699
Eur-d3a5_47_rabbit-4    0.452727  1.837853  0.727666  0.521972 -0.700952
Abe-4088_61_animals-15  1.086594 -0.241399  0.126680  0.472765  2.160090

                               5         6         7
token_id
Min-e696_95_deer-24    -0.944259  0.566778 -0.779567
Eur-d3a5_47_rabbit-4   -0.371306  0.035491  1.022848
Abe-4088_61_animals-15  0.509109  0.757491  0.350715
cluster data elongation along main axis

/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

                           effect        Dx  N      eff2
arcpath         lemma
nsubj<obj>conj> bird    -1.275181  0.000086  2  1.626086
                buffalo -1.248956  0.000037  1  1.559891
                snake   -1.129129  0.000086  2  1.274932
                turtle  -1.112352  0.000003  2  1.237327
                shark   -1.092524  0.000050  1  1.193609
                colour  -1.079654  0.000037  1  1.165653
                species -1.072816  0.000028  3  1.150934
                mouse   -1.057641  0.000050  1  1.118604
                frog    -1.033550  0.000028  3  1.068226
                rodent  -1.025442  0.000037  1  1.051531
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                              token         x
arcpath         lemma
nsubj<obj>conj> bird     Boa-7d46_71_constrictors-3 -4.525416
                bird         Kom-6ea1_112_dragons-3 -3.436012
                buffalo        Wil-28c2_2_buffalo-4 -1.866257
                colour     Bla-3ee3_82_blackbuck-26 -0.088108
                frog        Eur-1ed4_36_Hedgehogs-1 -4.198634
                frog     Dip-c98d_261_vertebrates-2 -3.803585
                frog       Gia-bc1d_69_salamander-4 -4.339201
                mouse        Ser-47ca_100_rodents-7 -1.662727
                rodent      Eur-1ed4_36_Hedgehogs-1 -4.198634
                shark         Ham-9078_102_sharks-2 -2.647458
                snake            Gra-2e39_2_snake-3 -1.588313
                snake       Eur-1ed4_36_Hedgehogs-1 -4.198634
                species  Dip-c98d_261_vertebrates-2 -3.803585
                species       Bov-d455_105_bovids-8 -3.029682
                species        Top-df25_97_acacia-2 -1.957448
                turtle       Coa-44f0_176_animals-2 -1.823541
                turtle   Dip-c98d_261_vertebrates-2 -3.803585
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
Spearman results
feat_tests
                         test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath         lemma
nsubj<obj>conj> bird         0.00000   -4.019        2    4805    -4.75
                buffalo      0.11257   -1.904        1    4805    -1.59
                colour       0.91695   -0.125        1    4805    -0.10
                frog         0.00000   -4.153        3    4805    -6.02
                mouse        0.15648   -1.700        1    4805    -1.42
                rodent       0.00041   -4.237        1    4805    -3.54
                shark        0.02520   -2.685        1    4805    -2.24
                snake        0.00055   -2.932        2    4805    -3.46
                species      0.00002   -2.969        3    4805    -4.29
                turtle       0.00077   -2.852        2    4805    -3.36
book_cl_elong
                           effect        Dx  N      eff2  test_pvalue  \
arcpath         lemma
nsubj<obj>conj> bird    -1.275181  0.000086  2  1.626086      0.00000
                buffalo -1.248956  0.000037  1  1.559891      0.11257
                snake   -1.129129  0.000086  2  1.274932      0.00055
                turtle  -1.112352  0.000003  2  1.237327      0.00077
                shark   -1.092524  0.000050  1  1.193609      0.02520
                colour  -1.079654  0.000037  1  1.165653      0.91695
                species -1.072816  0.000028  3  1.150934      0.00002
                mouse   -1.057641  0.000050  1  1.118604      0.15648
                frog    -1.033550  0.000028  3  1.068226      0.00000
                rodent  -1.025442  0.000037  1  1.051531      0.00041

                         test_dX  test_Nx  test_N  test_st
arcpath         lemma
nsubj<obj>conj> bird      -4.019        2    4805    -4.75
                buffalo   -1.904        1    4805    -1.59
                snake     -2.932        2    4805    -3.46
                turtle    -2.852        2    4805    -3.36
                shark     -2.685        1    4805    -2.24
                colour    -0.125        1    4805    -0.10
                species   -2.969        3    4805    -4.29
                mouse     -1.700        1    4805    -1.42
                frog      -4.153        3    4805    -6.02
                rodent    -4.237        1    4805    -3.54
cluster ====> 2
np.sqrt(eigvals)
[1.60212361 1.87888921 1.95575461 2.22891161 2.64418856 3.28685027
 4.47160683 6.77721923]
cl_elong_a, cl_elong_v.round(2)
1.515611609504003 [-0.17 -0.02  0.77 -0.55  0.18 -0.05 -0.22 -0.  ]
cluster data sample, mean shift
(259, 8)                                    0         1         2         3         4  \
token_id
Pap-75c9_71_swallowtail-33 -2.900455 -0.709619 -0.560019 -1.477165 -2.005501
Squ-4431_100_squirrels-32  -1.442266 -0.045520  0.755888 -3.248267  1.026658
Dug-d1d0_10_Dugong-39       1.723697 -2.659033  1.229661  0.224838 -1.140864

                                   5         6         7
token_id
Pap-75c9_71_swallowtail-33 -2.257694 -3.617133  0.513713
Squ-4431_100_squirrels-32  -3.235912 -3.627350  0.417434
Dug-d1d0_10_Dugong-39      -4.776824 -4.301215  0.790131
cluster data elongation along main axis
                        effect        Dx  N      eff2
arcpath lemma
amod>   other        -0.870077 -0.000525  2  0.757033
        various      -0.850802  0.000072  1  0.723864
        terrestrial  -0.825562  0.000017  1  0.681553
        several      -0.824688  0.000121  1  0.680110
        intermediate -0.818810  0.000349  1  0.670450
        small        -0.815473 -0.000317  4  0.664996
        similar      -0.809510  0.000184  1  0.655306
        certain      -0.802992  0.000141  1  0.644796
        native       -0.784129 -0.000015  1  0.614858
        common       -0.773254 -0.001101  3  0.597921
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                           token          x
arcpath lemma
amod>   certain       Blu-41f9_92_ichthyosaurs-8  -5.064866
        common                 Des-ca42_5_bat-26   6.512571
        common         Sep-9969_11_cuttlefish-72  10.611827
        common              Pap-75c9_45_raven-34   4.003099
        intermediate         Hor-ab9c_205_bat-41   0.618230
        native            Hed-8dc6_39_monogyna-2  -4.282905
        other         Apa-3e1a_301_vertebrates-2  -1.446084
        other         Bro-f1dc_297_vertebrates-2  -1.766890
        several             Pas-a544_48_fungi-12  -0.402049
        similar        Chi-0753_14_salamander-29  -1.972490
        small                 Roe-b5ac_55_deer-8   0.244874
        small         Com-3e4d_97_vertebrates-53   1.912784
        small               Cri-fe01_6_mammals-5  -0.284217
        small             Ech-0064_29_mammals-47   0.355400
        terrestrial     Squ-4431_100_squirrels-5  -3.275849
        various             Ste-0d9f_40_squid-35   0.013446
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
Spearman results
feat_tests
                      test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath lemma
amod>   certain           0.06576   -5.100        1     259    -1.85
        common            0.00001    7.110        3     259     4.59
        intermediate      0.82759    0.606        1     259     0.22
        native            0.11986   -4.315        1     259    -1.56
        other             0.40649   -1.634        2     259    -0.83
        several           0.88030   -0.419        1     259    -0.15
        similar           0.47280   -1.995        1     259    -0.72
        small             0.69369    0.551        4     259     0.39
        terrestrial       0.23414   -3.304        1     259    -1.19
        various           0.99955   -0.002        1     259    -0.00
book_cl_elong
                       effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath lemma
amod>   other       -0.870077 -0.000525  2  0.757033      0.40649   -1.634
        various     -0.850802  0.000072  1  0.723864      0.99955   -0.002
        terrestrial -0.825562  0.000017  1  0.681553      0.23414   -3.304
        several     -0.824688  0.000121  1  0.680110      0.88030   -0.419
        similar     -0.809510  0.000184  1  0.655306      0.47280   -1.995
        certain     -0.802992  0.000141  1  0.644796      0.06576   -5.100
        native      -0.784129 -0.000015  1  0.614858      0.11986   -4.315

                     test_Nx  test_N  test_st
arcpath lemma
amod>   other              2     259    -0.83
        various            1     259    -0.00
        terrestrial        1     259    -1.19
        several            1     259    -0.15
        similar            1     259    -0.72
        certain            1     259    -1.85
        native             1     259    -1.56
cluster ====> 3
np.sqrt(eigvals)
[0.0258062  0.02844254 0.03586278 0.05496432 0.09422813 0.11088469
 0.12893851 0.17069969]
cl_elong_a, cl_elong_v.round(2)
1.3238844934223468 [ 0.33  0.4   0.13 -0.52  0.03 -0.58 -0.02  0.33]
cluster data sample, mean shift
(1364, 8)                                       0         1         2         3  \
token_id
Eur-987c_25_vole-3             0.020360 -0.097674  0.164753 -0.062351
Wal-cefe_41_ibex-2            -0.014069 -0.056637  0.113963  0.023487
Nar-f40f_72_pseudonarcissus-2  0.028163  0.024072  0.011681 -0.017651

                                      4         5         6         7
token_id
Eur-987c_25_vole-3             0.182066 -0.064258  0.006458 -0.074881
Wal-cefe_41_ibex-2             0.065547 -0.000911 -0.010427 -0.020640
Nar-f40f_72_pseudonarcissus-2  0.002086  0.018305  0.067365  0.068697
cluster data elongation along main axis
                              effect        Dx   N      eff2
arcpath            lemma
compound>amod>     bent     0.488034  0.003413   3  0.238177
                   green    0.442997  0.028197  25  0.196247
amod>              high    -0.418063  0.002109   2  0.174777
                   greater -0.396028  0.000424   1  0.156838
conj>              mouse   -0.351947  0.001884   2  0.123867
amod>advmod>       long     0.345163  0.014439  14  0.119137
nmod>case>         of       0.335411 -0.000485   2  0.112501
compound>amod>     black    0.332783  0.011286  10  0.110744
compound>compound> New     -0.327356  0.001995   2  0.107162
compound>amod>     arctic   0.325108  0.002095   2  0.105695
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                             token         x
arcpath            lemma
amod>              greater       Gre-c26f_74_bat-3 -0.070319
                   high     Hig81e8_2_fritillary-3  0.039973
                   high     Vio6842_8_fritillary-3  0.039973
amod>advmod>       long     Lon-6fc7_10_seahorse-4  0.039973
                   long     Lon-6fc7_17_seahorse-4 -0.105636
...                                            ...       ...
compound>compound> New          New-caad_12_rats-3 -0.019702
conj>              mouse        New-caad_10_rats-3 -0.165546
                   mouse        New-caad_12_rats-3 -0.019702
nmod>case>         of             Law5343_5_Bird-1  0.039973
                   of         New-d8c1_127_Birds-1  0.039973

[63 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
Spearman results
feat_tests
                            test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath            lemma
amod>              greater      0.28674   -0.070        1    1364    -1.07
                   high         0.38246    0.041        2    1364     0.87
amod>advmod>       long         0.31721    0.018       14    1364     1.00
compound>amod>     arctic       0.88745   -0.007        2    1364    -0.14
                   bent         0.97050   -0.001        3    1364    -0.04
                   black        0.12444    0.032       10    1364     1.54
                   green        0.00181    0.041       25    1364     3.13
compound>compound> New          0.04664   -0.092        2    1364    -1.99
conj>              mouse        0.04664   -0.092        2    1364    -1.99
nmod>case>         of           0.38246    0.041        2    1364     0.87
book_cl_elong
                              effect        Dx   N      eff2  test_pvalue  \
arcpath            lemma
compound>amod>     green    0.442997  0.028197  25  0.196247      0.00181
amod>              greater -0.396028  0.000424   1  0.156838      0.28674
conj>              mouse   -0.351947  0.001884   2  0.123867      0.04664
amod>advmod>       long     0.345163  0.014439  14  0.119137      0.31721
nmod>case>         of       0.335411 -0.000485   2  0.112501      0.38246
compound>amod>     black    0.332783  0.011286  10  0.110744      0.12444
compound>compound> New     -0.327356  0.001995   2  0.107162      0.04664

                            test_dX  test_Nx  test_N  test_st
arcpath            lemma
compound>amod>     green      0.041       25    1364     3.13
amod>              greater   -0.070        1    1364    -1.07
conj>              mouse     -0.092        2    1364    -1.99
amod>advmod>       long       0.018       14    1364     1.00
nmod>case>         of         0.041        2    1364     0.87
compound>amod>     black      0.032       10    1364     1.54
compound>compound> New       -0.092        2    1364    -1.99
cluster ====> 4
np.sqrt(eigvals)
[0.26793959 0.37514375 0.43848123 0.50066865 0.58657016 0.62211203
 0.75520033 0.87019515]
cl_elong_a, cl_elong_v.round(2)
1.1522706111554095 [ 0.18 -0.46 -0.71  0.5  -0.08 -0.04 -0.08  0.02]
cluster data sample, mean shift
(8870, 8)                                  0         1         2         3         4  \
token_id
Aur-441a_64_jellyfish-30  0.068912 -0.666675 -0.580855 -0.517149 -0.207198
Blab943_11_bird-4        -0.822251 -0.660370  0.091627 -0.160284  0.770790
Arg-ab8e_28_crabro-14    -0.533369 -0.292748 -0.169823  0.173378  0.203896

                                 5         6         7
token_id
Aur-441a_64_jellyfish-30  0.389509 -0.192231  0.134795
Blab943_11_bird-4        -0.287004  0.095483  0.875821
Arg-ab8e_28_crabro-14     0.252503 -0.138379 -0.654589
cluster data elongation along main axis

/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

                       effect        Dx   N      eff2
arcpath lemma
amod>   isolate      0.907306  0.000019   1  0.823204
        most         0.896103  0.000410  40  0.803000
        know         0.891209  0.000007   8  0.794253
        numerous     0.886222 -0.000009   1  0.785390
        dromedary    0.885296  0.000007   1  0.783749
        live         0.875982  0.000005   2  0.767345
        large        0.875562 -0.000080  42  0.766609
        radiate      0.875216  0.000064   2  0.766002
        only         0.873629 -0.000018   4  0.763228
        terrestrial  0.866511 -0.000046   6  0.750841
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                 token         x
arcpath lemma
amod>   dromedary                Cam-1690_189_camel-10  0.211706
        isolate             Coc-65ef_103_cockroaches-6  0.146267
        know                  Bir-ebe4_10_dinosaurs-12  0.456025
        know         Car-eac4_14_carcharodontosaurid-9  1.610424
        know                 Cau-ba75_14_salamanders-5  1.579570
...                                                ...       ...
        terrestrial           Amb-94f9_56_ungulates-14  0.275275
        terrestrial             Ant-44b4_163_animal-11  1.522336
        terrestrial              Chi-171d_17_animal-12  1.601343
        terrestrial          Her-8d89_30_vertebrates-6  1.294182
        terrestrial         Sau-89d2_202_vertebrates-9  0.798630

[107 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
Spearman results
feat_tests
                     test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath lemma
amod>   dromedary        0.73770    0.197        1    8870     0.33
        isolate          0.82320    0.131        1    8870     0.22
        know             0.00002    0.882        8    8870     4.25
        large            0.00000    0.552       42    8870     6.09
        live             0.44534    0.317        2    8870     0.76
        most             0.00000    0.729       40    8870     7.86
        numerous         0.08618    1.007        1    8870     1.72
        only             0.71695    0.106        4    8870     0.36
        radiate          0.28183    0.447        2    8870     1.08
        terrestrial      0.00001    1.067        6    8870     4.45
book_cl_elong
                       effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath lemma
amod>   isolate      0.907306  0.000019   1  0.823204      0.82320    0.131
        most         0.896103  0.000410  40  0.803000      0.00000    0.729
        know         0.891209  0.000007   8  0.794253      0.00002    0.882
        numerous     0.886222 -0.000009   1  0.785390      0.08618    1.007
        dromedary    0.885296  0.000007   1  0.783749      0.73770    0.197
        live         0.875982  0.000005   2  0.767345      0.44534    0.317
        large        0.875562 -0.000080  42  0.766609      0.00000    0.552
        radiate      0.875216  0.000064   2  0.766002      0.28183    0.447
        only         0.873629 -0.000018   4  0.763228      0.71695    0.106
        terrestrial  0.866511 -0.000046   6  0.750841      0.00001    1.067

                     test_Nx  test_N  test_st
arcpath lemma
amod>   isolate            1    8870     0.22
        most              40    8870     7.86
        know               8    8870     4.25
        numerous           1    8870     1.72
        dromedary          1    8870     0.33
        live               2    8870     0.76
        large             42    8870     6.09
        radiate            2    8870     1.08
        only               4    8870     0.36
        terrestrial        6    8870     4.45
cluster ====> 5
np.sqrt(eigvals)
[0.21637744 0.28075389 0.32492539 0.43953802 0.48902216 0.51959338
 0.75805793 0.89978964]
cl_elong_a, cl_elong_v.round(2)
1.186966863953084 [ 0.12  0.89  0.39  0.14  0.06  0.1  -0.    0.04]
cluster data sample, mean shift
(5154, 8)                              0         1         2         3         4  \
token_id
Polf59e_2_voles-8     0.199174  0.012585  0.661813 -0.046252  0.135580
Bla-d6a7_27_humans-9 -0.212306  0.123246  0.764278  0.154818 -0.309021
Hor-ab9c_184_bat-13  -0.299182 -0.371009  0.025256 -1.766795  1.430324

                             5         6         7
token_id
Polf59e_2_voles-8    -0.589727  0.053513  0.038258
Bla-d6a7_27_humans-9 -0.325868  0.125143 -0.353803
Hor-ab9c_184_bat-13  -0.524095 -0.106084  0.283492
cluster data elongation along main axis
                                   effect        Dx  N      eff2
arcpath            lemma
nmod:poss>conj>cc> and          -0.862443  0.000043  1  0.743807
obl<               produce       0.755878  0.000390  8  0.571351
nmod<obj<obl>      reptile      -0.750317  0.000133  2  0.562975
acl:relcl>         eat          -0.740726  0.000048  2  0.548676
obl<               characterize  0.738756  0.000051  1  0.545760
                   transmit      0.735205  0.000022  1  0.540527
acl:relcl>         feed         -0.729764  0.000015  2  0.532555
obl<               gai           0.729424  0.000051  1  0.532059
                   obtain        0.726166  0.000034  1  0.527317
                   specialize    0.725038  0.000034  1  0.525680
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                         token         x
arcpath            lemma
acl:relcl>         eat                  Ani-161e_70_turtles-14 -1.025098
                   eat                   Cat-605b_118_plant-23 -1.562859
                   feed                   Ani2696_56_people-11 -0.474671
                   feed                   Red-f791_60_cones-44 -1.144991
nmod:poss>conj>cc> and                    Com8122_2_mammals-15 -0.761719
nmod<obj<obl>      reptile               Com-4c8f_11_turtle-10 -0.483906
                   reptile       The-f5b4_13_Therizinosaurus-6 -0.399251
obl<               characterize          Mic-219b_16_grasses-8  0.798809
                   gai                     Pac-29db_128_dog-18  0.335771
                   obtain                Orc-0474_187_fungi-34  0.527336
                   produce                Afr-7494_111_cows-14  0.455100
                   produce                 Ara-552d_19_plant-6  0.171083
                   produce              Bel-4321_256_humans-13  1.251808
                   produce               Bur-08d7_34_animals-6  0.460781
                   produce                 Com-9711_67_raven-7  0.533338
                   produce                For-fc8f_7_aphids-13  0.148378
                   produce                Man-05b8_126_bats-19  0.475108
                   produce             Red-5937_112_piranhas-9  0.450690
                   specialize             Acc-0f45_121_bats-24  0.724018
                   transmit             Eas-550c_137_rodents-6  0.790381
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
Spearman results
feat_tests
                                 test_pvalue  test_dX  test_Nx  test_N  \
arcpath            lemma
acl:relcl>         eat               0.00033   -1.289        2    5154
                   feed              0.02495   -0.805        2    5154
nmod:poss>conj>cc> and               0.13615   -0.757        1    5154
nmod<obj<obl>      reptile           0.22413   -0.436        2    5154
obl<               characterize      0.11311    0.804        1    5154
                   gai               0.50160    0.341        1    5154
                   obtain            0.29399    0.533        1    5154
                   produce           0.00542    0.499        8    5154
                   specialize        0.15073    0.729        1    5154
                   transmit          0.11694    0.796        1    5154

                                 test_st
arcpath            lemma
acl:relcl>         eat             -3.60
                   feed            -2.24
nmod:poss>conj>cc> and             -1.49
nmod<obj<obl>      reptile         -1.22
obl<               characterize     1.58
                   gai              0.67
                   obtain           1.05
                   produce          2.78
                   specialize       1.44
                   transmit         1.57
book_cl_elong
                                   effect        Dx  N      eff2  test_pvalue  \
arcpath            lemma
nmod:poss>conj>cc> and          -0.862443  0.000043  1  0.743807      0.13615
obl<               produce       0.755878  0.000390  8  0.571351      0.00542
nmod<obj<obl>      reptile      -0.750317  0.000133  2  0.562975      0.22413
acl:relcl>         eat          -0.740726  0.000048  2  0.548676      0.00033
obl<               characterize  0.738756  0.000051  1  0.545760      0.11311
                   transmit      0.735205  0.000022  1  0.540527      0.11694
acl:relcl>         feed         -0.729764  0.000015  2  0.532555      0.02495
obl<               gai           0.729424  0.000051  1  0.532059      0.50160
                   obtain        0.726166  0.000034  1  0.527317      0.29399
                   specialize    0.725038  0.000034  1  0.525680      0.15073

                                 test_dX  test_Nx  test_N  test_st
arcpath            lemma
nmod:poss>conj>cc> and            -0.757        1    5154    -1.49
obl<               produce         0.499        8    5154     2.78
nmod<obj<obl>      reptile        -0.436        2    5154    -1.22
acl:relcl>         eat            -1.289        2    5154    -3.60
obl<               characterize    0.804        1    5154     1.58
                   transmit        0.796        1    5154     1.57
acl:relcl>         feed           -0.805        2    5154    -2.24
obl<               gai             0.341        1    5154     0.67
                   obtain          0.533        1    5154     1.05
                   specialize      0.729        1    5154     1.44
cluster ====> 6
np.sqrt(eigvals)
[0.66590021 0.84075626 0.93078009 1.00872763 1.10085655 1.19870442
 1.3980682  2.22037872]
cl_elong_a, cl_elong_v.round(2)
1.5881762534506279 [ 0.04  0.09 -0.17  0.26  0.11  0.   -0.1   0.93]
cluster data sample, mean shift
(2245, 8)                                     0         1         2         3         4  \
token_id
Rep-aa64_410_snakes-9       -0.291521  0.548236 -1.369957  0.415056  0.024461
Mag-8f64_10_Magnoliopsida-2  0.147426  0.655561  0.136252  1.279641  1.471077
Syc-34df_5_sycamore-75       0.937733  0.186747 -2.159469 -0.963225 -1.204267

                                    5         6         7
token_id
Rep-aa64_410_snakes-9        0.500340  0.597419  0.623706
Mag-8f64_10_Magnoliopsida-2 -1.259472 -1.921444  2.934458
Syc-34df_5_sycamore-75      -0.059061  0.025792  0.505340
cluster data elongation along main axis
                       effect        Dx   N      eff2
arcpath lemma
conj>   hare        -0.960667  0.001134  18  0.922882
        rabbit      -0.951575  0.000597  10  0.905495
        chipmunk    -0.949635  0.000143   2  0.901807
        variety     -0.946710  0.000129   2  0.896259
        animal      -0.942115  0.000984  19  0.887580
        guanaco     -0.941864  0.000161   2  0.887108
        carrion     -0.940523  0.001105  14  0.884583
        food        -0.939273  0.000129   2  0.882234
        example     -0.934565  0.000059   1  0.873412
        environment -0.932458  0.000053   1  0.869478
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                    token         x
arcpath lemma
conj>   animal     Ani-2170_118_humans-20 -0.166233
        animal       Ara-8421_54_plant-22 -3.080116
        animal    Arm-33e3_135_insects-25 -1.983136
        animal      Asc-4810_139_plants-4 -0.833943
        animal      Aus-f9df_11_plants-23  0.789910
...                                   ...       ...
        rabbit   Har-8a11_65_squirrels-13 -0.915657
        rabbit       Her-8d89_180_deer-15 -1.276406
        rabbit    Man-d9fd_119_rodents-16 -2.168446
        variety     Ech-581f_68_rodents-5 -1.647732
        variety      Flo-eb50_8_plants-40 -0.596479

[71 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
Spearman results
feat_tests
                     test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath lemma
conj>   animal           0.09410   -0.783       19    2245    -1.67
        carrion          0.00000   -5.225       14    2245    -9.81
        chipmunk         0.01323   -3.555        2    2245    -2.48
        environment      0.44311   -1.557        1    2245    -0.77
        example          0.48535   -1.416        1    2245    -0.70
        food             0.92954    0.127        2    2245     0.09
        guanaco          0.00181   -4.474        2    2245    -3.12
        hare             0.00000   -4.502       18    2245    -9.56
        rabbit           0.00003   -2.676       10    2245    -4.18
        variety          0.54307   -0.873        2    2245    -0.61
book_cl_elong
                       effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath lemma
conj>   hare        -0.960667  0.001134  18  0.922882      0.00000   -4.502
        rabbit      -0.951575  0.000597  10  0.905495      0.00003   -2.676
        chipmunk    -0.949635  0.000143   2  0.901807      0.01323   -3.555
        variety     -0.946710  0.000129   2  0.896259      0.54307   -0.873
        animal      -0.942115  0.000984  19  0.887580      0.09410   -0.783
        guanaco     -0.941864  0.000161   2  0.887108      0.00181   -4.474
        carrion     -0.940523  0.001105  14  0.884583      0.00000   -5.225
        example     -0.934565  0.000059   1  0.873412      0.48535   -1.416
        environment -0.932458  0.000053   1  0.869478      0.44311   -1.557

                     test_Nx  test_N  test_st
arcpath lemma
conj>   hare              18    2245    -9.56
        rabbit            10    2245    -4.18
        chipmunk           2    2245    -2.48
        variety            2    2245    -0.61
        animal            19    2245    -1.67
        guanaco            2    2245    -3.12
        carrion           14    2245    -9.81
        example            1    2245    -0.70
        environment        1    2245    -0.77
cluster ====> 7
np.sqrt(eigvals)
[0.50601208 0.52558064 0.62923622 0.8111872  0.82159142 0.8840461
 1.33442301 2.94122961]
cl_elong_a, cl_elong_v.round(2)
2.2041208690747536 [-0.7   0.02 -0.23 -0.27  0.16 -0.39  0.45  0.03]
cluster data sample, mean shift
(1889, 8)                                 0         1         2         3         4  \
token_id
Aar-5e58_102_pythons-23 -0.293004  0.432717  2.362378 -0.473325 -0.785569
Cor-5ac8_18_rodents-26  -0.339048  1.060370 -1.742928  1.516114 -0.021648
Com-597e_40_warthog-3   -0.345468  0.941764 -1.381168 -0.078495  0.260182

                                5         6         7
token_id
Aar-5e58_102_pythons-23  0.127118 -0.280167  0.704209
Cor-5ac8_18_rodents-26   0.329109 -2.470991 -1.290857
Com-597e_40_warthog-3    0.961121 -4.767027  0.459048
cluster data elongation along main axis
                      effect        Dx   N      eff2
arcpath    lemma
nmod>case> in      -0.804104 -0.000571  10  0.646584
           over    -0.795272  0.000032   1  0.632457
           to      -0.791271 -0.000080   3  0.626110
           of      -0.768651 -0.000595  16  0.590824
           from    -0.722810 -0.000135   3  0.522454
           on      -0.698936 -0.000101   3  0.488511
           include -0.688765 -0.000100   3  0.474397
           with    -0.671022 -0.000149   2  0.450271
           for     -0.668740 -0.000069   1  0.447214
           such    -0.652954  0.000141  26  0.426349
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                       token         x
arcpath    lemma
nmod>case> for             Aphe0a9_6_cows-18 -0.703107
           from       Cir-aed8_249_Circus-47 -1.354382
           from       Cir-aed8_249_Circus-54 -1.187210
           from        Sil-6383_38_sifaka-22 -2.176026
           in         Bog-cdf9_52_reptile-11 -2.360559
...                                      ...       ...
           to      Ant-938d_2_Hymenoptera-23 -2.069440
           to         Cho-a88d_83_beetles-28 -2.144432
           to     Gal-0153_188_amphibians-15 -2.830301
           with        Man-05b8_8_insects-27 -2.401208
           with       Aur-441a_5_mollusks-10 -1.329371

[68 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
Spearman results
feat_tests
                    test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
nmod>case> for          0.44549   -0.873        1    1889    -0.76
           from         0.00823   -1.744        3    1889    -2.65
           in           0.00000   -2.141       10    1889    -5.96
           include      0.01861   -1.554        3    1889    -2.36
           of           0.00014   -1.092       16    1889    -3.82
           on           0.00764   -1.761        3    1889    -2.67
           over         0.02600   -2.545        1    1889    -2.23
           such         0.00000   -1.429       26    1889    -6.39
           to           0.00013   -2.521        3    1889    -3.83
           with         0.01176   -2.037        2    1889    -2.52
book_cl_elong
                      effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath    lemma
nmod>case> in      -0.804104 -0.000571  10  0.646584      0.00000   -2.141
           over    -0.795272  0.000032   1  0.632457      0.02600   -2.545
           to      -0.791271 -0.000080   3  0.626110      0.00013   -2.521
           of      -0.768651 -0.000595  16  0.590824      0.00014   -1.092
           from    -0.722810 -0.000135   3  0.522454      0.00823   -1.744
           on      -0.698936 -0.000101   3  0.488511      0.00764   -1.761
           include -0.688765 -0.000100   3  0.474397      0.01861   -1.554
           with    -0.671022 -0.000149   2  0.450271      0.01176   -2.037
           for     -0.668740 -0.000069   1  0.447214      0.44549   -0.873
           such    -0.652954  0.000141  26  0.426349      0.00000   -1.429

                    test_Nx  test_N  test_st
arcpath    lemma
nmod>case> in            10    1889    -5.96
           over           1    1889    -2.23
           to             3    1889    -3.83
           of            16    1889    -3.82
           from           3    1889    -2.65
           on             3    1889    -2.67
           include        3    1889    -2.36
           with           2    1889    -2.52
           for            1    1889    -0.76
           such          26    1889    -6.39
cluster ====> 8
np.sqrt(eigvals)
[0.16101362 0.21699981 0.23942951 0.27380713 0.3033536  0.39300355
 0.41502402 0.65040132]
cl_elong_a, cl_elong_v.round(2)
1.567141403153825 [-0.05 -0.56 -0.24  0.52 -0.43  0.22  0.08 -0.33]
cluster data sample, mean shift

(4977, 8)                                0         1         2         3         4  \
token_id
Afr-655f_81_elephant-2 -0.268693  0.213770 -0.599649 -0.286494 -0.673381
The067f_13_camels-3    -0.380279  0.302888 -0.037307  0.027421 -0.036201
Hun-23f5_11_spiders-6   0.664105  0.060592  0.619119 -0.080039 -0.191112

                               5         6         7
token_id
Afr-655f_81_elephant-2  0.378184 -0.152703  0.051157
The067f_13_camels-3     0.060925 -0.032873  0.165299
Hun-23f5_11_spiders-6   0.141119 -0.007770 -0.355236
cluster data elongation along main axis
                                    effect        Dx  N      eff2
arcpath                 lemma
case>                   by       -0.510827 -0.000188  1  0.260945
compound<amod>compound> New      -0.505260  0.000420  3  0.255288
case>                   '        -0.500485 -0.000025  1  0.250486
obl<                    faster   -0.495693  0.000109  1  0.245711
compound<obl>case>      in        0.491829  0.000269  3  0.241896
appos<nsubj<            know      0.488055  0.000072  1  0.238198
case>                   from     -0.486546 -0.000248  2  0.236727
amod<                   ancestor  0.482595  0.000112  1  0.232898
compound>det>           the       0.475260 -0.000031  1  0.225872
case>                   of       -0.470150 -0.001101  5  0.221041
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                       token         x
arcpath                 lemma
amod<                   ancestor        Gal-c120_16_human-20  0.600162
appos<nsubj<            know            Thy-db39_2_bearers-5  0.351523
case>                   '              Ani-4d8b_117_lions-17 -0.500717
                        by                Bur-d18a_4_dogs-14 -0.314030
                        from           Lem-ec0f_101_shark-13 -0.603257
                        from         Pin-c005_73_longaeva-13 -0.603257
                        of           Bur-08d7_9_vertebrate-4 -0.215682
                        of                Bir-154b_55_bird-4  0.371586
                        of         Lea-7a1c_224_Mustelidae-9 -0.261260
                        of              Pla-0a07_123_trees-4  0.021904
                        of              Red-d827_154_Knot-11 -0.841791
compound<amod>compound> New             Din2693_40_reptile-3 -0.543928
                        New             Ptee0a7_10_reptile-3 -0.543928
                        New             Rep66e7_12_reptile-3 -0.543928
compound<obl>case>      in             Afr-354e_22_buffalo-7  0.419837
                        in            Fri-c770_100_lizards-8  0.506514
                        in                Roe-b5ac_50_deer-9  0.862450
compound>det>           the           Hibad6e_19_Hedgehogs-5  0.548463
obl<                    faster    Ame-35ae_97_chimpanzees-23 -0.405386
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)

/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

Spearman results
feat_tests
                                  test_pvalue  test_dX  test_Nx  test_N  \
arcpath                 lemma
amod<                   ancestor      0.05373    0.602        1    4977
appos<nsubj<            know          0.25770    0.353        1    4977
case>                   '             0.10964   -0.499        1    4977
                        by            0.31667   -0.312        1    4977
                        from          0.00637   -0.602        2    4977
                        of            0.18844   -0.184        5    4977
compound<amod>compound> New           0.00259   -0.543        3    4977
compound<obl>case>      in            0.00090    0.598        3    4977
compound>det>           the           0.07786    0.550        1    4977
obl<                    faster        0.19561   -0.404        1    4977

                                  test_st
arcpath                 lemma
amod<                   ancestor     1.93
appos<nsubj<            know         1.13
case>                   '           -1.60
                        by          -1.00
                        from        -2.73
                        of          -1.32
compound<amod>compound> New         -3.01
compound<obl>case>      in           3.32
compound>det>           the          1.76
obl<                    faster      -1.29
book_cl_elong
                                    effect        Dx  N      eff2  \
arcpath                 lemma
case>                   by       -0.510827 -0.000188  1  0.260945
compound<amod>compound> New      -0.505260  0.000420  3  0.255288
case>                   '        -0.500485 -0.000025  1  0.250486
obl<                    faster   -0.495693  0.000109  1  0.245711
compound<obl>case>      in        0.491829  0.000269  3  0.241896
appos<nsubj<            know      0.488055  0.000072  1  0.238198
case>                   from     -0.486546 -0.000248  2  0.236727
amod<                   ancestor  0.482595  0.000112  1  0.232898
compound>det>           the       0.475260 -0.000031  1  0.225872
case>                   of       -0.470150 -0.001101  5  0.221041

                                  test_pvalue  test_dX  test_Nx  test_N  \
arcpath                 lemma
case>                   by            0.31667   -0.312        1    4977
compound<amod>compound> New           0.00259   -0.543        3    4977
case>                   '             0.10964   -0.499        1    4977
obl<                    faster        0.19561   -0.404        1    4977
compound<obl>case>      in            0.00090    0.598        3    4977
appos<nsubj<            know          0.25770    0.353        1    4977
case>                   from          0.00637   -0.602        2    4977
amod<                   ancestor      0.05373    0.602        1    4977
compound>det>           the           0.07786    0.550        1    4977
case>                   of            0.18844   -0.184        5    4977

                                  test_st
arcpath                 lemma
case>                   by          -1.00
compound<amod>compound> New         -3.01
case>                   '           -1.60
obl<                    faster      -1.29
compound<obl>case>      in           3.32
appos<nsubj<            know         1.13
case>                   from        -2.73
amod<                   ancestor     1.93
compound>det>           the          1.76
case>                   of          -1.32
cluster ====> 9
np.sqrt(eigvals)
[0.30353631 0.345954   0.396395   0.43736354 0.52339409 0.56222388
 0.65377211 1.12025514]
cl_elong_a, cl_elong_v.round(2)
1.713525424709587 [-0.21 -0.68  0.11 -0.05  0.32 -0.22  0.56  0.1 ]
cluster data sample, mean shift
(3568, 8)                                0         1         2         3         4  \
token_id
Ven-77c9_98_spiders-11 -0.621606  0.273435 -1.027286 -0.506160  0.398718
Ham-9078_102_sharks-13 -0.747557  0.348512  0.793292 -0.776677 -0.036912
Tem-c190_7_grass-8      0.076040 -0.490749  0.049003  0.493601 -0.065963

                               5         6         7
token_id
Ven-77c9_98_spiders-11  0.812917  0.325841 -0.603618
Ham-9078_102_sharks-13  0.142350 -0.168807 -0.186372
Tem-c190_7_grass-8     -0.306867  0.076602 -0.664752
cluster data elongation along main axis
                             effect        Dx  N      eff2
arcpath         lemma
acl:relcl>      feed       0.620571 -0.000006  1  0.385109
                prefer     0.589457  0.000046  1  0.347459
conj<nmod<obj<  affect     0.566015  0.000176  2  0.320373
conj<conj>      pronghorn  0.560752  0.000094  7  0.314443
conj<nmod<obj<  consume    0.557279  0.000450  6  0.310560
conj<conj>      otter      0.554990 -0.000037  8  0.308014
conj<parataxis< p         -0.541683  0.000176  2  0.293421
conj<conj>      saiga      0.540976  0.000063  1  0.292655
                waterfowl  0.540158  0.000378  6  0.291771
                live       0.539369  0.000126  2  0.290919
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                token         x
arcpath         lemma
acl:relcl>      feed          Sta-6168_253_urchins-35  0.555834
                prefer        Amb-94f9_196_animals-20 -0.573902
conj<conj>      live           Rat-4b67_26_lizards-14  1.481620
                live        Spi-b4d6_31_tarantulas-11  0.248113
                otter           Ani-2170_339_bears-16  1.840729
                otter       Ani-2170_339_mongooses-23  1.306795
                otter           Bea-4f7a_225_minks-12  0.397730
                otter        Com-6e0a_211_raccoons-21  0.807866
                otter            Com-9711_199_dogs-25 -0.212539
                otter            Eur-3a81_48_shrew-18  0.544598
                otter           Gia-d1de_31_whales-14 -0.275792
                otter        Wea-8e57_5_wolverines-16  0.118141
                pronghorn        Coy-1bf1_262_deer-28  0.662897
                pronghorn         Coy-1bf1_262_elk-24  1.336042
                pronghorn       Coy-1bf1_280_sheep-25  0.637732
                pronghorn    Cro-5646_326_reindeer-30  1.745301
                pronghorn         Pra-7b55_12_deer-13 -0.142029
                pronghorn        Pra-7b55_154_deer-14 -0.162034
                pronghorn     Tho-fdaf_7_springbok-22  0.684183
                saiga            Tem-2c3b_12_Saiga-26 -0.083232
                waterfowl   Mar-4677_25_amphibians-12  1.103392
                waterfowl    Mar-4677_9_amphibians-12  1.103392
                waterfowl      Sho-489b_120_rodents-9  1.725017
                waterfowl  Sno-0a8f_396_shorebirds-20  1.213909
                waterfowl     Spa-e46a_15_seagulls-22  1.711624
                waterfowl   Spa-e46a_15_shorebirds-20  1.645897
conj<nmod<obj<  affect        Eur-fd2f_77_blackcap-15 -0.019438
                affect       Gar-8d9c_164_blackcap-15 -0.019438
                consume    Bar-2af9_129_angiosperms-9 -0.292091
                consume           Coc-9207_9_fungi-13 -0.287177
                consume       Coy-1bf1_292_beetles-14 -0.165176
                consume      Sir-1b7d_15_jellyfish-17 -0.037570
                consume           Tar-bf27_80_bats-16  1.431062
                consume          Tar-bf27_80_birds-18  1.351675
conj<parataxis< p                    Can-3366_38_m-58 -0.467009
                p                   Can-f359_107_m-58 -0.467009
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
Spearman results
feat_tests
                           test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath         lemma
acl:relcl>      feed           0.44680    0.552        1    3568     0.76
                prefer         0.42644   -0.578        1    3568    -0.80
conj<conj>      live           0.09328    0.862        2    3568     1.68
                otter          0.02824    0.564        8    3568     2.19
                pronghorn      0.01353    0.678        7    3568     2.47
                saiga          0.90491   -0.087        1    3568    -0.12
                waterfowl      0.00000    1.416        6    3568     4.79
conj<nmod<obj<  affect         0.96435   -0.023        2    3568    -0.04
                consume        0.26526    0.331        6    3568     1.11
conj<parataxis< p              0.35932   -0.471        2    3568    -0.92
book_cl_elong
                             effect        Dx  N      eff2  test_pvalue  \
arcpath         lemma
acl:relcl>      feed       0.620571 -0.000006  1  0.385109      0.44680
conj<conj>      pronghorn  0.560752  0.000094  7  0.314443      0.01353
conj<nmod<obj<  consume    0.557279  0.000450  6  0.310560      0.26526
conj<conj>      otter      0.554990 -0.000037  8  0.308014      0.02824
conj<parataxis< p         -0.541683  0.000176  2  0.293421      0.35932
conj<conj>      waterfowl  0.540158  0.000378  6  0.291771      0.00000
                live       0.539369  0.000126  2  0.290919      0.09328

                           test_dX  test_Nx  test_N  test_st
arcpath         lemma
acl:relcl>      feed         0.552        1    3568     0.76
conj<conj>      pronghorn    0.678        7    3568     2.47
conj<nmod<obj<  consume      0.331        6    3568     1.11
conj<conj>      otter        0.564        8    3568     2.19
conj<parataxis< p           -0.471        2    3568    -0.92
conj<conj>      waterfowl    1.416        6    3568     4.79
                live         0.862        2    3568     1.68
===========  end ==============

/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

In [84]:
cresTop.keys()

dict_keys(['clust_featdx_df_short', 'clust_featdx_df', 'cos_pvalue', 'score_pvalue', 'C0', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9'])

In [85]:
cresTop['score_pvalue']

                            cos_stat  cos_pvalue  score_stat  score_pvalue
arcpath            lemma
det>               a        0.648485    0.042540    0.869175      0.001091
case>              from     0.842424    0.002220    0.869175      0.001091
                   as       0.214740    0.551325    0.860915      0.001379
                   to       0.187592    0.603782    0.860915      0.001379
                   's       0.382980    0.274673    0.859276      0.001443
...                              ...         ...         ...           ...
conj<det>          the      0.006079    0.986703   -0.043905      0.904144
conj<obl<aux:pass> be      -0.398803    0.253627   -0.037982      0.917035
conj<conj>cc>      and      0.325178    0.359238   -0.037383      0.918338
conj<case>fixed>   as      -0.135767    0.708424   -0.013341      0.970822
amod>              african -0.248485    0.488776    0.006213      0.986409

[100 rows x 4 columns]

In [360]:
cresAda = analyze_category('adaptation',True)
cresLoc = analyze_category('location',True)
cresTax = analyze_category('taxongroup',True)
cresTop = analyze_category('topic',True)

checking for data/q_cluster/BGM_full_covar_adaptation.pkl
BGM loaded
bgm.predict(my_ica_data)).value_counts()
1    754
6    631
2    426
3    378
4    321
8    307
9    306
5    269
0    130
7     56
Name: count, dtype: int64
clust_feats (7134, 2)
                  cluster  freq
arcpath    lemma
cop>       be           1   159
           be           9   140
case>      of           8   131
conj>cc>   and          9   100
amod<case> of           6    87
=========================
clust_f_df pivot table (3355, 10)
clust_p_df is the probability distribution cluster-wise
                               0         1         2    3        4    5    6  \
arcpath              lemma
acl:relcl<           theory  0.0  0.000583  0.000000  0.0  0.00000  0.0  0.0
acl:relcl<amod>      other   0.0  0.000000  0.000000  0.0  0.00132  0.0  0.0
acl:relcl<case>      to      0.0  0.000000  0.000000  0.0  0.00066  0.0  0.0
acl:relcl<det>       the     0.0  0.000291  0.000324  0.0  0.00000  0.0  0.0
acl:relcl<nmod>case> of      0.0  0.000000  0.000324  0.0  0.00000  0.0  0.0

                               7    8         9
arcpath              lemma
acl:relcl<           theory  0.0  0.0  0.000000
acl:relcl<amod>      other   0.0  0.0  0.000000
acl:relcl<case>      to      0.0  0.0  0.000388
acl:relcl<det>       the     0.0  0.0  0.001164
acl:relcl<nmod>case> of      0.0  0.0  0.000776
=========================
Elementwise relative entropy by clusters, feature-wise
                           0         1         2         3         4  \
arcpath    lemma
cop>       be       0.000879  0.042825 -0.000224 -0.001966 -0.006378
nmod>case> of      -0.005391 -0.002539  0.005422  0.000000 -0.002103
nsubj<     include -0.003007 -0.004876 -0.001236  0.000000 -0.003179
case>      of       0.000000 -0.001128  0.011436  0.000000 -0.001946
det>       the     -0.002551 -0.002101  0.020928 -0.002747 -0.000365

                           5         6         7         8         9
arcpath    lemma
cop>       be       0.005879 -0.003349  0.000000  0.000000  0.058856
nmod>case> of       0.051056  0.000000  0.093501  0.000000 -0.000064
nsubj<     include  0.004897 -0.002383  0.254891  0.000000  0.000000
case>      of      -0.003103 -0.002343  0.000000  0.196415 -0.004453
det>       the      0.033776 -0.001331  0.000000 -0.003704  0.009852
========== clust_featdx_df ===============
                                         Dx   N
cluster arcpath         lemma
4       case>           by         0.026708  22
7       nmod>case>      of         0.093501  18
3       amod<           behaviour  0.047395  17
                        structure  0.036440  15
7       nsubj<obj>conj> fox        0.066827   8
=========================
pred_feats
feat_v
                                   0         1         2         3         4  \
arcpath          lemma
acl:relcl>nsubj> that      -0.062988 -0.031006 -0.225952  0.068970 -0.026001
advmod>          highly    -0.081970 -0.160034 -0.350098 -0.029999  0.068970
amod<            animal    -0.261963  0.136963 -0.220947  0.061005 -0.080994
                 behavior  -0.159058  0.010002 -0.128052  0.078003 -0.085022
                 behaviour -0.161987 -0.001000 -0.096985  0.062012 -0.099976

                                   5         6         7
arcpath          lemma
acl:relcl>nsubj> that      -0.140991  0.068970 -0.194946
advmod>          highly     0.080017  0.049988  0.122009
amod<            animal     0.139038 -0.175049 -0.150024
                 behavior   0.026993 -0.094971 -0.078979
                 behaviour  0.014999 -0.046997 -0.042999
mean_norm
[[ 0.04  0.08 -0.76  0.28 -0.19  0.32  0.43  0.13]
 [-0.25 -0.24 -0.16  0.6  -0.52 -0.36 -0.18 -0.23]
 [ 0.89 -0.1  -0.22 -0.08  0.29  0.16 -0.14  0.14]
 [-0.45 -0.01  0.61  0.35 -0.42 -0.16 -0.18  0.27]
 [-0.1   0.58  0.44 -0.37  0.45  0.04 -0.1  -0.34]
 [ 0.82  0.2  -0.03  0.28 -0.28  0.04 -0.2   0.3 ]
 [-0.77 -0.25 -0.17  0.13 -0.29  0.02 -0.25  0.39]
 [ 0.11  0.98  0.01  0.01 -0.15 -0.    0.02  0.1 ]
 [-0.23  0.02  0.19  0.01  0.92  0.01 -0.06  0.25]
 [ 0.48 -0.06 -0.28 -0.04 -0.17  0.01  0.03 -0.81]]
cos_predict.head(5)
                            0         1         2         3         4  \
arcpath       lemma
cc>           and    0.150172  0.197423 -0.075814 -0.116608 -0.094578
conj<conj>cc> and    0.291450 -0.004813  0.065358 -0.203398 -0.239811
conj<cop>     be     0.150587  0.162651 -0.200854  0.005861  0.023474
cc>           or     0.087285  0.174408 -0.138729  0.047826 -0.064327
amod>         other  0.082509  0.158398 -0.153726  0.071887 -0.075069

                            5         6         7         8         9
arcpath       lemma
cc>           and   -0.102399  0.015079 -0.053099 -0.106580  0.195120
conj<conj>cc> and   -0.086625  0.175428 -0.166796  0.040589 -0.038769
conj<cop>     be    -0.145465  0.224484  0.097454 -0.078506  0.056893
cc>           or    -0.082558  0.170020 -0.005239 -0.078763  0.031635
amod>         other -0.087664  0.173802 -0.009392 -0.080327 -0.002453
score_predict.head(5)
                         0      1      2    3      4      5      6    7  \
arcpath       lemma
cc>           and    0.001  0.762  0.017  0.0  0.161  0.045  0.004  0.0
conj<conj>cc> and    0.002  0.690  0.039  0.0  0.106  0.122  0.021  0.0
conj<cop>     be     0.001  0.777  0.012  0.0  0.140  0.031  0.033  0.0
cc>           or     0.001  0.743  0.010  0.0  0.170  0.041  0.028  0.0
amod>         other  0.001  0.731  0.010  0.0  0.172  0.044  0.033  0.0

                         8      9
arcpath       lemma
cc>           and    0.001  0.010
conj<conj>cc> and    0.006  0.013
conj<cop>     be     0.001  0.006
cc>           or     0.003  0.005
amod>         other  0.005  0.005
                            0         1         2    3        4         5  \
arcpath       lemma
cc>           and    0.054087  0.004661  0.002268  0.0  0.00000  0.001310
conj<conj>cc> and    0.037260  0.000291  0.000000  0.0  0.00000  0.000000
conj<cop>     be     0.033654  0.001165  0.001620  0.0  0.00000  0.000000
cc>           or     0.010817  0.000291  0.000324  0.0  0.00000  0.000000
amod>         other  0.013221  0.002330  0.004861  0.0  0.00396  0.009168

                            6         7         8         9
arcpath       lemma
cc>           and    0.026119  0.000000  0.000763  0.003879
conj<conj>cc> and    0.000000  0.000000  0.000000  0.001552
conj<cop>     be     0.007048  0.000000  0.000000  0.001164
cc>           or     0.005804  0.000000  0.000000  0.000388
amod>         other  0.001244  0.018315  0.006102  0.002715
=========== Internal structure in cluster==============
cluster ====> 0
np.sqrt(eigvals)
[0.44714136 0.51870298 0.59639538 0.59929468 0.85170397 0.99134695
 1.32400595 1.81270831]
cl_elong_a, cl_elong_v.round(2)
1.3691088873434494 [ 0.75  0.39 -0.04  0.09  0.4   0.29  0.15  0.06]
cluster data sample, mean shift
(114, 8)                                       0         1         2         3  \
token_id
Amb-b5dc_7_predators-3         0.351420  0.438627 -1.373728  1.224236
Fir-e344_48_bioluminescence-3  0.556745 -1.032913 -0.025240  0.805695
Pra-7b55_190_social-23        -0.705896  0.184033 -0.115029  1.118257

                                      4         5         6         7
token_id
Amb-b5dc_7_predators-3         0.382871  0.138163 -1.659469  0.288353
Fir-e344_48_bioluminescence-3  0.955414  0.547439 -2.286261  0.303075
Pra-7b55_190_social-23         0.753529  0.417839  0.665765 -1.183249
cluster data elongation along main axis
                      effect        Dx  N      eff2
arcpath    lemma
nmod>case> of       0.791892 -0.005391  7  0.627093
           in       0.770076  0.003405  5  0.593017
           include  0.766578  0.002057  2  0.587642
           from     0.756959  0.000617  1  0.572987
           such     0.740562  0.000325  3  0.548433
           like     0.704301  0.004997  3  0.496040
           on       0.703964  0.002773  2  0.495565
amod>      ambush   0.659885  0.002080  2  0.435449
           pure     0.658424  0.007294  3  0.433522
nmod>case> for      0.646454  0.000749  1  0.417902
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                         token         x
arcpath    lemma
amod>      ambush       Amb-b5dc_7_predators-3  0.567340
           ambush      Pyt-d6ca_30_predators-8  0.690301
           pure      Smi-7190_144_scavenger-10 -0.009813
           pure       Tyr-9f97_14_scavenger-13 -1.454685
           pure      Tyr-9f97_537_scavenger-17 -1.065960
nmod>case> for        Aur-441a_25_predators-13  0.280296
           from        Lan-4994_75_language-20  1.064271
           in        Aur-c4ea_65_dimorphism-39  0.920155
           in        Cro-0859_136_predators-17  1.002693
           in         Kāk-e004_136_predators-2 -0.314572
           in          Mam-3742_19_language-36  1.211793
           in        Nil-600c_341_predators-25  1.722447
           include   Bee-ace3_329_predators-37  1.815256
           include    Com-0bc9_90_predators-17  0.560875
           like       Cap-5548_62_predators-34  0.770489
           like       The-f5b4_21_predators-21  0.559438
           like      Tyr-9f97_531_scavenger-13 -0.418401
           of        Atl-79fc_229_predators-24  2.367012
           of         Bla-1ce3_188_predators-4  2.431328
           of         Dal-d353_46_predators-22  1.078012
           of       Hib-c4bb_28_hibernation-12  0.679318
           of        Nor-c9d9_161_predators-28  0.602541
           of           Pre-0725_12_mimicry-29  1.935410
           of        Tem-2c3b_12_migrations-12  0.815020
           on         Maj-e024_203_predator-12 -0.321358
           on          Sta-6168_12_predators-8  0.467303
           such     And-dffe_117_scavengers-11  0.893778
           such      Eur-bc75_348_predators-33  1.905068
           such      Pre-0725_103_predators-20  1.351920
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (114,)
ftok (29, 2)
x0 token_id
Fir-e344_48_bioluminescence-3    0.307305
Pra-7b55_190_social-23           0.106494
Das-20a8_9_predators-38         -0.714519
Sca-5045_21_predators-30        -1.434643
Lan-4994_75_language-20          1.064271
                                   ...
Wil-a4b1_119_predators-18       -0.525374
Apo-f97b_57_nocturnal-32        -0.352496
Sea-fb32_429_use-30              0.176744
Aur-c4ea_65_dimorphism-39        0.920155
Bro-f1dc_18_carnivorous-39      -0.234154
Name: x, Length: 112, dtype: float64
x0 token_id
Amb-b5dc_7_predators-3           0.567340
Fir-e344_48_bioluminescence-3    0.307305
Pra-7b55_190_social-23           0.106494
Das-20a8_9_predators-38         -0.714519
Sca-5045_21_predators-30        -1.434643
                                   ...
Wil-a4b1_119_predators-18       -0.525374
Apo-f97b_57_nocturnal-32        -0.352496
Sea-fb32_429_use-30              0.176744
Aur-c4ea_65_dimorphism-39        0.920155
Bro-f1dc_18_carnivorous-39      -0.234154
Name: x, Length: 111, dtype: float64
x0 token_id
Amb-b5dc_7_predators-3           0.567340
Fir-e344_48_bioluminescence-3    0.307305
Pra-7b55_190_social-23           0.106494
Das-20a8_9_predators-38         -0.714519
Sca-5045_21_predators-30        -1.434643
                                   ...
Wil-a4b1_119_predators-18       -0.525374
Apo-f97b_57_nocturnal-32        -0.352496
Sea-fb32_429_use-30              0.176744
Aur-c4ea_65_dimorphism-39        0.920155
Bro-f1dc_18_carnivorous-39      -0.234154
Name: x, Length: 113, dtype: float64
x0 token_id
Amb-b5dc_7_predators-3           0.567340
Fir-e344_48_bioluminescence-3    0.307305
Pra-7b55_190_social-23           0.106494
Das-20a8_9_predators-38         -0.714519
Sca-5045_21_predators-30        -1.434643
                                   ...
Wil-a4b1_119_predators-18       -0.525374
Apo-f97b_57_nocturnal-32        -0.352496
Sea-fb32_429_use-30              0.176744
Aur-c4ea_65_dimorphism-39        0.920155
Bro-f1dc_18_carnivorous-39      -0.234154
Name: x, Length: 113, dtype: float64
x0 token_id
Amb-b5dc_7_predators-3           0.567340
Fir-e344_48_bioluminescence-3    0.307305
Pra-7b55_190_social-23           0.106494
Das-20a8_9_predators-38         -0.714519
Sca-5045_21_predators-30        -1.434643
                                   ...
Hum-2735_36_migrations-10       -0.029779
Wil-a4b1_119_predators-18       -0.525374
Apo-f97b_57_nocturnal-32        -0.352496
Sea-fb32_429_use-30              0.176744
Bro-f1dc_18_carnivorous-39      -0.234154
Name: x, Length: 109, dtype: float64
x0 token_id
Amb-b5dc_7_predators-3           0.567340
Fir-e344_48_bioluminescence-3    0.307305
Pra-7b55_190_social-23           0.106494
Das-20a8_9_predators-38         -0.714519
Sca-5045_21_predators-30        -1.434643
                                   ...
Wil-a4b1_119_predators-18       -0.525374
Apo-f97b_57_nocturnal-32        -0.352496
Sea-fb32_429_use-30              0.176744
Aur-c4ea_65_dimorphism-39        0.920155
Bro-f1dc_18_carnivorous-39      -0.234154
Name: x, Length: 112, dtype: float64
x0 token_id
Amb-b5dc_7_predators-3           0.567340
Fir-e344_48_bioluminescence-3    0.307305
Pra-7b55_190_social-23           0.106494
Das-20a8_9_predators-38         -0.714519
Sca-5045_21_predators-30        -1.434643
                                   ...
Wil-a4b1_119_predators-18       -0.525374
Apo-f97b_57_nocturnal-32        -0.352496
Sea-fb32_429_use-30              0.176744
Aur-c4ea_65_dimorphism-39        0.920155
Bro-f1dc_18_carnivorous-39      -0.234154
Name: x, Length: 111, dtype: float64
x0 token_id
Amb-b5dc_7_predators-3           0.567340
Fir-e344_48_bioluminescence-3    0.307305
Pra-7b55_190_social-23           0.106494
Das-20a8_9_predators-38         -0.714519
Sca-5045_21_predators-30        -1.434643
                                   ...
Wil-a4b1_119_predators-18       -0.525374
Apo-f97b_57_nocturnal-32        -0.352496
Sea-fb32_429_use-30              0.176744
Aur-c4ea_65_dimorphism-39        0.920155
Bro-f1dc_18_carnivorous-39      -0.234154
Name: x, Length: 107, dtype: float64
x0 token_id
Amb-b5dc_7_predators-3           0.567340
Fir-e344_48_bioluminescence-3    0.307305
Pra-7b55_190_social-23           0.106494
Das-20a8_9_predators-38         -0.714519
Sca-5045_21_predators-30        -1.434643
                                   ...
Wil-a4b1_119_predators-18       -0.525374
Apo-f97b_57_nocturnal-32        -0.352496
Sea-fb32_429_use-30              0.176744
Aur-c4ea_65_dimorphism-39        0.920155
Bro-f1dc_18_carnivorous-39      -0.234154
Name: x, Length: 112, dtype: float64
x0 token_id
Amb-b5dc_7_predators-3           0.567340
Fir-e344_48_bioluminescence-3    0.307305
Pra-7b55_190_social-23           0.106494
Das-20a8_9_predators-38         -0.714519
Sca-5045_21_predators-30        -1.434643
                                   ...
Wil-a4b1_119_predators-18       -0.525374
Apo-f97b_57_nocturnal-32        -0.352496
Sea-fb32_429_use-30              0.176744
Aur-c4ea_65_dimorphism-39        0.920155
Bro-f1dc_18_carnivorous-39      -0.234154
Name: x, Length: 111, dtype: float64
Spearman results
feat_tests
                    test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
amod>      ambush       0.23061    0.778        2     114     1.21
           pure         0.17174   -0.727        3     114    -1.38
nmod>case> for          0.64699    0.420        1     114     0.46
           from         0.18499    1.211        1     114     1.33
           in           0.00788    1.092        5     114     2.71
           include      0.03668    1.347        2     114     2.11
           like         0.39724    0.451        3     114     0.85
           of           0.00000    1.653        7     114     5.18
           on           0.74424    0.212        2     114     0.33
           such         0.00288    1.560        3     114     3.05
book_cl_elong
                      effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath    lemma
nmod>case> of       0.791892 -0.005391  7  0.627093      0.00000    1.653
           in       0.770076  0.003405  5  0.593017      0.00788    1.092
           include  0.766578  0.002057  2  0.587642      0.03668    1.347
           from     0.756959  0.000617  1  0.572987      0.18499    1.211
           such     0.740562  0.000325  3  0.548433      0.00288    1.560
           like     0.704301  0.004997  3  0.496040      0.39724    0.451
           on       0.703964  0.002773  2  0.495565      0.74424    0.212
amod>      ambush   0.659885  0.002080  2  0.435449      0.23061    0.778
nmod>case> for      0.646454  0.000749  1  0.417902      0.64699    0.420

                    test_Nx  test_N  test_st
arcpath    lemma
nmod>case> of             7     114     5.18
           in             5     114     2.71
           include        2     114     2.11
           from           1     114     1.33
           such           3     114     3.05
           like           3     114     0.85
           on             2     114     0.33
amod>      ambush         2     114     1.21
nmod>case> for            1     114     0.46
cluster ====> 1
np.sqrt(eigvals)
[0.30470227 0.34302201 0.4404658  0.4953986  0.5842706  0.6921703
 0.81682121 0.89830776]
cl_elong_a, cl_elong_v.round(2)
1.099760575003154 [ 0.14 -0.17  0.03 -0.13  0.24 -0.66 -0.31 -0.59]
cluster data sample, mean shift
(704, 8)                                    0         1         2         3         4  \
token_id
All-7078_312_carnivorous-7  0.044957  0.501524  0.009862  1.140380  0.553388
Agl-fec0_63_camouflage-4   -0.284740 -0.240723  0.402364  0.483535 -0.296020
Gre-8842_8_herbivorous-19   0.432151 -1.068447 -0.412939 -0.118793 -0.034413

                                   5         6         7
token_id
All-7078_312_carnivorous-7 -0.291435  0.430528  0.573710
Agl-fec0_63_camouflage-4    0.944766 -0.263393 -0.242560
Gre-8842_8_herbivorous-19  -0.348237 -0.038008 -0.941667
cluster data elongation along main axis
                         effect        Dx  N      eff2
arcpath    lemma
conj>      omnivorous  0.592893  0.002348  4  0.351522
           species     0.579117  0.000226  1  0.335376
           group       0.576958  0.000293  1  0.332881
           find        0.546905  0.000133  1  0.299105
cc>        rather     -0.545877  0.000568  2  0.297982
conj>      scavenger   0.541676 -0.000023  1  0.293413
           have        0.531679  0.000848  2  0.282683
           arboreal    0.518815  0.001341  2  0.269169
           oviparous   0.500661  0.001341  2  0.250661
obl<nsubj> crocodile   0.499389  0.000424  1  0.249389
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                            token         x
arcpath    lemma
cc>        rather      Cam-4bd8_115_camouflage-34 -1.081093
           rather       Lon-b0af_519_predators-18 -0.604779
conj>      arboreal       Aye-787b_52_nocturnal-7  0.167632
           arboreal        Uro-49a1_7_nocturnal-7  0.325588
           find            Uro-49a1_3_nocturnal-3  0.560101
           group            Col-6d94_129_social-9  0.872088
           have          Thy-db39_5_herbivorous-4  0.556646
           have             Vip0c87_4_predators-5  0.542191
           omnivorous  Bov-d455_138_herbivorous-7  0.912342
           omnivorous  Mur-6918_12_herbivorous-14  0.569031
           omnivorous  Sau-6bc5_60_herbivorous-20  0.490583
           omnivorous  Sau-cca0_13_herbivorous-35  1.156094
           oviparous     Viv-ac84_84_viviparous-9  0.457231
           oviparous     Viv-ac84_85_viviparous-3  0.645998
           scavenger      Neo-e8a9_19_predators-4  1.040128
           species      Kin-aa66_84_territorial-3  0.813500
obl<nsubj> crocodile    Nil-600c_332_predators-35 -0.346140
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (704,)
ftok (17, 2)
x0 token_id
All-7078_312_carnivorous-7    -0.370031
Agl-fec0_63_camouflage-4      -0.518173
Gre-8842_8_herbivorous-19      1.027300
Ter-605f_11_metamorphosis-9    0.264267
Cul-6926_14_social-19          0.133167
                                 ...
Eur-24a9_165_Predators-1       0.264787
Ani6f2b_115_migration-20       0.522095
Bea-4f7a_8_herbivorous-3       0.389214
Spe-2571_5_herbivorous-14      0.650619
Tar-5191_203_predator-5       -0.086896
Name: x, Length: 702, dtype: float64
x0 token_id
All-7078_312_carnivorous-7    -0.370031
Agl-fec0_63_camouflage-4      -0.518173
Gre-8842_8_herbivorous-19      1.027300
Ter-605f_11_metamorphosis-9    0.264267
Cul-6926_14_social-19          0.133167
                                 ...
Eur-24a9_165_Predators-1       0.264787
Ani6f2b_115_migration-20       0.522095
Bea-4f7a_8_herbivorous-3       0.389214
Spe-2571_5_herbivorous-14      0.650619
Tar-5191_203_predator-5       -0.086896
Name: x, Length: 702, dtype: float64
x0 token_id
All-7078_312_carnivorous-7    -0.370031
Agl-fec0_63_camouflage-4      -0.518173
Gre-8842_8_herbivorous-19      1.027300
Ter-605f_11_metamorphosis-9    0.264267
Cul-6926_14_social-19          0.133167
                                 ...
Eur-24a9_165_Predators-1       0.264787
Ani6f2b_115_migration-20       0.522095
Bea-4f7a_8_herbivorous-3       0.389214
Spe-2571_5_herbivorous-14      0.650619
Tar-5191_203_predator-5       -0.086896
Name: x, Length: 703, dtype: float64
x0 token_id
All-7078_312_carnivorous-7    -0.370031
Agl-fec0_63_camouflage-4      -0.518173
Gre-8842_8_herbivorous-19      1.027300
Ter-605f_11_metamorphosis-9    0.264267
Cul-6926_14_social-19          0.133167
                                 ...
Eur-24a9_165_Predators-1       0.264787
Ani6f2b_115_migration-20       0.522095
Bea-4f7a_8_herbivorous-3       0.389214
Spe-2571_5_herbivorous-14      0.650619
Tar-5191_203_predator-5       -0.086896
Name: x, Length: 703, dtype: float64
x0 token_id
All-7078_312_carnivorous-7    -0.370031
Agl-fec0_63_camouflage-4      -0.518173
Gre-8842_8_herbivorous-19      1.027300
Ter-605f_11_metamorphosis-9    0.264267
Cul-6926_14_social-19          0.133167
                                 ...
Eur-24a9_165_Predators-1       0.264787
Ani6f2b_115_migration-20       0.522095
Bea-4f7a_8_herbivorous-3       0.389214
Spe-2571_5_herbivorous-14      0.650619
Tar-5191_203_predator-5       -0.086896
Name: x, Length: 702, dtype: float64
x0 token_id
All-7078_312_carnivorous-7    -0.370031
Agl-fec0_63_camouflage-4      -0.518173
Gre-8842_8_herbivorous-19      1.027300
Ter-605f_11_metamorphosis-9    0.264267
Cul-6926_14_social-19          0.133167
                                 ...
Eur-24a9_165_Predators-1       0.264787
Ani6f2b_115_migration-20       0.522095
Bea-4f7a_8_herbivorous-3       0.389214
Spe-2571_5_herbivorous-14      0.650619
Tar-5191_203_predator-5       -0.086896
Name: x, Length: 700, dtype: float64
x0 token_id
All-7078_312_carnivorous-7    -0.370031
Agl-fec0_63_camouflage-4      -0.518173
Gre-8842_8_herbivorous-19      1.027300
Ter-605f_11_metamorphosis-9    0.264267
Cul-6926_14_social-19          0.133167
                                 ...
Eur-24a9_165_Predators-1       0.264787
Ani6f2b_115_migration-20       0.522095
Bea-4f7a_8_herbivorous-3       0.389214
Spe-2571_5_herbivorous-14      0.650619
Tar-5191_203_predator-5       -0.086896
Name: x, Length: 702, dtype: float64
x0 token_id
All-7078_312_carnivorous-7    -0.370031
Agl-fec0_63_camouflage-4      -0.518173
Gre-8842_8_herbivorous-19      1.027300
Ter-605f_11_metamorphosis-9    0.264267
Cul-6926_14_social-19          0.133167
                                 ...
Eur-24a9_165_Predators-1       0.264787
Ani6f2b_115_migration-20       0.522095
Bea-4f7a_8_herbivorous-3       0.389214
Spe-2571_5_herbivorous-14      0.650619
Tar-5191_203_predator-5       -0.086896
Name: x, Length: 703, dtype: float64
x0 token_id
All-7078_312_carnivorous-7    -0.370031
Agl-fec0_63_camouflage-4      -0.518173
Gre-8842_8_herbivorous-19      1.027300
Ter-605f_11_metamorphosis-9    0.264267
Cul-6926_14_social-19          0.133167
                                 ...
Eur-24a9_165_Predators-1       0.264787
Ani6f2b_115_migration-20       0.522095
Bea-4f7a_8_herbivorous-3       0.389214
Spe-2571_5_herbivorous-14      0.650619
Tar-5191_203_predator-5       -0.086896
Name: x, Length: 703, dtype: float64
x0 token_id
All-7078_312_carnivorous-7    -0.370031
Agl-fec0_63_camouflage-4      -0.518173
Gre-8842_8_herbivorous-19      1.027300
Ter-605f_11_metamorphosis-9    0.264267
Cul-6926_14_social-19          0.133167
                                 ...
Eur-24a9_165_Predators-1       0.264787
Ani6f2b_115_migration-20       0.522095
Bea-4f7a_8_herbivorous-3       0.389214
Spe-2571_5_herbivorous-14      0.650619
Tar-5191_203_predator-5       -0.086896
Name: x, Length: 703, dtype: float64
Spearman results
feat_tests
                       test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
cc>        rather          0.03927   -0.859        2     704    -2.07
conj>      arboreal        0.57597    0.233        2     704     0.56
           find            0.35362    0.547        1     704     0.93
           group           0.14484    0.859        1     704     1.46
           have            0.19794    0.537        2     704     1.29
           omnivorous      0.00879    0.773        4     704     2.63
           oviparous       0.19611    0.539        2     704     1.29
           scavenger       0.08115    1.028        1     704     1.75
           species         0.17436    0.801        1     704     1.36
obl<nsubj> crocodile       0.54111   -0.360        1     704    -0.61
book_cl_elong
                      effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath lemma
conj>   omnivorous  0.592893  0.002348  4  0.351522      0.00879    0.773
        species     0.579117  0.000226  1  0.335376      0.17436    0.801
        group       0.576958  0.000293  1  0.332881      0.14484    0.859
        find        0.546905  0.000133  1  0.299105      0.35362    0.547
cc>     rather     -0.545877  0.000568  2  0.297982      0.03927   -0.859
conj>   scavenger   0.541676 -0.000023  1  0.293413      0.08115    1.028
        have        0.531679  0.000848  2  0.282683      0.19794    0.537
        arboreal    0.518815  0.001341  2  0.269169      0.57597    0.233
        oviparous   0.500661  0.001341  2  0.250661      0.19611    0.539

                    test_Nx  test_N  test_st
arcpath lemma
conj>   omnivorous        4     704     2.63
        species           1     704     1.36
        group             1     704     1.46
        find              1     704     0.93
cc>     rather            2     704    -2.07
conj>   scavenger         1     704     1.75
        have              2     704     1.29
        arboreal          2     704     0.56
        oviparous         2     704     1.29
cluster ====> 2
np.sqrt(eigvals)
[0.33808872 0.62697769 0.72007619 0.89632704 1.06410813 1.12230729
 1.18718248 1.53181058]
cl_elong_a, cl_elong_v.round(2)
1.2902907515964552 [ 0.09  0.85 -0.48 -0.07 -0.11 -0.06 -0.06  0.07]
cluster data sample, mean shift
(388, 8)                                    0         1         2         3         4  \
token_id
Mal-71cc_120_camouflage-21 -1.302009 -0.939534 -0.265016  0.023493  2.230906
Dee-529a_89_dimorphism-2   -0.844279 -2.267208  0.048733  0.195251  0.072276
Card567_6_predators-4       0.904100 -0.764851 -0.374446  0.547933 -0.936067

                                   5         6         7
token_id
Mal-71cc_120_camouflage-21 -0.516883  0.280702 -0.751195
Dee-529a_89_dimorphism-2   -0.085056  0.221367  0.178788
Card567_6_predators-4       1.381315 -0.272819 -1.397842
cluster data elongation along main axis
                                effect        Dx  N      eff2
arcpath              lemma
nsubj<obj>conj>      song     1.034581  0.000746  1  1.070357
obl<                 eat      0.684902  0.000110  1  0.469091
                     provide  0.675109  0.000321  2  0.455772
obj<advcl<advmod>    also    -0.649883  0.000074  1  0.422348
obl<                 prey     0.638891  0.000220  1  0.408181
nsubj:pass<obl>case> with    -0.621112  0.003181  5  0.385780
nsubj<acl>advmod>    not      0.618468  0.000388  1  0.382503
nmod>nmod>           Africa  -0.613119  0.002238  3  0.375914
obl<                 know     0.607204  0.000585  2  0.368696
                     compete  0.588936  0.001527  3  0.346845
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                                  token         x
arcpath              lemma
nmod>nmod>           Africa     Bar-b361_99_Migration-1 -1.056930
                     Africa    Smi-7190_210_predator-11  0.922894
                     Africa     Whi-100a_42_migration-9 -0.202672
nsubj:pass<obl>case> with      Asi-f65e_70_dimorphism-2 -5.536542
                     with       Bil-e183_43_Predators-1 -1.391066
                     with         Lan-4994_4_language-2 -2.434696
                     with      Lon-b0af_249_migration-2 -2.812940
                     with           Pat-9307_138_care-3 -2.663568
nsubj<acl>advmod>    not         Lan-4994_95_language-6  0.430549
nsubj<obj>conj>      song       Ani-4d8b_157_language-2  2.891154
obj<advcl<advmod>    also     Eur-bc75_418_predators-12 -0.302634
obl<                 compete  Eur-bc75_370_predators-17  1.650754
                     compete   Gia-ae2f_21_predators-17  0.819770
                     compete  Tig-b95e_102_predators-30  1.445061
                     eat       Fro-2392_143_predator-17  1.147696
                     know      Ani-ab87_78_migration-14  1.296795
                     know     Sai-afdf_54_migrations-13  0.887286
                     prey     Mal-71cc_148_predators-10  2.705868
                     provide    Pla-9279_9_predators-24  0.374909
                     provide   Sal-702e_12_migration-26  0.533080
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (388,)
ftok (20, 2)
x0 token_id
Mal-71cc_120_camouflage-21   -1.081832
Dee-529a_89_dimorphism-2     -2.048998
Card567_6_predators-4        -0.497791
Ich-89df_479_predators-6     -0.768583
Wol-7b5f_77_predator-12      -0.402488
                                ...
Viv-7a58_34_viviparous-4      0.414085
Tyr-70f1_338_scavenger-9     -0.693279
Ani-4d8b_38_languages-14     -0.210384
Eur-bc75_370_predators-17     1.650754
Tyr-70f1_67_predators-8       1.820175
Name: x, Length: 385, dtype: float64
x0 token_id
Mal-71cc_120_camouflage-21   -1.081832
Dee-529a_89_dimorphism-2     -2.048998
Card567_6_predators-4        -0.497791
Ich-89df_479_predators-6     -0.768583
Wol-7b5f_77_predator-12      -0.402488
                                ...
Tyr-70f1_338_scavenger-9     -0.693279
Ani-4d8b_38_languages-14     -0.210384
Eur-bc75_370_predators-17     1.650754
Tyr-70f1_67_predators-8       1.820175
Whi-100a_42_migration-9      -0.202672
Name: x, Length: 383, dtype: float64
x0 token_id
Mal-71cc_120_camouflage-21   -1.081832
Dee-529a_89_dimorphism-2     -2.048998
Card567_6_predators-4        -0.497791
Ich-89df_479_predators-6     -0.768583
Wol-7b5f_77_predator-12      -0.402488
                                ...
Tyr-70f1_338_scavenger-9     -0.693279
Ani-4d8b_38_languages-14     -0.210384
Eur-bc75_370_predators-17     1.650754
Tyr-70f1_67_predators-8       1.820175
Whi-100a_42_migration-9      -0.202672
Name: x, Length: 387, dtype: float64
x0 token_id
Mal-71cc_120_camouflage-21   -1.081832
Dee-529a_89_dimorphism-2     -2.048998
Card567_6_predators-4        -0.497791
Ich-89df_479_predators-6     -0.768583
Wol-7b5f_77_predator-12      -0.402488
                                ...
Tyr-70f1_338_scavenger-9     -0.693279
Ani-4d8b_38_languages-14     -0.210384
Eur-bc75_370_predators-17     1.650754
Tyr-70f1_67_predators-8       1.820175
Whi-100a_42_migration-9      -0.202672
Name: x, Length: 387, dtype: float64
x0 token_id
Mal-71cc_120_camouflage-21   -1.081832
Dee-529a_89_dimorphism-2     -2.048998
Card567_6_predators-4        -0.497791
Ich-89df_479_predators-6     -0.768583
Wol-7b5f_77_predator-12      -0.402488
                                ...
Tyr-70f1_338_scavenger-9     -0.693279
Ani-4d8b_38_languages-14     -0.210384
Eur-bc75_370_predators-17     1.650754
Tyr-70f1_67_predators-8       1.820175
Whi-100a_42_migration-9      -0.202672
Name: x, Length: 387, dtype: float64
x0 token_id
Mal-71cc_120_camouflage-21   -1.081832
Dee-529a_89_dimorphism-2     -2.048998
Card567_6_predators-4        -0.497791
Ich-89df_479_predators-6     -0.768583
Wol-7b5f_77_predator-12      -0.402488
                                ...
Viv-7a58_34_viviparous-4      0.414085
Tyr-70f1_338_scavenger-9     -0.693279
Ani-4d8b_38_languages-14     -0.210384
Tyr-70f1_67_predators-8       1.820175
Whi-100a_42_migration-9      -0.202672
Name: x, Length: 385, dtype: float64
x0 token_id
Mal-71cc_120_camouflage-21   -1.081832
Dee-529a_89_dimorphism-2     -2.048998
Card567_6_predators-4        -0.497791
Ich-89df_479_predators-6     -0.768583
Wol-7b5f_77_predator-12      -0.402488
                                ...
Tyr-70f1_338_scavenger-9     -0.693279
Ani-4d8b_38_languages-14     -0.210384
Eur-bc75_370_predators-17     1.650754
Tyr-70f1_67_predators-8       1.820175
Whi-100a_42_migration-9      -0.202672
Name: x, Length: 387, dtype: float64
x0 token_id
Mal-71cc_120_camouflage-21   -1.081832
Dee-529a_89_dimorphism-2     -2.048998
Card567_6_predators-4        -0.497791
Ich-89df_479_predators-6     -0.768583
Wol-7b5f_77_predator-12      -0.402488
                                ...
Tyr-70f1_338_scavenger-9     -0.693279
Ani-4d8b_38_languages-14     -0.210384
Eur-bc75_370_predators-17     1.650754
Tyr-70f1_67_predators-8       1.820175
Whi-100a_42_migration-9      -0.202672
Name: x, Length: 386, dtype: float64
x0 token_id
Mal-71cc_120_camouflage-21   -1.081832
Dee-529a_89_dimorphism-2     -2.048998
Card567_6_predators-4        -0.497791
Ich-89df_479_predators-6     -0.768583
Wol-7b5f_77_predator-12      -0.402488
                                ...
Tyr-70f1_338_scavenger-9     -0.693279
Ani-4d8b_38_languages-14     -0.210384
Eur-bc75_370_predators-17     1.650754
Tyr-70f1_67_predators-8       1.820175
Whi-100a_42_migration-9      -0.202672
Name: x, Length: 387, dtype: float64
x0 token_id
Mal-71cc_120_camouflage-21   -1.081832
Dee-529a_89_dimorphism-2     -2.048998
Card567_6_predators-4        -0.497791
Ich-89df_479_predators-6     -0.768583
Wol-7b5f_77_predator-12      -0.402488
                                ...
Tyr-70f1_338_scavenger-9     -0.693279
Ani-4d8b_38_languages-14     -0.210384
Eur-bc75_370_predators-17     1.650754
Tyr-70f1_67_predators-8       1.820175
Whi-100a_42_migration-9      -0.202672
Name: x, Length: 386, dtype: float64
Spearman results
feat_tests
                              test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath              lemma
nmod>nmod>           Africa       0.87584   -0.099        3     388    -0.16
nsubj:pass<obl>case> with         0.00000   -2.992        5     388    -6.41
nsubj<acl>advmod>    not          0.68332    0.446        1     388     0.41
nsubj<obj>conj>      song         0.00742    2.913        1     388     2.69
obj<advcl<advmod>    also         0.79130   -0.289        1     388    -0.26
obl<                 compete      0.03507    1.330        3     388     2.12
                     eat          0.28621    1.165        1     388     1.07
                     know         0.15023    1.112        2     388     1.44
                     prey         0.01224    2.727        1     388     2.52
                     provide      0.54306    0.471        2     388     0.61
book_cl_elong
                                effect        Dx  N      eff2  test_pvalue  \
arcpath              lemma
nsubj<obj>conj>      song     1.034581  0.000746  1  1.070357      0.00742
obl<                 eat      0.684902  0.000110  1  0.469091      0.28621
                     provide  0.675109  0.000321  2  0.455772      0.54306
obj<advcl<advmod>    also    -0.649883  0.000074  1  0.422348      0.79130
obl<                 prey     0.638891  0.000220  1  0.408181      0.01224
nsubj:pass<obl>case> with    -0.621112  0.003181  5  0.385780      0.00000
nsubj<acl>advmod>    not      0.618468  0.000388  1  0.382503      0.68332
nmod>nmod>           Africa  -0.613119  0.002238  3  0.375914      0.87584
obl<                 know     0.607204  0.000585  2  0.368696      0.15023
                     compete  0.588936  0.001527  3  0.346845      0.03507

                              test_dX  test_Nx  test_N  test_st
arcpath              lemma
nsubj<obj>conj>      song       2.913        1     388     2.69
obl<                 eat        1.165        1     388     1.07
                     provide    0.471        2     388     0.61
obj<advcl<advmod>    also      -0.289        1     388    -0.26
obl<                 prey       2.727        1     388     2.52
nsubj:pass<obl>case> with      -2.992        5     388    -6.41
nsubj<acl>advmod>    not        0.446        1     388     0.41
nmod>nmod>           Africa    -0.099        3     388    -0.16
obl<                 know       1.112        2     388     1.44
                     compete    1.330        3     388     2.12
cluster ====> 3
np.sqrt(eigvals)
[0.12123659 0.20270751 0.22880568 0.23752059 0.29008602 0.3231053
 0.35927247 0.54288877]
cl_elong_a, cl_elong_v.round(2)
1.5110781170663024 [-0.03 -0.    0.36  0.81 -0.43  0.1   0.12 -0.1 ]
cluster data sample, mean shift
(362, 8)                                  0         1         2         3         4  \
token_id
Ani-ab87_118_migration-2  0.328536  0.160135 -0.313143  0.574203  0.425930
Son-520b_73_migration-2  -0.079652 -0.202692  0.058953  0.189270 -0.367938
Flo-338d_126_flowering-2  0.047793 -0.678576 -0.225106  0.011060 -0.557196

                                 5         6         7
token_id
Ani-ab87_118_migration-2 -0.047408 -0.044356  0.204173
Son-520b_73_migration-2  -0.073362  0.013658 -0.481638
Flo-338d_126_flowering-2 -0.837260  0.073056 -0.617610
cluster data elongation along main axis
                                effect        Dx  N      eff2
arcpath             lemma
det>                no       -0.697949  0.000504  1  0.487132
                    a        -0.692759 -0.002447  1  0.479916
                    the      -0.644185 -0.002747  1  0.414974
compound<nmod<cc>   and      -0.487666  0.005721  2  0.237818
case>               unlike   -0.478693  0.002783  1  0.229147
amod<amod>advmod>   highly   -0.386827  0.002277  1  0.149635
compound>           Reindeer  0.344455  0.006249  2  0.118649
advmod>             however  -0.332114  0.002215  1  0.110300
compound<nmod<case> of       -0.329019  0.009373  3  0.108253
                    in       -0.322989  0.001948  1  0.104322
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                                  token         x
arcpath             lemma
advmod>             however   Eas-6961_45_territorial-6 -0.468134
amod<amod>advmod>   highly        Pan-3679_96_social-21  0.059674
case>               unlike       Amb-b5dc_3_predators-3 -0.364435
compound<nmod<case> in         Rat-4b67_135_predator-17 -0.073609
                    of         Lan-4994_112_language-14 -0.273776
                    of          Pas-a544_2_flowering-21 -0.385331
                    of        Wal-8f46_154_predators-16 -0.179538
compound<nmod<cc>   and         Orc-02f3_16_cultures-17 -0.269129
                    and       Swa-27b4_296_migration-21 -0.227935
compound>           Reindeer     Ani6f2b_67_migration-2  0.328596
                    Reindeer      Rei5e90_9_migration-2  0.328596
det>                a              Wes30d4_16_display-5 -0.157579
                    no         Ruf-ac2f_10_dimorphism-6 -0.390874
                    the           Tyrfbca_26_predator-4 -0.385425
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (362,)
ftok (14, 2)
x0 token_id
Ani-ab87_118_migration-2     0.128890
Son-520b_73_migration-2      0.374244
Flo-338d_126_flowering-2     0.149943
Noc-ac81_7_nocturnal-2       0.195781
Ama-5ad6_51_herbivorous-3   -0.383104
                               ...
Mon-a04f_103_social-12       0.055119
Tyr-70f1_312_social-34      -0.208863
Cam-4bd8_55_Camouflage-1    -0.011411
Cam-5746_6_herbivorous-6     0.003468
Vam-5657_54_social-4         0.090008
Name: x, Length: 361, dtype: float64
x0 token_id
Ani-ab87_118_migration-2     0.128890
Son-520b_73_migration-2      0.374244
Flo-338d_126_flowering-2     0.149943
Noc-ac81_7_nocturnal-2       0.195781
Ama-5ad6_51_herbivorous-3   -0.383104
                               ...
Mon-a04f_103_social-12       0.055119
Tyr-70f1_312_social-34      -0.208863
Cam-4bd8_55_Camouflage-1    -0.011411
Cam-5746_6_herbivorous-6     0.003468
Vam-5657_54_social-4         0.090008
Name: x, Length: 361, dtype: float64
x0 token_id
Ani-ab87_118_migration-2     0.128890
Son-520b_73_migration-2      0.374244
Flo-338d_126_flowering-2     0.149943
Noc-ac81_7_nocturnal-2       0.195781
Ama-5ad6_51_herbivorous-3   -0.383104
                               ...
Mon-a04f_103_social-12       0.055119
Tyr-70f1_312_social-34      -0.208863
Cam-4bd8_55_Camouflage-1    -0.011411
Cam-5746_6_herbivorous-6     0.003468
Vam-5657_54_social-4         0.090008
Name: x, Length: 361, dtype: float64
x0 token_id
Ani-ab87_118_migration-2     0.128890
Son-520b_73_migration-2      0.374244
Flo-338d_126_flowering-2     0.149943
Noc-ac81_7_nocturnal-2       0.195781
Ama-5ad6_51_herbivorous-3   -0.383104
                               ...
Mon-a04f_103_social-12       0.055119
Tyr-70f1_312_social-34      -0.208863
Cam-4bd8_55_Camouflage-1    -0.011411
Cam-5746_6_herbivorous-6     0.003468
Vam-5657_54_social-4         0.090008
Name: x, Length: 361, dtype: float64
x0 token_id
Ani-ab87_118_migration-2     0.128890
Son-520b_73_migration-2      0.374244
Flo-338d_126_flowering-2     0.149943
Noc-ac81_7_nocturnal-2       0.195781
Ama-5ad6_51_herbivorous-3   -0.383104
                               ...
Mon-a04f_103_social-12       0.055119
Tyr-70f1_312_social-34      -0.208863
Cam-4bd8_55_Camouflage-1    -0.011411
Cam-5746_6_herbivorous-6     0.003468
Vam-5657_54_social-4         0.090008
Name: x, Length: 359, dtype: float64
x0 token_id
Ani-ab87_118_migration-2     0.128890
Son-520b_73_migration-2      0.374244
Flo-338d_126_flowering-2     0.149943
Noc-ac81_7_nocturnal-2       0.195781
Ama-5ad6_51_herbivorous-3   -0.383104
                               ...
Mon-a04f_103_social-12       0.055119
Tyr-70f1_312_social-34      -0.208863
Cam-4bd8_55_Camouflage-1    -0.011411
Cam-5746_6_herbivorous-6     0.003468
Vam-5657_54_social-4         0.090008
Name: x, Length: 360, dtype: float64
x0 token_id
Ani-ab87_118_migration-2     0.128890
Son-520b_73_migration-2      0.374244
Flo-338d_126_flowering-2     0.149943
Noc-ac81_7_nocturnal-2       0.195781
Ama-5ad6_51_herbivorous-3   -0.383104
                               ...
Mon-a04f_103_social-12       0.055119
Tyr-70f1_312_social-34      -0.208863
Cam-4bd8_55_Camouflage-1    -0.011411
Cam-5746_6_herbivorous-6     0.003468
Vam-5657_54_social-4         0.090008
Name: x, Length: 360, dtype: float64
x0 token_id
Ani-ab87_118_migration-2     0.128890
Son-520b_73_migration-2      0.374244
Flo-338d_126_flowering-2     0.149943
Noc-ac81_7_nocturnal-2       0.195781
Ama-5ad6_51_herbivorous-3   -0.383104
                               ...
Mon-a04f_103_social-12       0.055119
Tyr-70f1_312_social-34      -0.208863
Cam-4bd8_55_Camouflage-1    -0.011411
Cam-5746_6_herbivorous-6     0.003468
Vam-5657_54_social-4         0.090008
Name: x, Length: 361, dtype: float64
x0 token_id
Ani-ab87_118_migration-2     0.128890
Son-520b_73_migration-2      0.374244
Flo-338d_126_flowering-2     0.149943
Noc-ac81_7_nocturnal-2       0.195781
Ama-5ad6_51_herbivorous-3   -0.383104
                               ...
Mon-a04f_103_social-12       0.055119
Tyr-70f1_312_social-34      -0.208863
Cam-4bd8_55_Camouflage-1    -0.011411
Cam-5746_6_herbivorous-6     0.003468
Vam-5657_54_social-4         0.090008
Name: x, Length: 361, dtype: float64
x0 token_id
Ani-ab87_118_migration-2     0.128890
Son-520b_73_migration-2      0.374244
Flo-338d_126_flowering-2     0.149943
Noc-ac81_7_nocturnal-2       0.195781
Ama-5ad6_51_herbivorous-3   -0.383104
                               ...
Mon-a04f_103_social-12       0.055119
Tyr-70f1_312_social-34      -0.208863
Cam-4bd8_55_Camouflage-1    -0.011411
Cam-5746_6_herbivorous-6     0.003468
Vam-5657_54_social-4         0.090008
Name: x, Length: 361, dtype: float64
Spearman results
feat_tests
                              test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath             lemma
advmod>             however       0.01903   -0.471        1     362    -2.36
amod<amod>advmod>   highly        0.77313    0.058        1     362     0.29
case>               unlike        0.06806   -0.367        1     362    -1.83
compound<nmod<case> in            0.70806   -0.076        1     362    -0.37
                    of            0.01474   -0.284        3     362    -2.45
compound<nmod<cc>   and           0.07744   -0.252        2     362    -1.77
compound>           Reindeer      0.02087    0.329        2     362     2.32
det>                a             0.42821   -0.160        1     362    -0.79
                    no            0.05034   -0.394        1     362    -1.96
                    the           0.05364   -0.388        1     362    -1.94
book_cl_elong
                                effect        Dx  N      eff2  test_pvalue  \
arcpath             lemma
det>                no       -0.697949  0.000504  1  0.487132      0.05034
                    a        -0.692759 -0.002447  1  0.479916      0.42821
                    the      -0.644185 -0.002747  1  0.414974      0.05364
compound<nmod<cc>   and      -0.487666  0.005721  2  0.237818      0.07744
case>               unlike   -0.478693  0.002783  1  0.229147      0.06806
compound>           Reindeer  0.344455  0.006249  2  0.118649      0.02087
advmod>             however  -0.332114  0.002215  1  0.110300      0.01903
compound<nmod<case> of       -0.329019  0.009373  3  0.108253      0.01474
                    in       -0.322989  0.001948  1  0.104322      0.70806

                              test_dX  test_Nx  test_N  test_st
arcpath             lemma
det>                no         -0.394        1     362    -1.96
                    a          -0.160        1     362    -0.79
                    the        -0.388        1     362    -1.94
compound<nmod<cc>   and        -0.252        2     362    -1.77
case>               unlike     -0.367        1     362    -1.83
compound>           Reindeer    0.329        2     362     2.32
advmod>             however    -0.471        1     362    -2.36
compound<nmod<case> of         -0.284        3     362    -2.45
                    in         -0.076        1     362    -0.37
cluster ====> 4
np.sqrt(eigvals)
[0.24027666 0.30279109 0.37055078 0.46206608 0.52513231 0.56956187
 0.72235103 0.89797674]
cl_elong_a, cl_elong_v.round(2)
1.2431307048417892 [-0.05  0.03  0.27 -0.08  0.   -0.36  0.78 -0.43]
cluster data sample, mean shift
(300, 8)                                       0         1         2         3  \
token_id
Too-567c_13_use-19            -0.527112  0.385411  0.475709 -0.584917
Fro-2392_447_metamorphosis-25 -0.094972  0.636952 -0.403808 -0.665577
Chi-c10a_21_languages-8        1.005078 -0.320222  0.378411  0.245245

                                      4         5         6         7
token_id
Too-567c_13_use-19            -0.479868 -0.147483  0.361605  1.026466
Fro-2392_447_metamorphosis-25  0.108193  0.263618 -0.373068  0.002743
Chi-c10a_21_languages-8       -0.133074 -0.189564  0.138743  0.508566
cluster data elongation along main axis
                            effect        Dx   N      eff2
arcpath        lemma
conj>          predator   0.566762  0.001007   1  0.321219
               scavenger  0.543247  0.000488   1  0.295117
               dog        0.488627  0.001215   1  0.238757
obl<nsubj>     which      0.437705  0.007233   5  0.191585
obl<advcl<cop> be         0.436936  0.007128   6  0.190913
obl<nsubj>     most       0.428364  0.003040   2  0.183496
               they       0.417609  0.013252  10  0.174397
amod>          top       -0.402885  0.000300   2  0.162316
obl<nsubj>     species    0.398463  0.004560   3  0.158773
               that       0.395761  0.006602   5  0.156626
Compute the feature-associated token x1 positions (ftok) on the projected axis

/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

ftok
                                                  token         x
arcpath        lemma
amod>          top              Bea-71ad_121_predator-4 -0.263663
               top            Tyr-70f1_340_predators-18  0.451225
conj>          dog             Pre-0725_285_predators-3  0.420563
               predator      Acc-0f45_127_scavengers-18  0.457585
               scavenger      Cou-56f5_141_predators-19  0.726948
obl<advcl<cop> be             Din-756f_382_predators-55 -0.015049
               be            Eur-1ed4_52_hibernation-13  0.936412
               be          Lep-f8ec_10_metamorphosis-16 -0.018072
               be               Mac-1abb_7_predators-16  0.633051
               be              Pan-f76a_27_predators-10  0.758492
               be              Red-4352_16_predators-23  0.311078
obl<nsubj>     most               Pea-41a9_39_display-7  1.103161
               most                 Too-567c_400_use-19  0.573826
               species    Amp-436a_121_metamorphosis-12  0.240431
               species       Lep-f8ec_347_camouflage-13  1.132840
               species         Red-4352_149_predator-14  0.004053
               that            Jum-50eb_108_predator-22  0.538150
               that            Mer-5a4a_103_predator-38  0.006736
               that           Pyg-4c07_10_camouflage-15 -0.168558
               that           Rat-4b67_161_predators-16  0.771097
               that           Sea-e4bc_40_camouflage-15  0.239992
               they           Com-9826_488_predators-17  0.829366
               they           Kom-6ea1_169_predators-20  0.098261
               they            Lea-27ee_6_camouflage-13  0.506380
               they               Lep-f8ec_530_parts-16  0.736940
               they           Per-145f_245_predators-27  0.347594
               they             Pik-2f87_43_predators-6  0.032882
               they           Rat-4b67_209_predators-15  0.632570
               they        Rhi-9081_10_metamorphosis-13  0.035633
               they             Sea-bfbc_38_migration-3  0.471612
               they             Tre-008a_41_predator-18  1.055529
               which           Aur-441a_56_predators-20  0.816316
               which       Sal-5617_26_metamorphosis-12 -0.483162
               which            Spa-e46a_10_spawning-29  0.279529
               which           Tho-fdaf_52_predators-28  0.582016
               which          Uro-49a1_12_camouflage-12  0.387983
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (300,)
ftok (36, 2)
x0 token_id
Too-567c_13_use-19               0.106826
Fro-2392_447_metamorphosis-25   -0.418244
Chi-c10a_21_languages-8         -0.016268
Noc-ac81_11_nocturnal-20         0.012625
Cen-cfeb_81_predators-19        -0.656620
                                   ...
Afr-3b7b_178_territorial-18     -0.085593
Coe-f000_125_predators-6        -0.030928
Dun-cad0_47_metamorphosis-8     -0.065294
Kom-6ea1_169_predators-20        0.098261
Eur-bc75_69_predator-29          0.480594
Name: x, Length: 298, dtype: float64
x0 token_id
Too-567c_13_use-19               0.106826
Fro-2392_447_metamorphosis-25   -0.418244
Chi-c10a_21_languages-8         -0.016268
Noc-ac81_11_nocturnal-20         0.012625
Cen-cfeb_81_predators-19        -0.656620
                                   ...
Afr-3b7b_178_territorial-18     -0.085593
Coe-f000_125_predators-6        -0.030928
Dun-cad0_47_metamorphosis-8     -0.065294
Kom-6ea1_169_predators-20        0.098261
Eur-bc75_69_predator-29          0.480594
Name: x, Length: 299, dtype: float64
x0 token_id
Too-567c_13_use-19               0.106826
Fro-2392_447_metamorphosis-25   -0.418244
Chi-c10a_21_languages-8         -0.016268
Noc-ac81_11_nocturnal-20         0.012625
Cen-cfeb_81_predators-19        -0.656620
                                   ...
Afr-3b7b_178_territorial-18     -0.085593
Coe-f000_125_predators-6        -0.030928
Dun-cad0_47_metamorphosis-8     -0.065294
Kom-6ea1_169_predators-20        0.098261
Eur-bc75_69_predator-29          0.480594
Name: x, Length: 299, dtype: float64
x0 token_id
Too-567c_13_use-19               0.106826
Fro-2392_447_metamorphosis-25   -0.418244
Chi-c10a_21_languages-8         -0.016268
Noc-ac81_11_nocturnal-20         0.012625
Cen-cfeb_81_predators-19        -0.656620
                                   ...
Afr-3b7b_178_territorial-18     -0.085593
Coe-f000_125_predators-6        -0.030928
Dun-cad0_47_metamorphosis-8     -0.065294
Kom-6ea1_169_predators-20        0.098261
Eur-bc75_69_predator-29          0.480594
Name: x, Length: 299, dtype: float64
x0 token_id
Too-567c_13_use-19               0.106826
Fro-2392_447_metamorphosis-25   -0.418244
Chi-c10a_21_languages-8         -0.016268
Noc-ac81_11_nocturnal-20         0.012625
Cen-cfeb_81_predators-19        -0.656620
                                   ...
Afr-3b7b_178_territorial-18     -0.085593
Coe-f000_125_predators-6        -0.030928
Dun-cad0_47_metamorphosis-8     -0.065294
Kom-6ea1_169_predators-20        0.098261
Eur-bc75_69_predator-29          0.480594
Name: x, Length: 294, dtype: float64
x0 token_id
Too-567c_13_use-19               0.106826
Fro-2392_447_metamorphosis-25   -0.418244
Chi-c10a_21_languages-8         -0.016268
Noc-ac81_11_nocturnal-20         0.012625
Cen-cfeb_81_predators-19        -0.656620
                                   ...
Afr-3b7b_178_territorial-18     -0.085593
Coe-f000_125_predators-6        -0.030928
Dun-cad0_47_metamorphosis-8     -0.065294
Kom-6ea1_169_predators-20        0.098261
Eur-bc75_69_predator-29          0.480594
Name: x, Length: 298, dtype: float64
x0 token_id
Too-567c_13_use-19               0.106826
Fro-2392_447_metamorphosis-25   -0.418244
Chi-c10a_21_languages-8         -0.016268
Noc-ac81_11_nocturnal-20         0.012625
Cen-cfeb_81_predators-19        -0.656620
                                   ...
Afr-3b7b_178_territorial-18     -0.085593
Coe-f000_125_predators-6        -0.030928
Dun-cad0_47_metamorphosis-8     -0.065294
Kom-6ea1_169_predators-20        0.098261
Eur-bc75_69_predator-29          0.480594
Name: x, Length: 297, dtype: float64
x0 token_id
Too-567c_13_use-19               0.106826
Fro-2392_447_metamorphosis-25   -0.418244
Chi-c10a_21_languages-8         -0.016268
Noc-ac81_11_nocturnal-20         0.012625
Cen-cfeb_81_predators-19        -0.656620
                                   ...
Afr-3b7b_178_territorial-18     -0.085593
Coe-f000_125_predators-6        -0.030928
Dun-cad0_47_metamorphosis-8     -0.065294
Kom-6ea1_169_predators-20        0.098261
Eur-bc75_69_predator-29          0.480594
Name: x, Length: 295, dtype: float64
x0 token_id
Too-567c_13_use-19               0.106826
Fro-2392_447_metamorphosis-25   -0.418244
Chi-c10a_21_languages-8         -0.016268
Noc-ac81_11_nocturnal-20         0.012625
Cen-cfeb_81_predators-19        -0.656620
                                   ...
Lem-ec0f_29_migrations-9        -0.349045
Afr-3b7b_178_territorial-18     -0.085593
Coe-f000_125_predators-6        -0.030928
Dun-cad0_47_metamorphosis-8     -0.065294
Eur-bc75_69_predator-29          0.480594
Name: x, Length: 290, dtype: float64
x0 token_id
Too-567c_13_use-19               0.106826
Fro-2392_447_metamorphosis-25   -0.418244
Chi-c10a_21_languages-8         -0.016268
Noc-ac81_11_nocturnal-20         0.012625
Cen-cfeb_81_predators-19        -0.656620
                                   ...
Afr-3b7b_178_territorial-18     -0.085593
Coe-f000_125_predators-6        -0.030928
Dun-cad0_47_metamorphosis-8     -0.065294
Kom-6ea1_169_predators-20        0.098261
Eur-bc75_69_predator-29          0.480594
Name: x, Length: 295, dtype: float64
Spearman results
feat_tests
                          test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath        lemma
amod>          top            0.84117    0.064        2     300     0.20
conj>          dog            0.38391    0.392        1     300     0.87
               predator       0.34036    0.429        1     300     0.95
               scavenger      0.11958    0.699        1     300     1.56
obl<advcl<cop> be             0.02544    0.412        6     300     2.25
obl<nsubj>     most           0.01026    0.814        2     300     2.58
               species        0.09582    0.433        3     300     1.67
               that           0.21415    0.251        5     300     1.24
               they           0.00133    0.460       10     300     3.24
               which          0.15010    0.291        5     300     1.44
book_cl_elong
                            effect        Dx   N      eff2  test_pvalue  \
arcpath        lemma
conj>          predator   0.566762  0.001007   1  0.321219      0.34036
               scavenger  0.543247  0.000488   1  0.295117      0.11958
               dog        0.488627  0.001215   1  0.238757      0.38391
obl<nsubj>     which      0.437705  0.007233   5  0.191585      0.15010
obl<advcl<cop> be         0.436936  0.007128   6  0.190913      0.02544
obl<nsubj>     most       0.428364  0.003040   2  0.183496      0.01026
               they       0.417609  0.013252  10  0.174397      0.00133
               species    0.398463  0.004560   3  0.158773      0.09582
               that       0.395761  0.006602   5  0.156626      0.21415

                          test_dX  test_Nx  test_N  test_st
arcpath        lemma
conj>          predator     0.429        1     300     0.95
               scavenger    0.699        1     300     1.56
               dog          0.392        1     300     0.87
obl<nsubj>     which        0.291        5     300     1.44
obl<advcl<cop> be           0.412        6     300     2.25
obl<nsubj>     most         0.814        2     300     2.58
               they         0.460       10     300     3.24
               species      0.433        3     300     1.67
               that         0.251        5     300     1.24
cluster ====> 5
np.sqrt(eigvals)
[0.27659867 0.32460314 0.37713471 0.5691667  0.63004029 0.9342581
 1.16087891 1.35654457]
cl_elong_a, cl_elong_v.round(2)
1.1685495835952644 [ 0.17 -0.33  0.84  0.33  0.01 -0.15  0.06 -0.11]
cluster data sample, mean shift
(225, 8)                                   0         1         2         3         4  \
token_id
Rei-38eb_375_migrations-2  1.557142 -1.827753  1.158081 -0.768688 -0.138240
Sif-455b_24_Predators-1    1.215570 -0.150444  0.367608 -0.416331 -0.923397
Amo-ffe8_49_flowerings-4   1.539991 -0.088814  0.468683 -0.375404 -0.248663

                                  5         6         7
token_id
Rei-38eb_375_migrations-2  1.368218 -0.271862  0.282012
Sif-455b_24_Predators-1    0.738884 -0.428754  0.093353
Amo-ffe8_49_flowerings-4  -0.418040 -0.323803  0.637534
cluster data elongation along main axis
                          effect        Dx  N      eff2
arcpath         lemma
nsubj<advcl>    eat    -0.735485  0.001267  1  0.540939
cc>             and    -0.734013 -0.002569  2  0.538775
nsubj<obj>conj> shark  -0.726312  0.000273  1  0.527529
                gull   -0.701640  0.000273  1  0.492299
                hawk   -0.659465 -0.000130  1  0.434895
                marten -0.648754 -0.000130  1  0.420881
nsubj<          bear   -0.614532  0.000920  1  0.377650
                kill   -0.602624  0.001203  1  0.363155
mark>           as     -0.572789  0.000385  1  0.328087
nsubj<advcl>    take   -0.563878  0.003016  2  0.317959
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                               token         x
arcpath         lemma
cc>             and          Ani-4d8b_11_language-33 -1.403043
                and         Wes-8d71_350_predators-4 -1.098548
mark>           as      Sha-8b9d_273_ovoviviparous-8 -0.349241
nsubj<          bear          Tun-4bf6_71_predator-5 -1.544804
                kill        Sea-fb32_322_predators-2 -1.049956
nsubj<advcl>    eat         Pre-0725_206_Predators-1 -1.126455
                take         Cho-a88d_87_Predators-1 -1.436675
                take        Red-56ec_100_predators-7 -2.388116
nsubj<obj>conj> gull         Tun-4bf6_72_predators-4 -2.168231
                hawk        Eur-bc75_432_predators-3 -0.955835
                marten      Whi-b4c3_683_predators-3 -2.159667
                shark        Gri-95f2_38_predators-2 -0.812985
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (225,)
ftok (12, 2)
x0 token_id
Rei-38eb_375_migrations-2     1.336063
Sif-455b_24_Predators-1       0.275867
Amo-ffe8_49_flowerings-4      0.542374
Bla-4edd_101_predators-6      1.750102
Cho-a88d_87_Predators-1      -1.436675
                                ...
Com-3b7c_133_predator-6       0.569291
Ani-57f1_28_language-11       1.359060
Aus-3dd7_29_predator-7       -0.692916
Asi-8957_139_hibernation-6   -0.106691
Saidf6a_9_Migration-1         0.733845
Name: x, Length: 223, dtype: float64
x0 token_id
Rei-38eb_375_migrations-2     1.336063
Sif-455b_24_Predators-1       0.275867
Amo-ffe8_49_flowerings-4      0.542374
Bla-4edd_101_predators-6      1.750102
Cho-a88d_87_Predators-1      -1.436675
                                ...
Com-3b7c_133_predator-6       0.569291
Ani-57f1_28_language-11       1.359060
Aus-3dd7_29_predator-7       -0.692916
Asi-8957_139_hibernation-6   -0.106691
Saidf6a_9_Migration-1         0.733845
Name: x, Length: 224, dtype: float64
x0 token_id
Rei-38eb_375_migrations-2     1.336063
Sif-455b_24_Predators-1       0.275867
Amo-ffe8_49_flowerings-4      0.542374
Bla-4edd_101_predators-6      1.750102
Cho-a88d_87_Predators-1      -1.436675
                                ...
Com-3b7c_133_predator-6       0.569291
Ani-57f1_28_language-11       1.359060
Aus-3dd7_29_predator-7       -0.692916
Asi-8957_139_hibernation-6   -0.106691
Saidf6a_9_Migration-1         0.733845
Name: x, Length: 224, dtype: float64
x0 token_id
Rei-38eb_375_migrations-2     1.336063
Sif-455b_24_Predators-1       0.275867
Amo-ffe8_49_flowerings-4      0.542374
Bla-4edd_101_predators-6      1.750102
Cho-a88d_87_Predators-1      -1.436675
                                ...
Com-3b7c_133_predator-6       0.569291
Ani-57f1_28_language-11       1.359060
Aus-3dd7_29_predator-7       -0.692916
Asi-8957_139_hibernation-6   -0.106691
Saidf6a_9_Migration-1         0.733845
Name: x, Length: 224, dtype: float64
x0 token_id
Rei-38eb_375_migrations-2     1.336063
Sif-455b_24_Predators-1       0.275867
Amo-ffe8_49_flowerings-4      0.542374
Bla-4edd_101_predators-6      1.750102
Cho-a88d_87_Predators-1      -1.436675
                                ...
Com-3b7c_133_predator-6       0.569291
Ani-57f1_28_language-11       1.359060
Aus-3dd7_29_predator-7       -0.692916
Asi-8957_139_hibernation-6   -0.106691
Saidf6a_9_Migration-1         0.733845
Name: x, Length: 224, dtype: float64
x0 token_id
Rei-38eb_375_migrations-2     1.336063
Sif-455b_24_Predators-1       0.275867
Amo-ffe8_49_flowerings-4      0.542374
Bla-4edd_101_predators-6      1.750102
Atl4b97_29_migration-23       0.324287
                                ...
Com-3b7c_133_predator-6       0.569291
Ani-57f1_28_language-11       1.359060
Aus-3dd7_29_predator-7       -0.692916
Asi-8957_139_hibernation-6   -0.106691
Saidf6a_9_Migration-1         0.733845
Name: x, Length: 223, dtype: float64
x0 token_id
Rei-38eb_375_migrations-2     1.336063
Sif-455b_24_Predators-1       0.275867
Amo-ffe8_49_flowerings-4      0.542374
Bla-4edd_101_predators-6      1.750102
Cho-a88d_87_Predators-1      -1.436675
                                ...
Com-3b7c_133_predator-6       0.569291
Ani-57f1_28_language-11       1.359060
Aus-3dd7_29_predator-7       -0.692916
Asi-8957_139_hibernation-6   -0.106691
Saidf6a_9_Migration-1         0.733845
Name: x, Length: 224, dtype: float64
x0 token_id
Rei-38eb_375_migrations-2     1.336063
Sif-455b_24_Predators-1       0.275867
Amo-ffe8_49_flowerings-4      0.542374
Bla-4edd_101_predators-6      1.750102
Cho-a88d_87_Predators-1      -1.436675
                                ...
Com-3b7c_133_predator-6       0.569291
Ani-57f1_28_language-11       1.359060
Aus-3dd7_29_predator-7       -0.692916
Asi-8957_139_hibernation-6   -0.106691
Saidf6a_9_Migration-1         0.733845
Name: x, Length: 224, dtype: float64
x0 token_id
Rei-38eb_375_migrations-2     1.336063
Sif-455b_24_Predators-1       0.275867
Amo-ffe8_49_flowerings-4      0.542374
Bla-4edd_101_predators-6      1.750102
Cho-a88d_87_Predators-1      -1.436675
                                ...
Com-3b7c_133_predator-6       0.569291
Ani-57f1_28_language-11       1.359060
Aus-3dd7_29_predator-7       -0.692916
Asi-8957_139_hibernation-6   -0.106691
Saidf6a_9_Migration-1         0.733845
Name: x, Length: 224, dtype: float64
x0 token_id
Rei-38eb_375_migrations-2     1.336063
Sif-455b_24_Predators-1       0.275867
Amo-ffe8_49_flowerings-4      0.542374
Bla-4edd_101_predators-6      1.750102
Cho-a88d_87_Predators-1      -1.436675
                                ...
Com-3b7c_133_predator-6       0.569291
Ani-57f1_28_language-11       1.359060
Aus-3dd7_29_predator-7       -0.692916
Asi-8957_139_hibernation-6   -0.106691
Saidf6a_9_Migration-1         0.733845
Name: x, Length: 224, dtype: float64
Spearman results
feat_tests
                        test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath         lemma
cc>             and         0.03664   -1.348        2     225    -2.10
mark>           as          0.63321   -0.436        1     225    -0.48
nsubj<          bear        0.07240   -1.637        1     225    -1.81
                kill        0.21173   -1.140        1     225    -1.25
nsubj<advcl>    eat         0.18243   -1.217        1     225    -1.34
                take        0.00167   -2.015        2     225    -3.18
nsubj<obj>conj> gull        0.01270   -2.263        1     225    -2.51
                hawk        0.25223   -1.046        1     225    -1.15
                marten      0.01305   -2.255        1     225    -2.50
                shark       0.32341   -0.902        1     225    -0.99
book_cl_elong
                          effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath         lemma
nsubj<advcl>    eat    -0.735485  0.001267  1  0.540939      0.18243   -1.217
cc>             and    -0.734013 -0.002569  2  0.538775      0.03664   -1.348
nsubj<obj>conj> shark  -0.726312  0.000273  1  0.527529      0.32341   -0.902
                gull   -0.701640  0.000273  1  0.492299      0.01270   -2.263
                hawk   -0.659465 -0.000130  1  0.434895      0.25223   -1.046
                marten -0.648754 -0.000130  1  0.420881      0.01305   -2.255
nsubj<          bear   -0.614532  0.000920  1  0.377650      0.07240   -1.637
                kill   -0.602624  0.001203  1  0.363155      0.21173   -1.140
mark>           as     -0.572789  0.000385  1  0.328087      0.63321   -0.436
nsubj<advcl>    take   -0.563878  0.003016  2  0.317959      0.00167   -2.015

                        test_Nx  test_N  test_st
arcpath         lemma
nsubj<advcl>    eat           1     225    -1.34
cc>             and           2     225    -2.10
nsubj<obj>conj> shark         1     225    -0.99
                gull          1     225    -2.51
                hawk          1     225    -1.15
                marten        1     225    -2.50
nsubj<          bear          1     225    -1.81
                kill          1     225    -1.25
mark>           as            1     225    -0.48
nsubj<advcl>    take          2     225    -3.18
cluster ====> 6
np.sqrt(eigvals)
[0.2232351  0.25060335 0.3181119  0.35343123 0.44665214 0.5020071
 0.60398304 0.7115003 ]
cl_elong_a, cl_elong_v.round(2)
1.178013696860885 [ 0.03 -0.44 -0.65 -0.48 -0.16  0.32 -0.07  0.16]
cluster data sample, mean shift
(592, 8)                                     0         1         2         3         4  \
token_id
The-f5b4_229_herbivorous-27  0.787818 -0.495332  0.125351  0.533694 -0.160688
Sem-88a0_181_semelparous-5  -0.409528 -0.450029 -0.437162 -0.376757  0.825246
Hou-905b_192_social-7        0.311038  1.015451 -0.111412 -0.051584 -0.109523

                                    5         6         7
token_id
The-f5b4_229_herbivorous-27 -0.489806 -0.293769 -0.093034
Sem-88a0_181_semelparous-5   1.035690 -0.192545 -0.076000
Hou-905b_192_social-7        0.176855 -0.069926  0.288345
cluster data elongation along main axis
                                     effect        Dx   N      eff2
arcpath                  lemma
det>                     a         0.743858 -0.002351   3  0.553324
                         that      0.719770 -0.000193   1  0.518068
                         these     0.702850 -0.000117   1  0.493998
                         this      0.683348 -0.000309   1  0.466964
                         the       0.673413 -0.001331   1  0.453485
compound<nmod<nmod:poss> they      0.631585  0.000353   1  0.398900
amod<nmod<amod>          numerous  0.627911  0.001909   2  0.394273
cc>                      rather    0.612505  0.000263   1  0.375162
amod<nmod<amod>          other     0.606951  0.002864   3  0.368390
cc>                      or        0.581793  0.006918  14  0.338483
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                                          token         x
arcpath                  lemma
amod<nmod<amod>          numerous         Din-756f_12_social-24  0.353199
                         numerous         Eur-d3a5_12_social-23  0.617284
                         other           Coo-03b6_183_social-17  0.734284
                         other           Hum-c1bb_376_social-26  0.289316
                         other           Lem-f2d0_303_social-22  0.570278
cc>                      or            Ame-86f0_83_predators-14  0.289620
                         or            Apo-f97b_16_poisonous-25  0.241771
                         or           Che-369e_336_predators-29  0.730594
                         or              Eur-6423_165_social-56 -0.068000
                         or           Fer-bbf9_81_scavengers-23  0.232547
                         or          Gas-303b_113_scavengers-12  0.908863
                         or            Gia-b75c_119_nocturnal-8  0.195540
                         or               Haz-b2c1_29_torpor-22  0.712023
                         or        Lep-f8ec_170_metamorphosis-9  0.893868
                         or           Lon-b0af_148_nocturnal-37  0.850611
                         or           Lon-b0af_219_nocturnal-10  0.976176
                         or              Mil-11ed_213_social-10  0.478483
                         or              Pre-0725_130_social-24  1.354074
                         or           Red-5893_168_predators-32  0.690737
                         rather      Liz-2f75_178_camouflage-16  0.627312
compound<nmod<nmod:poss> they         Lan-4994_123_language-126 -0.231329
det>                     a               Arm-33e3_51_nomadic-10 -0.063110
                         a              Smi-7190_127_predator-3  0.804140
                         a                 Wolbadc_2_predator-5  0.403436
                         that        Cam-4bd8_146_camouflage-32  1.361293
                         the           Ant-cf9b_35_predators-13 -0.061909
                         these         Cep-fb80_127_predators-2  0.825457
                         this           Nil-600c_341_predator-2  0.247042
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (592,)
ftok (28, 2)
x0 token_id
The-f5b4_229_herbivorous-27   -0.223943
Sem-88a0_181_semelparous-5     0.853801
Hou-905b_192_social-7         -0.213038
Viv-7a58_35_viviparous-13      0.956877
Rat-9c9a_74_herbivorous-46    -0.241408
                                 ...
Bla-1ce3_110_social-23        -0.765470
Eur-894a_54_social-5           0.110598
Skif7b3_10_social-31          -0.281310
Ani-66e9_249_social-25        -0.033465
Hor-8eda_50_social-5          -0.505221
Name: x, Length: 590, dtype: float64
x0 token_id
The-f5b4_229_herbivorous-27   -0.223943
Sem-88a0_181_semelparous-5     0.853801
Hou-905b_192_social-7         -0.213038
Viv-7a58_35_viviparous-13      0.956877
Rat-9c9a_74_herbivorous-46    -0.241408
                                 ...
Bla-1ce3_110_social-23        -0.765470
Eur-894a_54_social-5           0.110598
Skif7b3_10_social-31          -0.281310
Ani-66e9_249_social-25        -0.033465
Hor-8eda_50_social-5          -0.505221
Name: x, Length: 589, dtype: float64
x0 token_id
The-f5b4_229_herbivorous-27   -0.223943
Sem-88a0_181_semelparous-5     0.853801
Hou-905b_192_social-7         -0.213038
Viv-7a58_35_viviparous-13      0.956877
Rat-9c9a_74_herbivorous-46    -0.241408
                                 ...
Bla-1ce3_110_social-23        -0.765470
Eur-894a_54_social-5           0.110598
Skif7b3_10_social-31          -0.281310
Ani-66e9_249_social-25        -0.033465
Hor-8eda_50_social-5          -0.505221
Name: x, Length: 578, dtype: float64
x0 token_id
The-f5b4_229_herbivorous-27   -0.223943
Sem-88a0_181_semelparous-5     0.853801
Hou-905b_192_social-7         -0.213038
Viv-7a58_35_viviparous-13      0.956877
Rat-9c9a_74_herbivorous-46    -0.241408
                                 ...
Bla-1ce3_110_social-23        -0.765470
Eur-894a_54_social-5           0.110598
Skif7b3_10_social-31          -0.281310
Ani-66e9_249_social-25        -0.033465
Hor-8eda_50_social-5          -0.505221
Name: x, Length: 591, dtype: float64
x0 token_id
The-f5b4_229_herbivorous-27   -0.223943
Sem-88a0_181_semelparous-5     0.853801
Hou-905b_192_social-7         -0.213038
Viv-7a58_35_viviparous-13      0.956877
Rat-9c9a_74_herbivorous-46    -0.241408
                                 ...
Bla-1ce3_110_social-23        -0.765470
Eur-894a_54_social-5           0.110598
Skif7b3_10_social-31          -0.281310
Ani-66e9_249_social-25        -0.033465
Hor-8eda_50_social-5          -0.505221
Name: x, Length: 591, dtype: float64
x0 token_id
The-f5b4_229_herbivorous-27   -0.223943
Sem-88a0_181_semelparous-5     0.853801
Hou-905b_192_social-7         -0.213038
Viv-7a58_35_viviparous-13      0.956877
Rat-9c9a_74_herbivorous-46    -0.241408
                                 ...
Bla-1ce3_110_social-23        -0.765470
Eur-894a_54_social-5           0.110598
Skif7b3_10_social-31          -0.281310
Ani-66e9_249_social-25        -0.033465
Hor-8eda_50_social-5          -0.505221
Name: x, Length: 589, dtype: float64
x0 token_id
The-f5b4_229_herbivorous-27   -0.223943
Sem-88a0_181_semelparous-5     0.853801
Hou-905b_192_social-7         -0.213038
Viv-7a58_35_viviparous-13      0.956877
Rat-9c9a_74_herbivorous-46    -0.241408
                                 ...
Bla-1ce3_110_social-23        -0.765470
Eur-894a_54_social-5           0.110598
Skif7b3_10_social-31          -0.281310
Ani-66e9_249_social-25        -0.033465
Hor-8eda_50_social-5          -0.505221
Name: x, Length: 591, dtype: float64
x0 token_id
The-f5b4_229_herbivorous-27   -0.223943
Sem-88a0_181_semelparous-5     0.853801
Hou-905b_192_social-7         -0.213038
Viv-7a58_35_viviparous-13      0.956877
Rat-9c9a_74_herbivorous-46    -0.241408
                                 ...
Bla-1ce3_110_social-23        -0.765470
Eur-894a_54_social-5           0.110598
Skif7b3_10_social-31          -0.281310
Ani-66e9_249_social-25        -0.033465
Hor-8eda_50_social-5          -0.505221
Name: x, Length: 591, dtype: float64
x0 token_id
The-f5b4_229_herbivorous-27   -0.223943
Sem-88a0_181_semelparous-5     0.853801
Hou-905b_192_social-7         -0.213038
Viv-7a58_35_viviparous-13      0.956877
Rat-9c9a_74_herbivorous-46    -0.241408
                                 ...
Bla-1ce3_110_social-23        -0.765470
Eur-894a_54_social-5           0.110598
Skif7b3_10_social-31          -0.281310
Ani-66e9_249_social-25        -0.033465
Hor-8eda_50_social-5          -0.505221
Name: x, Length: 591, dtype: float64
x0 token_id
The-f5b4_229_herbivorous-27   -0.223943
Sem-88a0_181_semelparous-5     0.853801
Hou-905b_192_social-7         -0.213038
Viv-7a58_35_viviparous-13      0.956877
Rat-9c9a_74_herbivorous-46    -0.241408
                                 ...
Bla-1ce3_110_social-23        -0.765470
Eur-894a_54_social-5           0.110598
Skif7b3_10_social-31          -0.281310
Ani-66e9_249_social-25        -0.033465
Hor-8eda_50_social-5          -0.505221
Name: x, Length: 591, dtype: float64
Spearman results
feat_tests
                                   test_pvalue  test_dX  test_Nx  test_N  \
arcpath                  lemma
amod<nmod<amod>          numerous      0.20286    0.471        2     592
                         other         0.08635    0.518        3     592
cc>                      or            0.00002    0.605       14     592
                         rather        0.24132    0.613        1     592
compound<nmod<nmod:poss> they          0.63656   -0.247        1     592
det>                     a             0.22394    0.368        3     592
                         that          0.00979    1.348        1     592
                         the           0.88219   -0.078        1     592
                         these         0.12070    0.811        1     592
                         this          0.65763    0.232        1     592

                                   test_st
arcpath                  lemma
amod<nmod<amod>          numerous     1.27
                         other        1.72
cc>                      or           4.35
                         rather       1.17
compound<nmod<nmod:poss> they        -0.47
det>                     a            1.22
                         that         2.59
                         the         -0.15
                         these        1.55
                         this         0.44
book_cl_elong
                            effect        Dx   N      eff2  test_pvalue  \
arcpath         lemma
det>            a         0.743858 -0.002351   3  0.553324      0.22394
                that      0.719770 -0.000193   1  0.518068      0.00979
                these     0.702850 -0.000117   1  0.493998      0.12070
                this      0.683348 -0.000309   1  0.466964      0.65763
amod<nmod<amod> numerous  0.627911  0.001909   2  0.394273      0.20286
cc>             rather    0.612505  0.000263   1  0.375162      0.24132
amod<nmod<amod> other     0.606951  0.002864   3  0.368390      0.08635
cc>             or        0.581793  0.006918  14  0.338483      0.00002

                          test_dX  test_Nx  test_N  test_st
arcpath         lemma
det>            a           0.368        3     592     1.22
                that        1.348        1     592     2.59
                these       0.811        1     592     1.55
                this        0.232        1     592     0.44
amod<nmod<amod> numerous    0.471        2     592     1.27
cc>             rather      0.613        1     592     1.17
amod<nmod<amod> other       0.518        3     592     1.72
cc>             or          0.605       14     592     4.35
cluster ====> 7
np.sqrt(eigvals)
[0.12140657 0.22072894 0.24992592 0.37051162 0.50897178 0.66044193
 0.91155104 3.99092604]
cl_elong_a, cl_elong_v.round(2)
4.37817070221761 [ 0.03 -0.01  0.85 -0.42  0.14  0.11 -0.25  0.04]
cluster data sample, mean shift
(34, 8)                                  0         1         2         3         4  \
token_id
Elk-a58a_163_Predators-1  0.464887  0.338281  1.175419 -0.372775 -0.455096
Wes-8d71_347_predators-2  0.304192  0.537981 -0.646662  0.000307  0.072452
Lan-4994_40_language-4   -1.110708 -4.026065 -0.151554 -0.984383 -0.459296

                                 5         6         7
token_id
Elk-a58a_163_Predators-1  0.546577  0.140464  0.360037
Wes-8d71_347_predators-2 -0.356812  0.354595  0.283944
Lan-4994_40_language-4    0.066947 -0.436168 -0.028737
cluster data elongation along main axis
                      effect        Dx  N      eff2
arcpath lemma
amod>   other      -0.797233  0.019863  5  0.635580
        such       -0.786409  0.006638  1  0.618439
        major      -0.778833  0.004550  1  0.606581
        large      -0.716845  0.002889  1  0.513866
        common     -0.710293  0.005893  1  0.504516
        natural    -0.618167  0.006667  2  0.382131
        Mammalian  -0.609988  0.006545  1  0.372086
        ambush     -0.588592  0.004712  1  0.346440
        potential  -0.505447  0.003103  1  0.255477
        Vertebrate -0.482714  0.016242  2  0.233012
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                       token         x
arcpath lemma
amod>   Mammalian   Tai-3286_130_predators-2 -0.591035
        Vertebrate   Pre-0725_85_predators-3 -0.487031
        Vertebrate  Bee-ace3_231_predators-2 -0.129107
        ambush       Pre-0725_85_predators-3 -0.487031
        common      Nor-c9d9_158_predators-3 -0.322862
        large       Cro-5646_352_predators-3 -1.880397
        major       Wil-de29_118_predators-2 -0.277323
        natural     Nor-c9d9_158_predators-3 -0.322862
        natural     Cap-154f_110_predators-2  0.201567
        other       Com-43a2_100_predators-2  0.697094
        other       Cro-5646_352_predators-3 -1.880397
        other       Hum-85c3_271_predators-2 -1.364015
        other       Lem-f2d0_486_predators-2 -0.426579
        other       Slo-4b9b_175_predators-3 -0.986531
        potential   Slo-4b9b_175_predators-3 -0.986531
        such         Str-7d42_87_predators-2 -0.030513
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (34,)
ftok (16, 2)
x0 token_id
Elk-a58a_163_Predators-1    1.145863
Wes-8d71_347_predators-2   -0.655883
Lan-4994_40_language-4      0.354102
Woo-a311_26_Predators-1     0.859439
Hum-85c3_271_predators-2   -1.364015
Gre-e890_122_Predators-1    0.365537
Str-7d42_87_predators-2    -0.030513
Wes-8d71_348_predators-2    0.013449
Taw-0bfd_102_Predators-1    0.577393
Lem-f2d0_486_predators-2   -0.426579
Meg-fd01_293_predators-2    0.292361
Wil-de29_118_predators-2   -0.277323
Pre-0725_85_predators-3    -0.487031
Slo-13c7_59_Predators-1     0.887728
Coa-e8c3_75_predators-2     0.054652
Cro-5646_352_predators-3   -1.880397
Nor-4d51_286_Predators-1   -0.492640
Wil-3cbf_108_Predators-1    0.818485
Slo-4b9b_175_predators-3   -0.986531
Nor-c9d9_158_predators-3   -0.322862
Gun-5a73_99_Predators-1     0.795404
Woo-fa9e_26_Predators-1     1.167656
Lep-7440_55_Predators-1     0.551982
Mex-2908_68_Predators-1     0.553689
Pre-0725_103_predators-2    0.014113
Whi-100a_59_Predators-1     0.916946
Bee-ace3_231_predators-2   -0.129107
Com-43a2_100_predators-2    0.697094
Sta-7425_30_Predators-1    -1.373112
Oli-4839_141_predators-6   -0.079031
Wil-3cbf_103_Predators-1    0.239388
Chi-6eec_125_Predators-1    0.859107
Cap-154f_110_predators-2    0.201567
Name: x, dtype: float64
x0 token_id
Elk-a58a_163_Predators-1    1.145863
Wes-8d71_347_predators-2   -0.655883
Lan-4994_40_language-4      0.354102
Woo-a311_26_Predators-1     0.859439
Hum-85c3_271_predators-2   -1.364015
Gre-e890_122_Predators-1    0.365537
Str-7d42_87_predators-2    -0.030513
Wes-8d71_348_predators-2    0.013449
Taw-0bfd_102_Predators-1    0.577393
Lem-f2d0_486_predators-2   -0.426579
Meg-fd01_293_predators-2    0.292361
Wil-de29_118_predators-2   -0.277323
Slo-13c7_59_Predators-1     0.887728
Coa-e8c3_75_predators-2     0.054652
Cro-5646_352_predators-3   -1.880397
Nor-4d51_286_Predators-1   -0.492640
Wil-3cbf_108_Predators-1    0.818485
Slo-4b9b_175_predators-3   -0.986531
Nor-c9d9_158_predators-3   -0.322862
Gun-5a73_99_Predators-1     0.795404
Woo-fa9e_26_Predators-1     1.167656
Lep-7440_55_Predators-1     0.551982
Mex-2908_68_Predators-1     0.553689
Pre-0725_103_predators-2    0.014113
Whi-100a_59_Predators-1     0.916946
Com-43a2_100_predators-2    0.697094
Tai-3286_130_predators-2   -0.591035
Sta-7425_30_Predators-1    -1.373112
Oli-4839_141_predators-6   -0.079031
Wil-3cbf_103_Predators-1    0.239388
Chi-6eec_125_Predators-1    0.859107
Cap-154f_110_predators-2    0.201567
Name: x, dtype: float64
x0 token_id
Elk-a58a_163_Predators-1    1.145863
Wes-8d71_347_predators-2   -0.655883
Lan-4994_40_language-4      0.354102
Woo-a311_26_Predators-1     0.859439
Hum-85c3_271_predators-2   -1.364015
Gre-e890_122_Predators-1    0.365537
Str-7d42_87_predators-2    -0.030513
Wes-8d71_348_predators-2    0.013449
Taw-0bfd_102_Predators-1    0.577393
Lem-f2d0_486_predators-2   -0.426579
Meg-fd01_293_predators-2    0.292361
Wil-de29_118_predators-2   -0.277323
Slo-13c7_59_Predators-1     0.887728
Coa-e8c3_75_predators-2     0.054652
Cro-5646_352_predators-3   -1.880397
Nor-4d51_286_Predators-1   -0.492640
Wil-3cbf_108_Predators-1    0.818485
Slo-4b9b_175_predators-3   -0.986531
Nor-c9d9_158_predators-3   -0.322862
Gun-5a73_99_Predators-1     0.795404
Woo-fa9e_26_Predators-1     1.167656
Lep-7440_55_Predators-1     0.551982
Mex-2908_68_Predators-1     0.553689
Pre-0725_103_predators-2    0.014113
Whi-100a_59_Predators-1     0.916946
Bee-ace3_231_predators-2   -0.129107
Com-43a2_100_predators-2    0.697094
Tai-3286_130_predators-2   -0.591035
Sta-7425_30_Predators-1    -1.373112
Oli-4839_141_predators-6   -0.079031
Wil-3cbf_103_Predators-1    0.239388
Chi-6eec_125_Predators-1    0.859107
Cap-154f_110_predators-2    0.201567
Name: x, dtype: float64
x0 token_id
Elk-a58a_163_Predators-1    1.145863
Wes-8d71_347_predators-2   -0.655883
Lan-4994_40_language-4      0.354102
Woo-a311_26_Predators-1     0.859439
Hum-85c3_271_predators-2   -1.364015
Gre-e890_122_Predators-1    0.365537
Str-7d42_87_predators-2    -0.030513
Wes-8d71_348_predators-2    0.013449
Taw-0bfd_102_Predators-1    0.577393
Lem-f2d0_486_predators-2   -0.426579
Meg-fd01_293_predators-2    0.292361
Wil-de29_118_predators-2   -0.277323
Pre-0725_85_predators-3    -0.487031
Slo-13c7_59_Predators-1     0.887728
Coa-e8c3_75_predators-2     0.054652
Cro-5646_352_predators-3   -1.880397
Nor-4d51_286_Predators-1   -0.492640
Wil-3cbf_108_Predators-1    0.818485
Slo-4b9b_175_predators-3   -0.986531
Gun-5a73_99_Predators-1     0.795404
Woo-fa9e_26_Predators-1     1.167656
Lep-7440_55_Predators-1     0.551982
Mex-2908_68_Predators-1     0.553689
Pre-0725_103_predators-2    0.014113
Whi-100a_59_Predators-1     0.916946
Bee-ace3_231_predators-2   -0.129107
Com-43a2_100_predators-2    0.697094
Tai-3286_130_predators-2   -0.591035
Sta-7425_30_Predators-1    -1.373112
Oli-4839_141_predators-6   -0.079031
Wil-3cbf_103_Predators-1    0.239388
Chi-6eec_125_Predators-1    0.859107
Cap-154f_110_predators-2    0.201567
Name: x, dtype: float64
x0 token_id
Elk-a58a_163_Predators-1    1.145863
Wes-8d71_347_predators-2   -0.655883
Lan-4994_40_language-4      0.354102
Woo-a311_26_Predators-1     0.859439
Hum-85c3_271_predators-2   -1.364015
Gre-e890_122_Predators-1    0.365537
Str-7d42_87_predators-2    -0.030513
Wes-8d71_348_predators-2    0.013449
Taw-0bfd_102_Predators-1    0.577393
Lem-f2d0_486_predators-2   -0.426579
Meg-fd01_293_predators-2    0.292361
Wil-de29_118_predators-2   -0.277323
Pre-0725_85_predators-3    -0.487031
Slo-13c7_59_Predators-1     0.887728
Coa-e8c3_75_predators-2     0.054652
Nor-4d51_286_Predators-1   -0.492640
Wil-3cbf_108_Predators-1    0.818485
Slo-4b9b_175_predators-3   -0.986531
Nor-c9d9_158_predators-3   -0.322862
Gun-5a73_99_Predators-1     0.795404
Woo-fa9e_26_Predators-1     1.167656
Lep-7440_55_Predators-1     0.551982
Mex-2908_68_Predators-1     0.553689
Pre-0725_103_predators-2    0.014113
Whi-100a_59_Predators-1     0.916946
Bee-ace3_231_predators-2   -0.129107
Com-43a2_100_predators-2    0.697094
Tai-3286_130_predators-2   -0.591035
Sta-7425_30_Predators-1    -1.373112
Oli-4839_141_predators-6   -0.079031
Wil-3cbf_103_Predators-1    0.239388
Chi-6eec_125_Predators-1    0.859107
Cap-154f_110_predators-2    0.201567
Name: x, dtype: float64
x0 token_id
Elk-a58a_163_Predators-1    1.145863
Wes-8d71_347_predators-2   -0.655883
Lan-4994_40_language-4      0.354102
Woo-a311_26_Predators-1     0.859439
Hum-85c3_271_predators-2   -1.364015
Gre-e890_122_Predators-1    0.365537
Str-7d42_87_predators-2    -0.030513
Wes-8d71_348_predators-2    0.013449
Taw-0bfd_102_Predators-1    0.577393
Lem-f2d0_486_predators-2   -0.426579
Meg-fd01_293_predators-2    0.292361
Pre-0725_85_predators-3    -0.487031
Slo-13c7_59_Predators-1     0.887728
Coa-e8c3_75_predators-2     0.054652
Cro-5646_352_predators-3   -1.880397
Nor-4d51_286_Predators-1   -0.492640
Wil-3cbf_108_Predators-1    0.818485
Slo-4b9b_175_predators-3   -0.986531
Nor-c9d9_158_predators-3   -0.322862
Gun-5a73_99_Predators-1     0.795404
Woo-fa9e_26_Predators-1     1.167656
Lep-7440_55_Predators-1     0.551982
Mex-2908_68_Predators-1     0.553689
Pre-0725_103_predators-2    0.014113
Whi-100a_59_Predators-1     0.916946
Bee-ace3_231_predators-2   -0.129107
Com-43a2_100_predators-2    0.697094
Tai-3286_130_predators-2   -0.591035
Sta-7425_30_Predators-1    -1.373112
Oli-4839_141_predators-6   -0.079031
Wil-3cbf_103_Predators-1    0.239388
Chi-6eec_125_Predators-1    0.859107
Cap-154f_110_predators-2    0.201567
Name: x, dtype: float64
x0 token_id
Elk-a58a_163_Predators-1    1.145863
Wes-8d71_347_predators-2   -0.655883
Lan-4994_40_language-4      0.354102
Woo-a311_26_Predators-1     0.859439
Hum-85c3_271_predators-2   -1.364015
Gre-e890_122_Predators-1    0.365537
Str-7d42_87_predators-2    -0.030513
Wes-8d71_348_predators-2    0.013449
Taw-0bfd_102_Predators-1    0.577393
Lem-f2d0_486_predators-2   -0.426579
Meg-fd01_293_predators-2    0.292361
Wil-de29_118_predators-2   -0.277323
Pre-0725_85_predators-3    -0.487031
Slo-13c7_59_Predators-1     0.887728
Coa-e8c3_75_predators-2     0.054652
Cro-5646_352_predators-3   -1.880397
Nor-4d51_286_Predators-1   -0.492640
Wil-3cbf_108_Predators-1    0.818485
Slo-4b9b_175_predators-3   -0.986531
Gun-5a73_99_Predators-1     0.795404
Woo-fa9e_26_Predators-1     1.167656
Lep-7440_55_Predators-1     0.551982
Mex-2908_68_Predators-1     0.553689
Pre-0725_103_predators-2    0.014113
Whi-100a_59_Predators-1     0.916946
Bee-ace3_231_predators-2   -0.129107
Com-43a2_100_predators-2    0.697094
Tai-3286_130_predators-2   -0.591035
Sta-7425_30_Predators-1    -1.373112
Oli-4839_141_predators-6   -0.079031
Wil-3cbf_103_Predators-1    0.239388
Chi-6eec_125_Predators-1    0.859107
Name: x, dtype: float64
x0 token_id
Elk-a58a_163_Predators-1    1.145863
Wes-8d71_347_predators-2   -0.655883
Lan-4994_40_language-4      0.354102
Woo-a311_26_Predators-1     0.859439
Gre-e890_122_Predators-1    0.365537
Str-7d42_87_predators-2    -0.030513
Wes-8d71_348_predators-2    0.013449
Taw-0bfd_102_Predators-1    0.577393
Meg-fd01_293_predators-2    0.292361
Wil-de29_118_predators-2   -0.277323
Pre-0725_85_predators-3    -0.487031
Slo-13c7_59_Predators-1     0.887728
Coa-e8c3_75_predators-2     0.054652
Nor-4d51_286_Predators-1   -0.492640
Wil-3cbf_108_Predators-1    0.818485
Nor-c9d9_158_predators-3   -0.322862
Gun-5a73_99_Predators-1     0.795404
Woo-fa9e_26_Predators-1     1.167656
Lep-7440_55_Predators-1     0.551982
Mex-2908_68_Predators-1     0.553689
Pre-0725_103_predators-2    0.014113
Whi-100a_59_Predators-1     0.916946
Bee-ace3_231_predators-2   -0.129107
Tai-3286_130_predators-2   -0.591035
Sta-7425_30_Predators-1    -1.373112
Oli-4839_141_predators-6   -0.079031
Wil-3cbf_103_Predators-1    0.239388
Chi-6eec_125_Predators-1    0.859107
Cap-154f_110_predators-2    0.201567
Name: x, dtype: float64
x0 token_id
Elk-a58a_163_Predators-1    1.145863
Wes-8d71_347_predators-2   -0.655883
Lan-4994_40_language-4      0.354102
Woo-a311_26_Predators-1     0.859439
Hum-85c3_271_predators-2   -1.364015
Gre-e890_122_Predators-1    0.365537
Str-7d42_87_predators-2    -0.030513
Wes-8d71_348_predators-2    0.013449
Taw-0bfd_102_Predators-1    0.577393
Lem-f2d0_486_predators-2   -0.426579
Meg-fd01_293_predators-2    0.292361
Wil-de29_118_predators-2   -0.277323
Pre-0725_85_predators-3    -0.487031
Slo-13c7_59_Predators-1     0.887728
Coa-e8c3_75_predators-2     0.054652
Cro-5646_352_predators-3   -1.880397
Nor-4d51_286_Predators-1   -0.492640
Wil-3cbf_108_Predators-1    0.818485
Nor-c9d9_158_predators-3   -0.322862
Gun-5a73_99_Predators-1     0.795404
Woo-fa9e_26_Predators-1     1.167656
Lep-7440_55_Predators-1     0.551982
Mex-2908_68_Predators-1     0.553689
Pre-0725_103_predators-2    0.014113
Whi-100a_59_Predators-1     0.916946
Bee-ace3_231_predators-2   -0.129107
Com-43a2_100_predators-2    0.697094
Tai-3286_130_predators-2   -0.591035
Sta-7425_30_Predators-1    -1.373112
Oli-4839_141_predators-6   -0.079031
Wil-3cbf_103_Predators-1    0.239388
Chi-6eec_125_Predators-1    0.859107
Cap-154f_110_predators-2    0.201567
Name: x, dtype: float64
x0 token_id
Elk-a58a_163_Predators-1    1.145863
Wes-8d71_347_predators-2   -0.655883
Lan-4994_40_language-4      0.354102
Woo-a311_26_Predators-1     0.859439
Hum-85c3_271_predators-2   -1.364015
Gre-e890_122_Predators-1    0.365537
Wes-8d71_348_predators-2    0.013449
Taw-0bfd_102_Predators-1    0.577393
Lem-f2d0_486_predators-2   -0.426579
Meg-fd01_293_predators-2    0.292361
Wil-de29_118_predators-2   -0.277323
Pre-0725_85_predators-3    -0.487031
Slo-13c7_59_Predators-1     0.887728
Coa-e8c3_75_predators-2     0.054652
Cro-5646_352_predators-3   -1.880397
Nor-4d51_286_Predators-1   -0.492640
Wil-3cbf_108_Predators-1    0.818485
Slo-4b9b_175_predators-3   -0.986531
Nor-c9d9_158_predators-3   -0.322862
Gun-5a73_99_Predators-1     0.795404
Woo-fa9e_26_Predators-1     1.167656
Lep-7440_55_Predators-1     0.551982
Mex-2908_68_Predators-1     0.553689
Pre-0725_103_predators-2    0.014113
Whi-100a_59_Predators-1     0.916946
Bee-ace3_231_predators-2   -0.129107
Com-43a2_100_predators-2    0.697094
Tai-3286_130_predators-2   -0.591035
Sta-7425_30_Predators-1    -1.373112
Oli-4839_141_predators-6   -0.079031
Wil-3cbf_103_Predators-1    0.239388
Chi-6eec_125_Predators-1    0.859107
Cap-154f_110_predators-2    0.201567
Name: x, dtype: float64
Spearman results
feat_tests
                    test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath lemma
amod>   Mammalian       0.38341   -0.678        1      34    -0.88
        Vertebrate      0.47655   -0.398        2      34    -0.72
        ambush          0.46385   -0.571        1      34    -0.74
        common          0.60708   -0.401        1      34    -0.52
        large           0.00660   -2.006        1      34    -2.91
        major           0.64987   -0.355        1      34    -0.46
        natural         0.80947   -0.135        2      34    -0.24
        other           0.00400   -1.007        5      34    -3.10
        potential       0.15876   -1.085        1      34    -1.44
        such            0.89804   -0.100        1      34    -0.13
book_cl_elong
                      effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath lemma
amod>   other      -0.797233  0.019863  5  0.635580      0.00400   -1.007
        such       -0.786409  0.006638  1  0.618439      0.89804   -0.100
        major      -0.778833  0.004550  1  0.606581      0.64987   -0.355
        large      -0.716845  0.002889  1  0.513866      0.00660   -2.006
        common     -0.710293  0.005893  1  0.504516      0.60708   -0.401
        natural    -0.618167  0.006667  2  0.382131      0.80947   -0.135
        Mammalian  -0.609988  0.006545  1  0.372086      0.38341   -0.678
        ambush     -0.588592  0.004712  1  0.346440      0.46385   -0.571
        potential  -0.505447  0.003103  1  0.255477      0.15876   -1.085
        Vertebrate -0.482714  0.016242  2  0.233012      0.47655   -0.398

                    test_Nx  test_N  test_st
arcpath lemma
amod>   other             5      34    -3.10
        such              1      34    -0.13
        major             1      34    -0.46
        large             1      34    -2.91
        common            1      34    -0.52
        natural           2      34    -0.24
        Mammalian         1      34    -0.88
        ambush            1      34    -0.74
        potential         1      34    -1.44
        Vertebrate        2      34    -0.72
cluster ====> 8
np.sqrt(eigvals)
[0.20220075 0.22375373 0.2810337  0.39270189 0.44422204 0.54835898
 0.82435383 1.07742553]
cl_elong_a, cl_elong_v.round(2)
1.3069940253351235 [ 0.01 -0.59  0.73 -0.25 -0.2  -0.16 -0.04 -0.05]
cluster data sample, mean shift
(287, 8)                                   0         1         2         3         4  \
token_id
Mam-3742_541_culture-11    0.079321  0.111897 -0.562168  1.356399  0.091261
Ani-57f1_383_language-5    0.000006  0.670450 -0.816355  1.061186  1.344211
Lan-4994_138_languages-32  0.761150 -0.699438 -0.258795 -0.569420 -0.231773

                                  5         6         7
token_id
Mam-3742_541_culture-11    0.799698  0.371408 -0.095143
Ani-57f1_383_language-5    0.283490  0.032066  0.038373
Lan-4994_138_languages-32 -0.337194  0.053257  0.009117
cluster data elongation along main axis
                       effect        Dx  N      eff2
arcpath lemma
amod>   many        -0.726461  0.000991  2  0.527746
        various     -0.721013  0.000628  1  0.519859
        modern      -0.704547  0.006176  4  0.496386
        other       -0.698086 -0.000089  8  0.487325
        terrestrial -0.696932  0.001397  2  0.485715
cc>     and         -0.663858 -0.001908  1  0.440708
amod>   small       -0.638553  0.000620  1  0.407750
        floral      -0.634657  0.001486  1  0.402789
        mammalian   -0.633532  0.001389  3  0.401363
        large       -0.633357  0.000728  3  0.401141
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                         token         x
arcpath lemma
amod>   floral          Oph-1439_256_mimicry-7 -0.484707
        large           Cer349a_4_predators-10 -1.232818
        large        Nil-600c_252_predators-23 -1.062245
        large        Coe-f000_125_predators-29 -0.501518
        mammalian     Gar-8d9c_17_predators-27 -0.294574
        mammalian     Kea-483e_44_predators-11 -0.499540
        mammalian    Mal-71cc_147_predators-67 -0.066887
        many            Cer349a_4_predators-10 -1.232818
        many           Eur21da_30_predators-10  0.158208
        modern         Das-ed91_66_predators-9 -0.965663
        modern       Dir-7dc2_215_predators-47 -0.944998
        modern        Hum-c1bb_441_cultures-16 -0.766790
        modern       Tyr-9f97_524_predators-54 -0.633431
        other               Cap-154f_76_use-23 -1.500595
        other          Cou-56f5_9_predators-28 -0.775436
        other        Mac-251e_266_predators-22 -0.233918
        other        Nil-600c_252_predators-23 -1.062245
        other        Nil-600c_256_predators-12 -0.876622
        other         Pèr-9953_71_predators-39 -0.954329
        other        Sno-0a8f_473_predators-23 -1.402018
        other        Sno-0a8f_498_predators-29 -0.800904
        small          Wes-0eef_61_predators-5 -0.872544
        terrestrial  Bat-2d5b_326_predators-25 -1.471703
        terrestrial  Sea-4a1d_276_predators-19  0.250925
        various       Ban-5f22_71_predators-21 -1.051653
cc>     and             Sup-d6e5_85_mimicry-10  0.123295
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (287,)
ftok (26, 2)
x0 token_id
Mam-3742_541_culture-11      -0.964496
Ani-57f1_383_language-5      -1.558498
Lan-4994_138_languages-32     0.463710
May-973b_241_culture-3        0.297620
Ani-57f1_377_languages-2     -0.120915
                                ...
Coe-519b_158_dimorphism-14    0.520954
Hib-c4bb_40_hibernation-12    0.093715
Cor-f314_178_culture-5        0.079738
Pri-2545_359_use-8           -0.649855
Ini-09cc_5_dimorphism-9       0.886214
Name: x, Length: 286, dtype: float64
x0 token_id
Mam-3742_541_culture-11      -0.964496
Ani-57f1_383_language-5      -1.558498
Lan-4994_138_languages-32     0.463710
May-973b_241_culture-3        0.297620
Ani-57f1_377_languages-2     -0.120915
                                ...
Coe-519b_158_dimorphism-14    0.520954
Hib-c4bb_40_hibernation-12    0.093715
Cor-f314_178_culture-5        0.079738
Pri-2545_359_use-8           -0.649855
Ini-09cc_5_dimorphism-9       0.886214
Name: x, Length: 284, dtype: float64
x0 token_id
Mam-3742_541_culture-11      -0.964496
Ani-57f1_383_language-5      -1.558498
Lan-4994_138_languages-32     0.463710
May-973b_241_culture-3        0.297620
Ani-57f1_377_languages-2     -0.120915
                                ...
Coe-519b_158_dimorphism-14    0.520954
Hib-c4bb_40_hibernation-12    0.093715
Cor-f314_178_culture-5        0.079738
Pri-2545_359_use-8           -0.649855
Ini-09cc_5_dimorphism-9       0.886214
Name: x, Length: 284, dtype: float64
x0 token_id
Mam-3742_541_culture-11      -0.964496
Ani-57f1_383_language-5      -1.558498
Lan-4994_138_languages-32     0.463710
May-973b_241_culture-3        0.297620
Ani-57f1_377_languages-2     -0.120915
                                ...
Coe-519b_158_dimorphism-14    0.520954
Hib-c4bb_40_hibernation-12    0.093715
Cor-f314_178_culture-5        0.079738
Pri-2545_359_use-8           -0.649855
Ini-09cc_5_dimorphism-9       0.886214
Name: x, Length: 285, dtype: float64
x0 token_id
Mam-3742_541_culture-11      -0.964496
Ani-57f1_383_language-5      -1.558498
Lan-4994_138_languages-32     0.463710
May-973b_241_culture-3        0.297620
Ani-57f1_377_languages-2     -0.120915
                                ...
Coe-519b_158_dimorphism-14    0.520954
Hib-c4bb_40_hibernation-12    0.093715
Cor-f314_178_culture-5        0.079738
Pri-2545_359_use-8           -0.649855
Ini-09cc_5_dimorphism-9       0.886214
Name: x, Length: 283, dtype: float64
x0 token_id
Mam-3742_541_culture-11      -0.964496
Ani-57f1_383_language-5      -1.558498
Lan-4994_138_languages-32     0.463710
May-973b_241_culture-3        0.297620
Ani-57f1_377_languages-2     -0.120915
                                ...
Coe-519b_158_dimorphism-14    0.520954
Hib-c4bb_40_hibernation-12    0.093715
Cor-f314_178_culture-5        0.079738
Pri-2545_359_use-8           -0.649855
Ini-09cc_5_dimorphism-9       0.886214
Name: x, Length: 279, dtype: float64
x0 token_id
Mam-3742_541_culture-11      -0.964496
Ani-57f1_383_language-5      -1.558498
Lan-4994_138_languages-32     0.463710
May-973b_241_culture-3        0.297620
Ani-57f1_377_languages-2     -0.120915
                                ...
Coe-519b_158_dimorphism-14    0.520954
Hib-c4bb_40_hibernation-12    0.093715
Cor-f314_178_culture-5        0.079738
Pri-2545_359_use-8           -0.649855
Ini-09cc_5_dimorphism-9       0.886214
Name: x, Length: 286, dtype: float64
x0 token_id
Mam-3742_541_culture-11      -0.964496
Ani-57f1_383_language-5      -1.558498
Lan-4994_138_languages-32     0.463710
May-973b_241_culture-3        0.297620
Ani-57f1_377_languages-2     -0.120915
                                ...
Coe-519b_158_dimorphism-14    0.520954
Hib-c4bb_40_hibernation-12    0.093715
Cor-f314_178_culture-5        0.079738
Pri-2545_359_use-8           -0.649855
Ini-09cc_5_dimorphism-9       0.886214
Name: x, Length: 285, dtype: float64
x0 token_id
Mam-3742_541_culture-11      -0.964496
Ani-57f1_383_language-5      -1.558498
Lan-4994_138_languages-32     0.463710
May-973b_241_culture-3        0.297620
Ani-57f1_377_languages-2     -0.120915
                                ...
Coe-519b_158_dimorphism-14    0.520954
Hib-c4bb_40_hibernation-12    0.093715
Cor-f314_178_culture-5        0.079738
Pri-2545_359_use-8           -0.649855
Ini-09cc_5_dimorphism-9       0.886214
Name: x, Length: 286, dtype: float64
x0 token_id
Mam-3742_541_culture-11      -0.964496
Ani-57f1_383_language-5      -1.558498
Lan-4994_138_languages-32     0.463710
May-973b_241_culture-3        0.297620
Ani-57f1_377_languages-2     -0.120915
                                ...
Coe-519b_158_dimorphism-14    0.520954
Hib-c4bb_40_hibernation-12    0.093715
Cor-f314_178_culture-5        0.079738
Pri-2545_359_use-8           -0.649855
Ini-09cc_5_dimorphism-9       0.886214
Name: x, Length: 286, dtype: float64
Spearman results
feat_tests
                     test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath lemma
amod>   floral           0.38859   -0.494        1     287    -0.86
        large            0.00398   -0.950        3     287    -2.90
        mammalian        0.36991   -0.298        3     287    -0.90
        many             0.17597   -0.549        2     287    -1.36
        modern           0.00305   -0.847        4     287    -2.99
        other            0.00000   -0.986        8     287    -5.02
        small            0.12263   -0.883        1     287    -1.55
        terrestrial      0.12465   -0.622        2     287    -1.54
        various          0.06292   -1.063        1     287    -1.87
cc>     and              0.83929    0.116        1     287     0.20
book_cl_elong
                       effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath lemma
amod>   many        -0.726461  0.000991  2  0.527746      0.17597   -0.549
        various     -0.721013  0.000628  1  0.519859      0.06292   -1.063
        modern      -0.704547  0.006176  4  0.496386      0.00305   -0.847
        other       -0.698086 -0.000089  8  0.487325      0.00000   -0.986
        terrestrial -0.696932  0.001397  2  0.485715      0.12465   -0.622
        small       -0.638553  0.000620  1  0.407750      0.12263   -0.883
        floral      -0.634657  0.001486  1  0.402789      0.38859   -0.494
        mammalian   -0.633532  0.001389  3  0.401363      0.36991   -0.298
        large       -0.633357  0.000728  3  0.401141      0.00398   -0.950

                     test_Nx  test_N  test_st
arcpath lemma
amod>   many               2     287    -1.36
        various            1     287    -1.87
        modern             4     287    -2.99
        other              8     287    -5.02
        terrestrial        2     287    -1.54
        small              1     287    -1.55
        floral             1     287    -0.86
        mammalian          3     287    -0.90
        large              3     287    -2.90
cluster ====> 9
np.sqrt(eigvals)
[0.48894902 0.57832983 0.65531413 0.89056588 0.9466902  1.1941636
 1.35948539 1.58929508]
cl_elong_a, cl_elong_v.round(2)
1.169041677976304 [ 0.09 -0.11 -0.01  0.24  0.22 -0.17  0.04  0.92]
cluster data sample, mean shift
(284, 8)                                    0         1         2         3         4  \
token_id
Gal-c120_347_predators-13   0.959149 -0.876635 -0.312678  0.111260 -1.087831
Tyr-9f97_556_scavengers-21  0.767889  0.069749 -0.782301  0.575592  0.054453
Gia-57fd_133_flowering-5    1.181898 -0.009824  1.828820 -1.525066  1.255434

                                   5         6         7
token_id
Gal-c120_347_predators-13  -1.101934  0.627918  1.565745
Tyr-9f97_556_scavengers-21  0.756600 -0.503911 -0.131503
Gia-57fd_133_flowering-5    0.751571 -0.168155 -2.552667
cluster data elongation along main axis
                       effect        Dx  N      eff2
arcpath lemma
conj>   animal      -0.913441  0.001786  2  0.834375
        omnivorous  -0.893821  0.000355  1  0.798915
        scavenger   -0.875574  0.002473  4  0.766629
        feed        -0.875098  0.004466  5  0.765796
        eat         -0.871176  0.001075  2  0.758947
        crepuscular -0.853541  0.002546  4  0.728532
        live        -0.848815  0.001352  2  0.720488
        predator    -0.843685  0.001309  2  0.711804
        active      -0.835733  0.001786  2  0.698449
        have        -0.832563  0.001352  2  0.693161
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                          token         x
arcpath lemma
conj>   active         Pla-4bec_105_nocturnal-5 -2.171433
        active         Eri-edb8_16_nocturnal-12 -1.399702
        animal         Ame-fe9c_111_predators-5 -1.117361
        animal          Bla-e03a_12_scavenger-6 -6.088509
        crepuscular   Bir-ebe4_308_nocturnal-20 -1.199139
        crepuscular     Eas-6961_38_nocturnal-8 -2.428002
        crepuscular    Pla-4bec_105_nocturnal-5 -2.171433
        crepuscular    Sco-5d0f_129_nocturnal-5 -2.910100
        eat             Bla-e03a_12_scavenger-6 -6.088509
        eat           Eur-3a81_60_herbivorous-4 -1.834173
        feed            Bla-e03a_12_scavenger-6 -6.088509
        feed         Bro-f1dc_212_herbivorous-8 -1.273679
        feed              Com-f222_7_predator-7 -0.485251
        feed           Eur-c08e_4_herbivorous-3 -1.546501
        feed            Fir-e344_20_predators-8 -3.614185
        have             Pet-f628_4_nocturnal-5  0.346570
        have             Tig-9404_70_predator-7 -1.481084
        live            Ama-5ad6_44_nocturnal-4 -2.345074
        live             Woo-a311_9_nocturnal-3 -3.201843
        omnivorous   Din-756f_391_herbivorous-5 -0.716576
        predator      Cro-4b5e_145_scavenger-24  0.058777
        predator       Whi-b4c3_258_predators-7 -3.667706
        scavenger      Asi-7d4f_16_predators-10 -1.072155
        scavenger        Tyr-9f97_14_predator-9 -0.827697
        scavenger       Tyr-9f97_15_predator-11 -0.376682
        scavenger      Tyr-9f97_531_predator-10 -1.573923
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (284,)
ftok (26, 2)
x0 token_id
Gal-c120_347_predators-13      1.610874
Tyr-9f97_556_scavengers-21    -0.047649
Gia-57fd_133_flowering-5      -2.469416
Azh-4750_15_predator-36       -1.239196
Bro-5fe4_39_nocturnal-5       -2.288970
                                 ...
Wat-4f58_195_predators-7      -0.862142
Har-8a11_61_predators-24       3.102318
Lizaf6e_17_parts-18           -0.456444
Mac-251e_160_social-8         -0.740749
Sem-88a0_146_semelparous-40   -0.159026
Name: x, Length: 282, dtype: float64
x0 token_id
Gal-c120_347_predators-13      1.610874
Tyr-9f97_556_scavengers-21    -0.047649
Gia-57fd_133_flowering-5      -2.469416
Azh-4750_15_predator-36       -1.239196
Bro-5fe4_39_nocturnal-5       -2.288970
                                 ...
Wat-4f58_195_predators-7      -0.862142
Har-8a11_61_predators-24       3.102318
Lizaf6e_17_parts-18           -0.456444
Mac-251e_160_social-8         -0.740749
Sem-88a0_146_semelparous-40   -0.159026
Name: x, Length: 282, dtype: float64
x0 token_id
Gal-c120_347_predators-13      1.610874
Tyr-9f97_556_scavengers-21    -0.047649
Gia-57fd_133_flowering-5      -2.469416
Azh-4750_15_predator-36       -1.239196
Bro-5fe4_39_nocturnal-5       -2.288970
                                 ...
Wat-4f58_195_predators-7      -0.862142
Har-8a11_61_predators-24       3.102318
Lizaf6e_17_parts-18           -0.456444
Mac-251e_160_social-8         -0.740749
Sem-88a0_146_semelparous-40   -0.159026
Name: x, Length: 280, dtype: float64
x0 token_id
Gal-c120_347_predators-13      1.610874
Tyr-9f97_556_scavengers-21    -0.047649
Gia-57fd_133_flowering-5      -2.469416
Azh-4750_15_predator-36       -1.239196
Bro-5fe4_39_nocturnal-5       -2.288970
                                 ...
Wat-4f58_195_predators-7      -0.862142
Har-8a11_61_predators-24       3.102318
Lizaf6e_17_parts-18           -0.456444
Mac-251e_160_social-8         -0.740749
Sem-88a0_146_semelparous-40   -0.159026
Name: x, Length: 282, dtype: float64
x0 token_id
Gal-c120_347_predators-13      1.610874
Tyr-9f97_556_scavengers-21    -0.047649
Gia-57fd_133_flowering-5      -2.469416
Azh-4750_15_predator-36       -1.239196
Bro-5fe4_39_nocturnal-5       -2.288970
                                 ...
Wat-4f58_195_predators-7      -0.862142
Har-8a11_61_predators-24       3.102318
Lizaf6e_17_parts-18           -0.456444
Mac-251e_160_social-8         -0.740749
Sem-88a0_146_semelparous-40   -0.159026
Name: x, Length: 279, dtype: float64
x0 token_id
Gal-c120_347_predators-13      1.610874
Tyr-9f97_556_scavengers-21    -0.047649
Gia-57fd_133_flowering-5      -2.469416
Azh-4750_15_predator-36       -1.239196
Bro-5fe4_39_nocturnal-5       -2.288970
                                 ...
Wat-4f58_195_predators-7      -0.862142
Har-8a11_61_predators-24       3.102318
Lizaf6e_17_parts-18           -0.456444
Mac-251e_160_social-8         -0.740749
Sem-88a0_146_semelparous-40   -0.159026
Name: x, Length: 282, dtype: float64
x0 token_id
Gal-c120_347_predators-13      1.610874
Tyr-9f97_556_scavengers-21    -0.047649
Gia-57fd_133_flowering-5      -2.469416
Azh-4750_15_predator-36       -1.239196
Bro-5fe4_39_nocturnal-5       -2.288970
                                 ...
Wat-4f58_195_predators-7      -0.862142
Har-8a11_61_predators-24       3.102318
Lizaf6e_17_parts-18           -0.456444
Mac-251e_160_social-8         -0.740749
Sem-88a0_146_semelparous-40   -0.159026
Name: x, Length: 282, dtype: float64
x0 token_id
Gal-c120_347_predators-13      1.610874
Tyr-9f97_556_scavengers-21    -0.047649
Gia-57fd_133_flowering-5      -2.469416
Azh-4750_15_predator-36       -1.239196
Bro-5fe4_39_nocturnal-5       -2.288970
                                 ...
Wat-4f58_195_predators-7      -0.862142
Har-8a11_61_predators-24       3.102318
Lizaf6e_17_parts-18           -0.456444
Mac-251e_160_social-8         -0.740749
Sem-88a0_146_semelparous-40   -0.159026
Name: x, Length: 283, dtype: float64
x0 token_id
Gal-c120_347_predators-13      1.610874
Tyr-9f97_556_scavengers-21    -0.047649
Gia-57fd_133_flowering-5      -2.469416
Azh-4750_15_predator-36       -1.239196
Bro-5fe4_39_nocturnal-5       -2.288970
                                 ...
Wat-4f58_195_predators-7      -0.862142
Har-8a11_61_predators-24       3.102318
Lizaf6e_17_parts-18           -0.456444
Mac-251e_160_social-8         -0.740749
Sem-88a0_146_semelparous-40   -0.159026
Name: x, Length: 282, dtype: float64
x0 token_id
Gal-c120_347_predators-13      1.610874
Tyr-9f97_556_scavengers-21    -0.047649
Gia-57fd_133_flowering-5      -2.469416
Azh-4750_15_predator-36       -1.239196
Bro-5fe4_39_nocturnal-5       -2.288970
                                 ...
Wat-4f58_195_predators-7      -0.862142
Har-8a11_61_predators-24       3.102318
Lizaf6e_17_parts-18           -0.456444
Mac-251e_160_social-8         -0.740749
Sem-88a0_146_semelparous-40   -0.159026
Name: x, Length: 280, dtype: float64
Spearman results
feat_tests
                     test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath lemma
conj>   active           0.15240   -1.512        2     284    -1.43
        animal           0.00144   -3.342        2     284    -3.22
        crepuscular      0.01013   -1.920        4     284    -2.59
        eat              0.00040   -3.703        2     284    -3.58
        feed             0.00039   -2.359        5     284    -3.59
        have             0.78788   -0.285        2     284    -0.27
        live             0.01728   -2.507        2     284    -2.39
        omnivorous       0.77163   -0.434        1     284    -0.29
        predator         0.14729   -1.531        2     284    -1.45
        scavenger        0.35938   -0.688        4     284    -0.92
book_cl_elong
                       effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath lemma
conj>   animal      -0.913441  0.001786  2  0.834375      0.00144   -3.342
        omnivorous  -0.893821  0.000355  1  0.798915      0.77163   -0.434
        scavenger   -0.875574  0.002473  4  0.766629      0.35938   -0.688
        feed        -0.875098  0.004466  5  0.765796      0.00039   -2.359
        eat         -0.871176  0.001075  2  0.758947      0.00040   -3.703
        crepuscular -0.853541  0.002546  4  0.728532      0.01013   -1.920
        live        -0.848815  0.001352  2  0.720488      0.01728   -2.507
        predator    -0.843685  0.001309  2  0.711804      0.14729   -1.531
        active      -0.835733  0.001786  2  0.698449      0.15240   -1.512
        have        -0.832563  0.001352  2  0.693161      0.78788   -0.285

                     test_Nx  test_N  test_st
arcpath lemma
conj>   animal             2     284    -3.22
        omnivorous         1     284    -0.29
        scavenger          4     284    -0.92
        feed               5     284    -3.59
        eat                2     284    -3.58
        crepuscular        4     284    -2.59
        live               2     284    -2.39
        predator           2     284    -1.45
        active             2     284    -1.43
        have               2     284    -0.27
===========  end ==============
checking for data/q_cluster/BGM_full_covar_location.pkl
BGM loaded
bgm.predict(my_ica_data)).value_counts()
3    481
0    466
2    376
7    313
6    256
8    221
5    201
1    167
9     43
4     15
Name: count, dtype: int64

clust_feats (4103, 2)
                     cluster  freq
arcpath       lemma
case>         in           3   177
det>          the          3   165
amod<         bear         7   146
compound<det> the          0   137
amod<         bear         2   133
=========================
clust_f_df pivot table (2215, 10)
clust_p_df is the probability distribution cluster-wise
                                     0    1         2         3         4  \
arcpath           lemma
acl:relcl>        flood       0.000000  0.0  0.000000  0.000391  0.000000
                  live        0.000000  0.0  0.000000  0.000391  0.000000
                  provide     0.000672  0.0  0.000723  0.000000  0.000000
acl:relcl>advmod> seasonally  0.000000  0.0  0.000000  0.000391  0.000000
                  where       0.000000  0.0  0.000723  0.002347  0.007092

                                     5    6    7         8    9
arcpath           lemma
acl:relcl>        flood       0.000000  0.0  0.0  0.000655  0.0
                  live        0.000000  0.0  0.0  0.000655  0.0
                  provide     0.000000  0.0  0.0  0.000655  0.0
acl:relcl>advmod> seasonally  0.000000  0.0  0.0  0.000655  0.0
                  where       0.001171  0.0  0.0  0.003932  0.0
=========================
Elementwise relative entropy by clusters, feature-wise
                            0         1         2         3         4  \
arcpath       lemma
amod<         bear  -0.011292  0.000000  0.094361 -0.006412 -0.011531
det>          the   -0.002635  0.026917 -0.012384  0.041696  0.019030
case>         in     0.000000  0.011944  0.000000  0.081257 -0.000142
              of     0.000000  0.047583  0.000000 -0.004777  0.000000
compound<det> the    0.179813 -0.003893 -0.002036 -0.004724 -0.004344

                            5         6         7         8         9
arcpath       lemma
amod<         bear  -0.002412 -0.010754  0.457659 -0.002626  0.000000
det>          the   -0.011622  0.091835  0.000000 -0.001683 -0.009228
case>         in    -0.005826  0.069919  0.000000 -0.000445 -0.007012
              of    -0.001843  0.135799  0.000000 -0.004999 -0.004988
compound<det> the    0.000000 -0.004417 -0.004546 -0.004728 -0.004802
========== clust_featdx_df ===============
                                          Dx    N
cluster arcpath              lemma
9       compound<conj<conj>  hare   0.050321    5
        nsubj:pass<aux:pass> be     0.072651    8
2       cc>                  and    0.092593   78
5       conj<conj>cc>        and    0.144877  109
2       amod<case>           of     0.047637   29
=========================
pred_feats
feat_v
                                0         1         2         3         4  \
arcpath           lemma
acl:relcl>advmod> where -0.002001  0.008003 -0.018005  0.250977 -0.124023
amod<             bear  -0.298096  0.171021 -0.284912  0.072998 -0.075012
amod<case>        of    -0.301025 -0.120972 -0.368896 -0.227051  0.451904
amod<cc>          and    0.239014 -0.270020  0.046997  0.035004  0.091980
amod<det>         a     -0.042999  0.104004 -0.489014 -0.020004 -0.125000

                                5         6         7
arcpath           lemma
acl:relcl>advmod> where  0.094971  0.117981 -0.172974
amod<             bear   0.224976 -0.323975 -0.228027
amod<case>        of     0.040985 -0.024002  0.037994
amod<cc>          and    0.014000 -0.010002 -0.170044
amod<det>         a     -0.052002 -0.056000  0.322998
mean_norm
[[-0.27 -0.38  0.63  0.29 -0.21 -0.49 -0.05  0.13]
 [ 0.25 -0.19 -0.06 -0.26  0.89  0.11 -0.13  0.04]
 [-0.71 -0.03 -0.34  0.04 -0.44  0.14 -0.26  0.32]
 [ 0.37  0.52  0.34 -0.55  0.1   0.03 -0.16 -0.38]
 [ 0.84 -0.05 -0.4  -0.1  -0.32 -0.03 -0.07 -0.09]
 [-0.11  0.07 -0.32 -0.04 -0.1   0.04  0.92  0.16]
 [-0.2  -0.04  0.18 -0.4   0.83  0.04 -0.16  0.23]
 [-0.52  0.01  0.59  0.3  -0.38 -0.08 -0.27  0.27]
 [ 0.04 -0.06 -0.36 -0.01 -0.03  0.08  0.03 -0.93]
 [ 0.23 -0.26  0.6  -0.02 -0.05  0.68  0.04  0.22]]
cos_predict.head(5)
                                 0         1         2         3         4  \
arcpath            lemma
compound<det>      the    0.010062 -0.188385 -0.000819 -0.103438  0.024171
compound<case>     of    -0.250757 -0.117921  0.382074 -0.020649 -0.091831
compound<nmod<det> the   -0.279847  0.440238  0.158999 -0.139009 -0.224127
compound<case>     in     0.030052  0.177037 -0.266503  0.020587  0.178124
compound<          hare  -0.245271 -0.092739  0.358513 -0.244929  0.172697

                                 5         6         7         8         9
arcpath            lemma
compound<det>      the    0.093571 -0.261353  0.026764  0.179135  0.019083
compound<case>     of    -0.185027 -0.081577  0.046934  0.302248 -0.191826
compound<nmod<det> the    0.092220  0.478762 -0.288704  0.083957 -0.241907
compound<case>     in    -0.106679 -0.003150 -0.168042  0.164694  0.119788
compound<          hare   0.179875 -0.098162 -0.117130 -0.134194 -0.290231
score_predict.head(5)
                              0      1      2      3    4      5      6    7  \
arcpath            lemma
compound<det>      the    0.084  0.056  0.155  0.457  0.0  0.054  0.163  0.0
compound<case>     of     0.005  0.020  0.345  0.330  0.0  0.016  0.269  0.0
compound<nmod<det> the    0.006  0.058  0.029  0.125  0.0  0.007  0.763  0.0
compound<case>     in     0.030  0.106  0.017  0.667  0.0  0.013  0.141  0.0
compound<          hare   0.007  0.020  0.624  0.189  0.0  0.036  0.108  0.0

                              8      9
arcpath            lemma
compound<det>      the    0.030  0.001
compound<case>     of     0.012  0.003
compound<nmod<det> the    0.011  0.001
compound<case>     in     0.022  0.005
compound<          hare   0.016  0.000
                                 0         1         2         3         4  \
arcpath            lemma
compound<det>      the    0.092132  0.002162  0.010846  0.003912  0.007092
compound<case>     of     0.043712  0.000000  0.000000  0.000782  0.000000
compound<nmod<det> the    0.024882  0.000000  0.000723  0.001174  0.000000
compound<case>     in     0.021520  0.001081  0.011569  0.002347  0.000000
compound<          hare   0.024882  0.000000  0.002169  0.000782  0.000000

                            5         6         7         8         9
arcpath            lemma
compound<det>      the    0.0  0.002997  0.003300  0.003932  0.004484
compound<case>     of     0.0  0.000000  0.011551  0.001311  0.000000
compound<nmod<det> the    0.0  0.000000  0.001650  0.001311  0.000000
compound<case>     in     0.0  0.001998  0.008251  0.000655  0.004484
compound<          hare   0.0  0.001998  0.021452  0.000000  0.022422
=========== Internal structure in cluster==============
cluster ====> 0
np.sqrt(eigvals)
[0.23476534 0.25775781 0.29944099 0.30140161 0.37129535 0.42885711
 0.54034757 0.72520374]
cl_elong_a, cl_elong_v.round(2)
1.342106032825818 [0.05 0.31 0.48 0.59 0.45 0.05 0.03 0.35]
cluster data sample, mean shift
(414, 8)                                 0         1         2         3         4  \
token_id
Tun-4bf6_114_Tundra-1    0.371640 -0.122973  1.064851 -0.379093 -0.928231
Osp-8ead_143_coastal-18  0.173047  0.266327  0.192948  0.082636  0.334979
Hed-8dc6_114_hedgerow-3 -0.149343  0.400153 -0.377079  0.494853  0.521596

                                5         6         7
token_id
Tun-4bf6_114_Tundra-1    0.707977 -0.698083  0.708075
Osp-8ead_143_coastal-18  0.113375 -0.155471 -0.140855
Hed-8dc6_114_hedgerow-3  0.357178  0.219327  0.541528
cluster data elongation along main axis
                                     effect        Dx   N      eff2
arcpath                  lemma
det>                     the      -0.886653 -0.002635   1  0.786153
conj>cc>                 and      -0.600341 -0.001985   1  0.360409
compound<nsubj>          habitats -0.538542  0.001240   1  0.290028
compound<nmod<case>      in       -0.521943  0.009902   8  0.272424
compound<obl<            develop  -0.497387  0.001058   1  0.247394
                         replace  -0.496485  0.003097   2  0.246498
                         know     -0.468447  0.001827   2  0.219443
compound<nsubj<          species  -0.454696  0.007742   5  0.206748
compound<nmod<case>      of       -0.437699  0.017033  11  0.191581
compound<obl<nsubj:pass> it       -0.435655  0.003555   3  0.189796
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                        token         x
arcpath                  lemma
compound<nmod<case>      in        Ant-938d_251_rainforest-43 -1.125473
                         in          Bon-fbc3_136_mountain-15 -0.170072
                         in           Coa-44f0_155_coastal-13 -0.179538
                         in              Lem-06b1_2_tundra-16 -1.493579
                         in             Mal21f9_7_mountain-14  0.058647
                         in            Mou338e_12_mountain-23 -0.836342
                         in         Poi-d65f_122_rainforest-8 -0.749627
                         in            Swa-27b4_247_desert-15 -0.722635
                         of         Ame-35ae_345_Mountains-19 -0.150797
                         of            Bar-89af_2_mountain-23 -0.261303
                         of             Big-0af3_9_mountain-9  0.012612
                         of                Bog-cdf9_50_bog-10 -0.801441
                         of             Dro-9dd9_299_desert-9 -0.230992
                         of                 Eri-8713_3_bog-19 -0.523132
                         of        Fos-88c7_151_rainforest-12 -0.447206
                         of          Nor-c9d9_197_mountain-15 -0.631760
                         of         Pan-3679_195_Mountains-25 -0.493748
                         of         Sil-6383_51_rainforest-35 -0.454829
                         of           Wal-cefe_10_mountain-13 -0.242133
compound<nsubj<          species          Des-78ef_2_desert-2 -0.550338
                         species      Eur-c08e_62_mountain-10 -0.730678
                         species           Mar-495f_2_marsh-2 -0.464181
                         species          Mar-80c6_33_marsh-3 -0.015142
                         species       Mou-9e66_14_mountain-2 -0.457378
compound<nsubj>          habitats      Wal-cefe_31_mountain-4 -0.401503
compound<obl<            develop    Sil-6383_116_rainforest-5 -0.204512
                         know          Arg-817f_2_mountain-12 -0.366211
                         know              Wes-9ef7_3_marsh-8 -0.772629
                         replace       Eur-bc75_260_tundra-92 -0.413321
                         replace        Mus-840b_38_tundra-39 -0.792637
compound<obl<nsubj:pass> it                Wes-9ef7_3_marsh-8 -0.772629
                         it               Wes-9ef7_47_marsh-4 -0.678040
                         it            Wes-9ef7_47_wetland-12 -0.702112
conj>cc>                 and            Rei-38eb_101_tundra-8 -0.038369
det>                     the             Wha-290e_33_ocean-62 -0.581209
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (414,)
ftok (35, 2)
x0 token_id
Tun-4bf6_114_Tundra-1       0.108047
Osp-8ead_143_coastal-18     0.334000
Hed-8dc6_114_hedgerow-3     0.672298
Wat-9861_8_swamp-18        -0.156834
Wal-cefe_10_mountain-13    -0.242133
                              ...
Mar-80c6_7_marsh-2         -0.342158
Des-78ef_17_desert-3        0.841166
Fro-2392_266_mountain-11    0.342784
Gol-9020_114_mountain-13    0.555484
Wat-4f58_108_marsh-23       0.003166
Name: x, Length: 406, dtype: float64
x0 token_id
Tun-4bf6_114_Tundra-1       0.108047
Osp-8ead_143_coastal-18     0.334000
Hed-8dc6_114_hedgerow-3     0.672298
Wat-9861_8_swamp-18        -0.156834
Rei-38eb_166_tundra-19     -0.065941
                              ...
Mar-80c6_7_marsh-2         -0.342158
Des-78ef_17_desert-3        0.841166
Fro-2392_266_mountain-11    0.342784
Gol-9020_114_mountain-13    0.555484
Wat-4f58_108_marsh-23       0.003166
Name: x, Length: 403, dtype: float64
x0 token_id
Tun-4bf6_114_Tundra-1       0.108047
Osp-8ead_143_coastal-18     0.334000
Hed-8dc6_114_hedgerow-3     0.672298
Wat-9861_8_swamp-18        -0.156834
Wal-cefe_10_mountain-13    -0.242133
                              ...
Mar-80c6_7_marsh-2         -0.342158
Des-78ef_17_desert-3        0.841166
Fro-2392_266_mountain-11    0.342784
Gol-9020_114_mountain-13    0.555484
Wat-4f58_108_marsh-23       0.003166
Name: x, Length: 409, dtype: float64
x0 token_id
Tun-4bf6_114_Tundra-1       0.108047
Osp-8ead_143_coastal-18     0.334000
Hed-8dc6_114_hedgerow-3     0.672298
Wat-9861_8_swamp-18        -0.156834
Wal-cefe_10_mountain-13    -0.242133
                              ...
Mar-80c6_7_marsh-2         -0.342158
Des-78ef_17_desert-3        0.841166
Fro-2392_266_mountain-11    0.342784
Gol-9020_114_mountain-13    0.555484
Wat-4f58_108_marsh-23       0.003166
Name: x, Length: 413, dtype: float64
x0 token_id
Tun-4bf6_114_Tundra-1       0.108047
Osp-8ead_143_coastal-18     0.334000
Hed-8dc6_114_hedgerow-3     0.672298
Wat-9861_8_swamp-18        -0.156834
Wal-cefe_10_mountain-13    -0.242133
                              ...
Mar-80c6_7_marsh-2         -0.342158
Des-78ef_17_desert-3        0.841166
Fro-2392_266_mountain-11    0.342784
Gol-9020_114_mountain-13    0.555484
Wat-4f58_108_marsh-23       0.003166
Name: x, Length: 413, dtype: float64

x0 token_id
Tun-4bf6_114_Tundra-1       0.108047
Osp-8ead_143_coastal-18     0.334000
Hed-8dc6_114_hedgerow-3     0.672298
Wat-9861_8_swamp-18        -0.156834
Wal-cefe_10_mountain-13    -0.242133
                              ...
Mar-80c6_7_marsh-2         -0.342158
Des-78ef_17_desert-3        0.841166
Fro-2392_266_mountain-11    0.342784
Gol-9020_114_mountain-13    0.555484
Wat-4f58_108_marsh-23       0.003166
Name: x, Length: 412, dtype: float64
x0 token_id
Tun-4bf6_114_Tundra-1       0.108047
Osp-8ead_143_coastal-18     0.334000
Hed-8dc6_114_hedgerow-3     0.672298
Wat-9861_8_swamp-18        -0.156834
Wal-cefe_10_mountain-13    -0.242133
                              ...
Mar-80c6_7_marsh-2         -0.342158
Des-78ef_17_desert-3        0.841166
Fro-2392_266_mountain-11    0.342784
Gol-9020_114_mountain-13    0.555484
Wat-4f58_108_marsh-23       0.003166
Name: x, Length: 412, dtype: float64
x0 token_id
Tun-4bf6_114_Tundra-1       0.108047
Osp-8ead_143_coastal-18     0.334000
Hed-8dc6_114_hedgerow-3     0.672298
Wat-9861_8_swamp-18        -0.156834
Wal-cefe_10_mountain-13    -0.242133
                              ...
Mar-80c6_7_marsh-2         -0.342158
Des-78ef_17_desert-3        0.841166
Fro-2392_266_mountain-11    0.342784
Gol-9020_114_mountain-13    0.555484
Wat-4f58_108_marsh-23       0.003166
Name: x, Length: 411, dtype: float64
x0 token_id
Tun-4bf6_114_Tundra-1       0.108047
Osp-8ead_143_coastal-18     0.334000
Hed-8dc6_114_hedgerow-3     0.672298
Wat-9861_8_swamp-18        -0.156834
Wal-cefe_10_mountain-13    -0.242133
                              ...
Mar-80c6_7_marsh-2         -0.342158
Des-78ef_17_desert-3        0.841166
Fro-2392_266_mountain-11    0.342784
Gol-9020_114_mountain-13    0.555484
Wat-4f58_108_marsh-23       0.003166
Name: x, Length: 413, dtype: float64
x0 token_id
Tun-4bf6_114_Tundra-1       0.108047
Osp-8ead_143_coastal-18     0.334000
Hed-8dc6_114_hedgerow-3     0.672298
Wat-9861_8_swamp-18        -0.156834
Wal-cefe_10_mountain-13    -0.242133
                              ...
Mar-80c6_7_marsh-2         -0.342158
Des-78ef_17_desert-3        0.841166
Fro-2392_266_mountain-11    0.342784
Gol-9020_114_mountain-13    0.555484
Wat-4f58_108_marsh-23       0.003166
Name: x, Length: 413, dtype: float64
Spearman results
feat_tests
                                   test_pvalue  test_dX  test_Nx  test_N  \
arcpath                  lemma
compound<nmod<case>      in            0.00001   -0.679        8     414
                         of            0.00219   -0.408       11     414
compound<nsubj<          species       0.01868   -0.462        5     414
compound<nsubj>          habitats      0.34333   -0.416        1     414
compound<obl<            develop       0.61909   -0.218        1     414
                         know          0.05899   -0.585        2     414
                         replace       0.04576   -0.619        2     414
compound<obl<nsubj:pass> it            0.00358   -0.736        3     414
conj>cc>                 and           0.90646   -0.052        1     414
det>                     the           0.17409   -0.596        1     414

                                   test_st
arcpath                  lemma
compound<nmod<case>      in          -4.44
                         of          -3.08
compound<nsubj<          species     -2.36
compound<nsubj>          habitats    -0.95
compound<obl<            develop     -0.50
                         know        -1.89
                         replace     -2.00
compound<obl<nsubj:pass> it          -2.93
conj>cc>                 and         -0.12
det>                     the         -1.36
book_cl_elong
                                     effect        Dx   N      eff2  \
arcpath                  lemma
det>                     the      -0.886653 -0.002635   1  0.786153
conj>cc>                 and      -0.600341 -0.001985   1  0.360409
compound<nsubj>          habitats -0.538542  0.001240   1  0.290028
compound<nmod<case>      in       -0.521943  0.009902   8  0.272424
compound<obl<            develop  -0.497387  0.001058   1  0.247394
                         replace  -0.496485  0.003097   2  0.246498
                         know     -0.468447  0.001827   2  0.219443
compound<nsubj<          species  -0.454696  0.007742   5  0.206748
compound<nmod<case>      of       -0.437699  0.017033  11  0.191581
compound<obl<nsubj:pass> it       -0.435655  0.003555   3  0.189796

                                   test_pvalue  test_dX  test_Nx  test_N  \
arcpath                  lemma
det>                     the           0.17409   -0.596        1     414
conj>cc>                 and           0.90646   -0.052        1     414
compound<nsubj>          habitats      0.34333   -0.416        1     414
compound<nmod<case>      in            0.00001   -0.679        8     414
compound<obl<            develop       0.61909   -0.218        1     414
                         replace       0.04576   -0.619        2     414
                         know          0.05899   -0.585        2     414
compound<nsubj<          species       0.01868   -0.462        5     414
compound<nmod<case>      of            0.00219   -0.408       11     414
compound<obl<nsubj:pass> it            0.00358   -0.736        3     414

                                   test_st
arcpath                  lemma
det>                     the         -1.36
conj>cc>                 and         -0.12
compound<nsubj>          habitats    -0.95
compound<nmod<case>      in          -4.44
compound<obl<            develop     -0.50
                         replace     -2.00
                         know        -1.89
compound<nsubj<          species     -2.36
compound<nmod<case>      of          -3.08
compound<obl<nsubj:pass> it          -2.93
cluster ====> 1
np.sqrt(eigvals)
[0.32509798 0.36480572 0.50568663 0.63116562 0.77833534 0.92845258
 1.03279327 1.61076774]
cl_elong_a, cl_elong_v.round(2)
1.5596226199710639 [ 0.3  -0.59 -0.56 -0.03  0.2   0.18  0.42 -0.01]
cluster data sample, mean shift
(137, 8)                                  0         1         2         3         4  \
token_id
Rei-38eb_426_mountain-16 -0.248585  0.153626  1.059471  0.000220 -1.639945
Dra-48f6_125_swamps-19    0.966999 -0.073927  1.380434  0.064791 -0.233702
Cet-5f63_539_estuary-8    0.935694 -0.136249  1.581493  0.104976 -1.096822

                                 5         6         7
token_id
Rei-38eb_426_mountain-16  1.620301  0.230918  0.012719
Dra-48f6_125_swamps-19    0.673732 -0.160274  1.058270
Cet-5f63_539_estuary-8    0.637727  0.653119  0.657276
cluster data elongation along main axis
                            effect        Dx  N      eff2
arcpath         lemma
nmod>nmod>case> of        0.524891  0.003039  2  0.275511
amod>           large     0.509737  0.001349  1  0.259832
                open      0.492156 -0.000674  3  0.242218
nmod>nmod>case> to        0.490541  0.004979  2  0.240631
amod>           arctic    0.483268  0.004265  3  0.233548
                arid      0.480305  0.006930  3  0.230693
                brackish  0.465276  0.000213  1  0.216482
                cold      0.456988  0.001468  1  0.208838
                move      0.455269  0.001977  1  0.207270
                coral     0.452616  0.001349  1  0.204861
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                               token         x
arcpath         lemma
amod>           arctic         Arc-00d6_22_tundra-35  0.076957
                arctic         Sib-2667_78_tundra-11  0.066599
                arctic        Wol-279e_128_tundra-15  0.145377
                arid           Lit-23ba_24_deserts-6  0.463076
                arid          Nak-3bf1_90_deserts-17 -0.441338
                arid          Swa-32cf_26_deserts-13  0.737373
                brackish      Bel-4321_301_waters-25 -0.742815
                cold           Mus-840b_32_tundra-11  0.245711
                coral             Cro60a5_1_reefs-17  0.774812
                large           Bro-dfd8_7_rivers-23  1.671335
                move           Yel-2b33_18_rivers-21 -0.180085
                open            Bra-fdd7_54_ocean-23  0.025940
                open            Cic-6b3c_60_ocean-18 -0.138885
                open           Eur-7866_4_farmland-7 -0.306087
nmod>nmod>case> of           Hed-8dc6_29_hedgerows-3  0.254605
                of                Sca-88f4_90_bed-53  1.166570
                to        Afr-7a1b_121_rainforest-20  0.714113
                to             Gol-1dbf_251_desert-6  0.397172
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (137,)
ftok (18, 2)
x0 token_id
Rei-38eb_426_mountain-16   -0.702453
Dra-48f6_125_swamps-19     -0.443416
Cet-5f63_539_estuary-8     -0.362672
Ame-d5c4_96_Mountains-58    0.140629
Tun-4bf6_40_tundra-13      -0.105871
                              ...
Seq-b61f_60_mountains-13    0.804088
Flo-eb50_5_wetlands-36      0.484008
Rei-38eb_91_tundra-8        0.448377
Par5cb2_21_parklands-23    -0.233671
Bot-5a32_69_forest-20       1.026774
Name: x, Length: 134, dtype: float64
x0 token_id
Rei-38eb_426_mountain-16   -0.702453
Dra-48f6_125_swamps-19     -0.443416
Cet-5f63_539_estuary-8     -0.362672
Ame-d5c4_96_Mountains-58    0.140629
Tun-4bf6_40_tundra-13      -0.105871
                              ...
Seq-b61f_60_mountains-13    0.804088
Flo-eb50_5_wetlands-36      0.484008
Rei-38eb_91_tundra-8        0.448377
Par5cb2_21_parklands-23    -0.233671
Bot-5a32_69_forest-20       1.026774
Name: x, Length: 134, dtype: float64

x0 token_id
Rei-38eb_426_mountain-16   -0.702453
Dra-48f6_125_swamps-19     -0.443416
Cet-5f63_539_estuary-8     -0.362672
Ame-d5c4_96_Mountains-58    0.140629
Tun-4bf6_40_tundra-13      -0.105871
                              ...
Seq-b61f_60_mountains-13    0.804088
Flo-eb50_5_wetlands-36      0.484008
Rei-38eb_91_tundra-8        0.448377
Par5cb2_21_parklands-23    -0.233671
Bot-5a32_69_forest-20       1.026774
Name: x, Length: 136, dtype: float64
x0 token_id
Rei-38eb_426_mountain-16   -0.702453
Dra-48f6_125_swamps-19     -0.443416
Cet-5f63_539_estuary-8     -0.362672
Ame-d5c4_96_Mountains-58    0.140629
Tun-4bf6_40_tundra-13      -0.105871
                              ...
Seq-b61f_60_mountains-13    0.804088
Flo-eb50_5_wetlands-36      0.484008
Rei-38eb_91_tundra-8        0.448377
Par5cb2_21_parklands-23    -0.233671
Bot-5a32_69_forest-20       1.026774
Name: x, Length: 136, dtype: float64
x0 token_id
Rei-38eb_426_mountain-16   -0.702453
Dra-48f6_125_swamps-19     -0.443416
Cet-5f63_539_estuary-8     -0.362672
Ame-d5c4_96_Mountains-58    0.140629
Tun-4bf6_40_tundra-13      -0.105871
                              ...
Seq-b61f_60_mountains-13    0.804088
Flo-eb50_5_wetlands-36      0.484008
Rei-38eb_91_tundra-8        0.448377
Par5cb2_21_parklands-23    -0.233671
Bot-5a32_69_forest-20       1.026774
Name: x, Length: 136, dtype: float64
x0 token_id
Rei-38eb_426_mountain-16   -0.702453
Dra-48f6_125_swamps-19     -0.443416
Cet-5f63_539_estuary-8     -0.362672
Ame-d5c4_96_Mountains-58    0.140629
Tun-4bf6_40_tundra-13      -0.105871
                              ...
Seq-b61f_60_mountains-13    0.804088
Flo-eb50_5_wetlands-36      0.484008
Rei-38eb_91_tundra-8        0.448377
Par5cb2_21_parklands-23    -0.233671
Bot-5a32_69_forest-20       1.026774
Name: x, Length: 136, dtype: float64
x0 token_id
Rei-38eb_426_mountain-16   -0.702453
Dra-48f6_125_swamps-19     -0.443416
Cet-5f63_539_estuary-8     -0.362672
Ame-d5c4_96_Mountains-58    0.140629
Tun-4bf6_40_tundra-13      -0.105871
                              ...
Seq-b61f_60_mountains-13    0.804088
Flo-eb50_5_wetlands-36      0.484008
Rei-38eb_91_tundra-8        0.448377
Par5cb2_21_parklands-23    -0.233671
Bot-5a32_69_forest-20       1.026774
Name: x, Length: 136, dtype: float64
x0 token_id
Rei-38eb_426_mountain-16   -0.702453
Dra-48f6_125_swamps-19     -0.443416
Cet-5f63_539_estuary-8     -0.362672
Ame-d5c4_96_Mountains-58    0.140629
Tun-4bf6_40_tundra-13      -0.105871
                              ...
Seq-b61f_60_mountains-13    0.804088
Flo-eb50_5_wetlands-36      0.484008
Rei-38eb_91_tundra-8        0.448377
Par5cb2_21_parklands-23    -0.233671
Bot-5a32_69_forest-20       1.026774
Name: x, Length: 134, dtype: float64
x0 token_id
Rei-38eb_426_mountain-16   -0.702453
Dra-48f6_125_swamps-19     -0.443416
Cet-5f63_539_estuary-8     -0.362672
Ame-d5c4_96_Mountains-58    0.140629
Tun-4bf6_40_tundra-13      -0.105871
                              ...
Seq-b61f_60_mountains-13    0.804088
Flo-eb50_5_wetlands-36      0.484008
Rei-38eb_91_tundra-8        0.448377
Par5cb2_21_parklands-23    -0.233671
Bot-5a32_69_forest-20       1.026774
Name: x, Length: 135, dtype: float64
x0 token_id
Rei-38eb_426_mountain-16   -0.702453
Dra-48f6_125_swamps-19     -0.443416
Cet-5f63_539_estuary-8     -0.362672
Ame-d5c4_96_Mountains-58    0.140629
Tun-4bf6_40_tundra-13      -0.105871
                              ...
Seq-b61f_60_mountains-13    0.804088
Flo-eb50_5_wetlands-36      0.484008
Rei-38eb_91_tundra-8        0.448377
Par5cb2_21_parklands-23    -0.233671
Bot-5a32_69_forest-20       1.026774
Name: x, Length: 135, dtype: float64
Spearman results
feat_tests
                          test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath         lemma
amod>           arctic        0.87995    0.055        3     137     0.15
                arid          0.55402    0.215        3     137     0.59
                brackish      0.20468   -0.791        1     137    -1.27
                cold          0.74354    0.205        1     137     0.33
                coral         0.23717    0.738        1     137     1.19
                large         0.00788    1.641        1     137     2.70
                move          0.71992   -0.224        1     137    -0.36
                open          0.60848   -0.186        3     137    -0.51
nmod>nmod>case> of            0.12516    0.678        2     137     1.54
                to            0.23973    0.521        2     137     1.18
book_cl_elong
                          effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath         lemma
nmod>nmod>case> of      0.524891  0.003039  2  0.275511      0.12516    0.678
amod>           large   0.509737  0.001349  1  0.259832      0.00788    1.641
nmod>nmod>case> to      0.490541  0.004979  2  0.240631      0.23973    0.521
amod>           arctic  0.483268  0.004265  3  0.233548      0.87995    0.055
                arid    0.480305  0.006930  3  0.230693      0.55402    0.215
                cold    0.456988  0.001468  1  0.208838      0.74354    0.205
                coral   0.452616  0.001349  1  0.204861      0.23717    0.738

                        test_Nx  test_N  test_st
arcpath         lemma
nmod>nmod>case> of            2     137     1.54
amod>           large         1     137     2.70
nmod>nmod>case> to            2     137     1.18
amod>           arctic        3     137     0.15
                arid          3     137     0.59
                cold          1     137     0.33
                coral         1     137     1.19
cluster ====> 2
np.sqrt(eigvals)
[0.31737777 0.34533831 0.38726251 0.42861806 0.46738115 0.52134124
 0.6942731  0.88259353]
cl_elong_a, cl_elong_v.round(2)
1.2712483530567813 [-0.33 -0.61  0.15 -0.1  -0.56 -0.23 -0.24  0.27]
cluster data sample, mean shift
(341, 8)                             0         1         2         3         4  \
token_id
Bro48b9_2_polar-6   -0.727642 -1.138747 -0.043707  0.010465  0.786488
Que-fbc5_28_wood-18  0.401596 -0.033513  0.701756 -0.601601 -0.610104
Pin9930_6_polar-38  -0.509428 -0.662360 -0.183877  0.478493 -0.460254

                            5         6         7
token_id
Bro48b9_2_polar-6    0.404349 -0.375599 -0.000200
Que-fbc5_28_wood-18 -0.643470  0.343049  0.496321
Pin9930_6_polar-38   0.083839 -0.409811 -0.429073
cluster data elongation along main axis
                            effect        Dx  N      eff2
arcpath        lemma
case>          through   -0.521346  0.000641  1  0.271802
amod>          other     -0.486180  0.000529  1  0.236371
case>          like      -0.465835  0.001352  1  0.217002
               for       -0.445029  0.000408  1  0.198051
conj<nmod<det> a         -0.436042  0.002005  3  0.190133
amod>          high      -0.429139 -0.000394  1  0.184160
               temporary -0.420015  0.000305  1  0.176413
               arctic    -0.416116 -0.000134  1  0.173153
               true      -0.414064  0.001018  1  0.171449
               rich      -0.410688  0.001352  1  0.168664
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                               token         x
arcpath        lemma
amod>          arctic          Tun-c63e_27_tundras-2  0.168892
               high        Nub-af58_187_mountains-16 -0.372165
               other          Acr-6263_5_wetlands-13 -0.351442
               rich          Sno-3c77_60_farmland-21 -0.343190
               temporary       Amp-436a_349_pools-11 -0.531481
               true            Com-9826_80_desert-11 -1.006911
case>          for             Wete53f_30_wetlands-5 -0.897664
               like       Sem-387f_49_rainforests-12 -0.611117
               through      Nor-4c81_43_Mountains-47  0.054743
conj<nmod<det> a                 Bea-4f7a_7_lakes-18 -0.331551
               a               Rei-38eb_19_tundra-54 -0.751784
               a            Sik-94e7_81_farmlands-28  0.141092
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (341,)
ftok (12, 2)
x0 token_id
Bro48b9_2_polar-6           0.474541
Que-fbc5_28_wood-18         0.596462
Pin9930_6_polar-38          0.713137
Aes-8e92_25_marshes-11     -0.554108
Rei-38eb_392_taiga-16       0.974037
                              ...
Com-3b7c_79_hedgerows-11   -0.265754
Pol-a6a6_387_polar-3       -0.539816
Pol-a6a6_451_polar-6        0.650076
Polb6b1_89_polar-8          0.259097
Wet-a585_50_wetlands-22    -0.015004
Name: x, Length: 340, dtype: float64
x0 token_id
Bro48b9_2_polar-6           0.474541
Que-fbc5_28_wood-18         0.596462
Pin9930_6_polar-38          0.713137
Aes-8e92_25_marshes-11     -0.554108
Rei-38eb_392_taiga-16       0.974037
                              ...
Com-3b7c_79_hedgerows-11   -0.265754
Pol-a6a6_387_polar-3       -0.539816
Pol-a6a6_451_polar-6        0.650076
Polb6b1_89_polar-8          0.259097
Wet-a585_50_wetlands-22    -0.015004
Name: x, Length: 340, dtype: float64
x0 token_id
Bro48b9_2_polar-6           0.474541
Que-fbc5_28_wood-18         0.596462
Pin9930_6_polar-38          0.713137
Aes-8e92_25_marshes-11     -0.554108
Rei-38eb_392_taiga-16       0.974037
                              ...
Com-3b7c_79_hedgerows-11   -0.265754
Pol-a6a6_387_polar-3       -0.539816
Pol-a6a6_451_polar-6        0.650076
Polb6b1_89_polar-8          0.259097
Wet-a585_50_wetlands-22    -0.015004
Name: x, Length: 340, dtype: float64
x0 token_id
Bro48b9_2_polar-6           0.474541
Que-fbc5_28_wood-18         0.596462
Pin9930_6_polar-38          0.713137
Aes-8e92_25_marshes-11     -0.554108
Rei-38eb_392_taiga-16       0.974037
                              ...
Com-3b7c_79_hedgerows-11   -0.265754
Pol-a6a6_387_polar-3       -0.539816
Pol-a6a6_451_polar-6        0.650076
Polb6b1_89_polar-8          0.259097
Wet-a585_50_wetlands-22    -0.015004
Name: x, Length: 340, dtype: float64
x0 token_id
Bro48b9_2_polar-6           0.474541
Que-fbc5_28_wood-18         0.596462
Pin9930_6_polar-38          0.713137
Aes-8e92_25_marshes-11     -0.554108
Rei-38eb_392_taiga-16       0.974037
                              ...
Com-3b7c_79_hedgerows-11   -0.265754
Pol-a6a6_387_polar-3       -0.539816
Pol-a6a6_451_polar-6        0.650076
Polb6b1_89_polar-8          0.259097
Wet-a585_50_wetlands-22    -0.015004
Name: x, Length: 340, dtype: float64
x0 token_id
Bro48b9_2_polar-6           0.474541
Que-fbc5_28_wood-18         0.596462
Pin9930_6_polar-38          0.713137
Aes-8e92_25_marshes-11     -0.554108
Rei-38eb_392_taiga-16       0.974037
                              ...
Com-3b7c_79_hedgerows-11   -0.265754
Pol-a6a6_387_polar-3       -0.539816
Pol-a6a6_451_polar-6        0.650076
Polb6b1_89_polar-8          0.259097
Wet-a585_50_wetlands-22    -0.015004
Name: x, Length: 340, dtype: float64
x0 token_id
Bro48b9_2_polar-6           0.474541
Que-fbc5_28_wood-18         0.596462
Pin9930_6_polar-38          0.713137
Aes-8e92_25_marshes-11     -0.554108
Rei-38eb_392_taiga-16       0.974037
                              ...
Com-3b7c_79_hedgerows-11   -0.265754
Pol-a6a6_387_polar-3       -0.539816
Pol-a6a6_451_polar-6        0.650076
Polb6b1_89_polar-8          0.259097
Wet-a585_50_wetlands-22    -0.015004
Name: x, Length: 340, dtype: float64
x0 token_id
Bro48b9_2_polar-6           0.474541
Que-fbc5_28_wood-18         0.596462
Pin9930_6_polar-38          0.713137
Aes-8e92_25_marshes-11     -0.554108
Rei-38eb_392_taiga-16       0.974037
                              ...
Com-3b7c_79_hedgerows-11   -0.265754
Pol-a6a6_387_polar-3       -0.539816
Pol-a6a6_451_polar-6        0.650076
Polb6b1_89_polar-8          0.259097
Wet-a585_50_wetlands-22    -0.015004
Name: x, Length: 340, dtype: float64
x0 token_id
Bro48b9_2_polar-6           0.474541
Que-fbc5_28_wood-18         0.596462
Pin9930_6_polar-38          0.713137
Aes-8e92_25_marshes-11     -0.554108
Rei-38eb_392_taiga-16       0.974037
                              ...
Com-3b7c_79_hedgerows-11   -0.265754
Pol-a6a6_387_polar-3       -0.539816
Pol-a6a6_451_polar-6        0.650076
Polb6b1_89_polar-8          0.259097
Wet-a585_50_wetlands-22    -0.015004
Name: x, Length: 340, dtype: float64
x0 token_id
Bro48b9_2_polar-6           0.474541
Que-fbc5_28_wood-18         0.596462
Pin9930_6_polar-38          0.713137
Aes-8e92_25_marshes-11     -0.554108
Rei-38eb_392_taiga-16       0.974037
                              ...
Com-3b7c_79_hedgerows-11   -0.265754
Pol-a6a6_387_polar-3       -0.539816
Pol-a6a6_451_polar-6        0.650076
Polb6b1_89_polar-8          0.259097
Wet-a585_50_wetlands-22    -0.015004
Name: x, Length: 338, dtype: float64
Spearman results
feat_tests
                          test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath        lemma
amod>          arctic         0.70958    0.148        1     341     0.37
               high           0.32223   -0.394        1     341    -0.99
               other          0.34843   -0.373        1     341    -0.94
               rich           0.35923   -0.365        1     341    -0.92
               temporary      0.16390   -0.554        1     341    -1.40
               true           0.00934   -1.031        1     341    -2.61
case>          for            0.02030   -0.921        1     341    -2.33
               like           0.11105   -0.634        1     341    -1.60
               through        0.93215    0.034        1     341     0.09
conj<nmod<det> a              0.14244   -0.338        3     341    -1.47
book_cl_elong
                            effect        Dx  N      eff2  test_pvalue  \
arcpath        lemma
amod>          other     -0.486180  0.000529  1  0.236371      0.34843
case>          like      -0.465835  0.001352  1  0.217002      0.11105
               for       -0.445029  0.000408  1  0.198051      0.02030
conj<nmod<det> a         -0.436042  0.002005  3  0.190133      0.14244
amod>          high      -0.429139 -0.000394  1  0.184160      0.32223
               temporary -0.420015  0.000305  1  0.176413      0.16390
               true      -0.414064  0.001018  1  0.171449      0.00934
               rich      -0.410688  0.001352  1  0.168664      0.35923

                          test_dX  test_Nx  test_N  test_st
arcpath        lemma
amod>          other       -0.373        1     341    -0.94
case>          like        -0.634        1     341    -1.60
               for         -0.921        1     341    -2.33
conj<nmod<det> a           -0.338        3     341    -1.47
amod>          high        -0.394        1     341    -0.99
               temporary   -0.554        1     341    -1.40
               true        -1.031        1     341    -2.61
               rich        -0.365        1     341    -0.92
cluster ====> 3
np.sqrt(eigvals)
[0.26247926 0.44072012 0.56546502 0.62892883 0.69223248 0.75968631
 1.19697004 1.25618448]
cl_elong_a, cl_elong_v.round(2)
1.0494702713114128 [ 0.04  0.02  0.11 -0.17 -0.46  0.67 -0.44  0.31]
cluster data sample, mean shift
(405, 8)                                  0         1         2         3         4  \
token_id
Gre-8842_258_ocean-4     -1.030871  0.200674  0.292885 -1.064355  0.222302
Com-9826_486_farmlands-7 -1.287164 -0.771871  0.274622 -0.184147  0.673622
Bom-c423_307_farmland-14  0.417929 -0.004820  1.693472 -0.349631  0.494642

                                 5         6         7
token_id
Gre-8842_258_ocean-4     -0.226547 -0.243631 -0.471002
Com-9826_486_farmlands-7  0.224871  0.315972 -1.865007
Bom-c423_307_farmland-14 -0.268069  0.229000 -0.826509
cluster data elongation along main axis
                                effect        Dx   N      eff2
arcpath             lemma
obl<det>            a         0.539859  0.001326   2  0.291447
nmod>case>          at        0.527077 -0.000005   2  0.277810
amod>               true     -0.498103  0.000310   1  0.248107
obl<acl:relcl<cop>  be        0.490225  0.002182   3  0.240321
nmod>case>          around    0.446584  0.000359   1  0.199437
nmod>det>           a         0.444007  0.000460   2  0.197142
amod>               similar  -0.439997  0.001802   2  0.193597
nmod>case>          to        0.438104  0.004193  10  0.191935
compound<conj<amod> european  0.432041  0.000318   1  0.186660
nmod>case>          on        0.425597 -0.000074   4  0.181133
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                                   token         x
arcpath             lemma
amod>               similar    Dir-7dc2_149_parklands-19 -0.854076
                    similar         Sum-fc8d_26_swamps-3  0.385520
                    true         Gol-1dbf_254_deserts-13 -0.095034
compound<conj<amod> european    Eur-bc75_297_mountain-12  0.189860
nmod>case>          around            Por-f868_29_seas-9  1.960365
                    at         For-7d57_98_rainforest-30  0.652665
                    at             Him95bf_3_mountains-8  0.448225
                    on          Afr-354e_20_rainforest-6  0.197357
                    on        Amo-ffe8_41_rainforests-17  0.242954
                    on                Gia7637_6_vents-17  0.755132
                    on           Pyg-4c07_48_mangroves-6  0.757018
                    to         Ame-d5c4_103_Mountains-12  0.785662
                    to             Dee-529a_24_tundra-11  1.019266
                    to          Eur-0e00_171_Mountains-9  2.042702
                    to          Eur-9ec0_33_hedgerows-12  0.432332
                    to         Leo-56b9_10_rainforest-12  0.642884
                    to                Mal-994a_82_zone-8  1.383512
                    to             Per-145f_149_tundra-7  1.001943
                    to          Pin-c005_26_Mountains-21  1.012022
                    to               Sho-489b_7_swamps-9  0.873647
                    to           Wat-4f58_110_wetland-17  0.154296
nmod>det>           a               Cam1e51_16_desert-15  1.200244
                    a            Nom-aef8_36_mountains-9  0.736645
obl<acl:relcl<cop>  be         Afr-354e_4_rainforests-13  0.821775
                    be          Aur-441a_12_estuaries-14  0.306010
                    be           Hed-8dc6_45_hedgerows-8  0.903368
obl<det>            a          Cro-5646_351_rainforest-3  0.018535
                    a               Gra-bd0d_34_rivers-2 -0.140718
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (405,)
ftok (28, 2)
x0 token_id
Gre-8842_258_ocean-4         -0.121989
Com-9826_486_farmlands-7     -0.891321
Bom-c423_307_farmland-14     -0.503629
Hed-8dc6_45_hedgerows-8       0.903368
Whi-b4c3_497_coastal-43      -0.683353
                                ...
Bel-4321_145_estuaries-17    -0.175096
Sil-6383_38_rainforests-16   -0.027203
Kin-aa66_62_rivers-7         -1.264143
Thrc77b_3_rainforests-13      0.534527
Gee-216d_2_Mountains-40       0.007566
Name: x, Length: 403, dtype: float64
x0 token_id
Gre-8842_258_ocean-4         -0.121989
Com-9826_486_farmlands-7     -0.891321
Bom-c423_307_farmland-14     -0.503629
Hed-8dc6_45_hedgerows-8       0.903368
Whi-b4c3_497_coastal-43      -0.683353
                                ...
Bel-4321_145_estuaries-17    -0.175096
Sil-6383_38_rainforests-16   -0.027203
Kin-aa66_62_rivers-7         -1.264143
Thrc77b_3_rainforests-13      0.534527
Gee-216d_2_Mountains-40       0.007566
Name: x, Length: 404, dtype: float64
x0 token_id
Gre-8842_258_ocean-4         -0.121989
Com-9826_486_farmlands-7     -0.891321
Bom-c423_307_farmland-14     -0.503629
Hed-8dc6_45_hedgerows-8       0.903368
Whi-b4c3_497_coastal-43      -0.683353
                                ...
Bel-4321_145_estuaries-17    -0.175096
Sil-6383_38_rainforests-16   -0.027203
Kin-aa66_62_rivers-7         -1.264143
Thrc77b_3_rainforests-13      0.534527
Gee-216d_2_Mountains-40       0.007566
Name: x, Length: 404, dtype: float64
x0 token_id
Gre-8842_258_ocean-4         -0.121989
Com-9826_486_farmlands-7     -0.891321
Bom-c423_307_farmland-14     -0.503629
Hed-8dc6_45_hedgerows-8       0.903368
Whi-b4c3_497_coastal-43      -0.683353
                                ...
Bel-4321_145_estuaries-17    -0.175096
Sil-6383_38_rainforests-16   -0.027203
Kin-aa66_62_rivers-7         -1.264143
Thrc77b_3_rainforests-13      0.534527
Gee-216d_2_Mountains-40       0.007566
Name: x, Length: 404, dtype: float64
x0 token_id
Gre-8842_258_ocean-4         -0.121989
Com-9826_486_farmlands-7     -0.891321
Bom-c423_307_farmland-14     -0.503629
Hed-8dc6_45_hedgerows-8       0.903368
Whi-b4c3_497_coastal-43      -0.683353
                                ...
Bel-4321_145_estuaries-17    -0.175096
Sil-6383_38_rainforests-16   -0.027203
Kin-aa66_62_rivers-7         -1.264143
Thrc77b_3_rainforests-13      0.534527
Gee-216d_2_Mountains-40       0.007566
Name: x, Length: 403, dtype: float64
x0 token_id
Gre-8842_258_ocean-4         -0.121989
Com-9826_486_farmlands-7     -0.891321
Bom-c423_307_farmland-14     -0.503629
Hed-8dc6_45_hedgerows-8       0.903368
Whi-b4c3_497_coastal-43      -0.683353
                                ...
Bel-4321_145_estuaries-17    -0.175096
Sil-6383_38_rainforests-16   -0.027203
Kin-aa66_62_rivers-7         -1.264143
Thrc77b_3_rainforests-13      0.534527
Gee-216d_2_Mountains-40       0.007566
Name: x, Length: 401, dtype: float64
x0 token_id
Gre-8842_258_ocean-4         -0.121989
Com-9826_486_farmlands-7     -0.891321
Bom-c423_307_farmland-14     -0.503629
Hed-8dc6_45_hedgerows-8       0.903368
Whi-b4c3_497_coastal-43      -0.683353
                                ...
Bel-4321_145_estuaries-17    -0.175096
Sil-6383_38_rainforests-16   -0.027203
Kin-aa66_62_rivers-7         -1.264143
Thrc77b_3_rainforests-13      0.534527
Gee-216d_2_Mountains-40       0.007566
Name: x, Length: 395, dtype: float64
x0 token_id
Gre-8842_258_ocean-4         -0.121989
Com-9826_486_farmlands-7     -0.891321
Bom-c423_307_farmland-14     -0.503629
Hed-8dc6_45_hedgerows-8       0.903368
Whi-b4c3_497_coastal-43      -0.683353
                                ...
Bel-4321_145_estuaries-17    -0.175096
Sil-6383_38_rainforests-16   -0.027203
Kin-aa66_62_rivers-7         -1.264143
Thrc77b_3_rainforests-13      0.534527
Gee-216d_2_Mountains-40       0.007566
Name: x, Length: 403, dtype: float64
x0 token_id
Gre-8842_258_ocean-4         -0.121989
Com-9826_486_farmlands-7     -0.891321
Bom-c423_307_farmland-14     -0.503629
Whi-b4c3_497_coastal-43      -0.683353
Wat-4f58_111_marsh-17        -0.252332
                                ...
Bel-4321_145_estuaries-17    -0.175096
Sil-6383_38_rainforests-16   -0.027203
Kin-aa66_62_rivers-7         -1.264143
Thrc77b_3_rainforests-13      0.534527
Gee-216d_2_Mountains-40       0.007566
Name: x, Length: 402, dtype: float64
x0 token_id
Gre-8842_258_ocean-4         -0.121989
Com-9826_486_farmlands-7     -0.891321
Bom-c423_307_farmland-14     -0.503629
Hed-8dc6_45_hedgerows-8       0.903368
Whi-b4c3_497_coastal-43      -0.683353
                                ...
Bel-4321_145_estuaries-17    -0.175096
Sil-6383_38_rainforests-16   -0.027203
Kin-aa66_62_rivers-7         -1.264143
Thrc77b_3_rainforests-13      0.534527
Gee-216d_2_Mountains-40       0.007566
Name: x, Length: 403, dtype: float64
Spearman results
feat_tests
                              test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath             lemma
amod>               similar       0.57583   -0.269        2     405    -0.56
                    true          0.84954   -0.129        1     405    -0.19
compound<conj<amod> european      0.81775    0.157        1     405     0.23
nmod>case>          around        0.00429    1.932        1     405     2.87
                    at            0.28013    0.519        2     405     1.08
                    on            0.17796    0.459        4     405     1.35
                    to            0.00002    0.924       10     405     4.35
nmod>det>           a             0.05038    0.939        2     405     1.96
obl<acl:relcl<cop>  be            0.09886    0.648        3     405     1.65
obl<det>            a             0.84325   -0.095        2     405    -0.20
book_cl_elong
                                effect        Dx   N      eff2  test_pvalue  \
arcpath             lemma
nmod>case>          at        0.527077 -0.000005   2  0.277810      0.28013
amod>               true     -0.498103  0.000310   1  0.248107      0.84954
obl<acl:relcl<cop>  be        0.490225  0.002182   3  0.240321      0.09886
nmod>case>          around    0.446584  0.000359   1  0.199437      0.00429
nmod>det>           a         0.444007  0.000460   2  0.197142      0.05038
amod>               similar  -0.439997  0.001802   2  0.193597      0.57583
nmod>case>          to        0.438104  0.004193  10  0.191935      0.00002
compound<conj<amod> european  0.432041  0.000318   1  0.186660      0.81775
nmod>case>          on        0.425597 -0.000074   4  0.181133      0.17796

                              test_dX  test_Nx  test_N  test_st
arcpath             lemma
nmod>case>          at          0.519        2     405     1.08
amod>               true       -0.129        1     405    -0.19
obl<acl:relcl<cop>  be          0.648        3     405     1.65
nmod>case>          around      1.932        1     405     2.87
nmod>det>           a           0.939        2     405     1.96
amod>               similar    -0.269        2     405    -0.56
nmod>case>          to          0.924       10     405     4.35
compound<conj<amod> european    0.157        1     405     0.23
nmod>case>          on          0.459        4     405     1.35
cluster ====> 4
np.sqrt(eigvals)
[0.31385466 0.65068625 0.81618633 0.88467151 1.06378064 1.61092388
 1.79157018 2.89727413]
cl_elong_a, cl_elong_v.round(2)
1.6171703229387056 [-0.28  0.05  0.41  0.67 -0.11  0.07  0.33  0.43]
cluster data sample, mean shift
(13, 8)                               0         1         2         3         4  \
token_id
Rei-38eb_144_tundra-2 -2.451162 -3.921091  0.457902  2.736896  1.695173
Wes-9ef7_5_marsh-15   -1.590136 -1.338715 -1.539077  3.461559  1.770831
Tai-3286_55_taiga-6   -0.662972 -0.471915 -1.366941 -0.663383 -0.568824

                              5         6         7
token_id
Rei-38eb_144_tundra-2 -3.446200  1.253186  0.925342
Wes-9ef7_5_marsh-15   -0.515090 -0.698153  1.439342
Tai-3286_55_taiga-6    3.321467 -2.360091 -1.086560
cluster data elongation along main axis
                            effect        Dx  N      eff2
arcpath            lemma
det>               the   -0.763867  0.019030  7  0.583493
                   both  -0.750163  0.015244  1  0.562744
conj>cc>           and   -0.452927  0.010692  3  0.205143
nsubj<obl>case>    with  -0.360549  0.014002  1  0.129996
                   on    -0.357973  0.015704  1  0.128145
obl<obl>case>      from  -0.349397  0.013827  1  0.122078
compound<nmod>det> the   -0.325791  0.007747  1  0.106140
case>              in    -0.320080 -0.000142  3  0.102451
appos>conj>cc>     and   -0.293753  0.007989  1  0.086291
nsubj<obl>case>    in    -0.292627  0.013100  1  0.085631
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                              token         x
arcpath            lemma
appos>conj>cc>     and     Sno-d342_61_Mountains-19 -4.483969
case>              in     Gol-1dbf_312_Mountains-15  0.875420
                   in      Sno-d342_61_Mountains-19 -4.483969
                   in       Mal-71cc_99_wetlands-12 -1.969101
compound<nmod>det> the          Wes-9ef7_5_marsh-15  2.213227
conj>cc>           and      Bar-89af_19_mountain-28 -0.405059
                   and      Flo-eb50_9_grassland-20 -2.214803
                   and     Sno-d342_61_Mountains-19 -4.483969
det>               both     Mal-71cc_99_wetlands-12 -1.969101
                   the      Bar-89af_19_mountain-28 -0.405059
                   the       Eur-3ec7_308_tundra-43  0.130076
                   the      Flo-eb50_9_grassland-20 -2.214803
                   the    Gol-1dbf_312_Mountains-15  0.875420
                   the           Pel-cab2_9_ocean-8  0.046079
                   the     Sno-d342_61_Mountains-19 -4.483969
                   the          Tai-3286_55_taiga-6 -1.770858
nsubj<obl>case>    in           Tai-3286_55_taiga-6 -1.770858
                   on           Tai-3286_55_taiga-6 -1.770858
                   with         Tai-3286_55_taiga-6 -1.770858
obl<obl>case>      from    Sno-d342_61_Mountains-19 -4.483969
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (13,)
ftok (20, 2)
x0 token_id
Rei-38eb_144_tundra-2        2.884628
Wes-9ef7_5_marsh-15          2.213227
Tai-3286_55_taiga-6         -1.770858
Tai-3286_130_polar-73        2.710171
Wat-4f58_97_wetland-10       0.397659
Mar-80c6_24_wetlands-14     -0.900622
Flo-eb50_9_grassland-20     -2.214803
Pel-cab2_9_ocean-8           0.046079
Bar-89af_19_mountain-28     -0.405059
Mal-71cc_99_wetlands-12     -1.969101
Gol-1dbf_312_Mountains-15    0.875420
Eur-3ec7_308_tundra-43       0.130076
Name: x, dtype: float64
x0 token_id
Rei-38eb_144_tundra-2      2.884628
Wes-9ef7_5_marsh-15        2.213227
Tai-3286_55_taiga-6       -1.770858
Tai-3286_130_polar-73      2.710171
Wat-4f58_97_wetland-10     0.397659
Mar-80c6_24_wetlands-14   -0.900622
Flo-eb50_9_grassland-20   -2.214803
Pel-cab2_9_ocean-8         0.046079
Bar-89af_19_mountain-28   -0.405059
Eur-3ec7_308_tundra-43     0.130076
Name: x, dtype: float64
x0 token_id
Rei-38eb_144_tundra-2        2.884628
Tai-3286_55_taiga-6         -1.770858
Tai-3286_130_polar-73        2.710171
Wat-4f58_97_wetland-10       0.397659
Sno-d342_61_Mountains-19    -4.483969
Mar-80c6_24_wetlands-14     -0.900622
Flo-eb50_9_grassland-20     -2.214803
Pel-cab2_9_ocean-8           0.046079
Bar-89af_19_mountain-28     -0.405059
Mal-71cc_99_wetlands-12     -1.969101
Gol-1dbf_312_Mountains-15    0.875420
Eur-3ec7_308_tundra-43       0.130076
Name: x, dtype: float64
x0 token_id
Rei-38eb_144_tundra-2        2.884628
Wes-9ef7_5_marsh-15          2.213227
Tai-3286_55_taiga-6         -1.770858
Tai-3286_130_polar-73        2.710171
Wat-4f58_97_wetland-10       0.397659
Mar-80c6_24_wetlands-14     -0.900622
Pel-cab2_9_ocean-8           0.046079
Mal-71cc_99_wetlands-12     -1.969101
Gol-1dbf_312_Mountains-15    0.875420
Eur-3ec7_308_tundra-43       0.130076
Name: x, dtype: float64
x0 token_id
Rei-38eb_144_tundra-2        2.884628
Wes-9ef7_5_marsh-15          2.213227
Tai-3286_55_taiga-6         -1.770858
Tai-3286_130_polar-73        2.710171
Wat-4f58_97_wetland-10       0.397659
Sno-d342_61_Mountains-19    -4.483969
Mar-80c6_24_wetlands-14     -0.900622
Flo-eb50_9_grassland-20     -2.214803
Pel-cab2_9_ocean-8           0.046079
Bar-89af_19_mountain-28     -0.405059
Gol-1dbf_312_Mountains-15    0.875420
Eur-3ec7_308_tundra-43       0.130076
Name: x, dtype: float64
x0 token_id
Rei-38eb_144_tundra-2      2.884628
Wes-9ef7_5_marsh-15        2.213227
Tai-3286_130_polar-73      2.710171
Wat-4f58_97_wetland-10     0.397659
Mar-80c6_24_wetlands-14   -0.900622
Mal-71cc_99_wetlands-12   -1.969101
Name: x, dtype: float64
x0 token_id
Rei-38eb_144_tundra-2        2.884628
Wes-9ef7_5_marsh-15          2.213227
Tai-3286_130_polar-73        2.710171
Wat-4f58_97_wetland-10       0.397659
Sno-d342_61_Mountains-19    -4.483969
Mar-80c6_24_wetlands-14     -0.900622
Flo-eb50_9_grassland-20     -2.214803
Pel-cab2_9_ocean-8           0.046079
Bar-89af_19_mountain-28     -0.405059
Mal-71cc_99_wetlands-12     -1.969101
Gol-1dbf_312_Mountains-15    0.875420
Eur-3ec7_308_tundra-43       0.130076
Name: x, dtype: float64
x0 token_id
Rei-38eb_144_tundra-2        2.884628
Wes-9ef7_5_marsh-15          2.213227
Tai-3286_130_polar-73        2.710171
Wat-4f58_97_wetland-10       0.397659
Sno-d342_61_Mountains-19    -4.483969
Mar-80c6_24_wetlands-14     -0.900622
Flo-eb50_9_grassland-20     -2.214803
Pel-cab2_9_ocean-8           0.046079
Bar-89af_19_mountain-28     -0.405059
Mal-71cc_99_wetlands-12     -1.969101
Gol-1dbf_312_Mountains-15    0.875420
Eur-3ec7_308_tundra-43       0.130076
Name: x, dtype: float64
x0 token_id
Rei-38eb_144_tundra-2        2.884628
Wes-9ef7_5_marsh-15          2.213227
Tai-3286_130_polar-73        2.710171
Wat-4f58_97_wetland-10       0.397659
Sno-d342_61_Mountains-19    -4.483969
Mar-80c6_24_wetlands-14     -0.900622
Flo-eb50_9_grassland-20     -2.214803
Pel-cab2_9_ocean-8           0.046079
Bar-89af_19_mountain-28     -0.405059
Mal-71cc_99_wetlands-12     -1.969101
Gol-1dbf_312_Mountains-15    0.875420
Eur-3ec7_308_tundra-43       0.130076
Name: x, dtype: float64
x0 token_id
Rei-38eb_144_tundra-2        2.884628
Wes-9ef7_5_marsh-15          2.213227
Tai-3286_55_taiga-6         -1.770858
Tai-3286_130_polar-73        2.710171
Wat-4f58_97_wetland-10       0.397659
Mar-80c6_24_wetlands-14     -0.900622
Flo-eb50_9_grassland-20     -2.214803
Pel-cab2_9_ocean-8           0.046079
Bar-89af_19_mountain-28     -0.405059
Mal-71cc_99_wetlands-12     -1.969101
Gol-1dbf_312_Mountains-15    0.875420
Eur-3ec7_308_tundra-43       0.130076
Name: x, dtype: float64
Spearman results
feat_tests
                          test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath            lemma
appos>conj>cc>     and        0.02754   -4.650        1      13    -2.54
case>              in         0.12463   -2.168        3      13    -1.66
compound<nmod>det> the        0.25498    2.605        1      13     1.20
conj>cc>           and        0.03580   -2.830        3      13    -2.39
det>               both       0.40673   -1.926        1      13    -0.86
                   the        0.08861   -2.007        7      13    -1.87
nsubj<obl>case>    in         0.46262   -1.711        1      13    -0.76
                   on         0.46262   -1.711        1      13    -0.76
                   with       0.46262   -1.711        1      13    -0.76
obl<obl>case>      from       0.02754   -4.650        1      13    -2.54
book_cl_elong
                         effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath         lemma
det>            the   -0.763867  0.019030  7  0.583493      0.08861   -2.007
                both  -0.750163  0.015244  1  0.562744      0.40673   -1.926
conj>cc>        and   -0.452927  0.010692  3  0.205143      0.03580   -2.830
nsubj<obl>case> with  -0.360549  0.014002  1  0.129996      0.46262   -1.711
                on    -0.357973  0.015704  1  0.128145      0.46262   -1.711
obl<obl>case>   from  -0.349397  0.013827  1  0.122078      0.02754   -4.650
case>           in    -0.320080 -0.000142  3  0.102451      0.12463   -2.168
appos>conj>cc>  and   -0.293753  0.007989  1  0.086291      0.02754   -4.650
nsubj<obl>case> in    -0.292627  0.013100  1  0.085631      0.46262   -1.711

                       test_Nx  test_N  test_st
arcpath         lemma
det>            the          7      13    -1.87
                both         1      13    -0.86
conj>cc>        and          3      13    -2.39
nsubj<obl>case> with         1      13    -0.76
                on           1      13    -0.76
obl<obl>case>   from         1      13    -2.54
case>           in           3      13    -1.66
appos>conj>cc>  and          1      13    -2.54
nsubj<obl>case> in           1      13    -0.76
cluster ====> 5
np.sqrt(eigvals)
[0.39710948 0.43160613 0.53229448 0.59654682 0.6949234  0.96411098
 1.02364397 2.2758783 ]
cl_elong_a, cl_elong_v.round(2)
2.223310423416321 [-0.74  0.24  0.1  -0.22  0.45 -0.14  0.33  0.  ]
cluster data sample, mean shift
(174, 8)                                 0         1         2         3         4  \
token_id
Woo-fa9e_69_marshes-9   -0.030737 -0.724913 -2.108516  1.369933  0.238925
Cap-5548_41_marshes-23   0.530164  1.179054 -0.841582 -0.177485 -0.678166
Sag-0ea8_114_deserts-27  2.009399 -0.078496  1.052753 -0.912136 -0.369519

                                5         6         7
token_id
Woo-fa9e_69_marshes-9    1.192659 -2.638249  0.070210
Cap-5548_41_marshes-23  -0.084959  2.140255  1.167349
Sag-0ea8_114_deserts-27  0.072366 -0.664889  0.528400
cluster data elongation along main axis
                            effect        Dx  N      eff2
arcpath          lemma
nmod>case>       in      -0.617155 -0.001347  2  0.380881
                 from    -0.604048  0.000016  1  0.364874
                 around  -0.593986  0.002359  2  0.352820
                 of      -0.562808 -0.002289  3  0.316753
                 include -0.535242 -0.000234  1  0.286484
amod>            open    -0.488495 -0.001442  3  0.238628
                 shallow -0.472428  0.000008  1  0.223188
                 large   -0.456769  0.000371  1  0.208638
                 tallest -0.447664  0.001048  1  0.200403
conj<appos<case> by      -0.438722  0.002696  2  0.192477
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                              token         x
arcpath          lemma
amod>            large     Sto-c148_138_wetlands-20 -0.801676
                 open      Anc-6a43_47_heathland-22 -1.126904
                 open       Gol-1dbf_257_marshes-20  0.292754
                 open          Por-f868_13_ocean-31  0.183655
                 shallow        Raj-3022_35_seas-17 -1.073584
                 tallest   Mou-ec99_166_mountain-33 -0.328092
conj<appos<case> by         Wet-a585_50_wetlands-19 -0.439695
                 by         Wet-a585_50_wetlands-27 -0.189260
nmod>case>       around    Big-0af3_35_mountains-22 -1.039791
                 around        Fro-21e4_35_water-16 -1.958487
                 from         Gol-1dbf_217_taiga-19 -1.303221
                 in          Eur-19c7_55_estuary-27 -1.378748
                 in         Gol-1dbf_263_marshes-24  0.780816
                 include    Bra-fdd7_40_mangroves-8 -1.919759
                 of         Sag-0ea8_114_deserts-27 -1.592409
                 of             Siae4d7_4_swamps-11 -1.527301
                 of       Sou-ac15_131_estuaries-64 -0.770687
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (174,)
ftok (17, 2)
x0 token_id
Woo-fa9e_69_marshes-9       -1.617067
Cap-5548_41_marshes-23       0.274251
Sag-0ea8_114_deserts-27     -1.592409
Ant-f910_62_rainforests-8    0.687382
Gat-a3f4_38_hedgerows-19     0.658141
                               ...
Sha-8b9d_53_reef-18          1.949703
Siae4d7_4_swamps-11         -1.527301
Sto-c148_138_farmlands-16   -0.058879
Lar-2baf_25_rainforest-25    0.470316
Gol-1dbf_263_wetlands-38     1.656587
Name: x, Length: 173, dtype: float64
x0 token_id
Woo-fa9e_69_marshes-9       -1.617067
Cap-5548_41_marshes-23       0.274251
Sag-0ea8_114_deserts-27     -1.592409
Ant-f910_62_rainforests-8    0.687382
Gat-a3f4_38_hedgerows-19     0.658141
                               ...
Sha-8b9d_53_reef-18          1.949703
Siae4d7_4_swamps-11         -1.527301
Sto-c148_138_farmlands-16   -0.058879
Lar-2baf_25_rainforest-25    0.470316
Gol-1dbf_263_wetlands-38     1.656587
Name: x, Length: 171, dtype: float64
x0 token_id
Woo-fa9e_69_marshes-9       -1.617067
Cap-5548_41_marshes-23       0.274251
Sag-0ea8_114_deserts-27     -1.592409
Ant-f910_62_rainforests-8    0.687382
Gat-a3f4_38_hedgerows-19     0.658141
                               ...
Sha-8b9d_53_reef-18          1.949703
Siae4d7_4_swamps-11         -1.527301
Sto-c148_138_farmlands-16   -0.058879
Lar-2baf_25_rainforest-25    0.470316
Gol-1dbf_263_wetlands-38     1.656587
Name: x, Length: 173, dtype: float64
x0 token_id
Woo-fa9e_69_marshes-9       -1.617067
Cap-5548_41_marshes-23       0.274251
Sag-0ea8_114_deserts-27     -1.592409
Ant-f910_62_rainforests-8    0.687382
Gat-a3f4_38_hedgerows-19     0.658141
                               ...
Sha-8b9d_53_reef-18          1.949703
Siae4d7_4_swamps-11         -1.527301
Sto-c148_138_farmlands-16   -0.058879
Lar-2baf_25_rainforest-25    0.470316
Gol-1dbf_263_wetlands-38     1.656587
Name: x, Length: 173, dtype: float64
x0 token_id
Woo-fa9e_69_marshes-9       -1.617067
Cap-5548_41_marshes-23       0.274251
Sag-0ea8_114_deserts-27     -1.592409
Ant-f910_62_rainforests-8    0.687382
Gat-a3f4_38_hedgerows-19     0.658141
                               ...
Sha-8b9d_53_reef-18          1.949703
Siae4d7_4_swamps-11         -1.527301
Sto-c148_138_farmlands-16   -0.058879
Lar-2baf_25_rainforest-25    0.470316
Gol-1dbf_263_wetlands-38     1.656587
Name: x, Length: 172, dtype: float64
x0 token_id
Woo-fa9e_69_marshes-9       -1.617067
Cap-5548_41_marshes-23       0.274251
Sag-0ea8_114_deserts-27     -1.592409
Ant-f910_62_rainforests-8    0.687382
Gat-a3f4_38_hedgerows-19     0.658141
                               ...
Sha-8b9d_53_reef-18          1.949703
Siae4d7_4_swamps-11         -1.527301
Sto-c148_138_farmlands-16   -0.058879
Lar-2baf_25_rainforest-25    0.470316
Gol-1dbf_263_wetlands-38     1.656587
Name: x, Length: 172, dtype: float64
x0 token_id
Woo-fa9e_69_marshes-9       -1.617067
Cap-5548_41_marshes-23       0.274251
Sag-0ea8_114_deserts-27     -1.592409
Ant-f910_62_rainforests-8    0.687382
Gat-a3f4_38_hedgerows-19     0.658141
                               ...
Sha-8b9d_53_reef-18          1.949703
Siae4d7_4_swamps-11         -1.527301
Sto-c148_138_farmlands-16   -0.058879
Lar-2baf_25_rainforest-25    0.470316
Gol-1dbf_263_wetlands-38     1.656587
Name: x, Length: 173, dtype: float64
x0 token_id
Woo-fa9e_69_marshes-9       -1.617067
Cap-5548_41_marshes-23       0.274251
Sag-0ea8_114_deserts-27     -1.592409
Ant-f910_62_rainforests-8    0.687382
Gat-a3f4_38_hedgerows-19     0.658141
                               ...
Sha-8b9d_53_reef-18          1.949703
Siae4d7_4_swamps-11         -1.527301
Sto-c148_138_farmlands-16   -0.058879
Lar-2baf_25_rainforest-25    0.470316
Gol-1dbf_263_wetlands-38     1.656587
Name: x, Length: 172, dtype: float64
x0 token_id
Woo-fa9e_69_marshes-9       -1.617067
Cap-5548_41_marshes-23       0.274251
Sag-0ea8_114_deserts-27     -1.592409
Ant-f910_62_rainforests-8    0.687382
Gat-a3f4_38_hedgerows-19     0.658141
                               ...
Sha-8b9d_53_reef-18          1.949703
Siae4d7_4_swamps-11         -1.527301
Sto-c148_138_farmlands-16   -0.058879
Lar-2baf_25_rainforest-25    0.470316
Gol-1dbf_263_wetlands-38     1.656587
Name: x, Length: 173, dtype: float64
x0 token_id
Woo-fa9e_69_marshes-9       -1.617067
Cap-5548_41_marshes-23       0.274251
Ant-f910_62_rainforests-8    0.687382
Gat-a3f4_38_hedgerows-19     0.658141
Roo-1bd1_36_moorland-12     -0.121894
                               ...
Chi-c10a_89_rainforest-14    1.256010
Sha-8b9d_53_reef-18          1.949703
Sto-c148_138_farmlands-16   -0.058879
Lar-2baf_25_rainforest-25    0.470316
Gol-1dbf_263_wetlands-38     1.656587
Name: x, Length: 171, dtype: float64
Spearman results
feat_tests
                          test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath          lemma
amod>            large        0.44313   -0.823        1     174    -0.77
                 open         0.70322   -0.238        3     174    -0.38
                 shallow      0.30658   -1.097        1     174    -1.03
                 tallest      0.74680   -0.347        1     174    -0.32
conj<appos<case> by           0.66001   -0.335        2     174    -0.44
nmod>case>       around       0.04285   -1.533        2     174    -2.04
                 from         0.21547   -1.328        1     174    -1.24
                 in           0.67501   -0.319        2     174    -0.42
                 include      0.06846   -1.948        1     174    -1.83
                 of           0.03099   -1.337        3     174    -2.18
book_cl_elong
                            effect        Dx  N      eff2  test_pvalue  \
arcpath          lemma
nmod>case>       in      -0.617155 -0.001347  2  0.380881      0.67501
                 from    -0.604048  0.000016  1  0.364874      0.21547
                 around  -0.593986  0.002359  2  0.352820      0.04285
                 of      -0.562808 -0.002289  3  0.316753      0.03099
                 include -0.535242 -0.000234  1  0.286484      0.06846
amod>            open    -0.488495 -0.001442  3  0.238628      0.70322
                 shallow -0.472428  0.000008  1  0.223188      0.30658
                 large   -0.456769  0.000371  1  0.208638      0.44313
                 tallest -0.447664  0.001048  1  0.200403      0.74680
conj<appos<case> by      -0.438722  0.002696  2  0.192477      0.66001

                          test_dX  test_Nx  test_N  test_st
arcpath          lemma
nmod>case>       in        -0.319        2     174    -0.42
                 from      -1.328        1     174    -1.24
                 around    -1.533        2     174    -2.04
                 of        -1.337        3     174    -2.18
                 include   -1.948        1     174    -1.83
amod>            open      -0.238        3     174    -0.38
                 shallow   -1.097        1     174    -1.03
                 large     -0.823        1     174    -0.77
                 tallest   -0.347        1     174    -0.32
conj<appos<case> by        -0.335        2     174    -0.44
cluster ====> 6
np.sqrt(eigvals)
[0.2115202  0.26423219 0.32584259 0.35930328 0.46415812 0.56105434
 0.79345482 1.00706068]
cl_elong_a, cl_elong_v.round(2)
1.2692098522530233 [ 0.27 -0.9   0.    0.25 -0.04  0.13 -0.05  0.19]
cluster data sample, mean shift
(210, 8)                                  0         1         2         3         4  \
token_id
Hed-8dc6_110_hedgerow-26 -0.175325 -0.282244 -0.516174 -0.955975  0.950764
Wet-a585_414_wetlands-20 -0.158833  0.244969  0.383536 -0.345528  0.297732
Con-7997_10_mountains-28 -0.368684 -0.897095 -1.179292  0.166682  1.068836

                                 5         6         7
token_id
Hed-8dc6_110_hedgerow-26  0.079294  0.264151 -0.026606
Wet-a585_414_wetlands-20 -0.418508 -0.051952  0.232027
Con-7997_10_mountains-28  1.294435  0.280416  0.468664
cluster data elongation along main axis
                                      effect        Dx  N      eff2
arcpath                   lemma
obl<                      make     -0.759692  0.001722  1  0.577132
                          feed     -0.735651  0.001261  1  0.541183
                          forage   -0.684577  0.001584  1  0.468646
                          live     -0.592173  0.004561  5  0.350669
                          find     -0.568601 -0.000098  3  0.323308
compound<acl:relcl>nsubj> that     -0.558342  0.003940  2  0.311746
                          which    -0.525087  0.003748  2  0.275717
obl<                      occur    -0.522854  0.000821  1  0.273376
nmod<conj<amod>           dominant  0.509687  0.004601  2  0.259781
appos<obl>det>            the       0.503726  0.001796  1  0.253740
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                                         token         x
arcpath                   lemma
appos<obl>det>            the        Ada-f37b_64_Rainforest-15  0.143183
compound<acl:relcl>nsubj> that           Dro-9dd9_30_desert-39 -0.301774
                          that           Rei-38eb_77_tundra-32 -0.787999
                          which          Swa-b870_49_tundra-18 -0.240036
                          which          Whi-b4c3_684_marsh-29 -0.099843
nmod<conj<amod>           dominant    Con-7997_10_mountains-28  0.952486
                          dominant   Con-7997_194_mountains-28  0.835027
obl<                      feed           Ade-b6ba_31_desert-19 -0.987922
                          find          Bla-2fe0_100_desert-20 -0.062633
                          find              Hyd-d7b9_9_vents-8 -0.684080
                          find             Sti-ddcd_6_ocean-38 -0.147785
                          forage         Com-9711_140_tundra-7 -0.514497
                          live               Aukb31c_6_ocean-7 -0.102099
                          live          Las-be5f_4_heathland-9 -0.245954
                          live             Nom-aef8_8_tundra-9 -0.422135
                          live          Ona-2309_57_deserts-16 -0.601064
                          live      Pri-2545_371_rainforests-7 -0.875134
                          make              Comb5d5_22_taiga-5 -0.777806
                          occur      Eth-d9c8_195_Mountains-21 -0.816981
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (210,)
ftok (19, 2)
x0 token_id
Hed-8dc6_110_hedgerow-26   -0.074427
Wet-a585_414_wetlands-20   -0.366551
Con-7997_10_mountains-28    0.952486
Pik-2f87_40_tundra-8       -0.150378
Gob-6481_46_waters-14      -0.492939
                              ...
Fir-3b5c_170_wetlands-4     0.179945
Wet-a585_317_wetland-8     -0.022698
Wet-a585_414_wetlands-12   -0.538117
Wal-cefe_43_Mountains-6    -0.628452
Amp-436a_68_swamps-19       0.066767
Name: x, Length: 209, dtype: float64
x0 token_id
Hed-8dc6_110_hedgerow-26   -0.074427
Wet-a585_414_wetlands-20   -0.366551
Con-7997_10_mountains-28    0.952486
Pik-2f87_40_tundra-8       -0.150378
Gob-6481_46_waters-14      -0.492939
                              ...
Fir-3b5c_170_wetlands-4     0.179945
Wet-a585_317_wetland-8     -0.022698
Wet-a585_414_wetlands-12   -0.538117
Wal-cefe_43_Mountains-6    -0.628452
Amp-436a_68_swamps-19       0.066767
Name: x, Length: 208, dtype: float64
x0 token_id
Hed-8dc6_110_hedgerow-26   -0.074427
Wet-a585_414_wetlands-20   -0.366551
Con-7997_10_mountains-28    0.952486
Pik-2f87_40_tundra-8       -0.150378
Gob-6481_46_waters-14      -0.492939
                              ...
Fir-3b5c_170_wetlands-4     0.179945
Wet-a585_317_wetland-8     -0.022698
Wet-a585_414_wetlands-12   -0.538117
Wal-cefe_43_Mountains-6    -0.628452
Amp-436a_68_swamps-19       0.066767
Name: x, Length: 208, dtype: float64
x0 token_id
Hed-8dc6_110_hedgerow-26   -0.074427
Wet-a585_414_wetlands-20   -0.366551
Pik-2f87_40_tundra-8       -0.150378
Gob-6481_46_waters-14      -0.492939
Moo-69c5_32_moorland-3     -0.733453
                              ...
Fir-3b5c_170_wetlands-4     0.179945
Wet-a585_317_wetland-8     -0.022698
Wet-a585_414_wetlands-12   -0.538117
Wal-cefe_43_Mountains-6    -0.628452
Amp-436a_68_swamps-19       0.066767
Name: x, Length: 208, dtype: float64
x0 token_id
Hed-8dc6_110_hedgerow-26   -0.074427
Wet-a585_414_wetlands-20   -0.366551
Con-7997_10_mountains-28    0.952486
Pik-2f87_40_tundra-8       -0.150378
Gob-6481_46_waters-14      -0.492939
                              ...
Fir-3b5c_170_wetlands-4     0.179945
Wet-a585_317_wetland-8     -0.022698
Wet-a585_414_wetlands-12   -0.538117
Wal-cefe_43_Mountains-6    -0.628452
Amp-436a_68_swamps-19       0.066767
Name: x, Length: 209, dtype: float64
x0 token_id
Hed-8dc6_110_hedgerow-26   -0.074427
Wet-a585_414_wetlands-20   -0.366551
Con-7997_10_mountains-28    0.952486
Pik-2f87_40_tundra-8       -0.150378
Gob-6481_46_waters-14      -0.492939
                              ...
Fir-3b5c_170_wetlands-4     0.179945
Wet-a585_317_wetland-8     -0.022698
Wet-a585_414_wetlands-12   -0.538117
Wal-cefe_43_Mountains-6    -0.628452
Amp-436a_68_swamps-19       0.066767
Name: x, Length: 207, dtype: float64
x0 token_id
Hed-8dc6_110_hedgerow-26   -0.074427
Wet-a585_414_wetlands-20   -0.366551
Con-7997_10_mountains-28    0.952486
Pik-2f87_40_tundra-8       -0.150378
Gob-6481_46_waters-14      -0.492939
                              ...
Fir-3b5c_170_wetlands-4     0.179945
Wet-a585_317_wetland-8     -0.022698
Wet-a585_414_wetlands-12   -0.538117
Wal-cefe_43_Mountains-6    -0.628452
Amp-436a_68_swamps-19       0.066767
Name: x, Length: 209, dtype: float64
x0 token_id
Hed-8dc6_110_hedgerow-26   -0.074427
Wet-a585_414_wetlands-20   -0.366551
Con-7997_10_mountains-28    0.952486
Pik-2f87_40_tundra-8       -0.150378
Gob-6481_46_waters-14      -0.492939
                              ...
Fir-3b5c_170_wetlands-4     0.179945
Wet-a585_317_wetland-8     -0.022698
Wet-a585_414_wetlands-12   -0.538117
Wal-cefe_43_Mountains-6    -0.628452
Amp-436a_68_swamps-19       0.066767
Name: x, Length: 205, dtype: float64
x0 token_id
Hed-8dc6_110_hedgerow-26   -0.074427
Wet-a585_414_wetlands-20   -0.366551
Con-7997_10_mountains-28    0.952486
Pik-2f87_40_tundra-8       -0.150378
Gob-6481_46_waters-14      -0.492939
                              ...
Fir-3b5c_170_wetlands-4     0.179945
Wet-a585_317_wetland-8     -0.022698
Wet-a585_414_wetlands-12   -0.538117
Wal-cefe_43_Mountains-6    -0.628452
Amp-436a_68_swamps-19       0.066767
Name: x, Length: 209, dtype: float64
x0 token_id
Hed-8dc6_110_hedgerow-26   -0.074427
Wet-a585_414_wetlands-20   -0.366551
Con-7997_10_mountains-28    0.952486
Pik-2f87_40_tundra-8       -0.150378
Gob-6481_46_waters-14      -0.492939
                              ...
Fir-3b5c_170_wetlands-4     0.179945
Wet-a585_317_wetland-8     -0.022698
Wet-a585_414_wetlands-12   -0.538117
Wal-cefe_43_Mountains-6    -0.628452
Amp-436a_68_swamps-19       0.066767
Name: x, Length: 209, dtype: float64
Spearman results
feat_tests
                                    test_pvalue  test_dX  test_Nx  test_N  \
arcpath                   lemma
appos<obl>det>            the           0.76084    0.149        1     210
compound<acl:relcl>nsubj> that          0.11506   -0.545        2     210
                          which         0.63122   -0.166        2     210
nmod<conj<amod>           dominant      0.00834    0.907        2     210
obl<                      feed          0.04257   -0.988        1     210
                          find          0.29431   -0.297        3     210
                          forage        0.29496   -0.512        1     210
                          live          0.03847   -0.455        5     210
                          make          0.11153   -0.776        1     210
                          occur         0.09442   -0.816        1     210

                                    test_st
arcpath                   lemma
appos<obl>det>            the          0.30
compound<acl:relcl>nsubj> that        -1.58
                          which       -0.48
nmod<conj<amod>           dominant     2.66
obl<                      feed        -2.04
                          find        -1.05
                          forage      -1.05
                          live        -2.08
                          make        -1.60
                          occur       -1.68
book_cl_elong
                                      effect        Dx  N      eff2  \
arcpath                   lemma
obl<                      make     -0.759692  0.001722  1  0.577132
                          feed     -0.735651  0.001261  1  0.541183
                          forage   -0.684577  0.001584  1  0.468646
                          live     -0.592173  0.004561  5  0.350669
                          find     -0.568601 -0.000098  3  0.323308
compound<acl:relcl>nsubj> that     -0.558342  0.003940  2  0.311746
                          which    -0.525087  0.003748  2  0.275717
obl<                      occur    -0.522854  0.000821  1  0.273376
nmod<conj<amod>           dominant  0.509687  0.004601  2  0.259781
appos<obl>det>            the       0.503726  0.001796  1  0.253740

                                    test_pvalue  test_dX  test_Nx  test_N  \
arcpath                   lemma
obl<                      make          0.11153   -0.776        1     210
                          feed          0.04257   -0.988        1     210
                          forage        0.29496   -0.512        1     210
                          live          0.03847   -0.455        5     210
                          find          0.29431   -0.297        3     210
compound<acl:relcl>nsubj> that          0.11506   -0.545        2     210
                          which         0.63122   -0.166        2     210
obl<                      occur         0.09442   -0.816        1     210
nmod<conj<amod>           dominant      0.00834    0.907        2     210
appos<obl>det>            the           0.76084    0.149        1     210

                                    test_st
arcpath                   lemma
obl<                      make        -1.60
                          feed        -2.04
                          forage      -1.05
                          live        -2.08
                          find        -1.05
compound<acl:relcl>nsubj> that        -1.58
                          which       -0.48
obl<                      occur       -1.68
nmod<conj<amod>           dominant     2.66
appos<obl>det>            the          0.30
cluster ====> 7
np.sqrt(eigvals)
[0.1246797  0.16354361 0.19176303 0.20664048 0.21915982 0.26667938
 0.31158947 0.69844967]
cl_elong_a, cl_elong_v.round(2)
2.2415701997979873 [-0.02 -0.52  0.29  0.7  -0.34  0.03  0.17  0.13]
cluster data sample, mean shift
(298, 8)                              0         1         2         3         4  \
token_id
Pol-a6a6_244_polar-2 -0.425371  0.472651 -0.470743 -0.265876 -0.056275
Pol-a6a6_52_polar-10  0.299271  0.263121 -0.887385  0.043711  0.084803
Tem-9c2f_17_forest-3  0.277066  0.093265 -0.296696  0.445920  0.308775

                             5         6         7
token_id
Pol-a6a6_244_polar-2  0.650114  0.058581 -0.221901
Pol-a6a6_52_polar-10 -0.079185 -0.003434  0.169732
Tem-9c2f_17_forest-3 -0.145912 -0.020935  0.028952
cluster data elongation along main axis
                              effect        Dx   N      eff2
arcpath         lemma
compound<obl<   find       -0.552531  0.002791   1  0.305290
                cool       -0.428090  0.007599   2  0.183261
compound<       locust      0.422474  0.064256  21  0.178484
                management  0.419384  0.003236   1  0.175883
                survival    0.418090  0.007599   2  0.174799
compound<acl>   take       -0.406814  0.003236   1  0.165497
compound<       climate     0.352014  0.002816   1  0.123914
parataxis>conj> biology    -0.350658  0.007599   2  0.122961
compound<       ecosystem   0.348898  0.005432   2  0.121730
appos>conj>cc>  and        -0.340305  0.027707   9  0.115807
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                               token         x
arcpath         lemma
appos>conj>cc>  and          Mou-ec99_122_Mountain-1 -0.668594
                and          Mou-ec99_128_Mountain-1 -0.668594
                and          Mou-ec99_144_Mountain-1 -0.668594
                and          Mou-ec99_149_Mountain-1 -0.668594
                and         Rai-7e47_63_Rainforest-1 -0.420458
                and             Tun-4bf6_61_Tundra-1 -0.069155
                and           Wet-a585_175_Wetland-1 -0.431782
                and           Wet-a585_196_Wetland-1 -0.431782
                and            Wet-a585_53_Wetland-1 -0.225027
compound<       climate         Tun-c63e_77_Tundra-1 -0.132658
                ecosystem    Coa-44f0_206_coastal-33  0.432165
                ecosystem     Coa-44f0_24_coastal-30  0.432165
                locust         Des-78ef_121_Desert-1  0.467563
                locust         Des-78ef_150_Desert-1  0.588991
                locust         Des-78ef_152_Desert-1  0.411164
                locust         Des-78ef_156_Desert-1  0.411164
                locust         Des-78ef_159_Desert-1  0.411164
                locust         Des-78ef_168_Desert-1  0.411164
                locust         Des-78ef_199_Desert-1  0.546031
                locust          Des-78ef_19_Desert-1  0.482667
                locust           Des-78ef_1_Desert-1  0.411164
                locust         Des-78ef_206_Desert-1  0.411164
                locust         Des-78ef_212_Desert-1  0.411164
                locust         Des-78ef_215_Desert-1  0.411164
                locust         Des-78ef_219_Desert-1  0.411164
                locust         Des-78ef_223_Desert-1  0.411164
                locust         Des-78ef_230_Desert-1  0.501178
                locust         Des-78ef_231_Desert-1  0.411164
                locust          Des-78ef_30_Desert-1  0.504499
                locust         Des-78ef_334_Desert-1  0.411164
                locust          Des-78ef_52_Desert-1  0.332599
                locust          Des-78ef_81_Desert-1  0.411164
                locust          Des-78ef_90_Desert-1  0.411164
                management     Coa-44f0_75_coastal-4  0.108618
                survival        Bha03bc_1_Mountain-1  0.405949
                survival        Mar2a6b_1_Mountain-1  0.405949
compound<acl>   take         Mou-9e66_46_mountain-28 -0.465798
compound<obl<   cool            Afr0164_48_desert-12  0.129859
                cool            Desbe19_49_desert-12  0.129859
                find             Wes-0eef_96_taiga-6 -0.572361
parataxis>conj> biology         Tun-4bf6_62_Tundra-1 -0.335349
                biology         Tun-4bf6_77_Tundra-1 -0.373411
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (298,)
ftok (42, 2)
x0 token_id
Pol-a6a6_244_polar-2    -0.536346
Pol-a6a6_52_polar-10    -0.380399
Tem-9c2f_17_forest-3     0.061396
Pol-a6a6_328_polar-23   -0.156765
Wes-9ef7_54_marsh-2      0.262457
                           ...
Tai-3286_269_Taiga-1     0.385329
Pol-a6a6_324_polar-12   -0.014064
Pol-a6a6_265_Polar-1    -0.110736
Car-fccf_103_polar-4     0.173199
Des-78ef_1_Desert-1      0.411164
Name: x, Length: 289, dtype: float64
x0 token_id
Pol-a6a6_244_polar-2    -0.536346
Pol-a6a6_52_polar-10    -0.380399
Tem-9c2f_17_forest-3     0.061396
Pol-a6a6_328_polar-23   -0.156765
Wes-9ef7_54_marsh-2      0.262457
                           ...
Tai-3286_269_Taiga-1     0.385329
Pol-a6a6_324_polar-12   -0.014064
Pol-a6a6_265_Polar-1    -0.110736
Car-fccf_103_polar-4     0.173199
Des-78ef_1_Desert-1      0.411164
Name: x, Length: 297, dtype: float64
x0 token_id
Pol-a6a6_244_polar-2    -0.536346
Pol-a6a6_52_polar-10    -0.380399
Tem-9c2f_17_forest-3     0.061396
Pol-a6a6_328_polar-23   -0.156765
Wes-9ef7_54_marsh-2      0.262457
                           ...
Tai-3286_269_Taiga-1     0.385329
Pol-a6a6_324_polar-12   -0.014064
Pol-a6a6_265_Polar-1    -0.110736
Car-fccf_103_polar-4     0.173199
Des-78ef_1_Desert-1      0.411164
Name: x, Length: 296, dtype: float64
x0 token_id
Pol-a6a6_244_polar-2    -0.536346
Pol-a6a6_52_polar-10    -0.380399
Tem-9c2f_17_forest-3     0.061396
Pol-a6a6_328_polar-23   -0.156765
Wes-9ef7_54_marsh-2      0.262457
                           ...
Pol-a6a6_157_Polar-1    -0.174915
Tai-3286_269_Taiga-1     0.385329
Pol-a6a6_324_polar-12   -0.014064
Pol-a6a6_265_Polar-1    -0.110736
Car-fccf_103_polar-4     0.173199
Name: x, Length: 277, dtype: float64
x0 token_id
Pol-a6a6_244_polar-2    -0.536346
Pol-a6a6_52_polar-10    -0.380399
Tem-9c2f_17_forest-3     0.061396
Pol-a6a6_328_polar-23   -0.156765
Wes-9ef7_54_marsh-2      0.262457
                           ...
Tai-3286_269_Taiga-1     0.385329
Pol-a6a6_324_polar-12   -0.014064
Pol-a6a6_265_Polar-1    -0.110736
Car-fccf_103_polar-4     0.173199
Des-78ef_1_Desert-1      0.411164
Name: x, Length: 297, dtype: float64
x0 token_id
Pol-a6a6_244_polar-2    -0.536346
Pol-a6a6_52_polar-10    -0.380399
Tem-9c2f_17_forest-3     0.061396
Pol-a6a6_328_polar-23   -0.156765
Wes-9ef7_54_marsh-2      0.262457
                           ...
Tai-3286_269_Taiga-1     0.385329
Pol-a6a6_324_polar-12   -0.014064
Pol-a6a6_265_Polar-1    -0.110736
Car-fccf_103_polar-4     0.173199
Des-78ef_1_Desert-1      0.411164
Name: x, Length: 296, dtype: float64
x0 token_id
Pol-a6a6_244_polar-2    -0.536346
Pol-a6a6_52_polar-10    -0.380399
Tem-9c2f_17_forest-3     0.061396
Pol-a6a6_328_polar-23   -0.156765
Wes-9ef7_54_marsh-2      0.262457
                           ...
Tai-3286_269_Taiga-1     0.385329
Pol-a6a6_324_polar-12   -0.014064
Pol-a6a6_265_Polar-1    -0.110736
Car-fccf_103_polar-4     0.173199
Des-78ef_1_Desert-1      0.411164
Name: x, Length: 297, dtype: float64
x0 token_id
Pol-a6a6_244_polar-2    -0.536346
Pol-a6a6_52_polar-10    -0.380399
Tem-9c2f_17_forest-3     0.061396
Pol-a6a6_328_polar-23   -0.156765
Wes-9ef7_54_marsh-2      0.262457
                           ...
Tai-3286_269_Taiga-1     0.385329
Pol-a6a6_324_polar-12   -0.014064
Pol-a6a6_265_Polar-1    -0.110736
Car-fccf_103_polar-4     0.173199
Des-78ef_1_Desert-1      0.411164
Name: x, Length: 296, dtype: float64
x0 token_id
Pol-a6a6_244_polar-2    -0.536346
Pol-a6a6_52_polar-10    -0.380399
Tem-9c2f_17_forest-3     0.061396
Pol-a6a6_328_polar-23   -0.156765
Wes-9ef7_54_marsh-2      0.262457
                           ...
Tai-3286_269_Taiga-1     0.385329
Pol-a6a6_324_polar-12   -0.014064
Pol-a6a6_265_Polar-1    -0.110736
Car-fccf_103_polar-4     0.173199
Des-78ef_1_Desert-1      0.411164
Name: x, Length: 297, dtype: float64
x0 token_id
Pol-a6a6_244_polar-2    -0.536346
Pol-a6a6_52_polar-10    -0.380399
Tem-9c2f_17_forest-3     0.061396
Pol-a6a6_328_polar-23   -0.156765
Wes-9ef7_54_marsh-2      0.262457
                           ...
Tai-3286_269_Taiga-1     0.385329
Pol-a6a6_324_polar-12   -0.014064
Pol-a6a6_265_Polar-1    -0.110736
Car-fccf_103_polar-4     0.173199
Des-78ef_1_Desert-1      0.411164
Name: x, Length: 296, dtype: float64
Spearman results
feat_tests
                            test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath         lemma
appos>conj>cc>  and             0.00006   -0.481        9     298    -4.06
compound<       climate         0.72469   -0.127        1     298    -0.35
                ecosystem       0.08276    0.441        2     298     1.74
                locust          0.00000    0.477       21     298     6.24
                management      0.74888    0.115        1     298     0.32
                survival        0.10296    0.415        2     298     1.64
compound<acl>   take            0.19980   -0.461        1     298    -1.29
compound<obl<   cool            0.59099    0.137        2     298     0.54
                find            0.11397   -0.568        1     298    -1.59
parataxis>conj> biology         0.16876   -0.350        2     298    -1.38
book_cl_elong
                              effect        Dx   N      eff2  test_pvalue  \
arcpath         lemma
compound<obl<   find       -0.552531  0.002791   1  0.305290      0.11397
compound<       locust      0.422474  0.064256  21  0.178484      0.00000
                management  0.419384  0.003236   1  0.175883      0.74888
                survival    0.418090  0.007599   2  0.174799      0.10296
compound<acl>   take       -0.406814  0.003236   1  0.165497      0.19980
parataxis>conj> biology    -0.350658  0.007599   2  0.122961      0.16876
compound<       ecosystem   0.348898  0.005432   2  0.121730      0.08276
appos>conj>cc>  and        -0.340305  0.027707   9  0.115807      0.00006

                            test_dX  test_Nx  test_N  test_st
arcpath         lemma
compound<obl<   find         -0.568        1     298    -1.59
compound<       locust        0.477       21     298     6.24
                management    0.115        1     298     0.32
                survival      0.415        2     298     1.64
compound<acl>   take         -0.461        1     298    -1.29
parataxis>conj> biology      -0.350        2     298    -1.38
compound<       ecosystem     0.441        2     298     1.74
appos>conj>cc>  and          -0.481        9     298    -4.06
cluster ====> 8
np.sqrt(eigvals)
[0.51199872 0.70826522 0.78818508 0.87480017 0.93632018 1.12229924
 1.2117351  1.88714029]
cl_elong_a, cl_elong_v.round(2)
1.5573868350919267 [ 0.03 -0.22  0.05  0.05  0.1  -0.07 -0.04 -0.96]
cluster data sample, mean shift
(197, 8)                                 0         1         2         3         4  \
token_id
Bea-4f7a_7_rivers-14    -0.384940 -1.466852  0.176949  0.324627  2.085342
Eur-24a9_86_wetlands-24 -0.552838  0.637599  1.147024 -0.464877 -0.781994
Con-7997_194_taiga-15    1.554224  0.808101  0.110463 -0.168180 -0.358400

                                5         6         7
token_id
Bea-4f7a_7_rivers-14    -0.327042  0.272402  0.283390
Eur-24a9_86_wetlands-24 -0.128994  0.083213 -1.428177
Con-7997_194_taiga-15    1.716624  0.966197  1.042919
cluster data elongation along main axis
                     effect        Dx   N      eff2
arcpath lemma
conj>   savannah   0.958746  0.003018   2  0.919195
        savanna    0.936385  0.000752   2  0.876818
        tundra     0.936108  0.003018   2  0.876298
        woodland   0.928873  0.004867   4  0.862805
        habitat    0.926233  0.003606   3  0.857908
        forest     0.922231  0.005895   5  0.850510
        wetland    0.906282  0.003488   3  0.821346
        marsh      0.904972  0.019233  13  0.818974
        mangrove   0.903278  0.001202   1  0.815911
        grassland  0.902663  0.005290   5  0.814801
Compute the feature-associated token x1 positions (ftok) on the projected axis

/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

ftok
                                       token         x
arcpath lemma
conj>   forest         Dee-529a_26_forest-16  1.168513
        forest      Bot-5a32_69_rainforest-5  0.507644
        forest      Eas-e034_29_rainforest-8  0.333314
        forest         Rei-38eb_18_tundra-21  1.210816
        forest     Sil-6383_70_rainforest-13 -0.361352
        grassland   Tem-2c3b_20_grasslands-2  4.735490
        grassland    Viv-ac84_39_heathland-5  1.584542
        grassland     Nor-d815_32_moorland-7  6.705596
        grassland    Bar-78df_97_farmland-13 -0.859676
        grassland       Gun-5a73_34_desert-7  3.098544
        habitat          Com-0bc9_48_bogs-12  0.658632
        habitat     Com-9711_207_mountain-17  2.366461
        habitat        Dee-529a_26_forest-16  1.168513
        mangrove    Wet-a585_154_estuaries-5 -0.120829
        marsh           Cap-5548_41_lakes-14  5.972397
        marsh        Eur-be6c_26_farmland-10  1.453675
        marsh       Sto-c148_89_grasslands-5  5.088282
        marsh            Dro-4d9f_129_bogs-4  4.981253
        marsh         Fir-3b5c_174_marshes-9  3.175528
        marsh            Gre-acd6_4_lakes-12  1.724036
        marsh           Lit-0303_48_lakes-14  3.470445
        marsh           Man-7999_41_lakes-14  1.164219
        marsh         Nor-d815_32_moorland-7  6.705596
        marsh          Sho-489b_76_swamps-11  0.006542
        marsh          Sia-9432_15_rivers-16  2.438374
        marsh           Wesd1a0_8_moorland-5  2.734745
        marsh           Yel-2b33_18_swamps-8  1.620370
        savanna      Com-a681_63_wetlands-26  1.030907
        savanna     Tem-2c3b_20_grasslands-2  4.735490
        savannah        Cap-5548_41_lakes-14  5.972397
        savannah     Eur-be6c_26_farmland-10  1.453675
        tundra          Lon-b0af_686_bogs-27  0.438307
        tundra       Poa-a930_13_wetlands-16  0.992401
        wetland         Com-0e01_4_marshes-9  1.362431
        wetland         Jag-fac8_8_forest-22  0.589916
        wetland         Sir-1b7d_2_swamps-26  3.630195
        woodland       Bla0b20_4_hedgerows-9  0.485513
        woodland    Gol-1dbf_229_mountains-7  1.231395
        woodland    Sto-c148_89_grasslands-5  5.088282
        woodland     Viv-ac84_39_heathland-5  1.584542
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (197,)
ftok (40, 2)
x0 token_id
Bea-4f7a_7_rivers-14        0.275204
Eur-24a9_86_wetlands-24     1.192079
Con-7997_194_taiga-15      -1.344012
Arc-00d6_22_tundra-12       0.153361
Eur-987c_28_rivers-14       1.219017
                              ...
Gol-1dbf_262_wetlands-24    0.557947
Lit-0303_48_lakes-14        3.470445
Sol-e070_77_deserts-14      0.994014
Wet-a585_281_wetland-13    -1.607081
Gre-0f9b_52_lakes-33        1.580898
Name: x, Length: 192, dtype: float64
x0 token_id
Bea-4f7a_7_rivers-14        0.275204
Eur-24a9_86_wetlands-24     1.192079
Con-7997_194_taiga-15      -1.344012
Arc-00d6_22_tundra-12       0.153361
Eur-987c_28_rivers-14       1.219017
                              ...
Gol-1dbf_262_wetlands-24    0.557947
Lit-0303_48_lakes-14        3.470445
Sol-e070_77_deserts-14      0.994014
Wet-a585_281_wetland-13    -1.607081
Gre-0f9b_52_lakes-33        1.580898
Name: x, Length: 192, dtype: float64
x0 token_id
Bea-4f7a_7_rivers-14        0.275204
Eur-24a9_86_wetlands-24     1.192079
Con-7997_194_taiga-15      -1.344012
Arc-00d6_22_tundra-12       0.153361
Eur-987c_28_rivers-14       1.219017
                              ...
Gol-1dbf_262_wetlands-24    0.557947
Lit-0303_48_lakes-14        3.470445
Sol-e070_77_deserts-14      0.994014
Wet-a585_281_wetland-13    -1.607081
Gre-0f9b_52_lakes-33        1.580898
Name: x, Length: 194, dtype: float64
x0 token_id
Bea-4f7a_7_rivers-14        0.275204
Eur-24a9_86_wetlands-24     1.192079
Con-7997_194_taiga-15      -1.344012
Arc-00d6_22_tundra-12       0.153361
Eur-987c_28_rivers-14       1.219017
                              ...
Gol-1dbf_262_wetlands-24    0.557947
Lit-0303_48_lakes-14        3.470445
Sol-e070_77_deserts-14      0.994014
Wet-a585_281_wetland-13    -1.607081
Gre-0f9b_52_lakes-33        1.580898
Name: x, Length: 196, dtype: float64
x0 token_id
Bea-4f7a_7_rivers-14        0.275204
Eur-24a9_86_wetlands-24     1.192079
Con-7997_194_taiga-15      -1.344012
Arc-00d6_22_tundra-12       0.153361
Eur-987c_28_rivers-14       1.219017
                              ...
Asi-f65e_10_grasslands-4    5.093346
Gol-1dbf_262_wetlands-24    0.557947
Sol-e070_77_deserts-14      0.994014
Wet-a585_281_wetland-13    -1.607081
Gre-0f9b_52_lakes-33        1.580898
Name: x, Length: 184, dtype: float64
x0 token_id
Bea-4f7a_7_rivers-14        0.275204
Eur-24a9_86_wetlands-24     1.192079
Con-7997_194_taiga-15      -1.344012
Arc-00d6_22_tundra-12       0.153361
Eur-987c_28_rivers-14       1.219017
                              ...
Gol-1dbf_262_wetlands-24    0.557947
Lit-0303_48_lakes-14        3.470445
Sol-e070_77_deserts-14      0.994014
Wet-a585_281_wetland-13    -1.607081
Gre-0f9b_52_lakes-33        1.580898
Name: x, Length: 195, dtype: float64
x0 token_id
Bea-4f7a_7_rivers-14        0.275204
Eur-24a9_86_wetlands-24     1.192079
Con-7997_194_taiga-15      -1.344012
Arc-00d6_22_tundra-12       0.153361
Eur-987c_28_rivers-14       1.219017
                              ...
Gol-1dbf_262_wetlands-24    0.557947
Lit-0303_48_lakes-14        3.470445
Sol-e070_77_deserts-14      0.994014
Wet-a585_281_wetland-13    -1.607081
Gre-0f9b_52_lakes-33        1.580898
Name: x, Length: 195, dtype: float64
x0 token_id
Bea-4f7a_7_rivers-14        0.275204
Eur-24a9_86_wetlands-24     1.192079
Con-7997_194_taiga-15      -1.344012
Arc-00d6_22_tundra-12       0.153361
Eur-987c_28_rivers-14       1.219017
                              ...
Gol-1dbf_262_wetlands-24    0.557947
Lit-0303_48_lakes-14        3.470445
Sol-e070_77_deserts-14      0.994014
Wet-a585_281_wetland-13    -1.607081
Gre-0f9b_52_lakes-33        1.580898
Name: x, Length: 195, dtype: float64
x0 token_id
Bea-4f7a_7_rivers-14        0.275204
Eur-24a9_86_wetlands-24     1.192079
Con-7997_194_taiga-15      -1.344012
Arc-00d6_22_tundra-12       0.153361
Eur-987c_28_rivers-14       1.219017
                              ...
Gol-1dbf_262_wetlands-24    0.557947
Lit-0303_48_lakes-14        3.470445
Sol-e070_77_deserts-14      0.994014
Wet-a585_281_wetland-13    -1.607081
Gre-0f9b_52_lakes-33        1.580898
Name: x, Length: 194, dtype: float64
x0 token_id
Bea-4f7a_7_rivers-14        0.275204
Eur-24a9_86_wetlands-24     1.192079
Con-7997_194_taiga-15      -1.344012
Arc-00d6_22_tundra-12       0.153361
Eur-987c_28_rivers-14       1.219017
                              ...
Gol-1dbf_262_wetlands-24    0.557947
Lit-0303_48_lakes-14        3.470445
Sol-e070_77_deserts-14      0.994014
Wet-a585_281_wetland-13    -1.607081
Gre-0f9b_52_lakes-33        1.580898
Name: x, Length: 193, dtype: float64
Spearman results
feat_tests
                   test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath lemma
conj>   forest         0.60862    0.429        5     197     0.51
        grassland      0.00031    2.975        5     197     3.68
        habitat        0.23956    1.263        3     197     1.18
        mangrove       0.88166   -0.276        1     197    -0.15
        marsh          0.00000    3.174       13     197     6.63
        savanna        0.03489    2.757        2     197     2.12
        savannah       0.00574    3.596        2     197     2.79
        tundra         0.66598    0.567        2     197     0.43
        wetland        0.10602    1.733        3     197     1.62
        woodland       0.03269    1.984        4     197     2.15
book_cl_elong
                     effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath lemma
conj>   savannah   0.958746  0.003018   2  0.919195      0.00574    3.596
        savanna    0.936385  0.000752   2  0.876818      0.03489    2.757
        tundra     0.936108  0.003018   2  0.876298      0.66598    0.567
        woodland   0.928873  0.004867   4  0.862805      0.03269    1.984
        habitat    0.926233  0.003606   3  0.857908      0.23956    1.263
        forest     0.922231  0.005895   5  0.850510      0.60862    0.429
        wetland    0.906282  0.003488   3  0.821346      0.10602    1.733
        marsh      0.904972  0.019233  13  0.818974      0.00000    3.174
        grassland  0.902663  0.005290   5  0.814801      0.00031    2.975

                   test_Nx  test_N  test_st
arcpath lemma
conj>   savannah         2     197     2.79
        savanna          2     197     2.12
        tundra           2     197     0.43
        woodland         4     197     2.15
        habitat          3     197     1.18
        forest           5     197     0.51
        wetland          3     197     1.62
        marsh           13     197     6.63
        grassland        5     197     3.68
cluster ====> 9
np.sqrt(eigvals)
[0.20395264 0.25812594 0.30804611 0.42069017 0.52314772 0.54772944
 0.96422968 2.26168429]
cl_elong_a, cl_elong_v.round(2)
2.3455866773902088 [ 0.9   0.08 -0.24 -0.23 -0.06 -0.12  0.16  0.17]
cluster data sample, mean shift
(36, 8)                                  0         1         2         3         4  \
token_id
Sno-0a8f_453_mountain-30  0.609891 -0.600948  1.050482 -0.038583 -1.278934
Cou-56f5_112_mountain-19  0.433213  0.842222  0.940424 -0.033831 -0.020506
Wet-a585_281_wetlands-2   0.569399 -0.863389 -1.622035  0.525186 -0.491934

                                 5         6         7
token_id
Sno-0a8f_453_mountain-30  1.207009  0.522214  0.306517
Cou-56f5_112_mountain-19 -0.242203  0.293900 -0.153941
Wet-a585_281_wetlands-2  -1.754326 -0.779548 -0.327872
cluster data elongation along main axis
                                     effect        Dx  N      eff2
arcpath                 lemma
nmod>                   m          0.541688  0.005924  1  0.293426
compound<conj<obj<      include    0.448565  0.040005  4  0.201211
compound<conj<obl>      pellet     0.369162  0.020651  2  0.136280
                        rabbit     0.351332  0.020651  2  0.123434
det>                    the        0.333372 -0.009228  5  0.111137
compound<conj<obl>      Knockando  0.318007  0.020651  2  0.101128
nsubj:pass<aux:pass>    be         0.252014  0.072651  8  0.063511
compound<conj<nsubj>    these     -0.245436  0.020651  2  0.060239
compound<compound<case> of        -0.237975  0.007448  1  0.056632
compound<conj<conj>     ree        0.227317  0.020651  2  0.051673
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                                      token         x
arcpath                 lemma
compound<compound<case> of            Rei-38eb_93_tundra-21 -1.321120
compound<conj<conj>     ree            Acr-39bb_17_swamp-58  0.644866
                        ree            Acr-39bb_17_swamp-64  0.598261
compound<conj<nsubj>    these           Mar-80c6_8_marsh-13 -0.757045
                        these           Mar-80c6_8_marsh-50 -0.678740
compound<conj<obj<      include     Gre-e288_95_mountain-35  1.172804
                        include          Req-2240_3_reef-42  0.202021
                        include          Req-2240_3_reef-46  0.164209
                        include          Req-2240_3_reef-67  0.162107
compound<conj<obl>      Knockando  Sno-0a8f_453_mountain-30  0.338141
                        Knockando  Sno-0a8f_453_mountain-96  0.215397
                        pellet     Sno-0a8f_453_mountain-30  0.338141
                        pellet     Sno-0a8f_453_mountain-96  0.215397
                        rabbit     Sno-0a8f_453_mountain-30  0.338141
                        rabbit     Sno-0a8f_453_mountain-96  0.215397
det>                    the        Bla-b48c_36_Mountains-31  0.130720
                        the             Int-c24a_25_zone-11  0.573482
                        the              Tid-b2db_80_zone-3  0.494964
                        the        Wet-a585_296_wetlands-30  0.754131
                        the          Wet-a585_370_wetland-5  0.015770
nmod>                   m          Cho-a88d_33_mountains-10  1.552074
nsubj:pass<aux:pass>    be              Int-c24a_25_zone-11  0.573482
                        be               Tid-b2db_80_zone-3  0.494964
                        be         Wet-a585_296_wetlands-30  0.754131
                        be           Wet-a585_370_wetland-5  0.015770
                        be          Mon37b6_16_mountains-16  0.461244
                        be                 Oakb84d_6_wood-2  0.351237
                        be         Ulm-8a7b_61_hedgerows-10 -0.025204
                        be          Wet-a585_281_wetlands-2  0.774261
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (36,)
ftok (29, 2)
x0 token_id
Sno-0a8f_453_mountain-30    0.338141
Cou-56f5_112_mountain-19    0.284384
Wet-a585_281_wetlands-2     0.774261
Sno-0a8f_453_mountain-96    0.215397
Whi-b4c3_527_marsh-26      -0.556285
Req-2240_3_reef-67          0.162107
Wet-a585_370_wetland-5      0.015770
Wet-a585_296_wetlands-30    0.754131
Che-369e_284_desert-11     -0.056715
Pel-a6d1_192_coastal-15    -0.833529
Mou-9e66_2_tundra-15        0.148998
Sno-0a8f_462_mountain-34   -0.143813
Red-1eff_89_wetland-14      0.101444
Int-c24a_25_zone-11         0.573482
Bla-b48c_36_Mountains-31    0.130720
Gal-0153_156_mountain-26   -0.534091
Mon37b6_16_mountains-16     0.461244
Pra-7b55_153_mountain-13   -0.329865
Pin-2e32_100_mountain-19    0.060735
Oakb84d_6_wood-2            0.351237
Mar-80c6_8_marsh-13        -0.757045
Gre-e288_95_mountain-35     1.172804
Ulm-8a7b_61_hedgerows-10   -0.025204
Wes-0eef_55_taiga-10       -0.654822
Acr-39bb_17_swamp-58        0.644866
Cho-a88d_33_mountains-10    1.552074
Req-2240_3_reef-46          0.164209
Tid-b2db_80_zone-3          0.494964
Req-2240_3_reef-42          0.202021
Mar-80c6_8_marsh-50        -0.678740
Pra-7b55_11_mountain-13    -0.329865
Per-145f_241_mountain-43   -0.893171
Acr-39bb_17_swamp-64        0.598261
Eas-550c_122_mountain-46   -0.598360
Pum-f726_49_mountain-18    -0.202579
Name: x, dtype: float64
x0 token_id
Sno-0a8f_453_mountain-30    0.338141
Cou-56f5_112_mountain-19    0.284384
Wet-a585_281_wetlands-2     0.774261
Sno-0a8f_453_mountain-96    0.215397
Whi-b4c3_527_marsh-26      -0.556285
Req-2240_3_reef-67          0.162107
Wet-a585_370_wetland-5      0.015770
Wet-a585_296_wetlands-30    0.754131
Che-369e_284_desert-11     -0.056715
Pel-a6d1_192_coastal-15    -0.833529
Mou-9e66_2_tundra-15        0.148998
Sno-0a8f_462_mountain-34   -0.143813
Red-1eff_89_wetland-14      0.101444
Int-c24a_25_zone-11         0.573482
Bla-b48c_36_Mountains-31    0.130720
Gal-0153_156_mountain-26   -0.534091
Rei-38eb_93_tundra-21      -1.321120
Mon37b6_16_mountains-16     0.461244
Pra-7b55_153_mountain-13   -0.329865
Pin-2e32_100_mountain-19    0.060735
Oakb84d_6_wood-2            0.351237
Mar-80c6_8_marsh-13        -0.757045
Gre-e288_95_mountain-35     1.172804
Ulm-8a7b_61_hedgerows-10   -0.025204
Wes-0eef_55_taiga-10       -0.654822
Cho-a88d_33_mountains-10    1.552074
Req-2240_3_reef-46          0.164209
Tid-b2db_80_zone-3          0.494964
Req-2240_3_reef-42          0.202021
Mar-80c6_8_marsh-50        -0.678740
Pra-7b55_11_mountain-13    -0.329865
Per-145f_241_mountain-43   -0.893171
Eas-550c_122_mountain-46   -0.598360
Pum-f726_49_mountain-18    -0.202579
Name: x, dtype: float64
x0 token_id
Sno-0a8f_453_mountain-30    0.338141
Cou-56f5_112_mountain-19    0.284384
Wet-a585_281_wetlands-2     0.774261
Sno-0a8f_453_mountain-96    0.215397
Whi-b4c3_527_marsh-26      -0.556285
Req-2240_3_reef-67          0.162107
Wet-a585_370_wetland-5      0.015770
Wet-a585_296_wetlands-30    0.754131
Che-369e_284_desert-11     -0.056715
Pel-a6d1_192_coastal-15    -0.833529
Mou-9e66_2_tundra-15        0.148998
Sno-0a8f_462_mountain-34   -0.143813
Red-1eff_89_wetland-14      0.101444
Int-c24a_25_zone-11         0.573482
Bla-b48c_36_Mountains-31    0.130720
Gal-0153_156_mountain-26   -0.534091
Rei-38eb_93_tundra-21      -1.321120
Mon37b6_16_mountains-16     0.461244
Pra-7b55_153_mountain-13   -0.329865
Pin-2e32_100_mountain-19    0.060735
Oakb84d_6_wood-2            0.351237
Gre-e288_95_mountain-35     1.172804
Ulm-8a7b_61_hedgerows-10   -0.025204
Wes-0eef_55_taiga-10       -0.654822
Acr-39bb_17_swamp-58        0.644866
Cho-a88d_33_mountains-10    1.552074
Req-2240_3_reef-46          0.164209
Tid-b2db_80_zone-3          0.494964
Req-2240_3_reef-42          0.202021
Pra-7b55_11_mountain-13    -0.329865
Per-145f_241_mountain-43   -0.893171
Acr-39bb_17_swamp-64        0.598261
Eas-550c_122_mountain-46   -0.598360
Pum-f726_49_mountain-18    -0.202579
Name: x, dtype: float64
x0 token_id
Sno-0a8f_453_mountain-30    0.338141
Cou-56f5_112_mountain-19    0.284384
Wet-a585_281_wetlands-2     0.774261
Sno-0a8f_453_mountain-96    0.215397
Whi-b4c3_527_marsh-26      -0.556285
Wet-a585_370_wetland-5      0.015770
Wet-a585_296_wetlands-30    0.754131
Che-369e_284_desert-11     -0.056715
Pel-a6d1_192_coastal-15    -0.833529
Mou-9e66_2_tundra-15        0.148998
Sno-0a8f_462_mountain-34   -0.143813
Red-1eff_89_wetland-14      0.101444
Int-c24a_25_zone-11         0.573482
Bla-b48c_36_Mountains-31    0.130720
Gal-0153_156_mountain-26   -0.534091
Rei-38eb_93_tundra-21      -1.321120
Mon37b6_16_mountains-16     0.461244
Pra-7b55_153_mountain-13   -0.329865
Pin-2e32_100_mountain-19    0.060735
Oakb84d_6_wood-2            0.351237
Mar-80c6_8_marsh-13        -0.757045
Ulm-8a7b_61_hedgerows-10   -0.025204
Wes-0eef_55_taiga-10       -0.654822
Acr-39bb_17_swamp-58        0.644866
Cho-a88d_33_mountains-10    1.552074
Tid-b2db_80_zone-3          0.494964
Mar-80c6_8_marsh-50        -0.678740
Pra-7b55_11_mountain-13    -0.329865
Per-145f_241_mountain-43   -0.893171
Acr-39bb_17_swamp-64        0.598261
Eas-550c_122_mountain-46   -0.598360
Pum-f726_49_mountain-18    -0.202579
Name: x, dtype: float64
x0 token_id
Cou-56f5_112_mountain-19    0.284384
Wet-a585_281_wetlands-2     0.774261
Whi-b4c3_527_marsh-26      -0.556285
Req-2240_3_reef-67          0.162107
Wet-a585_370_wetland-5      0.015770
Wet-a585_296_wetlands-30    0.754131
Che-369e_284_desert-11     -0.056715
Pel-a6d1_192_coastal-15    -0.833529
Mou-9e66_2_tundra-15        0.148998
Sno-0a8f_462_mountain-34   -0.143813
Red-1eff_89_wetland-14      0.101444
Int-c24a_25_zone-11         0.573482
Bla-b48c_36_Mountains-31    0.130720
Gal-0153_156_mountain-26   -0.534091
Rei-38eb_93_tundra-21      -1.321120
Mon37b6_16_mountains-16     0.461244
Pra-7b55_153_mountain-13   -0.329865
Pin-2e32_100_mountain-19    0.060735
Oakb84d_6_wood-2            0.351237
Mar-80c6_8_marsh-13        -0.757045
Gre-e288_95_mountain-35     1.172804
Ulm-8a7b_61_hedgerows-10   -0.025204
Wes-0eef_55_taiga-10       -0.654822
Acr-39bb_17_swamp-58        0.644866
Cho-a88d_33_mountains-10    1.552074
Req-2240_3_reef-46          0.164209
Tid-b2db_80_zone-3          0.494964
Req-2240_3_reef-42          0.202021
Mar-80c6_8_marsh-50        -0.678740
Pra-7b55_11_mountain-13    -0.329865
Per-145f_241_mountain-43   -0.893171
Acr-39bb_17_swamp-64        0.598261
Eas-550c_122_mountain-46   -0.598360
Pum-f726_49_mountain-18    -0.202579
Name: x, dtype: float64
x0 token_id
Cou-56f5_112_mountain-19    0.284384
Wet-a585_281_wetlands-2     0.774261
Whi-b4c3_527_marsh-26      -0.556285
Req-2240_3_reef-67          0.162107
Wet-a585_370_wetland-5      0.015770
Wet-a585_296_wetlands-30    0.754131
Che-369e_284_desert-11     -0.056715
Pel-a6d1_192_coastal-15    -0.833529
Mou-9e66_2_tundra-15        0.148998
Sno-0a8f_462_mountain-34   -0.143813
Red-1eff_89_wetland-14      0.101444
Int-c24a_25_zone-11         0.573482
Bla-b48c_36_Mountains-31    0.130720
Gal-0153_156_mountain-26   -0.534091
Rei-38eb_93_tundra-21      -1.321120
Mon37b6_16_mountains-16     0.461244
Pra-7b55_153_mountain-13   -0.329865
Pin-2e32_100_mountain-19    0.060735
Oakb84d_6_wood-2            0.351237
Mar-80c6_8_marsh-13        -0.757045
Gre-e288_95_mountain-35     1.172804
Ulm-8a7b_61_hedgerows-10   -0.025204
Wes-0eef_55_taiga-10       -0.654822
Acr-39bb_17_swamp-58        0.644866
Cho-a88d_33_mountains-10    1.552074
Req-2240_3_reef-46          0.164209
Tid-b2db_80_zone-3          0.494964
Req-2240_3_reef-42          0.202021
Mar-80c6_8_marsh-50        -0.678740
Pra-7b55_11_mountain-13    -0.329865
Per-145f_241_mountain-43   -0.893171
Acr-39bb_17_swamp-64        0.598261
Eas-550c_122_mountain-46   -0.598360
Pum-f726_49_mountain-18    -0.202579
Name: x, dtype: float64
x0 token_id
Cou-56f5_112_mountain-19    0.284384
Wet-a585_281_wetlands-2     0.774261
Whi-b4c3_527_marsh-26      -0.556285
Req-2240_3_reef-67          0.162107
Wet-a585_370_wetland-5      0.015770
Wet-a585_296_wetlands-30    0.754131
Che-369e_284_desert-11     -0.056715
Pel-a6d1_192_coastal-15    -0.833529
Mou-9e66_2_tundra-15        0.148998
Sno-0a8f_462_mountain-34   -0.143813
Red-1eff_89_wetland-14      0.101444
Int-c24a_25_zone-11         0.573482
Bla-b48c_36_Mountains-31    0.130720
Gal-0153_156_mountain-26   -0.534091
Rei-38eb_93_tundra-21      -1.321120
Mon37b6_16_mountains-16     0.461244
Pra-7b55_153_mountain-13   -0.329865
Pin-2e32_100_mountain-19    0.060735
Oakb84d_6_wood-2            0.351237
Mar-80c6_8_marsh-13        -0.757045
Gre-e288_95_mountain-35     1.172804
Ulm-8a7b_61_hedgerows-10   -0.025204
Wes-0eef_55_taiga-10       -0.654822
Acr-39bb_17_swamp-58        0.644866
Cho-a88d_33_mountains-10    1.552074
Req-2240_3_reef-46          0.164209
Tid-b2db_80_zone-3          0.494964
Req-2240_3_reef-42          0.202021
Mar-80c6_8_marsh-50        -0.678740
Pra-7b55_11_mountain-13    -0.329865
Per-145f_241_mountain-43   -0.893171
Acr-39bb_17_swamp-64        0.598261
Eas-550c_122_mountain-46   -0.598360
Pum-f726_49_mountain-18    -0.202579
Name: x, dtype: float64
x0 token_id
Sno-0a8f_453_mountain-30    0.338141
Cou-56f5_112_mountain-19    0.284384
Wet-a585_281_wetlands-2     0.774261
Sno-0a8f_453_mountain-96    0.215397
Whi-b4c3_527_marsh-26      -0.556285
Req-2240_3_reef-67          0.162107
Che-369e_284_desert-11     -0.056715
Pel-a6d1_192_coastal-15    -0.833529
Mou-9e66_2_tundra-15        0.148998
Sno-0a8f_462_mountain-34   -0.143813
Red-1eff_89_wetland-14      0.101444
Gal-0153_156_mountain-26   -0.534091
Rei-38eb_93_tundra-21      -1.321120
Mon37b6_16_mountains-16     0.461244
Pra-7b55_153_mountain-13   -0.329865
Pin-2e32_100_mountain-19    0.060735
Oakb84d_6_wood-2            0.351237
Mar-80c6_8_marsh-13        -0.757045
Gre-e288_95_mountain-35     1.172804
Ulm-8a7b_61_hedgerows-10   -0.025204
Wes-0eef_55_taiga-10       -0.654822
Acr-39bb_17_swamp-58        0.644866
Cho-a88d_33_mountains-10    1.552074
Req-2240_3_reef-46          0.164209
Req-2240_3_reef-42          0.202021
Mar-80c6_8_marsh-50        -0.678740
Pra-7b55_11_mountain-13    -0.329865
Per-145f_241_mountain-43   -0.893171
Acr-39bb_17_swamp-64        0.598261
Eas-550c_122_mountain-46   -0.598360
Pum-f726_49_mountain-18    -0.202579
Name: x, dtype: float64
x0 token_id
Sno-0a8f_453_mountain-30    0.338141
Cou-56f5_112_mountain-19    0.284384
Wet-a585_281_wetlands-2     0.774261
Sno-0a8f_453_mountain-96    0.215397
Whi-b4c3_527_marsh-26      -0.556285
Req-2240_3_reef-67          0.162107
Wet-a585_370_wetland-5      0.015770
Wet-a585_296_wetlands-30    0.754131
Che-369e_284_desert-11     -0.056715
Pel-a6d1_192_coastal-15    -0.833529
Mou-9e66_2_tundra-15        0.148998
Sno-0a8f_462_mountain-34   -0.143813
Red-1eff_89_wetland-14      0.101444
Int-c24a_25_zone-11         0.573482
Bla-b48c_36_Mountains-31    0.130720
Gal-0153_156_mountain-26   -0.534091
Rei-38eb_93_tundra-21      -1.321120
Mon37b6_16_mountains-16     0.461244
Pra-7b55_153_mountain-13   -0.329865
Pin-2e32_100_mountain-19    0.060735
Oakb84d_6_wood-2            0.351237
Mar-80c6_8_marsh-13        -0.757045
Gre-e288_95_mountain-35     1.172804
Ulm-8a7b_61_hedgerows-10   -0.025204
Wes-0eef_55_taiga-10       -0.654822
Acr-39bb_17_swamp-58        0.644866
Req-2240_3_reef-46          0.164209
Tid-b2db_80_zone-3          0.494964
Req-2240_3_reef-42          0.202021
Mar-80c6_8_marsh-50        -0.678740
Pra-7b55_11_mountain-13    -0.329865
Per-145f_241_mountain-43   -0.893171
Acr-39bb_17_swamp-64        0.598261
Eas-550c_122_mountain-46   -0.598360
Pum-f726_49_mountain-18    -0.202579
Name: x, dtype: float64
x0 token_id
Sno-0a8f_453_mountain-30    0.338141
Cou-56f5_112_mountain-19    0.284384
Sno-0a8f_453_mountain-96    0.215397
Whi-b4c3_527_marsh-26      -0.556285
Req-2240_3_reef-67          0.162107
Che-369e_284_desert-11     -0.056715
Pel-a6d1_192_coastal-15    -0.833529
Mou-9e66_2_tundra-15        0.148998
Sno-0a8f_462_mountain-34   -0.143813
Red-1eff_89_wetland-14      0.101444
Bla-b48c_36_Mountains-31    0.130720
Gal-0153_156_mountain-26   -0.534091
Rei-38eb_93_tundra-21      -1.321120
Pra-7b55_153_mountain-13   -0.329865
Pin-2e32_100_mountain-19    0.060735
Mar-80c6_8_marsh-13        -0.757045
Gre-e288_95_mountain-35     1.172804
Wes-0eef_55_taiga-10       -0.654822
Acr-39bb_17_swamp-58        0.644866
Cho-a88d_33_mountains-10    1.552074
Req-2240_3_reef-46          0.164209
Req-2240_3_reef-42          0.202021
Mar-80c6_8_marsh-50        -0.678740
Pra-7b55_11_mountain-13    -0.329865
Per-145f_241_mountain-43   -0.893171
Acr-39bb_17_swamp-64        0.598261
Eas-550c_122_mountain-46   -0.598360
Pum-f726_49_mountain-18    -0.202579
Name: x, dtype: float64
Spearman results
feat_tests
                                   test_pvalue  test_dX  test_Nx  test_N  \
arcpath                 lemma
compound<compound<case> of             0.02117   -1.396        1      36
compound<conj<conj>     ree            0.16361    0.620        2      36
compound<conj<nsubj>    these          0.07034   -0.798        2      36
compound<conj<obj<      include        0.17730    0.438        4      36
compound<conj<obl>      Knockando      0.57119    0.255        2      36
                        pellet         0.57119    0.255        2      36
                        rabbit         0.57119    0.255        2      36
det>                    the            0.15840    0.416        5      36
nmod>                   m              0.00923    1.560        1      36
nsubj:pass<aux:pass>    be             0.03791    0.500        8      36

                                   test_st
arcpath                 lemma
compound<compound<case> of           -2.42
compound<conj<conj>     ree           1.42
compound<conj<nsubj>    these        -1.87
compound<conj<obj<      include       1.38
compound<conj<obl>      Knockando     0.57
                        pellet        0.57
                        rabbit        0.57
det>                    the           1.44
nmod>                   m             2.76
nsubj:pass<aux:pass>    be            2.16
book_cl_elong
                                     effect        Dx  N      eff2  \
arcpath                 lemma
nmod>                   m          0.541688  0.005924  1  0.293426
compound<conj<obj<      include    0.448565  0.040005  4  0.201211
compound<conj<obl>      pellet     0.369162  0.020651  2  0.136280
                        rabbit     0.351332  0.020651  2  0.123434
det>                    the        0.333372 -0.009228  5  0.111137
compound<conj<obl>      Knockando  0.318007  0.020651  2  0.101128
nsubj:pass<aux:pass>    be         0.252014  0.072651  8  0.063511
compound<conj<nsubj>    these     -0.245436  0.020651  2  0.060239
compound<compound<case> of        -0.237975  0.007448  1  0.056632
compound<conj<conj>     ree        0.227317  0.020651  2  0.051673

                                   test_pvalue  test_dX  test_Nx  test_N  \
arcpath                 lemma
nmod>                   m              0.00923    1.560        1      36
compound<conj<obj<      include        0.17730    0.438        4      36
compound<conj<obl>      pellet         0.57119    0.255        2      36
                        rabbit         0.57119    0.255        2      36
det>                    the            0.15840    0.416        5      36
compound<conj<obl>      Knockando      0.57119    0.255        2      36
nsubj:pass<aux:pass>    be             0.03791    0.500        8      36
compound<conj<nsubj>    these          0.07034   -0.798        2      36
compound<compound<case> of             0.02117   -1.396        1      36
compound<conj<conj>     ree            0.16361    0.620        2      36

                                   test_st
arcpath                 lemma
nmod>                   m             2.76
compound<conj<obj<      include       1.38
compound<conj<obl>      pellet        0.57
                        rabbit        0.57
det>                    the           1.44
compound<conj<obl>      Knockando     0.57
nsubj:pass<aux:pass>    be            2.16
compound<conj<nsubj>    these        -1.87
compound<compound<case> of           -2.42
compound<conj<conj>     ree           1.42
===========  end ==============
checking for data/q_cluster/BGM_full_covar_taxongroup.pkl
BGM loaded
bgm.predict(my_ica_data)).value_counts()
9    2472
2    2429
6    1400
0     842
8     552
4     282
1     233
7     134
3      12
5       5
Name: count, dtype: int64

clust_feats (19040, 2)
                 cluster  freq
arcpath   lemma
case>     of           6   818
det>      the          2   613
          the          9   441
nmod<det> the          6   379
case>     of           2   346
=========================
clust_f_df pivot table (10866, 10)
clust_p_df is the probability distribution cluster-wise
                              0    1         2    3    4    5    6    7    8  \
arcpath              lemma
acl:relcl<case>      of     0.0  0.0  0.000096  0.0  0.0  0.0  0.0  0.0  0.0
acl:relcl<det>       the    0.0  0.0  0.000192  0.0  0.0  0.0  0.0  0.0  0.0
acl:relcl<obl<cop>   be     0.0  0.0  0.000096  0.0  0.0  0.0  0.0  0.0  0.0
acl:relcl<obl<nsubj> it     0.0  0.0  0.000096  0.0  0.0  0.0  0.0  0.0  0.0
acl:relcl>           be     0.0  0.0  0.000096  0.0  0.0  0.0  0.0  0.0  0.0

                                   9
arcpath              lemma
acl:relcl<case>      of     0.000000
acl:relcl<det>       the    0.000000
acl:relcl<obl<cop>   be     0.000000
acl:relcl<obl<nsubj> it     0.000000
acl:relcl>           be     0.000145
=========================
Elementwise relative entropy by clusters, feature-wise
                             0         1         2    3         4    5  \
arcpath        lemma
det>           the   -0.001607  0.007449  0.019732  0.0 -0.000204  0.0
case>          of    -0.002400 -0.003662  0.004788  0.0 -0.003980  0.0
cc>            and    0.000000  0.002718 -0.001966  0.0 -0.002310  0.0
amod>          other  0.000000  0.019691  0.006058  0.0 -0.002219  0.0
compound<case> of     0.109052  0.000000 -0.000748  0.0  0.000000  0.0

                             6         7         8         9
arcpath        lemma
det>           the    0.035031 -0.005187 -0.005351  0.023938
case>          of     0.187530 -0.004298 -0.001521 -0.002849
cc>            and    0.000000  0.002712  0.030488  0.020603
amod>          other  0.001924 -0.000865  0.005733  0.000332
compound<case> of    -0.000440  0.000000  0.000000 -0.000947
========== clust_featdx_df ===============
                                          Dx    N
cluster arcpath            lemma
3       flat<list>         Sepia    0.044139   12
7       appos<conj>amod>   african  0.008036    7
5       list<flat>         vossi    0.044624    5
8       cc>                and      0.030488  152
0       compound<nmod<det> the      0.048381   47
=========================
pred_feats
feat_v
                                0         1         2         3         4  \
arcpath          lemma
acl:relcl>nsubj> that   -0.062988 -0.031006 -0.225952  0.068970 -0.026001
                 which  -0.026993 -0.062988 -0.218018  0.080017  0.065979
acl>obl>det>     the     0.145020 -0.152954 -0.185059  0.146973  0.284912
amod>            common  0.469971  0.033997 -0.514160  0.641113  0.316895
                 large   0.499023 -0.064026 -0.609863  0.694824  0.412109

                                5         6         7
arcpath          lemma
acl:relcl>nsubj> that   -0.140991  0.068970 -0.194946
                 which  -0.091980  0.182983 -0.238037
acl>obl>det>     the     0.091980 -0.151978 -0.040985
amod>            common -0.314941  0.091980  0.020996
                 large  -0.080994 -0.144043 -0.040009
mean_norm
[[-0.28 -0.25  0.74  0.28 -0.24 -0.28 -0.11  0.3 ]
 [ 0.65  0.41 -0.23  0.3  -0.19  0.29 -0.14  0.35]
 [ 0.83  0.05 -0.24 -0.14  0.21 -0.09 -0.15 -0.4 ]
 [ 0.01 -0.27 -0.03  0.   -0.01  0.96  0.08 -0.06]
 [ 0.29 -0.34 -0.27 -0.01  0.13  0.07  0.03 -0.84]
 [ 0.03 -0.29 -0.18 -0.87 -0.23 -0.24  0.09  0.11]
 [-0.17 -0.04  0.06 -0.16  0.95  0.02 -0.1   0.19]
 [ 0.53 -0.21 -0.59 -0.26 -0.32 -0.21  0.16  0.29]
 [-0.09  0.01 -0.29  0.1  -0.06  0.08  0.94  0.05]
 [-0.28 -0.18 -0.34  0.26 -0.69 -0.07 -0.34  0.33]]
cos_predict.head(5)
                                    0         1         2         3         4  \
arcpath             lemma
compound<case>      of      -0.142858 -0.094829  0.065604 -0.103357  0.205167
compound<det>       the     -0.197243 -0.117362  0.105470 -0.036762  0.279232
compound<appos<det> the     -0.187869  0.097680  0.227300  0.124052  0.215901
compound<           species -0.332748  0.472939  0.498115 -0.288469  0.261418
compound<nmod<det>  the     -0.452854  0.551205  0.591522 -0.050425  0.401391

                                    5         6         7         8         9
arcpath             lemma
compound<case>      of       0.012351 -0.084102  0.080936  0.123147  0.058002
compound<det>       the     -0.015730 -0.021460  0.065196  0.221812 -0.066027
compound<appos<det> the     -0.151640  0.226762  0.033263 -0.100862 -0.076822
compound<           species -0.447692  0.074860  0.364147  0.214562 -0.017163
compound<nmod<det>  the     -0.553895  0.166650  0.307577  0.032184  0.016892
score_predict.head(5)
                               0      1      2    3    4    5      6    7  \
arcpath             lemma
compound<case>      of       0.0  0.000  0.059  0.0  0.0  0.0  0.227  0.0
compound<det>       the      0.0  0.000  0.098  0.0  0.0  0.0  0.219  0.0
compound<appos<det> the      0.0  0.002  0.057  0.0  0.0  0.0  0.635  0.0
compound<           species  0.0  0.008  0.203  0.0  0.0  0.0  0.246  0.0
compound<nmod<det>  the      0.0  0.011  0.219  0.0  0.0  0.0  0.320  0.0

                                 8      9
arcpath             lemma
compound<case>      of       0.002  0.712
compound<det>       the      0.003  0.680
compound<appos<det> the      0.001  0.306
compound<           species  0.004  0.539
compound<nmod<det>  the      0.003  0.447
                                    0         1         2    3         4    5  \
arcpath             lemma
compound<case>      of       0.049309  0.000000  0.000240  0.0  0.000000  0.0
compound<det>       the      0.036406  0.000000  0.000817  0.0  0.000892  0.0
compound<appos<det> the      0.027189  0.000668  0.000096  0.0  0.000000  0.0
compound<           species  0.025346  0.000000  0.000144  0.0  0.000595  0.0
compound<nmod<det>  the      0.021659  0.000000  0.000096  0.0  0.000000  0.0

                                    6    7    8         9
arcpath             lemma
compound<case>      of       0.000114  0.0  0.0  0.004342
compound<det>       the      0.000228  0.0  0.0  0.007671
compound<appos<det> the      0.000000  0.0  0.0  0.000796
compound<           species  0.000114  0.0  0.0  0.004559
compound<nmod<det>  the      0.000000  0.0  0.0  0.001447
=========== Internal structure in cluster==============
cluster ====> 0
np.sqrt(eigvals)
[0.13220147 0.18089723 0.22340393 0.24835196 0.28967368 0.34636284
 0.383435   0.65756759]
cl_elong_a, cl_elong_v.round(2)
1.714938856031669 [-0.13 -0.45  0.21 -0.8   0.01  0.03  0.12 -0.3 ]
cluster data sample, mean shift
(827, 8)                                   0         1         2         3         4  \
token_id
Arc-b4f2_60_Sterna-17      0.269772  0.011575 -0.217613 -0.617702  0.484017
Cir-aed8_182_animal-20    -0.400118  0.421515  0.117231  0.632574  0.089577
Fri-5711_17_Fritillaria-1  0.325610 -0.103719 -0.736775  0.372575 -0.091066

                                  5         6         7
token_id
Arc-b4f2_60_Sterna-17      1.523788 -0.255121  0.493460
Cir-aed8_182_animal-20     0.168482  0.063410  0.163747
Fri-5711_17_Fritillaria-1 -0.750147  0.213261 -0.226958
cluster data elongation along main axis
                        effect        Dx  N      eff2
arcpath     lemma
det>        the       0.728370 -0.001607  1  0.530522
amod>       true     -0.696367  0.000157  1  0.484926
            european -0.640723  0.000163  1  0.410526
            american -0.615469  0.000232  1  0.378803
            bighorn  -0.601725  0.000715  1  0.362073
            red      -0.575242 -0.000189  1  0.330904
            Siberian -0.573746  0.000625  1  0.329185
            bille    -0.569769  0.000900  1  0.324637
            early    -0.556316  0.000837  1  0.309487
appos<case> at        0.553682  0.000648  1  0.306564
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                          token         x
arcpath     lemma
amod>       Siberian    Sal-7dcf_2_salamander-6  0.076941
            american   Cro-0859_276_crocodile-9 -0.073167
            bighorn         Big-0af3_33_sheep-4 -0.567018
            bille       Igu-69c5_9_dinosaurs-25  0.210170
            early     Ani-4d8b_162_chimpanzee-2 -0.679259
            european         Eur-35e8_13_gull-3 -0.376998
            red         Red-a286_70_squirrel-29  0.602987
            true         Dun-cad0_16_beetles-60 -0.569069
appos<case> at          Lep-f8ec_671_Insecta-16  0.528630
det>        the         Sal-7dcf_2_salamander-6  0.076941
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (827,)
ftok (10, 2)
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64

x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
x0 token_id
Arc-b4f2_60_Sterna-17         0.273782
Cir-aed8_182_animal-20       -0.651327
Fri-5711_17_Fritillaria-1    -0.375972
Atl-12cc_25_Istiophorus-11    0.063683
Hem-5b5a_21_arthropod-29     -0.094266
                                ...
Pie-14e4_111_Pieris-1        -0.362709
Rig-c8bd_97_Eubalaena-7       0.158882
Pte-62aa_313_reptile-27      -0.030494
The-f5b4_16_dinosaur-18       0.081733
Wil-3cbf_107_Accipiter-42     0.068505
Name: x, Length: 826, dtype: float64
Spearman results
feat_tests
                      test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath     lemma
amod>       Siberian      0.80098    0.073        1     827     0.25
            american      0.79033   -0.077        1     827    -0.27
            bighorn       0.04858   -0.572        1     827    -1.98
            bille         0.47653    0.207        1     827     0.71
            early         0.01822   -0.684        1     827    -2.37
            european      0.18854   -0.381        1     827    -1.32
            red           0.03846    0.600        1     827     2.07
            true          0.04778   -0.574        1     827    -1.98
appos<case> at            0.06992    0.525        1     827     1.81
det>        the           0.80098    0.073        1     827     0.25
book_cl_elong
                        effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath     lemma
det>        the       0.728370 -0.001607  1  0.530522      0.80098    0.073
amod>       true     -0.696367  0.000157  1  0.484926      0.04778   -0.574
            european -0.640723  0.000163  1  0.410526      0.18854   -0.381
            american -0.615469  0.000232  1  0.378803      0.79033   -0.077
            bighorn  -0.601725  0.000715  1  0.362073      0.04858   -0.572
            early    -0.556316  0.000837  1  0.309487      0.01822   -0.684
appos<case> at        0.553682  0.000648  1  0.306564      0.06992    0.525

                      test_Nx  test_N  test_st
arcpath     lemma
det>        the             1     827     0.25
amod>       true            1     827    -1.98
            european        1     827    -1.32
            american        1     827    -0.27
            bighorn         1     827    -1.98
            early           1     827    -2.37
appos<case> at              1     827     1.81
cluster ====> 1
np.sqrt(eigvals)
[0.26171702 0.35119703 0.42300565 0.62206648 0.81641687 0.97901089
 1.25573878 2.80445139]
cl_elong_a, cl_elong_v.round(2)
2.2333079518709735 [ 0.56  0.06  0.78 -0.22  0.04 -0.1  -0.11  0.02]
cluster data sample, mean shift
(199, 8)                                  0         1         2         3         4  \
token_id
Tru-f072_21_animals-7     0.968425 -3.946513 -0.182949  1.656552  1.416039
Din-756f_27_Dinosauria-7  0.259754 -2.546674  0.521633  0.218453  0.434535
Sca-9161_30_Animals-1     0.173958 -2.289524  0.608234  0.203571  0.506868

                                 5         6         7
token_id
Tru-f072_21_animals-7     0.870430 -0.665120  0.560448
Din-756f_27_Dinosauria-7  0.999972 -0.221918 -0.319033
Sca-9161_30_Animals-1    -0.306838  0.046482  0.096311
cluster data elongation along main axis
                        effect        Dx   N      eff2
arcpath    lemma
cc>        and       -0.751177  0.002718  13  0.564267
nmod>case> of         0.729722  0.004417   8  0.532494
nmod>      Hewitson   0.725210  0.001158   1  0.525929
nsubj<     order      0.717932  0.001071   1  0.515427
nmod>case> in         0.702984  0.005788   9  0.494187
cc>        as        -0.698172  0.002902   3  0.487444
nmod>case> for        0.674864  0.004620   4  0.455442
nmod>      Boisduval  0.672279  0.001131   1  0.451959
nmod>case> with       0.668601  0.002075   4  0.447027
           as         0.662159  0.000889   1  0.438454
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                 token         x
arcpath    lemma
cc>        and                 Acc-0f45_128_animals-52 -1.517914
           and                  Art-1308_276_animals-9 -1.311260
           and                  Aus-e5de_84_animals-23  0.258544
           and                   Bur-98f9_35_snakes-23 -0.976707
           and                   Eur-9431_146_birds-36  0.939789
           and                 Gre-8842_263_animals-14 -1.078303
           and                    Hor-8eda_15_wasps-17 -0.262167
           and              Lon-b0af_465_amphibians-16 -0.651788
           and                Neo-e4e0_73_amphibians-7  0.419851
           and              Sal-5617_98_salamanders-11 -0.341240
           and                 Sem-88a0_20_molluscs-24 -0.300912
           and                   Tig-9404_36_sharks-31 -2.328309
           and                 Ulm-cc96_2_jellyfish-18 -0.542769
           as                   Bla-2fe0_156_plants-13 -0.134455
           as                Eur-c955_104_squirrels-19 -0.537578
           as                   Eas-b7c7_26_insects-22 -0.697873
nmod>      Boisduval            Pap-75c9_38_Papilio-14  1.066442
           Hewitson             Pap-75c9_41_Papilio-31  1.194487
nmod>case> as                 Din-756f_246_dinosaurs-3  1.060696
           for                  Art-1308_276_animals-9 -1.311260
           for                   Bai-1860_29_animals-4  1.264953
           for                  Bee-1811_473_insects-3  1.098793
           for                   Hed-8dc6_164_plants-3 -2.107495
           in                  Acc-0f45_128_animals-52 -1.517914
           in                 Neo-e4e0_73_amphibians-7  0.419851
           in               Sal-5617_98_salamanders-11 -0.341240
           in                   Ame-d5c4_209_animals-9  0.785165
           in                   Bla-2fe0_156_plants-13 -0.134455
           in                Eur-c955_104_squirrels-19 -0.537578
           in                 Red-a286_99_squirrels-17  1.182871
           in                   Redab4b_59_squirrels-9  0.742750
           in                     She-572b_18_animal-4  1.525565
           of                     Hor-8eda_15_wasps-17 -0.262167
           of                 All-7078_123_Dinosaurs-7  0.170848
           of                    Ble-2387_2_rodents-19  1.139131
           of            Com-264e_2_Syngnathiformes-18  0.820904
           of                    Har-f3ef_20_animals-6  0.929674
           of                        Kin-034b_9_bird-3  1.322116
           of                     Roe-b5ac_120_deer-22 -0.898712
           of         Tig-9404_17_Carcharhiniformes-10  0.428870
           with                  Eur-9431_146_birds-36  0.939789
           with                Ulm-cc96_2_jellyfish-18 -0.542769
           with                 Blu-3a31_23_animals-24  0.128067
           with                 The-f5b4_187_animals-3  1.533152
nsubj<     order                  Fly-ac51_4_Diptera-1  0.869151
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (199,)
ftok (45, 2)
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 186, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 196, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 198, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 198, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 198, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 195, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 190, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 191, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 195, dtype: float64
x0 token_id
Tru-f072_21_animals-7         -0.152113
Din-756f_27_Dinosauria-7       0.280056
Sca-9161_30_Animals-1          0.433783
Hor-ab9c_225_bat-8             0.123050
Dun-cad0_87_beetles-3          0.828830
                                 ...
Cam-4bd8_61_cephalopods-10    -0.496002
Min-e696_18_Mustela-14        -0.474476
Bir-154b_12_Paradisaeidae-3    0.257179
Bov-d455_139_plant-16         -0.322662
Com-0bc9_123_mammals-30        1.207571
Name: x, Length: 198, dtype: float64
Spearman results
feat_tests
                      test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
cc>        and            0.03505   -0.631       13     199    -2.12
           as             0.44919   -0.462        3     199    -0.76
nmod>      Boisduval      0.30727    1.073        1     199     1.02
           Hewitson       0.25272    1.202        1     199     1.15
nmod>case> as             0.30989    1.068        1     199     1.02
           for            0.61391   -0.268        4     199    -0.51
           in             0.48678    0.249        9     199     0.70
           of             0.20712    0.477        8     199     1.27
           with           0.32006    0.527        4     199     1.00
nsubj<     order          0.40541    0.875        1     199     0.83
book_cl_elong
                        effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath    lemma
cc>        and       -0.751177  0.002718  13  0.564267      0.03505   -0.631
nmod>case> of         0.729722  0.004417   8  0.532494      0.20712    0.477
nmod>      Hewitson   0.725210  0.001158   1  0.525929      0.25272    1.202
nsubj<     order      0.717932  0.001071   1  0.515427      0.40541    0.875
nmod>case> in         0.702984  0.005788   9  0.494187      0.48678    0.249
cc>        as        -0.698172  0.002902   3  0.487444      0.44919   -0.462
nmod>      Boisduval  0.672279  0.001131   1  0.451959      0.30727    1.073
nmod>case> with       0.668601  0.002075   4  0.447027      0.32006    0.527
           as         0.662159  0.000889   1  0.438454      0.30989    1.068

                      test_Nx  test_N  test_st
arcpath    lemma
cc>        and             13     199    -2.12
nmod>case> of               8     199     1.27
nmod>      Hewitson         1     199     1.15
nsubj<     order            1     199     0.83
nmod>case> in               9     199     0.70
cc>        as               3     199    -0.76
nmod>      Boisduval        1     199     1.02
nmod>case> with             4     199     1.00
           as               1     199     1.02
cluster ====> 2
np.sqrt(eigvals)
[0.3960085  0.6456979  0.71041842 0.80835755 0.95695145 1.1191785
 1.22046918 1.34060167]
cl_elong_a, cl_elong_v.round(2)
1.0984314004797417 [-0.02 -0.09  0.58  0.07  0.45  0.35 -0.07  0.56]
cluster data sample, mean shift
(2280, 8)                                     0         1         2         3         4  \
token_id
Bla-b48c_24_animals-6       -1.401316  0.605597  0.515301 -0.230137  0.838484
Sia-b899_44_primates-21      0.164422  0.536239  0.486635 -0.284216 -0.639501
Pha-1383_2_Diprotodontia-38  0.377362  0.023735  1.444552  0.866608 -0.346779

                                    5         6         7
token_id
Bla-b48c_24_animals-6        0.163035 -0.042755 -0.208050
Sia-b899_44_primates-21     -0.223604  0.070850  1.070395
Pha-1383_2_Diprotodontia-38  0.637382 -0.083543  0.325244
cluster data elongation along main axis

                         effect        Dx    N      eff2
arcpath  lemma
conj>cc> rather       -0.635106  0.000221    2  0.403359
         but          -0.629623  0.000721   13  0.396425
         or           -0.606872  0.003933   64  0.368294
         and          -0.584519  0.012895  277  0.341662
         as           -0.571473  0.000220    8  0.326581
conj>    form         -0.556713  0.000332    3  0.309929
         mollusc      -0.554473 -0.000032    1  0.307440
         invertebrate -0.547881  0.000086    2  0.300174
         tortoise     -0.546524  0.000066    1  0.298689
         fish         -0.545626  0.000063    4  0.297708
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                      token         x
arcpath  lemma
conj>    fish         Atl-fb88_25_fishes-15 -3.655930
         fish         Spa-e46a_21_animals-2 -0.698114
         fish      Sea-4a1d_309_reptiles-17  0.151133
         fish        Tam-0d84_13_characin-6 -0.806471
         form        Mos-3d44_144_animals-7 -1.886516
...                                     ...       ...
conj>cc> or           Tho-4613_4_spiders-11 -0.720854
         or         Tyr-9f97_325_lizards-43  0.080017
         or         Wea-8e57_5_Mustelidae-3 -0.705664
         rather  Cni-c1f9_224_cnidarians-33 -1.000411
         rather     Pte-62aa_442_animals-12 -1.728691

[375 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (2280,)
ftok (375, 2)
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2276, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2277, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2278, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2279, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2279, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Bir-ebe4_542_mammals-10        2.548465
Nil-600c_128_animals-14       -0.007033
                                 ...
Blu-41f9_91_animal-7          -0.795735
Com-a681_84_vertebrates-4     -0.793273
Chi-c10a_299_chimpanzees-27    0.210409
Bro-f1dc_290_animal-25        -1.844749
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2003, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2272, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2267, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2216, dtype: float64
x0 token_id
Bla-b48c_24_animals-6          0.580611
Sia-b899_44_primates-21        0.441320
Pha-1383_2_Diprotodontia-38    1.150963
Tai-3286_55_conifers-66       -1.630138
Bir-ebe4_542_mammals-10        2.548465
                                 ...
Afr-324e_51_animals-12        -1.394932
Afr-7494_20_elephant-27       -1.876918
Bro-f1dc_290_animal-25        -1.844749
Too-567c_27_cephalopods-2     -1.633854
Pap-75c9_71_Papilio-42         0.634474
Name: x, Length: 2278, dtype: float64
Spearman results
feat_tests
                       test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath  lemma
conj>    fish              0.02494   -1.216        4    2280    -2.24
         form              0.00003   -2.588        3    2280    -4.15
         invertebrate      0.34849   -0.719        2    2280    -0.94
         mollusc           0.02055   -2.511        1    2280    -2.32
         tortoise          0.12666   -1.656        1    2280    -1.53
conj>cc> and               0.00000   -1.120      277    2280   -17.13
         as                0.00002   -1.657        8    2280    -4.33
         but               0.00000   -1.890       13    2280    -6.32
         or                0.00000   -1.049       64    2280    -7.73
         rather            0.08346   -1.327        2    2280    -1.73
book_cl_elong
                         effect        Dx    N      eff2  test_pvalue  \
arcpath  lemma
conj>cc> rather       -0.635106  0.000221    2  0.403359      0.08346
         but          -0.629623  0.000721   13  0.396425      0.00000
         or           -0.606872  0.003933   64  0.368294      0.00000
         and          -0.584519  0.012895  277  0.341662      0.00000
         as           -0.571473  0.000220    8  0.326581      0.00002
conj>    form         -0.556713  0.000332    3  0.309929      0.00003
         mollusc      -0.554473 -0.000032    1  0.307440      0.02055
         invertebrate -0.547881  0.000086    2  0.300174      0.34849
         tortoise     -0.546524  0.000066    1  0.298689      0.12666
         fish         -0.545626  0.000063    4  0.297708      0.02494

                       test_dX  test_Nx  test_N  test_st
arcpath  lemma
conj>cc> rather         -1.327        2    2280    -1.73
         but            -1.890       13    2280    -6.32
         or             -1.049       64    2280    -7.73
         and            -1.120      277    2280   -17.13
         as             -1.657        8    2280    -4.33
conj>    form           -2.588        3    2280    -4.15
         mollusc        -2.511        1    2280    -2.32
         invertebrate   -0.719        2    2280    -0.94
         tortoise       -1.656        1    2280    -1.53
         fish           -1.216        4    2280    -2.24
cluster ====> 3
np.sqrt(eigvals)
[0.21115671 0.22982939 0.24384121 0.24768674 0.26566413 0.27196214
 0.35848478 7.07414045]
cl_elong_a, cl_elong_v.round(2)
19.733447379518083 [-0.08 -0.9   0.14 -0.25  0.06 -0.3   0.06 -0.06]
cluster data sample, mean shift
(12, 8)                              0         1         2         3         4  \
token_id
Sep-9969_11_Sepia-94 -0.109762 -0.722088 -0.089950  0.297656 -0.094313
Sep-9969_11_Sepia-13  0.014948 -0.707135  0.000731 -0.068633 -0.048942
Sep-9969_11_Sepia-8   0.037790 -0.494847 -0.650656  0.633717  0.177464

                             5         6         7
token_id
Sep-9969_11_Sepia-94  2.762769  0.404445 -0.129934
Sep-9969_11_Sepia-13  2.356798  0.135907 -0.174223
Sep-9969_11_Sepia-8   2.657096  0.340549 -0.148887
cluster data elongation along main axis

                                  effect        Dx   N      eff2
arcpath             lemma
compound>           Sepia      -0.268692  0.006471   2  0.072196
flat<flat>compound> Sepia      -0.255541  0.044139  12  0.065301
amod>               cuttlefish -0.238076  0.003235   1  0.056680
compound>           cuttlefish -0.232783  0.002969   1  0.054188
flat<flat>compound> cuttlefish -0.229504  0.040461  11  0.052672
flat<list>amod>     giant      -0.219652  0.044139  12  0.048247
flat<compound>      Sepia       0.193832  0.044139  12  0.037571
flat<compound>amod> cuttlefish  0.158390  0.044139  12  0.025087
flat<list>amod>     common     -0.148139  0.043844  12  0.021945
flat<flat>          Sepia      -0.132598  0.044139  12  0.017582
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                           token         x
arcpath         lemma
amod>           cuttlefish   Sep-9969_11_Sepia-8 -0.579888
compound>       Sepia        Sep-9969_11_Sepia-8 -0.579888
                Sepia       Sep-9969_11_Sepia-94 -0.244920
                cuttlefish  Sep-9969_11_Sepia-30 -0.055540
flat<compound>  Sepia        Sep-9969_11_Sepia-8 -0.579888
...                                          ...       ...
flat<list>amod> giant       Sep-9969_11_Sepia-44 -0.051512
                giant       Sep-9969_11_Sepia-46 -0.051512
                giant       Sep-9969_11_Sepia-48 -0.051512
                giant       Sep-9969_11_Sepia-50 -0.051512
                giant       Sep-9969_11_Sepia-52 -0.051512

[87 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (12,)
ftok (87, 2)
x0 token_id
Sep-9969_11_Sepia-94   -0.244920
Sep-9969_11_Sepia-13   -0.051512
Sep-9969_11_Sepia-48   -0.051512
Sep-9969_11_Sepia-14   -0.051512
Sep-9969_11_Sepia-50   -0.051512
Sep-9969_11_Sepia-52   -0.051512
Sep-9969_11_Sepia-30   -0.055540
Sep-9969_11_Sepia-39   -0.051512
Sep-9969_11_Sepia-46   -0.051512
Sep-9969_11_Sepia-44   -0.051512
Sep-9969_11_Sepia-10   -0.051512
Name: x, dtype: float64
x0 token_id
Sep-9969_11_Sepia-13   -0.051512
Sep-9969_11_Sepia-48   -0.051512
Sep-9969_11_Sepia-14   -0.051512
Sep-9969_11_Sepia-50   -0.051512
Sep-9969_11_Sepia-52   -0.051512
Sep-9969_11_Sepia-30   -0.055540
Sep-9969_11_Sepia-39   -0.051512
Sep-9969_11_Sepia-46   -0.051512
Sep-9969_11_Sepia-44   -0.051512
Sep-9969_11_Sepia-10   -0.051512
Name: x, dtype: float64
x0 token_id
Sep-9969_11_Sepia-94   -0.244920
Sep-9969_11_Sepia-13   -0.051512
Sep-9969_11_Sepia-8    -0.579888
Sep-9969_11_Sepia-48   -0.051512
Sep-9969_11_Sepia-14   -0.051512
Sep-9969_11_Sepia-50   -0.051512
Sep-9969_11_Sepia-52   -0.051512
Sep-9969_11_Sepia-39   -0.051512
Sep-9969_11_Sepia-46   -0.051512
Sep-9969_11_Sepia-44   -0.051512
Sep-9969_11_Sepia-10   -0.051512
Name: x, dtype: float64
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 token_id
Sep-9969_11_Sepia-30   -0.05554
Name: x, dtype: float64
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
Spearman results
feat_tests

/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)

                                test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath             lemma
amod>               cuttlefish      0.00001   -0.510        1      12    -8.40
compound>           Sepia           0.00010   -0.360        2      12    -6.21
                    cuttlefish      0.72679    0.062        1      12     0.36
flat<compound>      Sepia               NaN      NaN       12      12      NaN
flat<compound>amod> cuttlefish          NaN      NaN       12      12      NaN
flat<flat>          Sepia               NaN      NaN       12      12      NaN
flat<flat>compound> Sepia               NaN      NaN       12      12      NaN
                    cuttlefish      0.72679   -0.062       11      12    -0.36
flat<list>amod>     common              NaN      NaN       12      12      NaN
                    giant               NaN      NaN       12      12      NaN
book_cl_elong
                                  effect        Dx   N      eff2  test_pvalue  \
arcpath             lemma
compound>           Sepia      -0.268692  0.006471   2  0.072196      0.00010
amod>               cuttlefish -0.238076  0.003235   1  0.056680      0.00001
flat<flat>compound> cuttlefish -0.229504  0.040461  11  0.052672      0.72679

                                test_dX  test_Nx  test_N  test_st
arcpath             lemma
compound>           Sepia        -0.360        2      12    -6.21
amod>               cuttlefish   -0.510        1      12    -8.40
flat<flat>compound> cuttlefish   -0.062       11      12    -0.36
cluster ====> 4
np.sqrt(eigvals)
[0.87541035 1.0956898  1.1771284  1.38286394 1.47621182 1.83913222
 2.7747381  2.8546637 ]
cl_elong_a, cl_elong_v.round(2)
1.0288047371721647 [-0.02  0.1   0.16  0.23 -0.03 -0.16 -0.94 -0.06]
cluster data sample, mean shift
(258, 8)                                0         1         2         3         4  \
token_id
Bla-2fe0_148_plants-9  -1.589118  0.532876 -0.595739  2.765317 -0.979652
Das-ed91_129_animal-33  0.946745 -0.179290  0.062501 -0.988001 -0.497125
Dee-529a_76_deer-4     -0.865783  0.669462  1.146893  1.255307 -0.731483

                               5         6         7
token_id
Bla-2fe0_148_plants-9   0.019344  1.148160 -6.289577
Das-ed91_129_animal-33 -2.015726  1.201258  0.371768
Dee-529a_76_deer-4     -0.709612 -0.873352 -3.147970
cluster data elongation along main axis
                          effect        Dx  N      eff2
arcpath    lemma
conj>      Subfamily    0.667451  0.000640  1  0.445490
conj<conj> shark       -0.664978 -0.000046  2  0.442196
           bat         -0.663527  0.000714  3  0.440269
           flatworm    -0.566637  0.000473  1  0.321078
conj>      Sciurus      0.563619  0.000685  1  0.317666
           family       0.551452  0.000584  1  0.304100
           swallowtail  0.530675  0.001369  2  0.281616
           Blattodea    0.504107  0.000640  1  0.254124
conj<conj> c.          -0.499749  0.000406  1  0.249749
conj>      dinosaur     0.472400  0.001240  2  0.223162
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                           token         x
arcpath    lemma
conj<conj> bat              Bat-2d5b_226_bats-34 -2.213637
           bat              Bat-2d5b_226_bats-44 -2.468908
           bat                 Vam-5657_4_bat-24 -1.274221
           c.             Pap-75c9_46_Papilio-92 -0.364505
           flatworm      Ear-b650_253_beetles-22 -1.681358
           shark             Req-2240_3_shark-30 -1.162573
           shark             Req-2240_3_shark-33 -1.119459
conj>      Blattodea          Soc-cc7f_57_ants-9  1.419770
           Sciurus        Sci-501e_9_squirrel-55  0.873694
           Subfamily      Igu-7a3f_52_lizards-12  1.508407
           dinosaur     Had-5500_143_reptiles-23  0.601762
           dinosaur      Rep-aa64_159_reptiles-2  2.034344
           family        Oak-f2b6_135_Fagaceae-2  0.699875
           swallowtail     Pap-75c9_40_Papilio-1  1.875292
           swallowtail     Pap-75c9_60_Papilio-1 -0.124200
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (258,)
ftok (15, 2)
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 255, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 257, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 257, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 256, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 257, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 257, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 257, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Oce-2d88_489_animals-11       -0.038837
Vam-5657_4_bat-24             -1.274221
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 256, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 257, dtype: float64
x0 token_id
Bla-2fe0_148_plants-9         -0.044552
Das-ed91_129_animal-33        -1.060493
Dee-529a_76_deer-4             1.707225
Rep-aa64_159_reptiles-2        2.034344
Oce-2d88_489_animals-11       -0.038837
                                 ...
Ani-2170_6_reptiles-43         0.339926
Cir-aed8_167_cats-67          -1.097805
Sta-7425_15_insects-18        -1.612641
Bon-c081_229_vertebrates-30   -0.922130
And-dffe_106_animals-12        0.079022
Name: x, Length: 256, dtype: float64
Spearman results
feat_tests
                        test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
conj<conj> bat              0.00092   -2.019        3     258    -3.35
           c.               0.72373   -0.376        1     258    -0.35
           flatworm         0.10924   -1.698        1     258    -1.61
           shark            0.12259   -1.160        2     258    -1.55
conj>      Blattodea        0.18198    1.416        1     258     1.34
           Sciurus          0.41395    0.867        1     258     0.82
           Subfamily        0.15593    1.505        1     258     1.42
           dinosaur         0.07891    1.319        2     258     1.76
           family           0.51410    0.693        1     258     0.65
           swallowtail      0.24570    0.873        2     258     1.16
book_cl_elong
                          effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath    lemma
conj>      Subfamily    0.667451  0.000640  1  0.445490      0.15593    1.505
conj<conj> shark       -0.664978 -0.000046  2  0.442196      0.12259   -1.160
           bat         -0.663527  0.000714  3  0.440269      0.00092   -2.019
           flatworm    -0.566637  0.000473  1  0.321078      0.10924   -1.698
conj>      Sciurus      0.563619  0.000685  1  0.317666      0.41395    0.867
           family       0.551452  0.000584  1  0.304100      0.51410    0.693
           swallowtail  0.530675  0.001369  2  0.281616      0.24570    0.873
           Blattodea    0.504107  0.000640  1  0.254124      0.18198    1.416
conj<conj> c.          -0.499749  0.000406  1  0.249749      0.72373   -0.376
conj>      dinosaur     0.472400  0.001240  2  0.223162      0.07891    1.319

                        test_Nx  test_N  test_st
arcpath    lemma
conj>      Subfamily          1     258     1.42
conj<conj> shark              2     258    -1.55
           bat                3     258    -3.35
           flatworm           1     258    -1.61
conj>      Sciurus            1     258     0.82
           family             1     258     0.65
           swallowtail        2     258     1.16
           Blattodea          1     258     1.34
conj<conj> c.                 1     258    -0.35
conj>      dinosaur           2     258     1.76
cluster ====> 5
np.sqrt(eigvals)
[0.26601108 0.29226841 0.30037423 0.31435327 0.31755581 0.34179399
 0.42360761 8.70287425]
cl_elong_a, cl_elong_v.round(2)
20.5446597646298 [-0.08  0.89 -0.09  0.23 -0.35 -0.01 -0.    0.11]
cluster data sample, mean shift
(5, 8)                                   0         1         2         3         4  \
token_id
Sep-9969_11_cuttlefish-72  0.175137 -1.863047 -0.897680 -5.089547 -1.288464
Sep-9969_11_cuttlefish-61  0.131416 -1.717613 -0.936958 -4.846084 -1.459493
Sep-9969_11_Sepia-73       0.200669 -1.654411 -0.962844 -5.214492 -1.214779

                                  5         6         7
token_id
Sep-9969_11_cuttlefish-72 -1.376220  0.433929  0.686780
Sep-9969_11_cuttlefish-61 -1.435134  0.538422  0.448331
Sep-9969_11_Sepia-73      -1.360708  0.542007  0.680597
cluster data elongation along main axis
                                          effect        Dx  N      eff2
arcpath                 lemma
list<compound>amod>     cuttlefish     -0.373938  0.044624  5  0.139830
list<compound<compound< Sepia           0.356669  0.044624  5  0.127212
list<list>compound>     angulata       -0.348545  0.044624  5  0.121484
list<list>              novaehollandia -0.322935  0.044624  5  0.104287
list<flat>              Sepia          -0.311200  0.044624  5  0.096845
list<list>              papuensis      -0.306864  0.044624  5  0.094165
list<list>compound>     Guinean        -0.278939  0.035699  4  0.077807
list<list>              Sepia          -0.276003  0.044624  5  0.076178
                        officinalis    -0.275028  0.044624  5  0.075640
list<flat>              Subgenus       -0.274664  0.044624  5  0.075440
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                            token         x
arcpath                 lemma
list<compound<compound< Sepia                Sep-9969_11_Sepia-62 -2.103412
                        Sepia                Sep-9969_11_Sepia-73 -2.103412
                        Sepia           Sep-9969_11_cuttlefish-43 -1.587440
                        Sepia           Sep-9969_11_cuttlefish-61 -2.008829
                        Sepia           Sep-9969_11_cuttlefish-72 -2.236184
list<compound>amod>     cuttlefish           Sep-9969_11_Sepia-62 -2.103412
                        cuttlefish           Sep-9969_11_Sepia-73 -2.103412
                        cuttlefish      Sep-9969_11_cuttlefish-43 -1.587440
                        cuttlefish      Sep-9969_11_cuttlefish-61 -2.008829
                        cuttlefish      Sep-9969_11_cuttlefish-72 -2.236184
list<flat>              Sepia                Sep-9969_11_Sepia-62 -2.103412
                        Sepia                Sep-9969_11_Sepia-73 -2.103412
                        Sepia           Sep-9969_11_cuttlefish-43 -1.587440
                        Sepia           Sep-9969_11_cuttlefish-61 -2.008829
                        Sepia           Sep-9969_11_cuttlefish-72 -2.236184
                        Subgenus             Sep-9969_11_Sepia-62 -2.103412
                        Subgenus             Sep-9969_11_Sepia-73 -2.103412
                        Subgenus        Sep-9969_11_cuttlefish-43 -1.587440
                        Subgenus        Sep-9969_11_cuttlefish-61 -2.008829
                        Subgenus        Sep-9969_11_cuttlefish-72 -2.236184
list<list>              Sepia                Sep-9969_11_Sepia-62 -2.103412
                        Sepia                Sep-9969_11_Sepia-73 -2.103412
                        Sepia           Sep-9969_11_cuttlefish-43 -1.587440
                        Sepia           Sep-9969_11_cuttlefish-61 -2.008829
                        Sepia           Sep-9969_11_cuttlefish-72 -2.236184
                        novaehollandia       Sep-9969_11_Sepia-62 -2.103412
                        novaehollandia       Sep-9969_11_Sepia-73 -2.103412
                        novaehollandia  Sep-9969_11_cuttlefish-43 -1.587440
                        novaehollandia  Sep-9969_11_cuttlefish-61 -2.008829
                        novaehollandia  Sep-9969_11_cuttlefish-72 -2.236184
                        officinalis          Sep-9969_11_Sepia-62 -2.103412
                        officinalis          Sep-9969_11_Sepia-73 -2.103412
                        officinalis     Sep-9969_11_cuttlefish-43 -1.587440
                        officinalis     Sep-9969_11_cuttlefish-61 -2.008829
                        officinalis     Sep-9969_11_cuttlefish-72 -2.236184
                        papuensis            Sep-9969_11_Sepia-62 -2.103412
                        papuensis            Sep-9969_11_Sepia-73 -2.103412
                        papuensis       Sep-9969_11_cuttlefish-43 -1.587440
                        papuensis       Sep-9969_11_cuttlefish-61 -2.008829
                        papuensis       Sep-9969_11_cuttlefish-72 -2.236184
list<list>compound>     Guinean              Sep-9969_11_Sepia-62 -2.103412
                        Guinean              Sep-9969_11_Sepia-73 -2.103412
                        Guinean         Sep-9969_11_cuttlefish-61 -2.008829
                        Guinean         Sep-9969_11_cuttlefish-72 -2.236184
                        angulata             Sep-9969_11_Sepia-62 -2.103412
                        angulata             Sep-9969_11_Sepia-73 -2.103412
                        angulata        Sep-9969_11_cuttlefish-43 -1.587440
                        angulata        Sep-9969_11_cuttlefish-61 -2.008829
                        angulata        Sep-9969_11_cuttlefish-72 -2.236184
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (5,)
ftok (49, 2)

x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 Series([], Name: x, dtype: float64)
x0 token_id
Sep-9969_11_cuttlefish-43   -1.58744
Name: x, dtype: float64
x0 Series([], Name: x, dtype: float64)
Spearman results
feat_tests
                                        test_pvalue  test_dX  test_Nx  test_N  \
arcpath                 lemma
list<compound<compound< Sepia                   NaN      NaN        5       5
list<compound>amod>     cuttlefish              NaN      NaN        5       5
list<flat>              Sepia                   NaN      NaN        5       5
                        Subgenus                NaN      NaN        5       5
list<list>              Sepia                   NaN      NaN        5       5
                        novaehollandia          NaN      NaN        5       5
                        officinalis             NaN      NaN        5       5
                        papuensis               NaN      NaN        5       5
list<list>compound>     Guinean             0.01515   -0.526        4       5
                        angulata                NaN      NaN        5       5

                                        test_st
arcpath                 lemma
list<compound<compound< Sepia               NaN
list<compound>amod>     cuttlefish          NaN
list<flat>              Sepia               NaN
                        Subgenus            NaN
list<list>              Sepia               NaN
                        novaehollandia      NaN
                        officinalis         NaN
                        papuensis           NaN
list<list>compound>     Guinean           -5.03
                        angulata            NaN
book_cl_elong
                               effect        Dx  N      eff2  test_pvalue  \
arcpath             lemma
list<list>compound> Guinean -0.278939  0.035699  4  0.077807      0.01515

                             test_dX  test_Nx  test_N  test_st
arcpath             lemma
list<list>compound> Guinean   -0.526        4       5    -5.03
cluster ====> 6
np.sqrt(eigvals)
[0.24110727 0.31028343 0.37678552 0.50346858 0.52822512 0.61225642
 0.76127814 0.99444923]
cl_elong_a, cl_elong_v.round(2)
1.3062889477770603 [-0.05  0.93  0.33  0.09  0.02  0.12  0.03  0.03]
cluster data sample, mean shift
(1332, 8)                                    0         1         2         3         4  \
token_id
Hor-ab9c_184_bat-13        -0.438082 -0.355401  0.229085 -1.898982  1.375143
The-1978_215_Saurischia-16  0.246799 -0.374635 -0.626796 -0.283815  0.974614
Com-f222_479_birds-11       0.784924 -0.106542 -0.386290  1.482840  0.764857

                                   5         6         7
token_id
Hor-ab9c_184_bat-13        -0.538853 -0.121674  0.336166
The-1978_215_Saurischia-16  0.048036 -0.296486  0.502807
Com-f222_479_birds-11      -0.594153  0.128833  0.224974
cluster data elongation along main axis
                                    effect        Dx   N      eff2
arcpath              lemma
acl:relcl>           include     -0.771728  0.001694  10  0.595564
                     contain     -0.753686  0.000493   3  0.568042
obl<                 achieve      0.718221  0.000222   1  0.515841
                     use          0.712818  0.000120   3  0.508110
                     unique       0.711457  0.000193   1  0.506170
                     concentrate  0.709540  0.000222   1  0.503446
acl:relcl>           call        -0.709162  0.000222   1  0.502911
                     have        -0.703773  0.000412   3  0.495296
acl>obl>nmod:poss>   its         -0.703625  0.000787   3  0.495088
nmod<nsubj:pass<obl> diet        -0.700473  0.000525   2  0.490663
Compute the feature-associated token x1 positions (ftok) on the projected axis

/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/home/seppo/.local/lib/python3.10/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)

ftok
                                                        token         x
arcpath              lemma
acl:relcl>           call              Aur-4fbd_2_jellyfish-6 -0.663944
                     contain             Bla-975a_2_insects-6 -0.582368
                     contain               Latf3e7_1_snakes-8 -0.814585
                     contain          Mer-8390_2_arthropods-7 -1.095138
                     have               Gol-1dbf_201_birds-32 -0.630666
                     have               Ost-8757_2_animals-24 -1.033817
                     have               Tar2870_20_spiders-46 -1.204961
                     include      Amp-436a_182_salamanders-12 -0.523022
                     include            Bos-be23_2_bovines-17 -0.536654
                     include            Bov-d455_2_mammals-13 -0.204985
                     include              Cni33c8_2_animals-7 -1.007654
                     include               Cor-ff2a_2_fungi-7 -1.075492
                     include         Din-756f_431_dinosaurs-5 -0.782951
                     include              Ech86c4_4_animals-6 -0.967408
                     include             Ros-4632_2_plants-16 -0.720216
                     include            Ter-7888_3_Laridae-10 -0.711852
                     include           Ulm-cc96_2_jellyfish-7 -1.053087
acl>obl>nmod:poss>   its                  Har-a313_11_bird-15 -0.916473
                     its                  Nor-d815_14_bird-16 -0.762811
                     its                  Wes-9ef7_14_bird-16 -0.713869
nmod<nsubj:pass<obl> diet                 Com-f222_370_bird-5 -0.548459
                     diet                Eur-bc75_357_snake-5  0.649014
obl<                 achieve             Thi-b492_56_birds-10  0.107676
                     concentrate         Atl-79fc_231_bird-17 -0.093113
                     unique            Ser-d28b_44_mammals-64  0.359230
                     use                 Atl-f357_23_salmon-7  0.663917
                     use                 Bom-c423_293_bees-22  0.531577
                     use               She-572b_21_animals-14  1.277724
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (1332,)
ftok (28, 2)
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1331, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1329, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1329, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1322, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1329, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1330, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1331, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1331, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1331, dtype: float64
x0 token_id
Hor-ab9c_184_bat-13          -0.436558
The-1978_215_Saurischia-16   -0.559479
Com-f222_479_birds-11        -0.170013
Neo-d100_77_animal-31         0.020128
Mon-1726_195_plants-15        0.161954
                                ...
Jum-50eb_2_spiders-7          0.458994
Cro-4b5e_9_starfish-11       -0.595326
Din-756f_17_dinosaurs-3      -0.240029
Dro-42ae_269_dinosaurs-69     0.789935
Bro-dfd8_14_animals-10        0.990683
Name: x, Length: 1329, dtype: float64
Spearman results
feat_tests
                                  test_pvalue  test_dX  test_Nx  test_N  \
arcpath              lemma
acl:relcl>           call             0.23353   -0.666        1    1332
                     contain          0.00975   -0.835        3    1332
                     have             0.00292   -0.961        3    1332
                     include          0.00001   -0.766       10    1332
acl>obl>nmod:poss>   its              0.01306   -0.801        3    1332
nmod<nsubj:pass<obl> diet             0.90264    0.048        2    1332
obl<                 achieve          0.84999    0.106        1    1332
                     concentrate      0.86501   -0.095        1    1332
                     unique           0.52275    0.358        1    1332
                     use              0.01068    0.824        3    1332

                                  test_st
arcpath              lemma
acl:relcl>           call           -1.19
                     contain        -2.59
                     have           -2.98
                     include        -4.35
acl>obl>nmod:poss>   its            -2.49
nmod<nsubj:pass<obl> diet            0.12
obl<                 achieve         0.19
                     concentrate    -0.17
                     unique          0.64
                     use             2.56
book_cl_elong
                              effect        Dx   N      eff2  test_pvalue  \
arcpath            lemma
acl:relcl>         include -0.771728  0.001694  10  0.595564      0.00001
                   contain -0.753686  0.000493   3  0.568042      0.00975
obl<               achieve  0.718221  0.000222   1  0.515841      0.84999
                   use      0.712818  0.000120   3  0.508110      0.01068
                   unique   0.711457  0.000193   1  0.506170      0.52275
acl:relcl>         call    -0.709162  0.000222   1  0.502911      0.23353
                   have    -0.703773  0.000412   3  0.495296      0.00292
acl>obl>nmod:poss> its     -0.703625  0.000787   3  0.495088      0.01306

                            test_dX  test_Nx  test_N  test_st
arcpath            lemma
acl:relcl>         include   -0.766       10    1332    -4.35
                   contain   -0.835        3    1332    -2.59
obl<               achieve    0.106        1    1332     0.19
                   use        0.824        3    1332     2.56
                   unique     0.358        1    1332     0.64
acl:relcl>         call      -0.666        1    1332    -1.19
                   have      -0.961        3    1332    -2.98
acl>obl>nmod:poss> its       -0.801        3    1332    -2.49
cluster ====> 7
np.sqrt(eigvals)
[0.80997743 1.10038373 1.2566561  1.61377408 1.70595307 2.32934393
 2.44514931 2.70824346]
cl_elong_a, cl_elong_v.round(2)
1.1075983949986414 [-0.86 -0.29 -0.02 -0.25  0.08  0.19 -0.08  0.25]
cluster data sample, mean shift
(128, 8)                                  0         1         2         3         4  \
token_id
Cor-270b_264_Corvus-99    0.295753  3.831563  1.152315 -0.589901 -2.816580
All-7078_390_Dinosaurs-1  1.662505  3.296345  0.640880  3.501885  1.224498
Ham-9078_75_shark-36     -1.810255  2.770594  0.728095  0.416190 -0.749905

                                 5         6         7
token_id
Cor-270b_264_Corvus-99    1.510947 -1.014890 -2.082122
All-7078_390_Dinosaurs-1 -1.591875 -1.931148 -3.403993
Ham-9078_75_shark-36      0.711914  1.071881  0.103578
cluster data elongation along main axis
                         effect        Dx   N      eff2
arcpath    lemma
nmod>case> throughout -0.802088  0.001087   1  0.643345
           include    -0.777388  0.004553   7  0.604332
           such       -0.754215  0.007683  16  0.568840
           of         -0.714008  0.001517   7  0.509808
           within     -0.696511  0.002016   2  0.485128
           from       -0.682020  0.001253   3  0.465151
           to         -0.679576  0.005758   6  0.461824
amod>      gray       -0.676412  0.001067   1  0.457533
           black      -0.674611  0.001452   2  0.455099
nmod>case> in         -0.673234  0.004082  10  0.453244
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                             token         x
arcpath    lemma
amod>      black              Com-3b7c_19_birds-36 -4.716474
           black               Eur-35e8_60_gull-19 -3.349200
           gray             Sci-501e_7_squirrel-17 -0.368754
nmod>case> from             Cir-aed8_63_animals-42 -2.967543
           from                 Arc-b4f2_43_bird-8 -3.705202
           from            Lea-dca1_2_dinosaurs-17 -1.707399
           in                   Roe-b5ac_55_deer-8 -3.978991
           in                 Euo-1402_2_spider-13 -3.421679
           in               Rho-d4a0_238_plants-15 -4.881607
           in                Bur-9073_53_plants-17 -2.615279
           in                   Vio-0709_9_plant-6 -3.684067
           in                  Mar-9b95_2_mammal-8 -4.075736
           in                 Hem-78f3_7_insects-2 -5.043062
           in                   Roo-1bd1_22_bird-7 -3.286340
           in                    Blabf9a_12_ants-9 -3.031495
           in            Jel-28f4_209_jellyfish-54 -0.552635
           include           Agl-fec0_26_plants-12 -0.691474
           include        Bio-20c0_102_cnidaria-46 -0.105190
           include          Bio-20c0_148_animals-3 -3.758210
           include         Cha-1a30_159_animals-19  0.495082
           include            Euo-1402_2_spider-13 -3.421679
           include          Flo-23b8_35_animals-19 -1.803145
           include          Rho-d4a0_238_plants-15 -4.881607
           of               Bio-20c0_148_animals-3 -3.758210
           of               Pin-feaf_2_conifers-23 -4.018128
           of                Bir-154b_106_Birds-40  2.824040
           of               Orb-0601_125_Spiders-1  0.694177
           of                Pas-2c4d_116_birds-67  1.422175
           of                   Vio-0709_9_plant-6 -3.684067
           of                 Wes-9ef7_125_Birds-9  0.078227
           such             Boa-7d46_69_lizards-23 -0.542358
           such              Bur-9073_53_plants-17 -2.615279
           such        Cae-3f0c_154_vertebrates-23  0.054477
           such             Cir-aed8_63_animals-42 -2.967543
           such            Coa-44f0_179_animals-28  0.024571
           such               Com-3b7c_19_birds-36 -4.716474
           such              Gre-0f9b_76_birds-102  1.011578
           such              Ham-9078_75_sharks-23 -2.726671
           such              Mon-1726_257_plants-7 -2.674455
           such              Pap-75c9_7_Papilio-22 -2.110376
           such             Pin-feaf_2_conifers-23 -4.018128
           such              Pla-2751_104_plants-3 -3.010530
           such             Sho-fcec_73_mammals-18 -2.454346
           such            Sno-0a8f_245_mammals-33 -2.118270
           such            Son-520b_65_thrushes-29 -3.357597
           such            Tur-2bce_104_animals-25 -0.416492
           throughout           Roe-b5ac_55_deer-8 -3.978991
           to                 Euo-1402_2_spider-13 -3.421679
           to                   Arc-b4f2_43_bird-8 -3.705202
           to                    Asi-28dd_21_cat-9 -3.731708
           to           Cni-c1f9_228_cnidarians-34 -3.009683
           to                 Hem-78f3_7_insects-2 -5.043062
           to                   Roo-1bd1_22_bird-7 -3.286340
           within              Mar-9b95_2_mammal-8 -4.075736
           within        Sal-5617_108_amphibians-2 -3.673091
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (128,)
ftok (55, 2)
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Mar-9b95_2_mammal-8        -4.075736
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 126, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 127, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 125, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 118, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 121, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 121, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Car-fccf_17_mammals-15     -0.956986
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 112, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 127, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 122, dtype: float64
x0 token_id
Cor-270b_264_Corvus-99     -1.624221
All-7078_390_Dinosaurs-1   -4.174603
Ham-9078_75_shark-36        0.647749
Hom-2752_75_Pan-105         4.639745
Eur-35e8_60_gull-19        -3.349200
                              ...
Mal-71cc_109_plant-20       1.576487
Pap-75c9_46_Papilio-105     2.463827
Bub-df64_21_Bubalus-58      5.959568
Sho-fcec_73_mammals-18     -2.454346
Eng-0ed2_8_Engraulis-58     1.651360
Name: x, Length: 126, dtype: float64
Spearman results
feat_tests
                       test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
amod>      black           0.02439   -4.120        2     128    -2.28
           gray            0.87960   -0.394        1     128    -0.15
nmod>case> from            0.05529   -2.884        3     128    -1.93
           in              0.00000   -3.775       10     128    -4.82
           include         0.03026   -2.165        7     128    -2.19
           of              0.32168   -0.997        7     128    -0.99
           such            0.00050   -2.357       16     128    -3.58
           throughout      0.11968   -4.033        1     128    -1.57
           to              0.00022   -3.905        6     128    -3.81
           within          0.03068   -3.959        2     128    -2.19
book_cl_elong
                         effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath    lemma
nmod>case> throughout -0.802088  0.001087   1  0.643345      0.11968   -4.033
           include    -0.777388  0.004553   7  0.604332      0.03026   -2.165
           such       -0.754215  0.007683  16  0.568840      0.00050   -2.357
           of         -0.714008  0.001517   7  0.509808      0.32168   -0.997
           within     -0.696511  0.002016   2  0.485128      0.03068   -3.959
           from       -0.682020  0.001253   3  0.465151      0.05529   -2.884
           to         -0.679576  0.005758   6  0.461824      0.00022   -3.905
amod>      gray       -0.676412  0.001067   1  0.457533      0.87960   -0.394
           black      -0.674611  0.001452   2  0.455099      0.02439   -4.120
nmod>case> in         -0.673234  0.004082  10  0.453244      0.00000   -3.775

                       test_Nx  test_N  test_st
arcpath    lemma
nmod>case> throughout        1     128    -1.57
           include           7     128    -2.19
           such             16     128    -3.58
           of                7     128    -0.99
           within            2     128    -2.19
           from              3     128    -1.93
           to                6     128    -3.81
amod>      gray              1     128    -0.15
           black             2     128    -2.28
nmod>case> in               10     128    -4.82
cluster ====> 8
np.sqrt(eigvals)
[0.56421749 0.67182982 0.74075103 0.76203468 0.9330763  1.01076916
 1.28514622 2.98271395]
cl_elong_a, cl_elong_v.round(2)
2.3209140775452712 [ 0.26  0.65 -0.11 -0.03  0.51  0.25 -0.42 -0.02]
cluster data sample, mean shift
(525, 8)                               0         1         2         3         4  \
token_id
Rep-aa64_410_snakes-9  0.359614  0.230088 -1.278415 -0.134880  0.267500
Pin-a6d8_2_pine-10    -0.463923 -0.120735  1.663284 -1.343133  1.438222
Kin-dc2e_72_snake-26   0.673100  0.144951  1.276909  0.085060 -0.278574

                              5         6         7
token_id
Rep-aa64_410_snakes-9  0.127630 -2.106340 -1.127459
Pin-a6d8_2_pine-10     0.130861  2.684335 -0.576013
Kin-dc2e_72_snake-26   0.937551  4.097514 -0.439989
cluster data elongation along main axis
                        effect        Dx   N      eff2
arcpath    lemma
case>      from       0.512475 -0.000266   1  0.262630
acl:relcl> fly       -0.507750  0.000312   1  0.257810
obl<       higher     0.504366  0.000189   1  0.254385
conj<conj> waterfowl -0.500098  0.000708   2  0.250098
case>      of         0.497451 -0.001521   3  0.247457
conj<conj> marmot    -0.496653  0.001062   3  0.246664
           hedgehog  -0.487617  0.000708   2  0.237771
           squirrel  -0.486893  0.006020  17  0.237065
           seabird   -0.485202  0.000708   2  0.235421
case>      in         0.482628 -0.000417   1  0.232930
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                            token         x
arcpath    lemma
acl:relcl> fly              Com-f222_150_birds-26  0.481457
case>      from              Hor-ab9c_205_bats-17  1.041855
           in              Gro-2286_16_beetles-35  1.751050
           of                Pte-5908_14_animal-6  0.795176
           of               Red-d827_153_Birds-14  1.832718
           of            Rep-aa64_168_reptiles-18  1.327870
conj<conj> hedgehog       Ear-b650_253_beetles-25 -2.608653
           hedgehog        Hib-c4bb_29_rodents-11 -0.704696
           marmot            Eur-9931_185_deer-45 -5.245632
           marmot            Eur-9931_185_deer-48 -5.223102
           marmot         Eur-9931_185_rodents-21 -5.105360
           seabird    Oct-f4f7_270_cephalopods-24 -0.779433
           seabird          Req-2240_29_sharks-32 -2.297404
           squirrel          Eur-9931_185_deer-45 -5.245632
           squirrel          Eur-9931_185_deer-48 -5.223102
           squirrel       Eur-9931_185_rodents-21 -5.105360
           squirrel       Eas-e016_177_rodents-15 -0.106142
           squirrel            Nor-bda1_8_deer-44 -4.415807
           squirrel            Nor-bda1_8_deer-49 -4.189485
           squirrel       Nor-bda1_8_squirrels-15 -4.350743
           squirrel       Nor-bda1_8_squirrels-19 -3.946834
           squirrel        Per-01a0_75_mammals-36  0.036791
           squirrel         Que0eb3_19_mammals-17  0.505580
           squirrel        Rat-4b67_33_animals-18 -0.394119
           squirrel        Sci-501e_7_squirrel-35  0.185842
           squirrel        Sci-501e_7_squirrel-40  0.401226
           squirrel        Sci-501e_7_squirrel-57 -0.670827
           squirrel        Sci-501e_7_squirrel-63 -0.451672
           squirrel        Sci-501e_7_squirrel-68 -0.204199
           squirrel        Sci-501e_9_squirrel-24 -2.066153
           waterfowl        Riv-1495_224_birds-27 -1.182239
           waterfowl        Riv-1495_224_birds-32 -1.057329
obl<       higher          Nor-c9d9_52_rodents-31  2.940471
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (525,)
ftok (33, 2)
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 524, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 524, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 524, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 522, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 523, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 522, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 523, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 508, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 523, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9         1.454802
Pin-a6d8_2_pine-10           -0.672827
Kin-dc2e_72_snake-26         -1.479805
Chi-0753_37_salamanders-22    0.133924
Tai-3286_116_salamander-35   -0.401781
                                ...
Afr-0045_24_elephants-14      0.952338
Squ-be6b_20_lizards-38        1.849631
Fir-3b5c_161_plants-23        0.589923
Bee-1811_89_beetles-25        0.714051
Cro-0859_276_crocodile-39    -0.665806
Name: x, Length: 524, dtype: float64
Spearman results
feat_tests
                      test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
acl:relcl> fly            0.70329    0.561        1     525     0.38
case>      from           0.44611    1.123        1     525     0.76
           in             0.21328    1.833        1     525     1.25
           of             0.09887    1.406        3     525     1.65
conj<conj> hedgehog       0.12864   -1.584        2     525    -1.52
           marmot         0.00000   -5.142        3     525    -6.25
           seabird        0.15991   -1.465        2     525    -1.41
           squirrel       0.00000   -2.061       17     525    -5.86
           waterfowl      0.31645   -1.045        2     525    -1.00
obl<       higher         0.03977    3.025        1     525     2.06
book_cl_elong
                        effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath    lemma
case>      from       0.512475 -0.000266   1  0.262630      0.44611    1.123
obl<       higher     0.504366  0.000189   1  0.254385      0.03977    3.025
conj<conj> waterfowl -0.500098  0.000708   2  0.250098      0.31645   -1.045
case>      of         0.497451 -0.001521   3  0.247457      0.09887    1.406
conj<conj> marmot    -0.496653  0.001062   3  0.246664      0.00000   -5.142
           hedgehog  -0.487617  0.000708   2  0.237771      0.12864   -1.584
           squirrel  -0.486893  0.006020  17  0.237065      0.00000   -2.061
           seabird   -0.485202  0.000708   2  0.235421      0.15991   -1.465
case>      in         0.482628 -0.000417   1  0.232930      0.21328    1.833

                      test_Nx  test_N  test_st
arcpath    lemma
case>      from             1     525     0.76
obl<       higher           1     525     2.06
conj<conj> waterfowl        2     525    -1.00
case>      of               3     525     1.65
conj<conj> marmot           3     525    -6.25
           hedgehog         2     525    -1.52
           squirrel        17     525    -5.86
           seabird          2     525    -1.41
case>      in               1     525     1.25
cluster ====> 9
np.sqrt(eigvals)
[0.34838879 0.47693821 0.51050328 0.53708375 0.61027253 0.69511422
 0.83622693 1.05344033]
cl_elong_a, cl_elong_v.round(2)
1.2597541283848959 [ 0.1   0.02 -0.13  0.77  0.59  0.09  0.07 -0.09]
cluster data sample, mean shift
(2384, 8)                                   0         1         2         3         4  \
token_id
Sci-501e_7_squirrel-5      0.637601 -0.684479  0.628093  0.609925  0.372686
Ven-77c9_97_arthropods-16 -0.247887 -0.332420 -1.739143  1.609059 -0.349564
Ham-9078_102_sharks-13    -1.327506  0.625702  0.435497 -0.671847 -0.273906

                                  5         6         7
token_id
Sci-501e_7_squirrel-5     -1.470967 -0.415595  1.297738
Ven-77c9_97_arthropods-16  0.147505  0.889617  0.159340
Ham-9078_102_sharks-13     0.541869  0.840101  0.022440
cluster data elongation along main axis
                       effect        Dx   N      eff2
arcpath lemma
det>    those       -0.958516  0.000032   1  0.918753
        both        -0.953254  0.000482   4  0.908693
        no          -0.931955  0.000543   4  0.868541
        some        -0.929061  0.001081  23  0.863154
        any         -0.927626  0.000177   8  0.860490
amod>   predatory    0.925152  0.000151   5  0.855906
        terrestrial  0.924368  0.000452   8  0.854456
det>    a           -0.922012  0.001334  63  0.850106
        each        -0.921188  0.000130   1  0.848587
amod>   most         0.920634  0.000369  13  0.847567
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                   token         x
arcpath lemma
amod>   most   Art-1308_168_arthropods-2  0.508565
        most       Bov-d455_162_bovids-2  0.793022
        most      Col-6d94_171_plants-29 -0.619072
        most         Dra-242f_8_plants-4  1.234355
        most        Eur-35e8_138_bird-12  1.027774
...                                  ...       ...
det>    some         Too-567c_25_birds-2 -0.684618
        some       Too-567c_343_birds-33 -0.566455
        some       Too-567c_48_animals-2 -1.721029
        some      Ven-071d_69_lizards-23 -1.025333
        those     Swa-27b4_32_animals-36 -0.862943

[130 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (2384,)
ftok (130, 2)
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Lil-8f8e_2_Liliopsida-1     -0.570984
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2371, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2379, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Cro-0859_276_crocodile-61    0.667533
Pra-7b55_29_Rodentia-2       1.196157
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2376, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2321, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2376, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2380, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2383, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2380, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2361, dtype: float64
x0 token_id
Sci-501e_7_squirrel-5        0.389883
Ven-77c9_97_arthropods-16    1.290315
Ham-9078_102_sharks-13      -0.757125
Ani-161e_84_animals-4        0.356346
Cro-0859_276_crocodile-61    0.667533
                               ...
Cet-5f63_400_animals-17      1.231640
Jel-28f4_51_jellyfish-11     0.488976
Gree5e5_4_beetles-3         -0.000649
Art-1308_168_arthropods-2    0.508565
Rep-aa64_32_animals-26       0.039188
Name: x, Length: 2383, dtype: float64
Spearman results
feat_tests
                     test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath lemma
amod>   most             0.00002    0.955       13    2384     4.33
        predatory        0.32219    0.353        5    2384     0.99
        terrestrial      0.02573    0.629        8    2384     2.23
det>    a                0.00002   -0.429       63    2384    -4.23
        any              0.27835   -0.306        8    2384    -1.08
        both             0.04212   -0.810        4    2384    -2.03
        each             0.81657    0.185        1    2384     0.23
        no               0.82672   -0.087        4    2384    -0.22
        some             0.00000   -0.938       23    2384    -5.66
        those            0.29030   -0.843        1    2384    -1.06
book_cl_elong
                       effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath lemma
det>    those       -0.958516  0.000032   1  0.918753      0.29030   -0.843
        both        -0.953254  0.000482   4  0.908693      0.04212   -0.810
        no          -0.931955  0.000543   4  0.868541      0.82672   -0.087
        some        -0.929061  0.001081  23  0.863154      0.00000   -0.938
        any         -0.927626  0.000177   8  0.860490      0.27835   -0.306
amod>   predatory    0.925152  0.000151   5  0.855906      0.32219    0.353
        terrestrial  0.924368  0.000452   8  0.854456      0.02573    0.629
det>    a           -0.922012  0.001334  63  0.850106      0.00002   -0.429
amod>   most         0.920634  0.000369  13  0.847567      0.00002    0.955

                     test_Nx  test_N  test_st
arcpath lemma
det>    those              1    2384    -1.06
        both               4    2384    -2.03
        no                 4    2384    -0.22
        some              23    2384    -5.66
        any                8    2384    -1.08
amod>   predatory          5    2384     0.99
        terrestrial        8    2384     2.23
det>    a                 63    2384    -4.23
amod>   most              13    2384     4.33
===========  end ==============
checking for data/q_cluster/BGM_full_covar_topic.pkl
BGM loaded
bgm.predict(my_ica_data)).value_counts()
4    8896
0    6276
5    5179
8    5004
1    4837
9    3572
6    2254
7    1892
3    1364
2     259
Name: count, dtype: int64
clust_feats (80022, 2)
                  cluster  freq
arcpath    lemma
case>      of           5  2803
det>       the          4  2236
cc>        and          9  1723
nsubj<cop> be           4  1693
conj>cc>   and          0  1583
=========================
clust_f_df pivot table (39715, 10)
clust_p_df is the probability distribution cluster-wise
                                0         1    2    3         4    5  \
arcpath         lemma
acl:relcl<      animal   0.000041  0.000022  0.0  0.0  0.000000  0.0
acl:relcl<case> in       0.000020  0.000000  0.0  0.0  0.000000  0.0
                include  0.000041  0.000000  0.0  0.0  0.000000  0.0
                of       0.000061  0.000044  0.0  0.0  0.000018  0.0
                with     0.000041  0.000000  0.0  0.0  0.000000  0.0

                                6    7    8    9
arcpath         lemma
acl:relcl<      animal   0.000000  0.0  0.0  0.0
acl:relcl<case> in       0.000035  0.0  0.0  0.0
                include  0.000000  0.0  0.0  0.0
                of       0.000000  0.0  0.0  0.0
                with     0.000000  0.0  0.0  0.0
=========================
Elementwise relative entropy by clusters, feature-wise
                            0         1         2         3         4  \
arcpath       lemma
det>          the    0.010605  0.018945 -0.006144  0.000000  0.033138
case>         of     0.002828 -0.001154 -0.002765  0.000000 -0.001857
cc>           and   -0.000607 -0.001740 -0.003679  0.000000 -0.003533
conj<conj>cc> and   -0.000464 -0.001159  0.003259  0.000000 -0.000476
conj>cc>      and    0.045635 -0.002840 -0.002810 -0.002055 -0.002602

                            5         6         7         8         9
arcpath       lemma
det>          the    0.020697  0.009021 -0.005791 -0.003572 -0.006132
case>         of     0.158360 -0.003672 -0.000619 -0.001101  0.000000
cc>           and    0.000000 -0.003413  0.006159 -0.000537  0.123504
conj<conj>cc> and    0.000000 -0.002567  0.065665  0.000000  0.054071
conj>cc>      and   -0.002335  0.051015 -0.001236 -0.002215 -0.000810
========== clust_featdx_df ===============

                                              Dx     N
cluster arcpath              lemma
1       nsubj:pass<obl>case> in         0.013379   307
8       appos>conj>cc>       and        0.024966   195
3       appos>               behaviour  0.039804    37
1       det>                 the        0.018945  1425
0       det>                 the        0.010605  1252
=========================
pred_feats
feat_v
                                  0         1         2         3         4  \
arcpath          lemma
acl:relcl>nsubj> that     -0.062988 -0.031006 -0.225952  0.068970 -0.026001
                 which    -0.026993 -0.062988 -0.218018  0.080017  0.065979
amod>            african   0.415039  0.003000 -0.490967  0.591797  0.271973
                 common    0.469971  0.033997 -0.514160  0.641113  0.316895
                 european  0.458008  0.032990 -0.497070  0.551758  0.262939

                                  5         6         7
arcpath          lemma
acl:relcl>nsubj> that     -0.140991  0.068970 -0.194946
                 which    -0.091980  0.182983 -0.238037
amod>            african  -0.340088  0.029999 -0.014000
                 common   -0.314941  0.091980  0.020996
                 european -0.368896  0.104004  0.093994
mean_norm
[[-0.12  0.21  0.2  -0.26  0.25 -0.23 -0.17 -0.83]
 [ 0.72 -0.13 -0.35 -0.07 -0.07  0.45 -0.23  0.28]
 [ 0.15 -0.2  -0.01 -0.21 -0.15  0.03  0.93 -0.01]
 [-0.46  0.08  0.69  0.23 -0.35 -0.08 -0.22  0.28]
 [-0.12 -0.04 -0.15 -0.07 -0.66  0.03 -0.51  0.52]
 [-0.26 -0.03  0.2  -0.24  0.88  0.01 -0.11  0.22]
 [ 0.22 -0.16 -0.38 -0.16  0.05 -0.08 -0.08 -0.86]
 [-0.1  -0.   -0.12  0.05 -0.1   0.07  0.98  0.02]
 [-0.35 -0.15  0.64  0.34 -0.33 -0.37 -0.15  0.26]
 [-0.49  0.1  -0.38  0.18 -0.46  0.22  0.49  0.28]]
cos_predict.head(5)
                            0         1         2         3         4  \
arcpath       lemma
conj>cc>      and    0.113933 -0.099139  0.050291 -0.162928 -0.085752
obl<cop>      be     0.129717 -0.095287  0.153824 -0.247292 -0.230546
obl<aux:pass> be    -0.148502  0.245953 -0.080672 -0.471835 -0.229989
case>         to    -0.200182  0.289855 -0.037447 -0.520856 -0.280101
det>          the   -0.236019  0.278817 -0.003519 -0.483198 -0.209115

                            5         6         7         8         9
arcpath       lemma
conj>cc>      and   -0.119202  0.238046  0.093284 -0.094747  0.086193
obl<cop>      be    -0.069254  0.274914  0.194389 -0.170507  0.076603
obl<aux:pass> be    -0.118670  0.233154  0.025117 -0.230780 -0.099126
case>         to    -0.109692  0.206382  0.083583 -0.277058 -0.080214
det>          the   -0.114972  0.149592  0.093123 -0.237219 -0.057751
score_predict.head(5)
                         0      1    2    3      4      5      6      7    8  \
arcpath       lemma
conj>cc>      and    0.586  0.046  0.0  0.0  0.316  0.040  0.002  0.002  0.0
obl<cop>      be     0.737  0.063  0.0  0.0  0.157  0.026  0.004  0.004  0.0
obl<aux:pass> be     0.634  0.107  0.0  0.0  0.236  0.015  0.004  0.002  0.0
case>         to     0.662  0.142  0.0  0.0  0.175  0.010  0.005  0.003  0.0
det>          the    0.632  0.130  0.0  0.0  0.216  0.011  0.005  0.003  0.0

                         9
arcpath       lemma
conj>cc>      and    0.007
obl<cop>      be     0.008
obl<aux:pass> be     0.001
case>         to     0.001
det>          the    0.002
                            0         1         2         3         4  \
arcpath       lemma
conj>cc>      and    0.032282  0.002374  0.003589  0.000995  0.001702
obl<cop>      be     0.008279  0.001154  0.000000  0.000000  0.000123
obl<aux:pass> be     0.008341  0.007099  0.000538  0.000000  0.000456
case>         to     0.007749  0.002592  0.000000  0.000000  0.000228
det>          the    0.025532  0.031033  0.005384  0.000000  0.039227

                            5         6         7         8         9
arcpath       lemma
conj>cc>      and    0.001296  0.034480  0.000423  0.001156  0.000229
obl<cop>      be     0.000086  0.001919  0.000000  0.000000  0.000000
obl<aux:pass> be     0.000259  0.002652  0.000000  0.000000  0.000000
case>         to     0.006048  0.001989  0.000000  0.000000  0.000038
det>          the    0.032109  0.024394  0.004089  0.001461  0.005307
=========== Internal structure in cluster==============
cluster ====> 0
np.sqrt(eigvals)
[0.32799058 0.45370549 0.54230341 0.60692332 0.69363321 0.82727651
 0.90444641 1.08223637]
cl_elong_a, cl_elong_v.round(2)
1.1965732430453417 [-0.01  0.04 -0.28 -0.07  0.18  0.32 -0.8  -0.37]
cluster data sample, mean shift
(6258, 8)                               0         1         2         3         4  \
token_id
Cli-c809_26_animal-15 -0.308392 -0.707459  0.401081  1.654279  0.020958
Kag-2289_76_worms-15   0.758170  0.477786  0.229863 -0.785759  0.062551
Boi-e3d6_40_humans-23  0.276220  0.414552  1.083768 -0.495066  0.089636

                              5         6         7
token_id
Cli-c809_26_animal-15 -0.358530  0.153425  0.260352
Kag-2289_76_worms-15   1.438481 -0.628320 -1.463834
Boi-e3d6_40_humans-23  0.390080  0.150188  0.598176
cluster data elongation along main axis
                           effect            Dx  N      eff2
arcpath    lemma
conj<conj> martin       -0.814134  2.544002e-05  1  0.662814
           Gallai       -0.796491  2.661539e-05  1  0.634399
           eagle        -0.783533 -5.591858e-05  1  0.613924
           capuching    -0.738240  2.661539e-05  1  0.544998
conj>      Cricetidae    0.733911  9.391215e-05  2  0.538625
           nigricollis   0.732839  9.391215e-05  2  0.537052
           Ornithischia  0.724404  6.869657e-05  2  0.524761
           Reptilia      0.723743  4.107193e-07  1  0.523803
           Stegosauria   0.723654  7.823675e-05  3  0.523675
           Saurischia    0.723031  1.876529e-05  1  0.522774
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                token         x
arcpath    lemma
conj<conj> Gallai                 Gir-cc25_27_Rook-83 -1.532002
           capuching          Ceb-b443_19_capuchin-18 -1.070245
           eagle               Nor-4d51_285_eagles-16 -0.514836
           martin              Coma03b_19_swallows-18 -1.121982
conj>      Cricetidae          New-caad_18_Rodentia-5  0.755989
           Cricetidae          Shr-2a0f_11_Muridae-14  1.026054
           Ornithischia     Pte-62aa_25_Saurischia-33  1.014217
           Ornithischia      Sau-6bc5_51_Theropoda-20  0.693645
           Reptilia           Cro-9102_581_Amphibia-5  0.314303
           Saurischia    Orn-f740_113_Ornithischia-35  1.327374
           Stegosauria     Thy-db39_14_Ankylosauria-8  0.449961
           Stegosauria    Thy-db39_56_Ankylosauria-28  1.071223
           Stegosauria      Thy-db39_6_Ankylosauria-9  0.736581
           nigricollis            Har-f3ef_43_hare-61  0.467802
           nigricollis            Lep-7440_49_hare-61  0.467802
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (6258,)
ftok (15, 2)
x0 token_id
Cli-c809_26_animal-15          -0.582341
Kag-2289_76_worms-15            1.521019
Boi-e3d6_40_humans-23          -0.450185
Gol-1dbf_103_eagle-15           0.433982
Scr-c9e6_18_raptor-24           0.354069
                                  ...
Req-2240_50_shark-59           -1.357068
Cyn-57e5_3_dog-2               -1.092085
Bla-30a4_100_blackberries-18    1.077862
Spa-e46a_198_catfish-2          0.458598
Lil-43fd_144_Tulipa-1           0.354791
Name: x, Length: 6257, dtype: float64
x0 token_id
Cli-c809_26_animal-15          -0.582341
Kag-2289_76_worms-15            1.521019
Boi-e3d6_40_humans-23          -0.450185
Gol-1dbf_103_eagle-15           0.433982
Scr-c9e6_18_raptor-24           0.354069
                                  ...
Req-2240_50_shark-59           -1.357068
Cyn-57e5_3_dog-2               -1.092085
Bla-30a4_100_blackberries-18    1.077862
Spa-e46a_198_catfish-2          0.458598
Lil-43fd_144_Tulipa-1           0.354791
Name: x, Length: 6257, dtype: float64
x0 token_id
Cli-c809_26_animal-15          -0.582341
Kag-2289_76_worms-15            1.521019
Boi-e3d6_40_humans-23          -0.450185
Gol-1dbf_103_eagle-15           0.433982
Scr-c9e6_18_raptor-24           0.354069
                                  ...
Req-2240_50_shark-59           -1.357068
Cyn-57e5_3_dog-2               -1.092085
Bla-30a4_100_blackberries-18    1.077862
Spa-e46a_198_catfish-2          0.458598
Lil-43fd_144_Tulipa-1           0.354791
Name: x, Length: 6257, dtype: float64
x0 token_id
Cli-c809_26_animal-15          -0.582341
Kag-2289_76_worms-15            1.521019
Boi-e3d6_40_humans-23          -0.450185
Gol-1dbf_103_eagle-15           0.433982
Scr-c9e6_18_raptor-24           0.354069
                                  ...
Req-2240_50_shark-59           -1.357068
Cyn-57e5_3_dog-2               -1.092085
Bla-30a4_100_blackberries-18    1.077862
Spa-e46a_198_catfish-2          0.458598
Lil-43fd_144_Tulipa-1           0.354791
Name: x, Length: 6257, dtype: float64
x0 token_id
Cli-c809_26_animal-15          -0.582341
Kag-2289_76_worms-15            1.521019
Boi-e3d6_40_humans-23          -0.450185
Gol-1dbf_103_eagle-15           0.433982
Scr-c9e6_18_raptor-24           0.354069
                                  ...
Req-2240_50_shark-59           -1.357068
Cyn-57e5_3_dog-2               -1.092085
Bla-30a4_100_blackberries-18    1.077862
Spa-e46a_198_catfish-2          0.458598
Lil-43fd_144_Tulipa-1           0.354791
Name: x, Length: 6256, dtype: float64
x0 token_id
Cli-c809_26_animal-15          -0.582341
Kag-2289_76_worms-15            1.521019
Boi-e3d6_40_humans-23          -0.450185
Gol-1dbf_103_eagle-15           0.433982
Scr-c9e6_18_raptor-24           0.354069
                                  ...
Req-2240_50_shark-59           -1.357068
Cyn-57e5_3_dog-2               -1.092085
Bla-30a4_100_blackberries-18    1.077862
Spa-e46a_198_catfish-2          0.458598
Lil-43fd_144_Tulipa-1           0.354791
Name: x, Length: 6256, dtype: float64
x0 token_id
Cli-c809_26_animal-15          -0.582341
Kag-2289_76_worms-15            1.521019
Boi-e3d6_40_humans-23          -0.450185
Gol-1dbf_103_eagle-15           0.433982
Scr-c9e6_18_raptor-24           0.354069
                                  ...
Req-2240_50_shark-59           -1.357068
Cyn-57e5_3_dog-2               -1.092085
Bla-30a4_100_blackberries-18    1.077862
Spa-e46a_198_catfish-2          0.458598
Lil-43fd_144_Tulipa-1           0.354791
Name: x, Length: 6257, dtype: float64
x0 token_id
Cli-c809_26_animal-15          -0.582341
Kag-2289_76_worms-15            1.521019
Boi-e3d6_40_humans-23          -0.450185
Gol-1dbf_103_eagle-15           0.433982
Scr-c9e6_18_raptor-24           0.354069
                                  ...
Req-2240_50_shark-59           -1.357068
Cyn-57e5_3_dog-2               -1.092085
Bla-30a4_100_blackberries-18    1.077862
Spa-e46a_198_catfish-2          0.458598
Lil-43fd_144_Tulipa-1           0.354791
Name: x, Length: 6257, dtype: float64
x0 token_id
Cli-c809_26_animal-15          -0.582341
Kag-2289_76_worms-15            1.521019
Boi-e3d6_40_humans-23          -0.450185
Gol-1dbf_103_eagle-15           0.433982
Scr-c9e6_18_raptor-24           0.354069
                                  ...
Req-2240_50_shark-59           -1.357068
Cyn-57e5_3_dog-2               -1.092085
Bla-30a4_100_blackberries-18    1.077862
Spa-e46a_198_catfish-2          0.458598
Lil-43fd_144_Tulipa-1           0.354791
Name: x, Length: 6255, dtype: float64
x0 token_id
Cli-c809_26_animal-15          -0.582341
Kag-2289_76_worms-15            1.521019
Boi-e3d6_40_humans-23          -0.450185
Gol-1dbf_103_eagle-15           0.433982
Scr-c9e6_18_raptor-24           0.354069
                                  ...
Req-2240_50_shark-59           -1.357068
Cyn-57e5_3_dog-2               -1.092085
Bla-30a4_100_blackberries-18    1.077862
Spa-e46a_198_catfish-2          0.458598
Lil-43fd_144_Tulipa-1           0.354791
Name: x, Length: 6256, dtype: float64
Spearman results
feat_tests
                         test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
conj<conj> Gallai            0.00677   -1.574        1    6258    -2.71
           capuching         0.05578   -1.112        1    6258    -1.91
           eagle             0.33864   -0.556        1    6258    -0.96
           martin            0.04531   -1.163        1    6258    -2.00
conj>      Cricetidae        0.03862    0.850        2    6258     2.07
           Ornithischia      0.04793    0.813        2    6258     1.98
           Reptilia          0.63849    0.273        1    6258     0.47
           Saurischia        0.02687    1.286        1    6258     2.21
           Stegosauria       0.03395    0.712        3    6258     2.12
           nigricollis       0.29925    0.427        2    6258     1.04
book_cl_elong
                           effect            Dx  N      eff2  test_pvalue  \
arcpath    lemma
conj<conj> martin       -0.814134  2.544002e-05  1  0.662814      0.04531
           Gallai       -0.796491  2.661539e-05  1  0.634399      0.00677
           eagle        -0.783533 -5.591858e-05  1  0.613924      0.33864
           capuching    -0.738240  2.661539e-05  1  0.544998      0.05578
conj>      Cricetidae    0.733911  9.391215e-05  2  0.538625      0.03862
           nigricollis   0.732839  9.391215e-05  2  0.537052      0.29925
           Ornithischia  0.724404  6.869657e-05  2  0.524761      0.04793
           Reptilia      0.723743  4.107193e-07  1  0.523803      0.63849
           Stegosauria   0.723654  7.823675e-05  3  0.523675      0.03395
           Saurischia    0.723031  1.876529e-05  1  0.522774      0.02687

                         test_dX  test_Nx  test_N  test_st
arcpath    lemma
conj<conj> martin         -1.163        1    6258    -2.00
           Gallai         -1.574        1    6258    -2.71
           eagle          -0.556        1    6258    -0.96
           capuching      -1.112        1    6258    -1.91
conj>      Cricetidae      0.850        2    6258     2.07
           nigricollis     0.427        2    6258     1.04
           Ornithischia    0.813        2    6258     1.98
           Reptilia        0.273        1    6258     0.47
           Stegosauria     0.712        3    6258     2.12
           Saurischia      1.286        1    6258     2.21
cluster ====> 1
np.sqrt(eigvals)
[0.35763613 0.56465091 0.6729666  0.73558597 0.91585212 1.0168548
 1.1775666  1.33196632]
cl_elong_a, cl_elong_v.round(2)
1.1311176096064157 [ 0.1  -0.98 -0.08  0.16 -0.01  0.01 -0.05  0.05]
cluster data sample, mean shift
(4805, 8)                                0         1         2         3         4  \
token_id
Min-e696_95_deer-24     1.101398 -0.217850  0.300074  1.408250  0.664699
Eur-d3a5_47_rabbit-4    0.452727  1.837853  0.727666  0.521972 -0.700952
Abe-4088_61_animals-15  1.086594 -0.241399  0.126680  0.472765  2.160090

                               5         6         7
token_id
Min-e696_95_deer-24    -0.944259  0.566778 -0.779567
Eur-d3a5_47_rabbit-4   -0.371306  0.035491  1.022848
Abe-4088_61_animals-15  0.509109  0.757491  0.350715
cluster data elongation along main axis

/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

                           effect        Dx  N      eff2
arcpath         lemma
nsubj<obj>conj> bird    -1.275181  0.000086  2  1.626086
                buffalo -1.248956  0.000037  1  1.559891
                snake   -1.129129  0.000086  2  1.274932
                turtle  -1.112352  0.000003  2  1.237327
                shark   -1.092524  0.000050  1  1.193609
                colour  -1.079654  0.000037  1  1.165653
                species -1.072816  0.000028  3  1.150934
                mouse   -1.057641  0.000050  1  1.118604
                frog    -1.033550  0.000028  3  1.068226
                rodent  -1.025442  0.000037  1  1.051531
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                              token         x
arcpath         lemma
nsubj<obj>conj> bird     Boa-7d46_71_constrictors-3 -4.525416
                bird         Kom-6ea1_112_dragons-3 -3.436012
                buffalo        Wil-28c2_2_buffalo-4 -1.866257
                colour     Bla-3ee3_82_blackbuck-26 -0.088108
                frog        Eur-1ed4_36_Hedgehogs-1 -4.198634
                frog     Dip-c98d_261_vertebrates-2 -3.803585
                frog       Gia-bc1d_69_salamander-4 -4.339201
                mouse        Ser-47ca_100_rodents-7 -1.662727
                rodent      Eur-1ed4_36_Hedgehogs-1 -4.198634
                shark         Ham-9078_102_sharks-2 -2.647458
                snake            Gra-2e39_2_snake-3 -1.588313
                snake       Eur-1ed4_36_Hedgehogs-1 -4.198634
                species  Dip-c98d_261_vertebrates-2 -3.803585
                species       Bov-d455_105_bovids-8 -3.029682
                species        Top-df25_97_acacia-2 -1.957448
                turtle       Coa-44f0_176_animals-2 -1.823541
                turtle   Dip-c98d_261_vertebrates-2 -3.803585
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (4805,)
ftok (17, 2)
x0 token_id
Min-e696_95_deer-24        0.453191
Eur-d3a5_47_rabbit-4      -1.667668
Abe-4088_61_animals-15     0.387037
Moo899d_9_reptiles-19     -0.765449
Fro-2392_130_frog-6        0.311131
                             ...
Ear-61cf_15_seals-2        2.463842
Bea548d_12_rodents-9       1.518688
Ear750e_7_seal-5           2.251081
Flo0d28_3_plants-8        -0.053649
Cer-4e1c_13_dinosaurs-7    1.115499
Name: x, Length: 4803, dtype: float64
x0 token_id
Min-e696_95_deer-24        0.453191
Eur-d3a5_47_rabbit-4      -1.667668
Abe-4088_61_animals-15     0.387037
Moo899d_9_reptiles-19     -0.765449
Fro-2392_130_frog-6        0.311131
                             ...
Ear-61cf_15_seals-2        2.463842
Bea548d_12_rodents-9       1.518688
Ear750e_7_seal-5           2.251081
Flo0d28_3_plants-8        -0.053649
Cer-4e1c_13_dinosaurs-7    1.115499
Name: x, Length: 4804, dtype: float64
x0 token_id
Min-e696_95_deer-24        0.453191
Eur-d3a5_47_rabbit-4      -1.667668
Abe-4088_61_animals-15     0.387037
Moo899d_9_reptiles-19     -0.765449
Fro-2392_130_frog-6        0.311131
                             ...
Ear-61cf_15_seals-2        2.463842
Bea548d_12_rodents-9       1.518688
Ear750e_7_seal-5           2.251081
Flo0d28_3_plants-8        -0.053649
Cer-4e1c_13_dinosaurs-7    1.115499
Name: x, Length: 4804, dtype: float64
x0 token_id
Min-e696_95_deer-24        0.453191
Eur-d3a5_47_rabbit-4      -1.667668
Abe-4088_61_animals-15     0.387037
Moo899d_9_reptiles-19     -0.765449
Fro-2392_130_frog-6        0.311131
                             ...
Ear-61cf_15_seals-2        2.463842
Bea548d_12_rodents-9       1.518688
Ear750e_7_seal-5           2.251081
Flo0d28_3_plants-8        -0.053649
Cer-4e1c_13_dinosaurs-7    1.115499
Name: x, Length: 4802, dtype: float64
x0 token_id
Min-e696_95_deer-24        0.453191
Eur-d3a5_47_rabbit-4      -1.667668
Abe-4088_61_animals-15     0.387037
Moo899d_9_reptiles-19     -0.765449
Fro-2392_130_frog-6        0.311131
                             ...
Ear-61cf_15_seals-2        2.463842
Bea548d_12_rodents-9       1.518688
Ear750e_7_seal-5           2.251081
Flo0d28_3_plants-8        -0.053649
Cer-4e1c_13_dinosaurs-7    1.115499
Name: x, Length: 4804, dtype: float64
x0 token_id
Min-e696_95_deer-24        0.453191
Eur-d3a5_47_rabbit-4      -1.667668
Abe-4088_61_animals-15     0.387037
Moo899d_9_reptiles-19     -0.765449
Fro-2392_130_frog-6        0.311131
                             ...
Ear-61cf_15_seals-2        2.463842
Bea548d_12_rodents-9       1.518688
Ear750e_7_seal-5           2.251081
Flo0d28_3_plants-8        -0.053649
Cer-4e1c_13_dinosaurs-7    1.115499
Name: x, Length: 4804, dtype: float64
x0 token_id
Min-e696_95_deer-24        0.453191
Eur-d3a5_47_rabbit-4      -1.667668
Abe-4088_61_animals-15     0.387037
Moo899d_9_reptiles-19     -0.765449
Fro-2392_130_frog-6        0.311131
                             ...
Ear-61cf_15_seals-2        2.463842
Bea548d_12_rodents-9       1.518688
Ear750e_7_seal-5           2.251081
Flo0d28_3_plants-8        -0.053649
Cer-4e1c_13_dinosaurs-7    1.115499
Name: x, Length: 4804, dtype: float64
x0 token_id
Min-e696_95_deer-24        0.453191
Eur-d3a5_47_rabbit-4      -1.667668
Abe-4088_61_animals-15     0.387037
Moo899d_9_reptiles-19     -0.765449
Fro-2392_130_frog-6        0.311131
                             ...
Ear-61cf_15_seals-2        2.463842
Bea548d_12_rodents-9       1.518688
Ear750e_7_seal-5           2.251081
Flo0d28_3_plants-8        -0.053649
Cer-4e1c_13_dinosaurs-7    1.115499
Name: x, Length: 4803, dtype: float64
x0 token_id
Min-e696_95_deer-24        0.453191
Eur-d3a5_47_rabbit-4      -1.667668
Abe-4088_61_animals-15     0.387037
Moo899d_9_reptiles-19     -0.765449
Fro-2392_130_frog-6        0.311131
                             ...
Ear-61cf_15_seals-2        2.463842
Bea548d_12_rodents-9       1.518688
Ear750e_7_seal-5           2.251081
Flo0d28_3_plants-8        -0.053649
Cer-4e1c_13_dinosaurs-7    1.115499
Name: x, Length: 4802, dtype: float64
x0 token_id
Min-e696_95_deer-24        0.453191
Eur-d3a5_47_rabbit-4      -1.667668
Abe-4088_61_animals-15     0.387037
Moo899d_9_reptiles-19     -0.765449
Fro-2392_130_frog-6        0.311131
                             ...
Ear-61cf_15_seals-2        2.463842
Bea548d_12_rodents-9       1.518688
Ear750e_7_seal-5           2.251081
Flo0d28_3_plants-8        -0.053649
Cer-4e1c_13_dinosaurs-7    1.115499
Name: x, Length: 4803, dtype: float64
Spearman results
feat_tests
                         test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath         lemma
nsubj<obj>conj> bird         0.00000   -4.019        2    4805    -4.75
                buffalo      0.11257   -1.904        1    4805    -1.59
                colour       0.91695   -0.125        1    4805    -0.10
                frog         0.00000   -4.153        3    4805    -6.02
                mouse        0.15648   -1.700        1    4805    -1.42
                rodent       0.00041   -4.237        1    4805    -3.54
                shark        0.02520   -2.685        1    4805    -2.24
                snake        0.00055   -2.932        2    4805    -3.46
                species      0.00002   -2.969        3    4805    -4.29
                turtle       0.00077   -2.852        2    4805    -3.36
book_cl_elong
                           effect        Dx  N      eff2  test_pvalue  \
arcpath         lemma
nsubj<obj>conj> bird    -1.275181  0.000086  2  1.626086      0.00000
                buffalo -1.248956  0.000037  1  1.559891      0.11257
                snake   -1.129129  0.000086  2  1.274932      0.00055
                turtle  -1.112352  0.000003  2  1.237327      0.00077
                shark   -1.092524  0.000050  1  1.193609      0.02520
                colour  -1.079654  0.000037  1  1.165653      0.91695
                species -1.072816  0.000028  3  1.150934      0.00002
                mouse   -1.057641  0.000050  1  1.118604      0.15648
                frog    -1.033550  0.000028  3  1.068226      0.00000
                rodent  -1.025442  0.000037  1  1.051531      0.00041

                         test_dX  test_Nx  test_N  test_st
arcpath         lemma
nsubj<obj>conj> bird      -4.019        2    4805    -4.75
                buffalo   -1.904        1    4805    -1.59
                snake     -2.932        2    4805    -3.46
                turtle    -2.852        2    4805    -3.36
                shark     -2.685        1    4805    -2.24
                colour    -0.125        1    4805    -0.10
                species   -2.969        3    4805    -4.29
                mouse     -1.700        1    4805    -1.42
                frog      -4.153        3    4805    -6.02
                rodent    -4.237        1    4805    -3.54
cluster ====> 2
np.sqrt(eigvals)
[1.60212361 1.87888921 1.95575461 2.22891161 2.64418856 3.28685027
 4.47160683 6.77721923]
cl_elong_a, cl_elong_v.round(2)
1.515611609504003 [-0.17 -0.02  0.77 -0.55  0.18 -0.05 -0.22 -0.  ]
cluster data sample, mean shift

(259, 8)                                    0         1         2         3         4  \
token_id
Pap-75c9_71_swallowtail-33 -2.900455 -0.709619 -0.560019 -1.477165 -2.005501
Squ-4431_100_squirrels-32  -1.442266 -0.045520  0.755888 -3.248267  1.026658
Dug-d1d0_10_Dugong-39       1.723697 -2.659033  1.229661  0.224838 -1.140864

                                   5         6         7
token_id
Pap-75c9_71_swallowtail-33 -2.257694 -3.617133  0.513713
Squ-4431_100_squirrels-32  -3.235912 -3.627350  0.417434
Dug-d1d0_10_Dugong-39      -4.776824 -4.301215  0.790131
cluster data elongation along main axis
                        effect        Dx  N      eff2
arcpath lemma
amod>   other        -0.870077 -0.000525  2  0.757033
        various      -0.850802  0.000072  1  0.723864
        terrestrial  -0.825562  0.000017  1  0.681553
        several      -0.824688  0.000121  1  0.680110
        intermediate -0.818810  0.000349  1  0.670450
        small        -0.815473 -0.000317  4  0.664996
        similar      -0.809510  0.000184  1  0.655306
        certain      -0.802992  0.000141  1  0.644796
        native       -0.784129 -0.000015  1  0.614858
        common       -0.773254 -0.001101  3  0.597921
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                           token          x
arcpath lemma
amod>   certain       Blu-41f9_92_ichthyosaurs-8  -5.064866
        common                 Des-ca42_5_bat-26   6.512571
        common         Sep-9969_11_cuttlefish-72  10.611827
        common              Pap-75c9_45_raven-34   4.003099
        intermediate         Hor-ab9c_205_bat-41   0.618230
        native            Hed-8dc6_39_monogyna-2  -4.282905
        other         Apa-3e1a_301_vertebrates-2  -1.446084
        other         Bro-f1dc_297_vertebrates-2  -1.766890
        several             Pas-a544_48_fungi-12  -0.402049
        similar        Chi-0753_14_salamander-29  -1.972490
        small                 Roe-b5ac_55_deer-8   0.244874
        small         Com-3e4d_97_vertebrates-53   1.912784
        small               Cri-fe01_6_mammals-5  -0.284217
        small             Ech-0064_29_mammals-47   0.355400
        terrestrial     Squ-4431_100_squirrels-5  -3.275849
        various             Ste-0d9f_40_squid-35   0.013446
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (259,)
ftok (16, 2)
x0 token_id
Pap-75c9_71_swallowtail-33    1.406252
Squ-4431_100_squirrels-32     3.723840
Dug-d1d0_10_Dugong-39         1.542659
Fri-5711_3_fritillary-9      -2.825063
Har-f3ef_44_hare-2            1.011087
                                ...
Ani-2170_6_reptiles-43        2.240057
Ste-0d9f_40_squid-35          0.013446
Coa-e8c3_75_boa-13            3.164663
Map-fd86_51_dinosaurs-34      1.396137
Hed-8dc6_39_monogyna-2       -4.282905
Name: x, Length: 258, dtype: float64
x0 token_id
Pap-75c9_71_swallowtail-33    1.406252
Squ-4431_100_squirrels-32     3.723840
Dug-d1d0_10_Dugong-39         1.542659
Fri-5711_3_fritillary-9      -2.825063
Har-f3ef_44_hare-2            1.011087
                                ...
Ani-2170_6_reptiles-43        2.240057
Ste-0d9f_40_squid-35          0.013446
Coa-e8c3_75_boa-13            3.164663
Map-fd86_51_dinosaurs-34      1.396137
Hed-8dc6_39_monogyna-2       -4.282905
Name: x, Length: 256, dtype: float64
x0 token_id
Pap-75c9_71_swallowtail-33    1.406252
Squ-4431_100_squirrels-32     3.723840
Dug-d1d0_10_Dugong-39         1.542659
Fri-5711_3_fritillary-9      -2.825063
Har-f3ef_44_hare-2            1.011087
                                ...
Ani-2170_6_reptiles-43        2.240057
Ste-0d9f_40_squid-35          0.013446
Coa-e8c3_75_boa-13            3.164663
Map-fd86_51_dinosaurs-34      1.396137
Hed-8dc6_39_monogyna-2       -4.282905
Name: x, Length: 258, dtype: float64
x0 token_id
Pap-75c9_71_swallowtail-33    1.406252
Squ-4431_100_squirrels-32     3.723840
Dug-d1d0_10_Dugong-39         1.542659
Fri-5711_3_fritillary-9      -2.825063
Har-f3ef_44_hare-2            1.011087
                                ...
Eur-bc75_400_hawk-144        -2.024761
Ani-2170_6_reptiles-43        2.240057
Ste-0d9f_40_squid-35          0.013446
Coa-e8c3_75_boa-13            3.164663
Map-fd86_51_dinosaurs-34      1.396137
Name: x, Length: 258, dtype: float64
x0 token_id
Pap-75c9_71_swallowtail-33    1.406252
Squ-4431_100_squirrels-32     3.723840
Dug-d1d0_10_Dugong-39         1.542659
Fri-5711_3_fritillary-9      -2.825063
Har-f3ef_44_hare-2            1.011087
                                ...
Ani-2170_6_reptiles-43        2.240057
Ste-0d9f_40_squid-35          0.013446
Coa-e8c3_75_boa-13            3.164663
Map-fd86_51_dinosaurs-34      1.396137
Hed-8dc6_39_monogyna-2       -4.282905
Name: x, Length: 257, dtype: float64
x0 token_id
Pap-75c9_71_swallowtail-33    1.406252
Squ-4431_100_squirrels-32     3.723840
Dug-d1d0_10_Dugong-39         1.542659
Fri-5711_3_fritillary-9      -2.825063
Har-f3ef_44_hare-2            1.011087
                                ...
Ani-2170_6_reptiles-43        2.240057
Ste-0d9f_40_squid-35          0.013446
Coa-e8c3_75_boa-13            3.164663
Map-fd86_51_dinosaurs-34      1.396137
Hed-8dc6_39_monogyna-2       -4.282905
Name: x, Length: 258, dtype: float64
x0 token_id
Pap-75c9_71_swallowtail-33    1.406252
Squ-4431_100_squirrels-32     3.723840
Dug-d1d0_10_Dugong-39         1.542659
Fri-5711_3_fritillary-9      -2.825063
Har-f3ef_44_hare-2            1.011087
                                ...
Ani-2170_6_reptiles-43        2.240057
Ste-0d9f_40_squid-35          0.013446
Coa-e8c3_75_boa-13            3.164663
Map-fd86_51_dinosaurs-34      1.396137
Hed-8dc6_39_monogyna-2       -4.282905
Name: x, Length: 258, dtype: float64
x0 token_id
Pap-75c9_71_swallowtail-33    1.406252
Squ-4431_100_squirrels-32     3.723840
Dug-d1d0_10_Dugong-39         1.542659
Fri-5711_3_fritillary-9      -2.825063
Har-f3ef_44_hare-2            1.011087
                                ...
Ani-2170_6_reptiles-43        2.240057
Ste-0d9f_40_squid-35          0.013446
Coa-e8c3_75_boa-13            3.164663
Map-fd86_51_dinosaurs-34      1.396137
Hed-8dc6_39_monogyna-2       -4.282905
Name: x, Length: 255, dtype: float64
x0 token_id
Pap-75c9_71_swallowtail-33    1.406252
Squ-4431_100_squirrels-32     3.723840
Dug-d1d0_10_Dugong-39         1.542659
Fri-5711_3_fritillary-9      -2.825063
Har-f3ef_44_hare-2            1.011087
                                ...
Ani-2170_6_reptiles-43        2.240057
Ste-0d9f_40_squid-35          0.013446
Coa-e8c3_75_boa-13            3.164663
Map-fd86_51_dinosaurs-34      1.396137
Hed-8dc6_39_monogyna-2       -4.282905
Name: x, Length: 258, dtype: float64
x0 token_id
Pap-75c9_71_swallowtail-33    1.406252
Squ-4431_100_squirrels-32     3.723840
Dug-d1d0_10_Dugong-39         1.542659
Fri-5711_3_fritillary-9      -2.825063
Har-f3ef_44_hare-2            1.011087
                                ...
Eur-bc75_400_hawk-144        -2.024761
Ani-2170_6_reptiles-43        2.240057
Coa-e8c3_75_boa-13            3.164663
Map-fd86_51_dinosaurs-34      1.396137
Hed-8dc6_39_monogyna-2       -4.282905
Name: x, Length: 258, dtype: float64
Spearman results
feat_tests
                      test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath lemma
amod>   certain           0.06576   -5.100        1     259    -1.85
        common            0.00001    7.110        3     259     4.59
        intermediate      0.82759    0.606        1     259     0.22
        native            0.11986   -4.315        1     259    -1.56
        other             0.40649   -1.634        2     259    -0.83
        several           0.88030   -0.419        1     259    -0.15
        similar           0.47280   -1.995        1     259    -0.72
        small             0.69369    0.551        4     259     0.39
        terrestrial       0.23414   -3.304        1     259    -1.19
        various           0.99955   -0.002        1     259    -0.00
book_cl_elong
                       effect        Dx  N      eff2  test_pvalue  test_dX  \
arcpath lemma
amod>   other       -0.870077 -0.000525  2  0.757033      0.40649   -1.634
        various     -0.850802  0.000072  1  0.723864      0.99955   -0.002
        terrestrial -0.825562  0.000017  1  0.681553      0.23414   -3.304
        several     -0.824688  0.000121  1  0.680110      0.88030   -0.419
        similar     -0.809510  0.000184  1  0.655306      0.47280   -1.995
        certain     -0.802992  0.000141  1  0.644796      0.06576   -5.100
        native      -0.784129 -0.000015  1  0.614858      0.11986   -4.315

                     test_Nx  test_N  test_st
arcpath lemma
amod>   other              2     259    -0.83
        various            1     259    -0.00
        terrestrial        1     259    -1.19
        several            1     259    -0.15
        similar            1     259    -0.72
        certain            1     259    -1.85
        native             1     259    -1.56
cluster ====> 3
np.sqrt(eigvals)
[0.0258062  0.02844254 0.03586278 0.05496432 0.09422813 0.11088469
 0.12893851 0.17069969]
cl_elong_a, cl_elong_v.round(2)
1.3238844934223468 [ 0.33  0.4   0.13 -0.52  0.03 -0.58 -0.02  0.33]
cluster data sample, mean shift
(1364, 8)                                       0         1         2         3  \
token_id
Eur-987c_25_vole-3             0.020360 -0.097674  0.164753 -0.062351
Wal-cefe_41_ibex-2            -0.014069 -0.056637  0.113963  0.023487
Nar-f40f_72_pseudonarcissus-2  0.028163  0.024072  0.011681 -0.017651

                                      4         5         6         7
token_id
Eur-987c_25_vole-3             0.182066 -0.064258  0.006458 -0.074881
Wal-cefe_41_ibex-2             0.065547 -0.000911 -0.010427 -0.020640
Nar-f40f_72_pseudonarcissus-2  0.002086  0.018305  0.067365  0.068697
cluster data elongation along main axis
                              effect        Dx   N      eff2
arcpath            lemma
compound>amod>     bent     0.488034  0.003413   3  0.238177
                   green    0.442997  0.028197  25  0.196247
amod>              high    -0.418063  0.002109   2  0.174777
                   greater -0.396028  0.000424   1  0.156838
conj>              mouse   -0.351947  0.001884   2  0.123867
amod>advmod>       long     0.345163  0.014439  14  0.119137
nmod>case>         of       0.335411 -0.000485   2  0.112501
compound>amod>     black    0.332783  0.011286  10  0.110744
compound>compound> New     -0.327356  0.001995   2  0.107162
compound>amod>     arctic   0.325108  0.002095   2  0.105695
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                             token         x
arcpath            lemma
amod>              greater       Gre-c26f_74_bat-3 -0.070319
                   high     Hig81e8_2_fritillary-3  0.039973
                   high     Vio6842_8_fritillary-3  0.039973
amod>advmod>       long     Lon-6fc7_10_seahorse-4  0.039973
                   long     Lon-6fc7_17_seahorse-4 -0.105636
...                                            ...       ...
compound>compound> New          New-caad_12_rats-3 -0.019702
conj>              mouse        New-caad_10_rats-3 -0.165546
                   mouse        New-caad_12_rats-3 -0.019702
nmod>case>         of             Law5343_5_Bird-1  0.039973
                   of         New-d8c1_127_Birds-1  0.039973

[63 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (1364,)
ftok (63, 2)
x0 token_id
Eur-987c_25_vole-3               0.039545
Wal-cefe_41_ibex-2              -0.029092
Nar-f40f_72_pseudonarcissus-2    0.039973
Fie-7e8b_121_Fieldfare-1         0.069059
Gal-c07a_26_iguana-3            -0.039761
                                   ...
Mou338e_6_hares-2                0.039973
Ank-02ea_16_Ankylosauria-1      -0.063362
Roe-b5ac_174_deer-2             -0.096066
Com-264e_16_seadragon-2         -0.105636
Cyp-0899_18_Cyperaceae-1         0.041258
Name: x, Length: 1363, dtype: float64
x0 token_id
Eur-987c_25_vole-3               0.039545
Wal-cefe_41_ibex-2              -0.029092
Nar-f40f_72_pseudonarcissus-2    0.039973
Fie-7e8b_121_Fieldfare-1         0.069059
Gal-c07a_26_iguana-3            -0.039761
                                   ...
Mou338e_6_hares-2                0.039973
Ank-02ea_16_Ankylosauria-1      -0.063362
Roe-b5ac_174_deer-2             -0.096066
Com-264e_16_seadragon-2         -0.105636
Cyp-0899_18_Cyperaceae-1         0.041258
Name: x, Length: 1362, dtype: float64
x0 token_id
Eur-987c_25_vole-3               0.039545
Wal-cefe_41_ibex-2              -0.029092
Nar-f40f_72_pseudonarcissus-2    0.039973
Fie-7e8b_121_Fieldfare-1         0.069059
Gal-c07a_26_iguana-3            -0.039761
                                   ...
Mou338e_6_hares-2                0.039973
Ank-02ea_16_Ankylosauria-1      -0.063362
Roe-b5ac_174_deer-2             -0.096066
Com-264e_16_seadragon-2         -0.105636
Cyp-0899_18_Cyperaceae-1         0.041258
Name: x, Length: 1350, dtype: float64
x0 token_id
Eur-987c_25_vole-3               0.039545
Wal-cefe_41_ibex-2              -0.029092
Nar-f40f_72_pseudonarcissus-2    0.039973
Fie-7e8b_121_Fieldfare-1         0.069059
Gal-c07a_26_iguana-3            -0.039761
                                   ...
Mou338e_6_hares-2                0.039973
Ank-02ea_16_Ankylosauria-1      -0.063362
Roe-b5ac_174_deer-2             -0.096066
Com-264e_16_seadragon-2         -0.105636
Cyp-0899_18_Cyperaceae-1         0.041258
Name: x, Length: 1362, dtype: float64
x0 token_id
Eur-987c_25_vole-3               0.039545
Wal-cefe_41_ibex-2              -0.029092
Nar-f40f_72_pseudonarcissus-2    0.039973
Fie-7e8b_121_Fieldfare-1         0.069059
Gal-c07a_26_iguana-3            -0.039761
                                   ...
Mou338e_6_hares-2                0.039973
Ank-02ea_16_Ankylosauria-1      -0.063362
Roe-b5ac_174_deer-2             -0.096066
Com-264e_16_seadragon-2         -0.105636
Cyp-0899_18_Cyperaceae-1         0.041258
Name: x, Length: 1361, dtype: float64
x0 token_id
Eur-987c_25_vole-3               0.039545
Wal-cefe_41_ibex-2              -0.029092
Nar-f40f_72_pseudonarcissus-2    0.039973
Fie-7e8b_121_Fieldfare-1         0.069059
Gal-c07a_26_iguana-3            -0.039761
                                   ...
Mou338e_6_hares-2                0.039973
Ank-02ea_16_Ankylosauria-1      -0.063362
Roe-b5ac_174_deer-2             -0.096066
Com-264e_16_seadragon-2         -0.105636
Cyp-0899_18_Cyperaceae-1         0.041258
Name: x, Length: 1354, dtype: float64
x0 token_id
Eur-987c_25_vole-3               0.039545
Wal-cefe_41_ibex-2              -0.029092
Nar-f40f_72_pseudonarcissus-2    0.039973
Fie-7e8b_121_Fieldfare-1         0.069059
Gal-c07a_26_iguana-3            -0.039761
                                   ...
Mou338e_6_hares-2                0.039973
Ank-02ea_16_Ankylosauria-1      -0.063362
Roe-b5ac_174_deer-2             -0.096066
Com-264e_16_seadragon-2         -0.105636
Cyp-0899_18_Cyperaceae-1         0.041258
Name: x, Length: 1339, dtype: float64
x0 token_id
Eur-987c_25_vole-3               0.039545
Wal-cefe_41_ibex-2              -0.029092
Nar-f40f_72_pseudonarcissus-2    0.039973
Fie-7e8b_121_Fieldfare-1         0.069059
Gal-c07a_26_iguana-3            -0.039761
                                   ...
Mou338e_6_hares-2                0.039973
Ank-02ea_16_Ankylosauria-1      -0.063362
Roe-b5ac_174_deer-2             -0.096066
Com-264e_16_seadragon-2         -0.105636
Cyp-0899_18_Cyperaceae-1         0.041258
Name: x, Length: 1362, dtype: float64
x0 token_id
Eur-987c_25_vole-3               0.039545
Wal-cefe_41_ibex-2              -0.029092
Nar-f40f_72_pseudonarcissus-2    0.039973
Fie-7e8b_121_Fieldfare-1         0.069059
Gal-c07a_26_iguana-3            -0.039761
                                   ...
Mou338e_6_hares-2                0.039973
Ank-02ea_16_Ankylosauria-1      -0.063362
Roe-b5ac_174_deer-2             -0.096066
Com-264e_16_seadragon-2         -0.105636
Cyp-0899_18_Cyperaceae-1         0.041258
Name: x, Length: 1362, dtype: float64
x0 token_id
Eur-987c_25_vole-3               0.039545
Wal-cefe_41_ibex-2              -0.029092
Nar-f40f_72_pseudonarcissus-2    0.039973
Fie-7e8b_121_Fieldfare-1         0.069059
Gal-c07a_26_iguana-3            -0.039761
                                   ...
Mou338e_6_hares-2                0.039973
Ank-02ea_16_Ankylosauria-1      -0.063362
Roe-b5ac_174_deer-2             -0.096066
Com-264e_16_seadragon-2         -0.105636
Cyp-0899_18_Cyperaceae-1         0.041258
Name: x, Length: 1362, dtype: float64
Spearman results
feat_tests
                            test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath            lemma
amod>              greater      0.28674   -0.070        1    1364    -1.07
                   high         0.38246    0.041        2    1364     0.87
amod>advmod>       long         0.31721    0.018       14    1364     1.00
compound>amod>     arctic       0.88745   -0.007        2    1364    -0.14
                   bent         0.97050   -0.001        3    1364    -0.04
                   black        0.12444    0.032       10    1364     1.54
                   green        0.00181    0.041       25    1364     3.13
compound>compound> New          0.04664   -0.092        2    1364    -1.99
conj>              mouse        0.04664   -0.092        2    1364    -1.99
nmod>case>         of           0.38246    0.041        2    1364     0.87
book_cl_elong
                              effect        Dx   N      eff2  test_pvalue  \
arcpath            lemma
compound>amod>     green    0.442997  0.028197  25  0.196247      0.00181
amod>              greater -0.396028  0.000424   1  0.156838      0.28674
conj>              mouse   -0.351947  0.001884   2  0.123867      0.04664
amod>advmod>       long     0.345163  0.014439  14  0.119137      0.31721
nmod>case>         of       0.335411 -0.000485   2  0.112501      0.38246
compound>amod>     black    0.332783  0.011286  10  0.110744      0.12444
compound>compound> New     -0.327356  0.001995   2  0.107162      0.04664

                            test_dX  test_Nx  test_N  test_st
arcpath            lemma
compound>amod>     green      0.041       25    1364     3.13
amod>              greater   -0.070        1    1364    -1.07
conj>              mouse     -0.092        2    1364    -1.99
amod>advmod>       long       0.018       14    1364     1.00
nmod>case>         of         0.041        2    1364     0.87
compound>amod>     black      0.032       10    1364     1.54
compound>compound> New       -0.092        2    1364    -1.99
cluster ====> 4
np.sqrt(eigvals)
[0.26793959 0.37514375 0.43848123 0.50066865 0.58657016 0.62211203
 0.75520033 0.87019515]
cl_elong_a, cl_elong_v.round(2)
1.1522706111554095 [ 0.18 -0.46 -0.71  0.5  -0.08 -0.04 -0.08  0.02]
cluster data sample, mean shift
(8870, 8)                                  0         1         2         3         4  \
token_id
Aur-441a_64_jellyfish-30  0.068912 -0.666675 -0.580855 -0.517149 -0.207198
Blab943_11_bird-4        -0.822251 -0.660370  0.091627 -0.160284  0.770790
Arg-ab8e_28_crabro-14    -0.533369 -0.292748 -0.169823  0.173378  0.203896

                                 5         6         7
token_id
Aur-441a_64_jellyfish-30  0.389509 -0.192231  0.134795
Blab943_11_bird-4        -0.287004  0.095483  0.875821
Arg-ab8e_28_crabro-14     0.252503 -0.138379 -0.654589
cluster data elongation along main axis

/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

                       effect        Dx   N      eff2
arcpath lemma
amod>   isolate      0.907306  0.000019   1  0.823204
        most         0.896103  0.000410  40  0.803000
        know         0.891209  0.000007   8  0.794253
        numerous     0.886222 -0.000009   1  0.785390
        dromedary    0.885296  0.000007   1  0.783749
        live         0.875982  0.000005   2  0.767345
        large        0.875562 -0.000080  42  0.766609
        radiate      0.875216  0.000064   2  0.766002
        only         0.873629 -0.000018   4  0.763228
        terrestrial  0.866511 -0.000046   6  0.750841
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                 token         x
arcpath lemma
amod>   dromedary                Cam-1690_189_camel-10  0.211706
        isolate             Coc-65ef_103_cockroaches-6  0.146267
        know                  Bir-ebe4_10_dinosaurs-12  0.456025
        know         Car-eac4_14_carcharodontosaurid-9  1.610424
        know                 Cau-ba75_14_salamanders-5  1.579570
...                                                ...       ...
        terrestrial           Amb-94f9_56_ungulates-14  0.275275
        terrestrial             Ant-44b4_163_animal-11  1.522336
        terrestrial              Chi-171d_17_animal-12  1.601343
        terrestrial          Her-8d89_30_vertebrates-6  1.294182
        terrestrial         Sau-89d2_202_vertebrates-9  0.798630

[107 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (8870,)
ftok (107, 2)
x0 token_id
Aur-441a_64_jellyfish-30      0.489141
Blab943_11_bird-4            -0.027253
Arg-ab8e_28_crabro-14         0.220488
Tri-1ad8_143_Cerapoda-14     -0.039536
Cap-154f_103_apes-9           1.078130
                                ...
Mon-1726_179_Liliaceae-32     0.847640
Pap-75c9_71_swallowtail-53    0.679010
Jel-28f4_51_jellyfish-11      1.105324
Boa-7d46_30_constrictor-3    -0.075155
Gree5e5_4_beetles-3           0.016617
Name: x, Length: 8869, dtype: float64
x0 token_id
Aur-441a_64_jellyfish-30      0.489141
Blab943_11_bird-4            -0.027253
Arg-ab8e_28_crabro-14         0.220488
Tri-1ad8_143_Cerapoda-14     -0.039536
Cap-154f_103_apes-9           1.078130
                                ...
Mon-1726_179_Liliaceae-32     0.847640
Pap-75c9_71_swallowtail-53    0.679010
Jel-28f4_51_jellyfish-11      1.105324
Boa-7d46_30_constrictor-3    -0.075155
Gree5e5_4_beetles-3           0.016617
Name: x, Length: 8869, dtype: float64
x0 token_id
Aur-441a_64_jellyfish-30      0.489141
Blab943_11_bird-4            -0.027253
Arg-ab8e_28_crabro-14         0.220488
Tri-1ad8_143_Cerapoda-14     -0.039536
Cap-154f_103_apes-9           1.078130
                                ...
Mon-1726_179_Liliaceae-32     0.847640
Pap-75c9_71_swallowtail-53    0.679010
Jel-28f4_51_jellyfish-11      1.105324
Boa-7d46_30_constrictor-3    -0.075155
Gree5e5_4_beetles-3           0.016617
Name: x, Length: 8862, dtype: float64
x0 token_id
Aur-441a_64_jellyfish-30      0.489141
Blab943_11_bird-4            -0.027253
Arg-ab8e_28_crabro-14         0.220488
Tri-1ad8_143_Cerapoda-14     -0.039536
Cap-154f_103_apes-9           1.078130
                                ...
Bow-5df3_55_whale-3          -0.351621
Mon-1726_179_Liliaceae-32     0.847640
Pap-75c9_71_swallowtail-53    0.679010
Boa-7d46_30_constrictor-3    -0.075155
Gree5e5_4_beetles-3           0.016617
Name: x, Length: 8828, dtype: float64
x0 token_id
Aur-441a_64_jellyfish-30      0.489141
Blab943_11_bird-4            -0.027253
Arg-ab8e_28_crabro-14         0.220488
Tri-1ad8_143_Cerapoda-14     -0.039536
Cap-154f_103_apes-9           1.078130
                                ...
Mon-1726_179_Liliaceae-32     0.847640
Pap-75c9_71_swallowtail-53    0.679010
Jel-28f4_51_jellyfish-11      1.105324
Boa-7d46_30_constrictor-3    -0.075155
Gree5e5_4_beetles-3           0.016617
Name: x, Length: 8868, dtype: float64
x0 token_id
Aur-441a_64_jellyfish-30      0.489141
Blab943_11_bird-4            -0.027253
Arg-ab8e_28_crabro-14         0.220488
Tri-1ad8_143_Cerapoda-14     -0.039536
Cap-154f_103_apes-9           1.078130
                                ...
Mon-1726_179_Liliaceae-32     0.847640
Pap-75c9_71_swallowtail-53    0.679010
Jel-28f4_51_jellyfish-11      1.105324
Boa-7d46_30_constrictor-3    -0.075155
Gree5e5_4_beetles-3           0.016617
Name: x, Length: 8830, dtype: float64
x0 token_id
Aur-441a_64_jellyfish-30      0.489141
Blab943_11_bird-4            -0.027253
Arg-ab8e_28_crabro-14         0.220488
Tri-1ad8_143_Cerapoda-14     -0.039536
Cap-154f_103_apes-9           1.078130
                                ...
Mon-1726_179_Liliaceae-32     0.847640
Pap-75c9_71_swallowtail-53    0.679010
Jel-28f4_51_jellyfish-11      1.105324
Boa-7d46_30_constrictor-3    -0.075155
Gree5e5_4_beetles-3           0.016617
Name: x, Length: 8869, dtype: float64
x0 token_id
Aur-441a_64_jellyfish-30      0.489141
Blab943_11_bird-4            -0.027253
Arg-ab8e_28_crabro-14         0.220488
Tri-1ad8_143_Cerapoda-14     -0.039536
Cap-154f_103_apes-9           1.078130
                                ...
Mon-1726_179_Liliaceae-32     0.847640
Pap-75c9_71_swallowtail-53    0.679010
Jel-28f4_51_jellyfish-11      1.105324
Boa-7d46_30_constrictor-3    -0.075155
Gree5e5_4_beetles-3           0.016617
Name: x, Length: 8866, dtype: float64
x0 token_id
Aur-441a_64_jellyfish-30      0.489141
Blab943_11_bird-4            -0.027253
Arg-ab8e_28_crabro-14         0.220488
Tri-1ad8_143_Cerapoda-14     -0.039536
Cap-154f_103_apes-9           1.078130
                                ...
Mon-1726_179_Liliaceae-32     0.847640
Pap-75c9_71_swallowtail-53    0.679010
Jel-28f4_51_jellyfish-11      1.105324
Boa-7d46_30_constrictor-3    -0.075155
Gree5e5_4_beetles-3           0.016617
Name: x, Length: 8868, dtype: float64
x0 token_id
Aur-441a_64_jellyfish-30      0.489141
Blab943_11_bird-4            -0.027253
Arg-ab8e_28_crabro-14         0.220488
Tri-1ad8_143_Cerapoda-14     -0.039536
Cap-154f_103_apes-9           1.078130
                                ...
Mon-1726_179_Liliaceae-32     0.847640
Pap-75c9_71_swallowtail-53    0.679010
Jel-28f4_51_jellyfish-11      1.105324
Boa-7d46_30_constrictor-3    -0.075155
Gree5e5_4_beetles-3           0.016617
Name: x, Length: 8864, dtype: float64
Spearman results
feat_tests
                     test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath lemma
amod>   dromedary        0.73770    0.197        1    8870     0.33
        isolate          0.82320    0.131        1    8870     0.22
        know             0.00002    0.882        8    8870     4.25
        large            0.00000    0.552       42    8870     6.09
        live             0.44534    0.317        2    8870     0.76
        most             0.00000    0.729       40    8870     7.86
        numerous         0.08618    1.007        1    8870     1.72
        only             0.71695    0.106        4    8870     0.36
        radiate          0.28183    0.447        2    8870     1.08
        terrestrial      0.00001    1.067        6    8870     4.45
book_cl_elong
                       effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath lemma
amod>   isolate      0.907306  0.000019   1  0.823204      0.82320    0.131
        most         0.896103  0.000410  40  0.803000      0.00000    0.729
        know         0.891209  0.000007   8  0.794253      0.00002    0.882
        numerous     0.886222 -0.000009   1  0.785390      0.08618    1.007
        dromedary    0.885296  0.000007   1  0.783749      0.73770    0.197
        live         0.875982  0.000005   2  0.767345      0.44534    0.317
        large        0.875562 -0.000080  42  0.766609      0.00000    0.552
        radiate      0.875216  0.000064   2  0.766002      0.28183    0.447
        only         0.873629 -0.000018   4  0.763228      0.71695    0.106
        terrestrial  0.866511 -0.000046   6  0.750841      0.00001    1.067

                     test_Nx  test_N  test_st
arcpath lemma
amod>   isolate            1    8870     0.22
        most              40    8870     7.86
        know               8    8870     4.25
        numerous           1    8870     1.72
        dromedary          1    8870     0.33
        live               2    8870     0.76
        large             42    8870     6.09
        radiate            2    8870     1.08
        only               4    8870     0.36
        terrestrial        6    8870     4.45
cluster ====> 5
np.sqrt(eigvals)
[0.21637744 0.28075389 0.32492539 0.43953802 0.48902216 0.51959338
 0.75805793 0.89978964]
cl_elong_a, cl_elong_v.round(2)
1.186966863953084 [ 0.12  0.89  0.39  0.14  0.06  0.1  -0.    0.04]
cluster data sample, mean shift

(5154, 8)                              0         1         2         3         4  \
token_id
Polf59e_2_voles-8     0.199174  0.012585  0.661813 -0.046252  0.135580
Bla-d6a7_27_humans-9 -0.212306  0.123246  0.764278  0.154818 -0.309021
Hor-ab9c_184_bat-13  -0.299182 -0.371009  0.025256 -1.766795  1.430324

                             5         6         7
token_id
Polf59e_2_voles-8    -0.589727  0.053513  0.038258
Bla-d6a7_27_humans-9 -0.325868  0.125143 -0.353803
Hor-ab9c_184_bat-13  -0.524095 -0.106084  0.283492
cluster data elongation along main axis
                                   effect        Dx  N      eff2
arcpath            lemma
nmod:poss>conj>cc> and          -0.862443  0.000043  1  0.743807
obl<               produce       0.755878  0.000390  8  0.571351
nmod<obj<obl>      reptile      -0.750317  0.000133  2  0.562975
acl:relcl>         eat          -0.740726  0.000048  2  0.548676
obl<               characterize  0.738756  0.000051  1  0.545760
                   transmit      0.735205  0.000022  1  0.540527
acl:relcl>         feed         -0.729764  0.000015  2  0.532555
obl<               gai           0.729424  0.000051  1  0.532059
                   obtain        0.726166  0.000034  1  0.527317
                   specialize    0.725038  0.000034  1  0.525680
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                         token         x
arcpath            lemma
acl:relcl>         eat                  Ani-161e_70_turtles-14 -1.025098
                   eat                   Cat-605b_118_plant-23 -1.562859
                   feed                   Ani2696_56_people-11 -0.474671
                   feed                   Red-f791_60_cones-44 -1.144991
nmod:poss>conj>cc> and                    Com8122_2_mammals-15 -0.761719
nmod<obj<obl>      reptile               Com-4c8f_11_turtle-10 -0.483906
                   reptile       The-f5b4_13_Therizinosaurus-6 -0.399251
obl<               characterize          Mic-219b_16_grasses-8  0.798809
                   gai                     Pac-29db_128_dog-18  0.335771
                   obtain                Orc-0474_187_fungi-34  0.527336
                   produce                Afr-7494_111_cows-14  0.455100
                   produce                 Ara-552d_19_plant-6  0.171083
                   produce              Bel-4321_256_humans-13  1.251808
                   produce               Bur-08d7_34_animals-6  0.460781
                   produce                 Com-9711_67_raven-7  0.533338
                   produce                For-fc8f_7_aphids-13  0.148378
                   produce                Man-05b8_126_bats-19  0.475108
                   produce             Red-5937_112_piranhas-9  0.450690
                   specialize             Acc-0f45_121_bats-24  0.724018
                   transmit             Eas-550c_137_rodents-6  0.790381
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (5154,)
ftok (20, 2)
x0 token_id
Polf59e_2_voles-8              0.237255
Bla-d6a7_27_humans-9           0.340058
Hor-ab9c_184_bat-13           -0.564522
Komddae_13_lizards-7           0.215556
Hum13cf_6_bats-8               0.514373
                                 ...
Fro-2392_543_frogs-9          -0.301992
Com-7fbd_79_chiffchaff-15      0.636756
Eur-bc75_373_goshawks-43       0.207143
Bota3e6_6_vipers-7             0.474681
Sem-88a0_194_Hymenoptera-27   -1.023219
Name: x, Length: 5152, dtype: float64
x0 token_id
Polf59e_2_voles-8              0.237255
Bla-d6a7_27_humans-9           0.340058
Hor-ab9c_184_bat-13           -0.564522
Komddae_13_lizards-7           0.215556
Hum13cf_6_bats-8               0.514373
                                 ...
Fro-2392_543_frogs-9          -0.301992
Com-7fbd_79_chiffchaff-15      0.636756
Eur-bc75_373_goshawks-43       0.207143
Bota3e6_6_vipers-7             0.474681
Sem-88a0_194_Hymenoptera-27   -1.023219
Name: x, Length: 5152, dtype: float64
x0 token_id
Polf59e_2_voles-8              0.237255
Bla-d6a7_27_humans-9           0.340058
Hor-ab9c_184_bat-13           -0.564522
Komddae_13_lizards-7           0.215556
Hum13cf_6_bats-8               0.514373
                                 ...
Fro-2392_543_frogs-9          -0.301992
Com-7fbd_79_chiffchaff-15      0.636756
Eur-bc75_373_goshawks-43       0.207143
Bota3e6_6_vipers-7             0.474681
Sem-88a0_194_Hymenoptera-27   -1.023219
Name: x, Length: 5153, dtype: float64
x0 token_id
Polf59e_2_voles-8              0.237255
Bla-d6a7_27_humans-9           0.340058
Hor-ab9c_184_bat-13           -0.564522
Komddae_13_lizards-7           0.215556
Hum13cf_6_bats-8               0.514373
                                 ...
Fro-2392_543_frogs-9          -0.301992
Com-7fbd_79_chiffchaff-15      0.636756
Eur-bc75_373_goshawks-43       0.207143
Bota3e6_6_vipers-7             0.474681
Sem-88a0_194_Hymenoptera-27   -1.023219
Name: x, Length: 5152, dtype: float64
x0 token_id
Polf59e_2_voles-8              0.237255
Bla-d6a7_27_humans-9           0.340058
Hor-ab9c_184_bat-13           -0.564522
Komddae_13_lizards-7           0.215556
Hum13cf_6_bats-8               0.514373
                                 ...
Fro-2392_543_frogs-9          -0.301992
Com-7fbd_79_chiffchaff-15      0.636756
Eur-bc75_373_goshawks-43       0.207143
Bota3e6_6_vipers-7             0.474681
Sem-88a0_194_Hymenoptera-27   -1.023219
Name: x, Length: 5153, dtype: float64
x0 token_id
Polf59e_2_voles-8              0.237255
Bla-d6a7_27_humans-9           0.340058
Hor-ab9c_184_bat-13           -0.564522
Komddae_13_lizards-7           0.215556
Hum13cf_6_bats-8               0.514373
                                 ...
Fro-2392_543_frogs-9          -0.301992
Com-7fbd_79_chiffchaff-15      0.636756
Eur-bc75_373_goshawks-43       0.207143
Bota3e6_6_vipers-7             0.474681
Sem-88a0_194_Hymenoptera-27   -1.023219
Name: x, Length: 5153, dtype: float64
x0 token_id
Polf59e_2_voles-8              0.237255
Bla-d6a7_27_humans-9           0.340058
Hor-ab9c_184_bat-13           -0.564522
Komddae_13_lizards-7           0.215556
Hum13cf_6_bats-8               0.514373
                                 ...
Fro-2392_543_frogs-9          -0.301992
Com-7fbd_79_chiffchaff-15      0.636756
Eur-bc75_373_goshawks-43       0.207143
Bota3e6_6_vipers-7             0.474681
Sem-88a0_194_Hymenoptera-27   -1.023219
Name: x, Length: 5153, dtype: float64
x0 token_id
Polf59e_2_voles-8              0.237255
Bla-d6a7_27_humans-9           0.340058
Hor-ab9c_184_bat-13           -0.564522
Komddae_13_lizards-7           0.215556
Hum13cf_6_bats-8               0.514373
                                 ...
Fro-2392_543_frogs-9          -0.301992
Com-7fbd_79_chiffchaff-15      0.636756
Eur-bc75_373_goshawks-43       0.207143
Bota3e6_6_vipers-7             0.474681
Sem-88a0_194_Hymenoptera-27   -1.023219
Name: x, Length: 5146, dtype: float64
x0 token_id
Polf59e_2_voles-8              0.237255
Bla-d6a7_27_humans-9           0.340058
Hor-ab9c_184_bat-13           -0.564522
Komddae_13_lizards-7           0.215556
Hum13cf_6_bats-8               0.514373
                                 ...
Fro-2392_543_frogs-9          -0.301992
Com-7fbd_79_chiffchaff-15      0.636756
Eur-bc75_373_goshawks-43       0.207143
Bota3e6_6_vipers-7             0.474681
Sem-88a0_194_Hymenoptera-27   -1.023219
Name: x, Length: 5153, dtype: float64
x0 token_id
Polf59e_2_voles-8              0.237255
Bla-d6a7_27_humans-9           0.340058
Hor-ab9c_184_bat-13           -0.564522
Komddae_13_lizards-7           0.215556
Hum13cf_6_bats-8               0.514373
                                 ...
Fro-2392_543_frogs-9          -0.301992
Com-7fbd_79_chiffchaff-15      0.636756
Eur-bc75_373_goshawks-43       0.207143
Bota3e6_6_vipers-7             0.474681
Sem-88a0_194_Hymenoptera-27   -1.023219
Name: x, Length: 5153, dtype: float64
Spearman results
feat_tests
                                 test_pvalue  test_dX  test_Nx  test_N  \
arcpath            lemma
acl:relcl>         eat               0.00033   -1.289        2    5154
                   feed              0.02495   -0.805        2    5154
nmod:poss>conj>cc> and               0.13615   -0.757        1    5154
nmod<obj<obl>      reptile           0.22413   -0.436        2    5154
obl<               characterize      0.11311    0.804        1    5154
                   gai               0.50160    0.341        1    5154
                   obtain            0.29399    0.533        1    5154
                   produce           0.00542    0.499        8    5154
                   specialize        0.15073    0.729        1    5154
                   transmit          0.11694    0.796        1    5154

                                 test_st
arcpath            lemma
acl:relcl>         eat             -3.60
                   feed            -2.24
nmod:poss>conj>cc> and             -1.49
nmod<obj<obl>      reptile         -1.22
obl<               characterize     1.58
                   gai              0.67
                   obtain           1.05
                   produce          2.78
                   specialize       1.44
                   transmit         1.57
book_cl_elong
                                   effect        Dx  N      eff2  test_pvalue  \
arcpath            lemma
nmod:poss>conj>cc> and          -0.862443  0.000043  1  0.743807      0.13615
obl<               produce       0.755878  0.000390  8  0.571351      0.00542
nmod<obj<obl>      reptile      -0.750317  0.000133  2  0.562975      0.22413
acl:relcl>         eat          -0.740726  0.000048  2  0.548676      0.00033
obl<               characterize  0.738756  0.000051  1  0.545760      0.11311
                   transmit      0.735205  0.000022  1  0.540527      0.11694
acl:relcl>         feed         -0.729764  0.000015  2  0.532555      0.02495
obl<               gai           0.729424  0.000051  1  0.532059      0.50160
                   obtain        0.726166  0.000034  1  0.527317      0.29399
                   specialize    0.725038  0.000034  1  0.525680      0.15073

                                 test_dX  test_Nx  test_N  test_st
arcpath            lemma
nmod:poss>conj>cc> and            -0.757        1    5154    -1.49
obl<               produce         0.499        8    5154     2.78
nmod<obj<obl>      reptile        -0.436        2    5154    -1.22
acl:relcl>         eat            -1.289        2    5154    -3.60
obl<               characterize    0.804        1    5154     1.58
                   transmit        0.796        1    5154     1.57
acl:relcl>         feed           -0.805        2    5154    -2.24
obl<               gai             0.341        1    5154     0.67
                   obtain          0.533        1    5154     1.05
                   specialize      0.729        1    5154     1.44
cluster ====> 6
np.sqrt(eigvals)
[0.66590021 0.84075626 0.93078009 1.00872763 1.10085655 1.19870442
 1.3980682  2.22037872]
cl_elong_a, cl_elong_v.round(2)
1.5881762534506279 [ 0.04  0.09 -0.17  0.26  0.11  0.   -0.1   0.93]
cluster data sample, mean shift
(2245, 8)                                     0         1         2         3         4  \
token_id
Rep-aa64_410_snakes-9       -0.291521  0.548236 -1.369957  0.415056  0.024461
Mag-8f64_10_Magnoliopsida-2  0.147426  0.655561  0.136252  1.279641  1.471077
Syc-34df_5_sycamore-75       0.937733  0.186747 -2.159469 -0.963225 -1.204267

                                    5         6         7
token_id
Rep-aa64_410_snakes-9        0.500340  0.597419  0.623706
Mag-8f64_10_Magnoliopsida-2 -1.259472 -1.921444  2.934458
Syc-34df_5_sycamore-75      -0.059061  0.025792  0.505340
cluster data elongation along main axis
                       effect        Dx   N      eff2
arcpath lemma
conj>   hare        -0.960667  0.001134  18  0.922882
        rabbit      -0.951575  0.000597  10  0.905495
        chipmunk    -0.949635  0.000143   2  0.901807
        variety     -0.946710  0.000129   2  0.896259
        animal      -0.942115  0.000984  19  0.887580
        guanaco     -0.941864  0.000161   2  0.887108
        carrion     -0.940523  0.001105  14  0.884583
        food        -0.939273  0.000129   2  0.882234
        example     -0.934565  0.000059   1  0.873412
        environment -0.932458  0.000053   1  0.869478
Compute the feature-associated token x1 positions (ftok) on the projected axis

ftok
                                    token         x
arcpath lemma
conj>   animal     Ani-2170_118_humans-20 -0.166233
        animal       Ara-8421_54_plant-22 -3.080116
        animal    Arm-33e3_135_insects-25 -1.983136
        animal      Asc-4810_139_plants-4 -0.833943
        animal      Aus-f9df_11_plants-23  0.789910
...                                   ...       ...
        rabbit   Har-8a11_65_squirrels-13 -0.915657
        rabbit       Her-8d89_180_deer-15 -1.276406
        rabbit    Man-d9fd_119_rodents-16 -2.168446
        variety     Ech-581f_68_rodents-5 -1.647732
        variety      Flo-eb50_8_plants-40 -0.596479

[71 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (2245,)
ftok (71, 2)
x0 token_id
Rep-aa64_410_snakes-9          0.900744
Mag-8f64_10_Magnoliopsida-2    3.472810
Syc-34df_5_sycamore-75         0.500002
Com-3b7c_116_blackbird-14      2.033704
Bla-2fe0_148_plants-9         -5.481783
                                 ...
Wes-8d71_344_butterflies-2    -1.605437
Gul-1ea1_60_arthropods-21     -8.733552
Nar-e858_506_roses-13         -0.080795
Fli-9841_25_pterosaurs-3       0.417789
Bon-fbc3_160_giraffe-5         1.125488
Name: x, Length: 2226, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9          0.900744
Mag-8f64_10_Magnoliopsida-2    3.472810
Syc-34df_5_sycamore-75         0.500002
Com-3b7c_116_blackbird-14      2.033704
Bla-2fe0_148_plants-9         -5.481783
                                 ...
Afr-7494_20_elephant-27       -1.213090
Wes-8d71_344_butterflies-2    -1.605437
Nar-e858_506_roses-13         -0.080795
Fli-9841_25_pterosaurs-3       0.417789
Bon-fbc3_160_giraffe-5         1.125488
Name: x, Length: 2231, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9          0.900744
Mag-8f64_10_Magnoliopsida-2    3.472810
Syc-34df_5_sycamore-75         0.500002
Com-3b7c_116_blackbird-14      2.033704
Bla-2fe0_148_plants-9         -5.481783
                                 ...
Wes-8d71_344_butterflies-2    -1.605437
Gul-1ea1_60_arthropods-21     -8.733552
Nar-e858_506_roses-13         -0.080795
Fli-9841_25_pterosaurs-3       0.417789
Bon-fbc3_160_giraffe-5         1.125488
Name: x, Length: 2243, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9          0.900744
Mag-8f64_10_Magnoliopsida-2    3.472810
Syc-34df_5_sycamore-75         0.500002
Com-3b7c_116_blackbird-14      2.033704
Bla-2fe0_148_plants-9         -5.481783
                                 ...
Wes-8d71_344_butterflies-2    -1.605437
Gul-1ea1_60_arthropods-21     -8.733552
Nar-e858_506_roses-13         -0.080795
Fli-9841_25_pterosaurs-3       0.417789
Bon-fbc3_160_giraffe-5         1.125488
Name: x, Length: 2244, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9          0.900744
Mag-8f64_10_Magnoliopsida-2    3.472810
Syc-34df_5_sycamore-75         0.500002
Com-3b7c_116_blackbird-14      2.033704
Bla-2fe0_148_plants-9         -5.481783
                                 ...
Wes-8d71_344_butterflies-2    -1.605437
Gul-1ea1_60_arthropods-21     -8.733552
Nar-e858_506_roses-13         -0.080795
Fli-9841_25_pterosaurs-3       0.417789
Bon-fbc3_160_giraffe-5         1.125488
Name: x, Length: 2244, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9          0.900744
Mag-8f64_10_Magnoliopsida-2    3.472810
Syc-34df_5_sycamore-75         0.500002
Com-3b7c_116_blackbird-14      2.033704
Bla-2fe0_148_plants-9         -5.481783
                                 ...
Wes-8d71_344_butterflies-2    -1.605437
Gul-1ea1_60_arthropods-21     -8.733552
Nar-e858_506_roses-13         -0.080795
Fli-9841_25_pterosaurs-3       0.417789
Bon-fbc3_160_giraffe-5         1.125488
Name: x, Length: 2243, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9          0.900744
Mag-8f64_10_Magnoliopsida-2    3.472810
Syc-34df_5_sycamore-75         0.500002
Com-3b7c_116_blackbird-14      2.033704
Bla-2fe0_148_plants-9         -5.481783
                                 ...
Wes-8d71_344_butterflies-2    -1.605437
Gul-1ea1_60_arthropods-21     -8.733552
Nar-e858_506_roses-13         -0.080795
Fli-9841_25_pterosaurs-3       0.417789
Bon-fbc3_160_giraffe-5         1.125488
Name: x, Length: 2243, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9          0.900744
Mag-8f64_10_Magnoliopsida-2    3.472810
Syc-34df_5_sycamore-75         0.500002
Com-3b7c_116_blackbird-14      2.033704
Bla-2fe0_148_plants-9         -5.481783
                                 ...
Wes-8d71_344_butterflies-2    -1.605437
Gul-1ea1_60_arthropods-21     -8.733552
Nar-e858_506_roses-13         -0.080795
Fli-9841_25_pterosaurs-3       0.417789
Bon-fbc3_160_giraffe-5         1.125488
Name: x, Length: 2227, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9          0.900744
Mag-8f64_10_Magnoliopsida-2    3.472810
Syc-34df_5_sycamore-75         0.500002
Com-3b7c_116_blackbird-14      2.033704
Bla-2fe0_148_plants-9         -5.481783
                                 ...
Wes-8d71_344_butterflies-2    -1.605437
Gul-1ea1_60_arthropods-21     -8.733552
Nar-e858_506_roses-13         -0.080795
Fli-9841_25_pterosaurs-3       0.417789
Bon-fbc3_160_giraffe-5         1.125488
Name: x, Length: 2235, dtype: float64
x0 token_id
Rep-aa64_410_snakes-9          0.900744
Mag-8f64_10_Magnoliopsida-2    3.472810
Syc-34df_5_sycamore-75         0.500002
Com-3b7c_116_blackbird-14      2.033704
Bla-2fe0_148_plants-9         -5.481783
                                 ...
Wes-8d71_344_butterflies-2    -1.605437
Gul-1ea1_60_arthropods-21     -8.733552
Nar-e858_506_roses-13         -0.080795
Fli-9841_25_pterosaurs-3       0.417789
Bon-fbc3_160_giraffe-5         1.125488
Name: x, Length: 2243, dtype: float64
Spearman results
feat_tests
                     test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath lemma
conj>   animal           0.09410   -0.783       19    2245    -1.67
        carrion          0.00000   -5.225       14    2245    -9.81
        chipmunk         0.01323   -3.555        2    2245    -2.48
        environment      0.44311   -1.557        1    2245    -0.77
        example          0.48535   -1.416        1    2245    -0.70
        food             0.92954    0.127        2    2245     0.09
        guanaco          0.00181   -4.474        2    2245    -3.12
        hare             0.00000   -4.502       18    2245    -9.56
        rabbit           0.00003   -2.676       10    2245    -4.18
        variety          0.54307   -0.873        2    2245    -0.61
book_cl_elong
                       effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath lemma
conj>   hare        -0.960667  0.001134  18  0.922882      0.00000   -4.502
        rabbit      -0.951575  0.000597  10  0.905495      0.00003   -2.676
        chipmunk    -0.949635  0.000143   2  0.901807      0.01323   -3.555
        variety     -0.946710  0.000129   2  0.896259      0.54307   -0.873
        animal      -0.942115  0.000984  19  0.887580      0.09410   -0.783
        guanaco     -0.941864  0.000161   2  0.887108      0.00181   -4.474
        carrion     -0.940523  0.001105  14  0.884583      0.00000   -5.225
        example     -0.934565  0.000059   1  0.873412      0.48535   -1.416
        environment -0.932458  0.000053   1  0.869478      0.44311   -1.557

                     test_Nx  test_N  test_st
arcpath lemma
conj>   hare              18    2245    -9.56
        rabbit            10    2245    -4.18
        chipmunk           2    2245    -2.48
        variety            2    2245    -0.61
        animal            19    2245    -1.67
        guanaco            2    2245    -3.12
        carrion           14    2245    -9.81
        example            1    2245    -0.70
        environment        1    2245    -0.77
cluster ====> 7
np.sqrt(eigvals)
[0.50601208 0.52558064 0.62923622 0.8111872  0.82159142 0.8840461
 1.33442301 2.94122961]
cl_elong_a, cl_elong_v.round(2)
2.2041208690747536 [-0.7   0.02 -0.23 -0.27  0.16 -0.39  0.45  0.03]
cluster data sample, mean shift
(1889, 8)                                 0         1         2         3         4  \
token_id
Aar-5e58_102_pythons-23 -0.293004  0.432717  2.362378 -0.473325 -0.785569
Cor-5ac8_18_rodents-26  -0.339048  1.060370 -1.742928  1.516114 -0.021648
Com-597e_40_warthog-3   -0.345468  0.941764 -1.381168 -0.078495  0.260182

                                5         6         7
token_id
Aar-5e58_102_pythons-23  0.127118 -0.280167  0.704209
Cor-5ac8_18_rodents-26   0.329109 -2.470991 -1.290857
Com-597e_40_warthog-3    0.961121 -4.767027  0.459048
cluster data elongation along main axis

                      effect        Dx   N      eff2
arcpath    lemma
nmod>case> in      -0.804104 -0.000571  10  0.646584
           over    -0.795272  0.000032   1  0.632457
           to      -0.791271 -0.000080   3  0.626110
           of      -0.768651 -0.000595  16  0.590824
           from    -0.722810 -0.000135   3  0.522454
           on      -0.698936 -0.000101   3  0.488511
           include -0.688765 -0.000100   3  0.474397
           with    -0.671022 -0.000149   2  0.450271
           for     -0.668740 -0.000069   1  0.447214
           such    -0.652954  0.000141  26  0.426349
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                       token         x
arcpath    lemma
nmod>case> for             Aphe0a9_6_cows-18 -0.703107
           from       Cir-aed8_249_Circus-47 -1.354382
           from       Cir-aed8_249_Circus-54 -1.187210
           from        Sil-6383_38_sifaka-22 -2.176026
           in         Bog-cdf9_52_reptile-11 -2.360559
...                                      ...       ...
           to      Ant-938d_2_Hymenoptera-23 -2.069440
           to         Cho-a88d_83_beetles-28 -2.144432
           to     Gal-0153_188_amphibians-15 -2.830301
           with        Man-05b8_8_insects-27 -2.401208
           with       Aur-441a_5_mollusks-10 -1.329371

[68 rows x 2 columns]
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (1889,)
ftok (68, 2)
x0 token_id
Aar-5e58_102_pythons-23    -0.488830
Cor-5ac8_18_rodents-26     -1.030350
Com-597e_40_warthog-3      -1.873751
Pin-a6d8_2_pine-10          1.355226
Per-145f_241_ravens-15      0.208166
                              ...
Che9203_3_lemurs-2         -1.344497
Whi-b4c3_270_gulls-17      -0.174885
Mou-2737_8_arthropods-15    0.852433
Des-000c_362_ants-5         0.693117
Pol-a6a6_328_bears-29      -1.799778
Name: x, Length: 1888, dtype: float64
x0 token_id
Aar-5e58_102_pythons-23    -0.488830
Cor-5ac8_18_rodents-26     -1.030350
Com-597e_40_warthog-3      -1.873751
Pin-a6d8_2_pine-10          1.355226
Per-145f_241_ravens-15      0.208166
                              ...
Che9203_3_lemurs-2         -1.344497
Whi-b4c3_270_gulls-17      -0.174885
Mou-2737_8_arthropods-15    0.852433
Des-000c_362_ants-5         0.693117
Pol-a6a6_328_bears-29      -1.799778
Name: x, Length: 1886, dtype: float64
x0 token_id
Aar-5e58_102_pythons-23    -0.488830
Cor-5ac8_18_rodents-26     -1.030350
Com-597e_40_warthog-3      -1.873751
Pin-a6d8_2_pine-10          1.355226
Per-145f_241_ravens-15      0.208166
                              ...
Che9203_3_lemurs-2         -1.344497
Whi-b4c3_270_gulls-17      -0.174885
Mou-2737_8_arthropods-15    0.852433
Des-000c_362_ants-5         0.693117
Pol-a6a6_328_bears-29      -1.799778
Name: x, Length: 1879, dtype: float64
x0 token_id
Aar-5e58_102_pythons-23    -0.488830
Cor-5ac8_18_rodents-26     -1.030350
Com-597e_40_warthog-3      -1.873751
Pin-a6d8_2_pine-10          1.355226
Per-145f_241_ravens-15      0.208166
                              ...
Che9203_3_lemurs-2         -1.344497
Whi-b4c3_270_gulls-17      -0.174885
Mou-2737_8_arthropods-15    0.852433
Des-000c_362_ants-5         0.693117
Pol-a6a6_328_bears-29      -1.799778
Name: x, Length: 1886, dtype: float64
x0 token_id
Aar-5e58_102_pythons-23    -0.488830
Cor-5ac8_18_rodents-26     -1.030350
Com-597e_40_warthog-3      -1.873751
Pin-a6d8_2_pine-10          1.355226
Per-145f_241_ravens-15      0.208166
                              ...
Che9203_3_lemurs-2         -1.344497
Whi-b4c3_270_gulls-17      -0.174885
Mou-2737_8_arthropods-15    0.852433
Des-000c_362_ants-5         0.693117
Pol-a6a6_328_bears-29      -1.799778
Name: x, Length: 1873, dtype: float64
x0 token_id
Aar-5e58_102_pythons-23    -0.488830
Cor-5ac8_18_rodents-26     -1.030350
Com-597e_40_warthog-3      -1.873751
Pin-a6d8_2_pine-10          1.355226
Per-145f_241_ravens-15      0.208166
                              ...
Che9203_3_lemurs-2         -1.344497
Whi-b4c3_270_gulls-17      -0.174885
Mou-2737_8_arthropods-15    0.852433
Des-000c_362_ants-5         0.693117
Pol-a6a6_328_bears-29      -1.799778
Name: x, Length: 1886, dtype: float64
x0 token_id
Aar-5e58_102_pythons-23    -0.488830
Cor-5ac8_18_rodents-26     -1.030350
Com-597e_40_warthog-3      -1.873751
Pin-a6d8_2_pine-10          1.355226
Per-145f_241_ravens-15      0.208166
                              ...
Che9203_3_lemurs-2         -1.344497
Whi-b4c3_270_gulls-17      -0.174885
Mou-2737_8_arthropods-15    0.852433
Des-000c_362_ants-5         0.693117
Pol-a6a6_328_bears-29      -1.799778
Name: x, Length: 1888, dtype: float64
x0 token_id
Aar-5e58_102_pythons-23    -0.488830
Cor-5ac8_18_rodents-26     -1.030350
Com-597e_40_warthog-3      -1.873751
Pin-a6d8_2_pine-10          1.355226
Per-145f_241_ravens-15      0.208166
                              ...
Che9203_3_lemurs-2         -1.344497
Whi-b4c3_270_gulls-17      -0.174885
Mou-2737_8_arthropods-15    0.852433
Des-000c_362_ants-5         0.693117
Pol-a6a6_328_bears-29      -1.799778
Name: x, Length: 1863, dtype: float64
x0 token_id
Aar-5e58_102_pythons-23    -0.488830
Cor-5ac8_18_rodents-26     -1.030350
Com-597e_40_warthog-3      -1.873751
Pin-a6d8_2_pine-10          1.355226
Per-145f_241_ravens-15      0.208166
                              ...
Che9203_3_lemurs-2         -1.344497
Whi-b4c3_270_gulls-17      -0.174885
Mou-2737_8_arthropods-15    0.852433
Des-000c_362_ants-5         0.693117
Pol-a6a6_328_bears-29      -1.799778
Name: x, Length: 1886, dtype: float64
x0 token_id
Aar-5e58_102_pythons-23    -0.488830
Cor-5ac8_18_rodents-26     -1.030350
Com-597e_40_warthog-3      -1.873751
Pin-a6d8_2_pine-10          1.355226
Per-145f_241_ravens-15      0.208166
                              ...
Che9203_3_lemurs-2         -1.344497
Whi-b4c3_270_gulls-17      -0.174885
Mou-2737_8_arthropods-15    0.852433
Des-000c_362_ants-5         0.693117
Pol-a6a6_328_bears-29      -1.799778
Name: x, Length: 1887, dtype: float64
Spearman results
feat_tests
                    test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath    lemma
nmod>case> for          0.44549   -0.873        1    1889    -0.76
           from         0.00823   -1.744        3    1889    -2.65
           in           0.00000   -2.141       10    1889    -5.96
           include      0.01861   -1.554        3    1889    -2.36
           of           0.00014   -1.092       16    1889    -3.82
           on           0.00764   -1.761        3    1889    -2.67
           over         0.02600   -2.545        1    1889    -2.23
           such         0.00000   -1.429       26    1889    -6.39
           to           0.00013   -2.521        3    1889    -3.83
           with         0.01176   -2.037        2    1889    -2.52
book_cl_elong
                      effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath    lemma
nmod>case> in      -0.804104 -0.000571  10  0.646584      0.00000   -2.141
           over    -0.795272  0.000032   1  0.632457      0.02600   -2.545
           to      -0.791271 -0.000080   3  0.626110      0.00013   -2.521
           of      -0.768651 -0.000595  16  0.590824      0.00014   -1.092
           from    -0.722810 -0.000135   3  0.522454      0.00823   -1.744
           on      -0.698936 -0.000101   3  0.488511      0.00764   -1.761
           include -0.688765 -0.000100   3  0.474397      0.01861   -1.554
           with    -0.671022 -0.000149   2  0.450271      0.01176   -2.037
           for     -0.668740 -0.000069   1  0.447214      0.44549   -0.873
           such    -0.652954  0.000141  26  0.426349      0.00000   -1.429

                    test_Nx  test_N  test_st
arcpath    lemma
nmod>case> in            10    1889    -5.96
           over           1    1889    -2.23
           to             3    1889    -3.83
           of            16    1889    -3.82
           from           3    1889    -2.65
           on             3    1889    -2.67
           include        3    1889    -2.36
           with           2    1889    -2.52
           for            1    1889    -0.76
           such          26    1889    -6.39
cluster ====> 8
np.sqrt(eigvals)
[0.16101362 0.21699981 0.23942951 0.27380713 0.3033536  0.39300355
 0.41502402 0.65040132]
cl_elong_a, cl_elong_v.round(2)
1.567141403153825 [-0.05 -0.56 -0.24  0.52 -0.43  0.22  0.08 -0.33]
cluster data sample, mean shift

(4977, 8)                                0         1         2         3         4  \
token_id
Afr-655f_81_elephant-2 -0.268693  0.213770 -0.599649 -0.286494 -0.673381
The067f_13_camels-3    -0.380279  0.302888 -0.037307  0.027421 -0.036201
Hun-23f5_11_spiders-6   0.664105  0.060592  0.619119 -0.080039 -0.191112

                               5         6         7
token_id
Afr-655f_81_elephant-2  0.378184 -0.152703  0.051157
The067f_13_camels-3     0.060925 -0.032873  0.165299
Hun-23f5_11_spiders-6   0.141119 -0.007770 -0.355236
cluster data elongation along main axis
                                    effect        Dx  N      eff2
arcpath                 lemma
case>                   by       -0.510827 -0.000188  1  0.260945
compound<amod>compound> New      -0.505260  0.000420  3  0.255288
case>                   '        -0.500485 -0.000025  1  0.250486
obl<                    faster   -0.495693  0.000109  1  0.245711
compound<obl>case>      in        0.491829  0.000269  3  0.241896
appos<nsubj<            know      0.488055  0.000072  1  0.238198
case>                   from     -0.486546 -0.000248  2  0.236727
amod<                   ancestor  0.482595  0.000112  1  0.232898
compound>det>           the       0.475260 -0.000031  1  0.225872
case>                   of       -0.470150 -0.001101  5  0.221041
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                       token         x
arcpath                 lemma
amod<                   ancestor        Gal-c120_16_human-20  0.600162
appos<nsubj<            know            Thy-db39_2_bearers-5  0.351523
case>                   '              Ani-4d8b_117_lions-17 -0.500717
                        by                Bur-d18a_4_dogs-14 -0.314030
                        from           Lem-ec0f_101_shark-13 -0.603257
                        from         Pin-c005_73_longaeva-13 -0.603257
                        of           Bur-08d7_9_vertebrate-4 -0.215682
                        of                Bir-154b_55_bird-4  0.371586
                        of         Lea-7a1c_224_Mustelidae-9 -0.261260
                        of              Pla-0a07_123_trees-4  0.021904
                        of              Red-d827_154_Knot-11 -0.841791
compound<amod>compound> New             Din2693_40_reptile-3 -0.543928
                        New             Ptee0a7_10_reptile-3 -0.543928
                        New             Rep66e7_12_reptile-3 -0.543928
compound<obl>case>      in             Afr-354e_22_buffalo-7  0.419837
                        in            Fri-c770_100_lizards-8  0.506514
                        in                Roe-b5ac_50_deer-9  0.862450
compound>det>           the           Hibad6e_19_Hedgehogs-5  0.548463
obl<                    faster    Ame-35ae_97_chimpanzees-23 -0.405386
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (4977,)
ftok (19, 2)
x0 token_id
Afr-655f_81_elephant-2    0.236092
The067f_13_camels-3      -0.153989
Hun-23f5_11_spiders-6    -0.031079
Auk-a4a3_24_divers-22     0.307631
Pin-32d8_16_pine-2       -0.674474
                            ...
Wes-8d71_327_bee-3        0.171030
Col-25ad_103_Columba-2   -0.309843
Tyrfbca_31_rex-2         -0.417014
Cul-6926_25_human-15      0.164772
Ala-9ac8_15_Alauda-1     -0.399550
Name: x, Length: 4976, dtype: float64
x0 token_id
Afr-655f_81_elephant-2    0.236092
The067f_13_camels-3      -0.153989
Hun-23f5_11_spiders-6    -0.031079
Auk-a4a3_24_divers-22     0.307631
Pin-32d8_16_pine-2       -0.674474
                            ...
Wes-8d71_327_bee-3        0.171030
Col-25ad_103_Columba-2   -0.309843
Tyrfbca_31_rex-2         -0.417014
Cul-6926_25_human-15      0.164772
Ala-9ac8_15_Alauda-1     -0.399550
Name: x, Length: 4976, dtype: float64
x0 token_id
Afr-655f_81_elephant-2    0.236092
The067f_13_camels-3      -0.153989
Hun-23f5_11_spiders-6    -0.031079
Auk-a4a3_24_divers-22     0.307631
Pin-32d8_16_pine-2       -0.674474
                            ...
Wes-8d71_327_bee-3        0.171030
Col-25ad_103_Columba-2   -0.309843
Tyrfbca_31_rex-2         -0.417014
Cul-6926_25_human-15      0.164772
Ala-9ac8_15_Alauda-1     -0.399550
Name: x, Length: 4976, dtype: float64
x0 token_id
Afr-655f_81_elephant-2    0.236092
The067f_13_camels-3      -0.153989
Hun-23f5_11_spiders-6    -0.031079
Auk-a4a3_24_divers-22     0.307631
Pin-32d8_16_pine-2       -0.674474
                            ...
Wes-8d71_327_bee-3        0.171030
Col-25ad_103_Columba-2   -0.309843
Tyrfbca_31_rex-2         -0.417014
Cul-6926_25_human-15      0.164772
Ala-9ac8_15_Alauda-1     -0.399550
Name: x, Length: 4976, dtype: float64
x0 token_id
Afr-655f_81_elephant-2    0.236092
The067f_13_camels-3      -0.153989
Hun-23f5_11_spiders-6    -0.031079
Auk-a4a3_24_divers-22     0.307631
Pin-32d8_16_pine-2       -0.674474
                            ...
Wes-8d71_327_bee-3        0.171030
Col-25ad_103_Columba-2   -0.309843
Tyrfbca_31_rex-2         -0.417014
Cul-6926_25_human-15      0.164772
Ala-9ac8_15_Alauda-1     -0.399550
Name: x, Length: 4975, dtype: float64
x0 token_id
Afr-655f_81_elephant-2    0.236092
The067f_13_camels-3      -0.153989
Hun-23f5_11_spiders-6    -0.031079
Auk-a4a3_24_divers-22     0.307631
Pin-32d8_16_pine-2       -0.674474
                            ...
Wes-8d71_327_bee-3        0.171030
Col-25ad_103_Columba-2   -0.309843
Tyrfbca_31_rex-2         -0.417014
Cul-6926_25_human-15      0.164772
Ala-9ac8_15_Alauda-1     -0.399550
Name: x, Length: 4972, dtype: float64
x0 token_id
Afr-655f_81_elephant-2    0.236092
The067f_13_camels-3      -0.153989
Hun-23f5_11_spiders-6    -0.031079
Auk-a4a3_24_divers-22     0.307631
Pin-32d8_16_pine-2       -0.674474
                            ...
Wes-8d71_327_bee-3        0.171030
Col-25ad_103_Columba-2   -0.309843
Tyrfbca_31_rex-2         -0.417014
Cul-6926_25_human-15      0.164772
Ala-9ac8_15_Alauda-1     -0.399550
Name: x, Length: 4974, dtype: float64

/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

x0 token_id
Afr-655f_81_elephant-2    0.236092
The067f_13_camels-3      -0.153989
Hun-23f5_11_spiders-6    -0.031079
Auk-a4a3_24_divers-22     0.307631
Pin-32d8_16_pine-2       -0.674474
                            ...
Wes-8d71_327_bee-3        0.171030
Col-25ad_103_Columba-2   -0.309843
Tyrfbca_31_rex-2         -0.417014
Cul-6926_25_human-15      0.164772
Ala-9ac8_15_Alauda-1     -0.399550
Name: x, Length: 4974, dtype: float64
x0 token_id
Afr-655f_81_elephant-2    0.236092
The067f_13_camels-3      -0.153989
Hun-23f5_11_spiders-6    -0.031079
Auk-a4a3_24_divers-22     0.307631
Pin-32d8_16_pine-2       -0.674474
                            ...
Wes-8d71_327_bee-3        0.171030
Col-25ad_103_Columba-2   -0.309843
Tyrfbca_31_rex-2         -0.417014
Cul-6926_25_human-15      0.164772
Ala-9ac8_15_Alauda-1     -0.399550
Name: x, Length: 4976, dtype: float64
x0 token_id
Afr-655f_81_elephant-2    0.236092
The067f_13_camels-3      -0.153989
Hun-23f5_11_spiders-6    -0.031079
Auk-a4a3_24_divers-22     0.307631
Pin-32d8_16_pine-2       -0.674474
                            ...
Wes-8d71_327_bee-3        0.171030
Col-25ad_103_Columba-2   -0.309843
Tyrfbca_31_rex-2         -0.417014
Cul-6926_25_human-15      0.164772
Ala-9ac8_15_Alauda-1     -0.399550
Name: x, Length: 4976, dtype: float64
Spearman results
feat_tests
                                  test_pvalue  test_dX  test_Nx  test_N  \
arcpath                 lemma
amod<                   ancestor      0.05373    0.602        1    4977
appos<nsubj<            know          0.25770    0.353        1    4977
case>                   '             0.10964   -0.499        1    4977
                        by            0.31667   -0.312        1    4977
                        from          0.00637   -0.602        2    4977
                        of            0.18844   -0.184        5    4977
compound<amod>compound> New           0.00259   -0.543        3    4977
compound<obl>case>      in            0.00090    0.598        3    4977
compound>det>           the           0.07786    0.550        1    4977
obl<                    faster        0.19561   -0.404        1    4977

                                  test_st
arcpath                 lemma
amod<                   ancestor     1.93
appos<nsubj<            know         1.13
case>                   '           -1.60
                        by          -1.00
                        from        -2.73
                        of          -1.32
compound<amod>compound> New         -3.01
compound<obl>case>      in           3.32
compound>det>           the          1.76
obl<                    faster      -1.29
book_cl_elong
                                    effect        Dx  N      eff2  \
arcpath                 lemma
case>                   by       -0.510827 -0.000188  1  0.260945
compound<amod>compound> New      -0.505260  0.000420  3  0.255288
case>                   '        -0.500485 -0.000025  1  0.250486
obl<                    faster   -0.495693  0.000109  1  0.245711
compound<obl>case>      in        0.491829  0.000269  3  0.241896
appos<nsubj<            know      0.488055  0.000072  1  0.238198
case>                   from     -0.486546 -0.000248  2  0.236727
amod<                   ancestor  0.482595  0.000112  1  0.232898
compound>det>           the       0.475260 -0.000031  1  0.225872
case>                   of       -0.470150 -0.001101  5  0.221041

                                  test_pvalue  test_dX  test_Nx  test_N  \
arcpath                 lemma
case>                   by            0.31667   -0.312        1    4977
compound<amod>compound> New           0.00259   -0.543        3    4977
case>                   '             0.10964   -0.499        1    4977
obl<                    faster        0.19561   -0.404        1    4977
compound<obl>case>      in            0.00090    0.598        3    4977
appos<nsubj<            know          0.25770    0.353        1    4977
case>                   from          0.00637   -0.602        2    4977
amod<                   ancestor      0.05373    0.602        1    4977
compound>det>           the           0.07786    0.550        1    4977
case>                   of            0.18844   -0.184        5    4977

                                  test_st
arcpath                 lemma
case>                   by          -1.00
compound<amod>compound> New         -3.01
case>                   '           -1.60
obl<                    faster      -1.29
compound<obl>case>      in           3.32
appos<nsubj<            know         1.13
case>                   from        -2.73
amod<                   ancestor     1.93
compound>det>           the          1.76
case>                   of          -1.32
cluster ====> 9
np.sqrt(eigvals)
[0.30353631 0.345954   0.396395   0.43736354 0.52339409 0.56222388
 0.65377211 1.12025514]
cl_elong_a, cl_elong_v.round(2)
1.713525424709587 [-0.21 -0.68  0.11 -0.05  0.32 -0.22  0.56  0.1 ]
cluster data sample, mean shift
(3568, 8)                                0         1         2         3         4  \
token_id
Ven-77c9_98_spiders-11 -0.621606  0.273435 -1.027286 -0.506160  0.398718
Ham-9078_102_sharks-13 -0.747557  0.348512  0.793292 -0.776677 -0.036912
Tem-c190_7_grass-8      0.076040 -0.490749  0.049003  0.493601 -0.065963

                               5         6         7
token_id
Ven-77c9_98_spiders-11  0.812917  0.325841 -0.603618
Ham-9078_102_sharks-13  0.142350 -0.168807 -0.186372
Tem-c190_7_grass-8     -0.306867  0.076602 -0.664752
cluster data elongation along main axis
                             effect        Dx  N      eff2
arcpath         lemma
acl:relcl>      feed       0.620571 -0.000006  1  0.385109
                prefer     0.589457  0.000046  1  0.347459
conj<nmod<obj<  affect     0.566015  0.000176  2  0.320373
conj<conj>      pronghorn  0.560752  0.000094  7  0.314443
conj<nmod<obj<  consume    0.557279  0.000450  6  0.310560
conj<conj>      otter      0.554990 -0.000037  8  0.308014
conj<parataxis< p         -0.541683  0.000176  2  0.293421
conj<conj>      saiga      0.540976  0.000063  1  0.292655
                waterfowl  0.540158  0.000378  6  0.291771
                live       0.539369  0.000126  2  0.290919
Compute the feature-associated token x1 positions (ftok) on the projected axis
ftok
                                                token         x
arcpath         lemma
acl:relcl>      feed          Sta-6168_253_urchins-35  0.555834
                prefer        Amb-94f9_196_animals-20 -0.573902
conj<conj>      live           Rat-4b67_26_lizards-14  1.481620
                live        Spi-b4d6_31_tarantulas-11  0.248113
                otter           Ani-2170_339_bears-16  1.840729
                otter       Ani-2170_339_mongooses-23  1.306795
                otter           Bea-4f7a_225_minks-12  0.397730
                otter        Com-6e0a_211_raccoons-21  0.807866
                otter            Com-9711_199_dogs-25 -0.212539
                otter            Eur-3a81_48_shrew-18  0.544598
                otter           Gia-d1de_31_whales-14 -0.275792
                otter        Wea-8e57_5_wolverines-16  0.118141
                pronghorn        Coy-1bf1_262_deer-28  0.662897
                pronghorn         Coy-1bf1_262_elk-24  1.336042
                pronghorn       Coy-1bf1_280_sheep-25  0.637732
                pronghorn    Cro-5646_326_reindeer-30  1.745301
                pronghorn         Pra-7b55_12_deer-13 -0.142029
                pronghorn        Pra-7b55_154_deer-14 -0.162034
                pronghorn     Tho-fdaf_7_springbok-22  0.684183
                saiga            Tem-2c3b_12_Saiga-26 -0.083232
                waterfowl   Mar-4677_25_amphibians-12  1.103392
                waterfowl    Mar-4677_9_amphibians-12  1.103392
                waterfowl      Sho-489b_120_rodents-9  1.725017
                waterfowl  Sno-0a8f_396_shorebirds-20  1.213909
                waterfowl     Spa-e46a_15_seagulls-22  1.711624
                waterfowl   Spa-e46a_15_shorebirds-20  1.645897
conj<nmod<obj<  affect        Eur-fd2f_77_blackcap-15 -0.019438
                affect       Gar-8d9c_164_blackcap-15 -0.019438
                consume    Bar-2af9_129_angiosperms-9 -0.292091
                consume           Coc-9207_9_fungi-13 -0.287177
                consume       Coy-1bf1_292_beetles-14 -0.165176
                consume      Sir-1b7d_15_jellyfish-17 -0.037570
                consume           Tar-bf27_80_bats-16  1.431062
                consume          Tar-bf27_80_birds-18  1.351675
conj<parataxis< p                    Can-3366_38_m-58 -0.467009
                p                   Can-f359_107_m-58 -0.467009
Evaluate the feature-associated token positions on the projected axis
Compare to the group of tokens not associated with the feature (X0)
feat_index (10,)
token_elong (3568,)
ftok (36, 2)
x0 token_id
Ven-77c9_98_spiders-11         -0.082827
Ham-9078_102_sharks-13         -0.110718
Tem-c190_7_grass-8              0.323520
All-826a_2_Asparagales-15      -0.564511
Bea-4f7a_139_human-8            1.044538
                                  ...
Eur-9931_183_deer-10            0.261543
Com-a9dd_104_sparrowhawks-24   -0.927369
Mal-71cc_108_dragonflies-25     1.056200
Eur-d570_83_dandelions-26       1.585324
Ter-7888_134_gulls-24           0.087879
Name: x, Length: 3567, dtype: float64
x0 token_id
Ven-77c9_98_spiders-11         -0.082827
Ham-9078_102_sharks-13         -0.110718
Tem-c190_7_grass-8              0.323520
All-826a_2_Asparagales-15      -0.564511
Bea-4f7a_139_human-8            1.044538
                                  ...
Eur-9931_183_deer-10            0.261543
Com-a9dd_104_sparrowhawks-24   -0.927369
Mal-71cc_108_dragonflies-25     1.056200
Eur-d570_83_dandelions-26       1.585324
Ter-7888_134_gulls-24           0.087879
Name: x, Length: 3567, dtype: float64
x0 token_id
Ven-77c9_98_spiders-11         -0.082827
Ham-9078_102_sharks-13         -0.110718
Tem-c190_7_grass-8              0.323520
All-826a_2_Asparagales-15      -0.564511
Bea-4f7a_139_human-8            1.044538
                                  ...
Eur-9931_183_deer-10            0.261543
Com-a9dd_104_sparrowhawks-24   -0.927369
Mal-71cc_108_dragonflies-25     1.056200
Eur-d570_83_dandelions-26       1.585324
Ter-7888_134_gulls-24           0.087879
Name: x, Length: 3566, dtype: float64
x0 token_id
Ven-77c9_98_spiders-11         -0.082827
Ham-9078_102_sharks-13         -0.110718
Tem-c190_7_grass-8              0.323520
All-826a_2_Asparagales-15      -0.564511
Bea-4f7a_139_human-8            1.044538
                                  ...
Eur-9931_183_deer-10            0.261543
Com-a9dd_104_sparrowhawks-24   -0.927369
Mal-71cc_108_dragonflies-25     1.056200
Eur-d570_83_dandelions-26       1.585324
Ter-7888_134_gulls-24           0.087879
Name: x, Length: 3560, dtype: float64
x0 token_id
Ven-77c9_98_spiders-11         -0.082827
Ham-9078_102_sharks-13         -0.110718
Tem-c190_7_grass-8              0.323520
All-826a_2_Asparagales-15      -0.564511
Bea-4f7a_139_human-8            1.044538
                                  ...
Eur-9931_183_deer-10            0.261543
Com-a9dd_104_sparrowhawks-24   -0.927369
Mal-71cc_108_dragonflies-25     1.056200
Eur-d570_83_dandelions-26       1.585324
Ter-7888_134_gulls-24           0.087879
Name: x, Length: 3561, dtype: float64
x0 token_id
Ven-77c9_98_spiders-11         -0.082827
Ham-9078_102_sharks-13         -0.110718
Tem-c190_7_grass-8              0.323520
All-826a_2_Asparagales-15      -0.564511
Bea-4f7a_139_human-8            1.044538
                                  ...
Eur-9931_183_deer-10            0.261543
Com-a9dd_104_sparrowhawks-24   -0.927369
Mal-71cc_108_dragonflies-25     1.056200
Eur-d570_83_dandelions-26       1.585324
Ter-7888_134_gulls-24           0.087879
Name: x, Length: 3567, dtype: float64
x0 token_id
Ven-77c9_98_spiders-11         -0.082827
Ham-9078_102_sharks-13         -0.110718
Tem-c190_7_grass-8              0.323520
All-826a_2_Asparagales-15      -0.564511
Bea-4f7a_139_human-8            1.044538
                                  ...
Eur-9931_183_deer-10            0.261543
Com-a9dd_104_sparrowhawks-24   -0.927369
Mal-71cc_108_dragonflies-25     1.056200
Eur-d570_83_dandelions-26       1.585324
Ter-7888_134_gulls-24           0.087879
Name: x, Length: 3562, dtype: float64
x0 token_id
Ven-77c9_98_spiders-11         -0.082827
Ham-9078_102_sharks-13         -0.110718
Tem-c190_7_grass-8              0.323520
All-826a_2_Asparagales-15      -0.564511
Bea-4f7a_139_human-8            1.044538
                                  ...
Eur-9931_183_deer-10            0.261543
Com-a9dd_104_sparrowhawks-24   -0.927369
Mal-71cc_108_dragonflies-25     1.056200
Eur-d570_83_dandelions-26       1.585324
Ter-7888_134_gulls-24           0.087879
Name: x, Length: 3566, dtype: float64
x0 token_id
Ven-77c9_98_spiders-11         -0.082827
Ham-9078_102_sharks-13         -0.110718
Tem-c190_7_grass-8              0.323520
All-826a_2_Asparagales-15      -0.564511
Bea-4f7a_139_human-8            1.044538
                                  ...
Eur-9931_183_deer-10            0.261543
Com-a9dd_104_sparrowhawks-24   -0.927369
Mal-71cc_108_dragonflies-25     1.056200
Eur-d570_83_dandelions-26       1.585324
Ter-7888_134_gulls-24           0.087879
Name: x, Length: 3562, dtype: float64
x0 token_id
Ven-77c9_98_spiders-11         -0.082827
Ham-9078_102_sharks-13         -0.110718
Tem-c190_7_grass-8              0.323520
All-826a_2_Asparagales-15      -0.564511
Bea-4f7a_139_human-8            1.044538
                                  ...
Eur-9931_183_deer-10            0.261543
Com-a9dd_104_sparrowhawks-24   -0.927369
Mal-71cc_108_dragonflies-25     1.056200
Eur-d570_83_dandelions-26       1.585324
Ter-7888_134_gulls-24           0.087879
Name: x, Length: 3566, dtype: float64
Spearman results
feat_tests
                           test_pvalue  test_dX  test_Nx  test_N  test_st
arcpath         lemma
acl:relcl>      feed           0.44680    0.552        1    3568     0.76
                prefer         0.42644   -0.578        1    3568    -0.80
conj<conj>      live           0.09328    0.862        2    3568     1.68
                otter          0.02824    0.564        8    3568     2.19
                pronghorn      0.01353    0.678        7    3568     2.47
                saiga          0.90491   -0.087        1    3568    -0.12
                waterfowl      0.00000    1.416        6    3568     4.79
conj<nmod<obj<  affect         0.96435   -0.023        2    3568    -0.04
                consume        0.26526    0.331        6    3568     1.11
conj<parataxis< p              0.35932   -0.471        2    3568    -0.92
book_cl_elong
                             effect        Dx  N      eff2  test_pvalue  \
arcpath         lemma
acl:relcl>      feed       0.620571 -0.000006  1  0.385109      0.44680
conj<conj>      pronghorn  0.560752  0.000094  7  0.314443      0.01353
conj<nmod<obj<  consume    0.557279  0.000450  6  0.310560      0.26526
conj<conj>      otter      0.554990 -0.000037  8  0.308014      0.02824
conj<parataxis< p         -0.541683  0.000176  2  0.293421      0.35932
conj<conj>      waterfowl  0.540158  0.000378  6  0.291771      0.00000
                live       0.539369  0.000126  2  0.290919      0.09328

                           test_dX  test_Nx  test_N  test_st
arcpath         lemma
acl:relcl>      feed         0.552        1    3568     0.76
conj<conj>      pronghorn    0.678        7    3568     2.47
conj<nmod<obj<  consume      0.331        6    3568     1.11
conj<conj>      otter        0.564        8    3568     2.19
conj<parataxis< p           -0.471        2    3568    -0.92
conj<conj>      waterfowl    1.416        6    3568     4.79
                live         0.862        2    3568     1.68
===========  end ==============

/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/home/seppo/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

In [361]:
cresTax['C1']

{'cl_elong_a': 2.2333079518709735,
 'cl_elong_v': array([ 0.55751149,  0.06348049,  0.78398189, -0.21571017,  0.04214997,
        -0.09931228, -0.10830427,  0.02496623]),
 'cl_elong_var': 7.8649476230195035,
 'cl_mean': array([ 0.88280341,  0.55957607, -0.31770235,  0.4087019 , -0.26105165,
         0.39534534, -0.19086827,  0.47535111]),
 'cl_ica_data':                                     0         1         2         3         4  \
 token_id
 Tru-f072_21_animals-7        0.968425 -3.946513 -0.182949  1.656552  1.416039
 Din-756f_27_Dinosauria-7     0.259754 -2.546674  0.521633  0.218453  0.434535
 Sca-9161_30_Animals-1        0.173958 -2.289524  0.608234  0.203571  0.506868
 Hor-ab9c_225_bat-8          -0.556522 -1.916160  0.564865 -0.502813  0.630258
 Dun-cad0_87_beetles-3        0.858886 -3.028922  0.490710 -1.067172 -0.262849
 ...                               ...       ...       ...       ...       ...
 Cam-4bd8_61_cephalopods-10   0.359986  0.909587 -1.023907 -0.083387 -0.063589
 Min-e696_18_Mustela-14       0.387402  0.520472 -0.919324  0.019191 -0.550325
 Bir-154b_12_Paradisaeidae-3 -0.223904 -2.712178  0.285865 -1.820382 -0.037162
 Bov-d455_139_plant-16        0.139552  0.891270 -0.405580  0.822045  0.471916
 Com-0bc9_123_mammals-30      0.704568  0.925819  0.995335  0.341130 -0.084090

                                     5         6         7
 token_id
 Tru-f072_21_animals-7        0.870430 -0.665120  0.560448
 Din-756f_27_Dinosauria-7     0.999972 -0.221918 -0.319033
 Sca-9161_30_Animals-1       -0.306838  0.046482  0.096311
 Hor-ab9c_225_bat-8           0.237448  0.063330  0.301439
 Dun-cad0_87_beetles-3        0.848392 -0.150754  0.255089
 ...                               ...       ...       ...
 Cam-4bd8_61_cephalopods-10  -0.513951  0.202656  0.155605
 Min-e696_18_Mustela-14      -0.582286  0.372178  0.282493
 Bir-154b_12_Paradisaeidae-3  1.052473 -0.362566  0.168738
 Bov-d455_139_plant-16       -0.561020  0.235888 -0.473080
 Com-0bc9_123_mammals-30     -1.125858  0.668344  0.535614

 [199 rows x 8 columns],
 'cl_feat_elong_top':                         effect        Dx   N      eff2
 arcpath    lemma
 cc>        and       -0.751177  0.002718  13  0.564267
 nmod>case> of         0.729722  0.004417   8  0.532494
 nmod>      Hewitson   0.725210  0.001158   1  0.525929
 nsubj<     order      0.717932  0.001071   1  0.515427
 nmod>case> in         0.702984  0.005788   9  0.494187
 cc>        as        -0.698172  0.002902   3  0.487444
 nmod>case> for        0.674864  0.004620   4  0.455442
 nmod>      Boisduval  0.672279  0.001131   1  0.451959
 nmod>case> with       0.668601  0.002075   4  0.447027
            as         0.662159  0.000889   1  0.438454,
 'book_cl_elong':                         effect        Dx   N      eff2  test_pvalue  test_dX  \
 arcpath    lemma
 cc>        and       -0.751177  0.002718  13  0.564267      0.03505   -0.631
 nmod>case> of         0.729722  0.004417   8  0.532494      0.20712    0.477
 nmod>      Hewitson   0.725210  0.001158   1  0.525929      0.25272    1.202
 nsubj<     order      0.717932  0.001071   1  0.515427      0.40541    0.875
 nmod>case> in         0.702984  0.005788   9  0.494187      0.48678    0.249
 cc>        as        -0.698172  0.002902   3  0.487444      0.44919   -0.462
 nmod>      Boisduval  0.672279  0.001131   1  0.451959      0.30727    1.073
 nmod>case> with       0.668601  0.002075   4  0.447027      0.32006    0.527
            as         0.662159  0.000889   1  0.438454      0.30989    1.068

                       test_Nx  test_N  test_st
 arcpath    lemma
 cc>        and             13     199    -2.12
 nmod>case> of               8     199     1.27
 nmod>      Hewitson         1     199     1.15
 nsubj<     order            1     199     0.83
 nmod>case> in               9     199     0.70
 cc>        as               3     199    -0.76
 nmod>      Boisduval        1     199     1.02
 nmod>case> with             4     199     1.00
            as               1     199     1.02  ,
 'token_elong': token_id
 Tru-f072_21_animals-7         -0.152113
 Din-756f_27_Dinosauria-7       0.280056
 Sca-9161_30_Animals-1          0.433783
 Hor-ab9c_225_bat-8             0.123050
 Dun-cad0_87_beetles-3          0.828830
                                  ...
 Cam-4bd8_61_cephalopods-10    -0.496002
 Min-e696_18_Mustela-14        -0.474476
 Bir-154b_12_Paradisaeidae-3    0.257179
 Bov-d455_139_plant-16         -0.322662
 Com-0bc9_123_mammals-30        1.207571
 Name: x, Length: 199, dtype: float64}

In [367]:
def cleanlatex(df, screen=True):
    s = df.reset_index().to_latex(index=False).replace('<','< ').replace('>','> ').\
          replace('0000 & ',' & ').replace('000 & ',' & ').replace('0000 \\',' \\').replace('000 \\',' \\')
    if screen:
        print(s)
        return
    return s

In [362]:
res = cresAda # take  data

In [369]:
res = cresLoc # take  data

In [375]:
res = cresTax # take  data

In [381]:
res = cresTop # take  data

In [382]:
n_df = pd.DataFrame(
    {'Nfeat':res['clust_featdx_df'].groupby(['arcpath','lemma']).N.sum(),
     'Nclust':res['clust_featdx_df'].reset_index().groupby(['arcpath','lemma']).cluster.count()})

n_df = n_df[(n_df.Nclust>2)|(n_df.Nfeat>=10)]


dx_eval = res['clust_featdx_df'].merge(n_df,left_index=True, right_index=True)
sc_eval = res['score_pvalue'].iloc[:,2:4].merge(n_df,left_index=True, right_index=True)
cd_eval = res['cos_pvalue'].iloc[:,0:2].merge(n_df,left_index=True, right_index=True)

dx_eval = dx_eval.sort_values(by=['Dx','Nclust'],ascending=False)
dx_eval = dx_eval.groupby(['cluster']).head(3)
dx_eval = dx_eval.groupby(['lemma']).head(1).drop(columns=['N'])
sc_eval = sc_eval.groupby(['lemma']).head(1).rename(columns={'score_pvalue':'p-value','score_stat':'log-likelihood Rho'})
cd_eval = cd_eval.groupby(['lemma']).head(1).rename(columns={'cos_pvalue':'p-value','cos_stat':'cosine Rho'})

dx_eval = dx_eval.sort_values(by='Dx',ascending=False).head(10)
sc_eval = sc_eval.sort_values(by='p-value').head(10)
cd_eval = cd_eval.sort_values(by='p-value').head(10)

In [383]:
dx_eval

                                            Dx  Nfeat  Nclust
arcpath          lemma       cluster
case>            of          5        0.158360   4186       8
cc>              and         9        0.123504   2902       8
appos>           description 3        0.097598    144       3
nmod<det>        the         5        0.089275   2094       6
appos>           reference   3        0.072228     83       3
                 Taxonomy    3        0.066884     92       4
nsubj<cop>       be          4        0.053416   2413       9
nmod<det>        a           5        0.032987    951       8
conj<case>fixed> as          9        0.031931    619       5
conj<obj<        include     7        0.012131    581       7

In [384]:
sc_eval

                        log-likelihood Rho   p-value  Nfeat  Nclust
arcpath          lemma
det>             a                0.869175  0.001091   1446       9
case>            from             0.869175  0.001091    366       9
                 as               0.860915  0.001379    508       7
                 to               0.860915  0.001379    780       6
                 's               0.859276  0.001443    427       8
obl<nsubj>det>   the              0.857382  0.001518    325       5
case>            of               0.827916  0.003100   4186       8
                 with             0.822581  0.003479    578       6
acl:relcl>nsubj> that             0.812897  0.004249    280       9
case>            for              0.769126  0.009307    488       9

In [385]:
cd_eval

                         cosine Rho   p-value  Nfeat  Nclust
arcpath         lemma
case>           like       0.863226  0.001294    327       8
case>fixed>     as         0.852825  0.001712    703       7
case>           with       0.844162  0.002128    578       6
nmod>case>      in         0.842424  0.002220    681       9
case>           from       0.842424  0.002220    366       9
                for        0.793939  0.006100    488       9
det>            some       0.790277  0.006514    277       8
case>           of         0.765961  0.009787   4186       8
conj<conj>amod> other      0.730554  0.016409    245       5
conj<case>      include    0.689617  0.027350    302       4

In [386]:
cleanlatex(dx_eval)
cleanlatex(sc_eval)
cleanlatex(cd_eval)

\begin{tabular}{llrrrr}
\toprule
arcpath & lemma & cluster & Dx & Nfeat & Nclust \\
\midrule
case>  & of & 5 & 0.158360 & 4186 & 8 \\
cc>  & and & 9 & 0.123504 & 2902 & 8 \\
appos>  & description & 3 & 0.097598 & 144 & 3 \\
nmod< det>  & the & 5 & 0.089275 & 2094 & 6 \\
appos>  & reference & 3 & 0.072228 & 83 & 3 \\
appos>  & Taxonomy & 3 & 0.066884 & 92 & 4 \\
nsubj< cop>  & be & 4 & 0.053416 & 2413 & 9 \\
nmod< det>  & a & 5 & 0.032987 & 951 & 8 \\
conj< case> fixed>  & as & 9 & 0.031931 & 619 & 5 \\
conj< obj<  & include & 7 & 0.012131 & 581 & 7 \\
\bottomrule
\end{tabular}

\begin{tabular}{llrrrr}
\toprule
arcpath & lemma & log-likelihood Rho & p-value & Nfeat & Nclust \\
\midrule
det>  & a & 0.869175 & 0.001091 & 1446 & 9 \\
case>  & from & 0.869175 & 0.001091 & 366 & 9 \\
case>  & as & 0.860915 & 0.001379 & 508 & 7 \\
case>  & to & 0.860915 & 0.001379 & 780 & 6 \\
case>  & 's & 0.859276 & 0.001443 & 427 & 8 \\
obl< nsubj> det>  & the & 0.857382 & 0.001518 & 325 & 5 \\
case>  & of & 0.827916 & 0.003100 & 4186 & 8 \\
case>  & with & 0.822581 & 0.003479 & 578 & 6 \\
acl:relcl> nsubj>  & that & 0.812897 & 0.004249 & 280 & 9 \\
case>  & for & 0.769126 & 0.009307 & 488 & 9 \\
\bottomrule
\end{tabular}

\begin{tabular}{llrrrr}
\toprule
arcpath & lemma & cosine Rho & p-value & Nfeat & Nclust \\
\midrule
case>  & like & 0.863226 & 0.001294 & 327 & 8 \\
case> fixed>  & as & 0.852825 & 0.001712 & 703 & 7 \\
case>  & with & 0.844162 & 0.002128 & 578 & 6 \\
nmod> case>  & in & 0.842424 & 0.002220 & 681 & 9 \\
case>  & from & 0.842424 & 0.002220 & 366 & 9 \\
case>  & for & 0.793939 & 0.006100 & 488 & 9 \\
det>  & some & 0.790277 & 0.006514 & 277 & 8 \\
case>  & of & 0.765961 & 0.009787 & 4186 & 8 \\
conj< conj> amod>  & other & 0.730554 & 0.016409 & 245 & 5 \\
conj< case>  & include & 0.689617 & 0.027350 & 302 & 4 \\
\bottomrule
\end{tabular}

In [111]:
feat_freq_df.loc['topic','case>','by']

count    557
Name: (topic, case>, by), dtype: int64

In [112]:
clust_featdx_df=cresTop['clust_featdx_df']
clust_featdx_df.reset_index(0).sort_index().loc['case>','by']

               cluster        Dx    N
arcpath lemma
case>   by           0  0.009342  270
        by           1  0.001265   95
        by           4 -0.000515   18
        by           5  0.004931  142
        by           6 -0.000273   27
        by           7 -0.000228    2

In [ ]:
#len(tf_df.loc['topic'].reset_index().set_index(['arcpath','lemma']).loc['case>','by'].token.unique())

True

In [ ]:
from matplotlib import pyplot as plt
#plt.plot(list(bdf.Dx),list(bdf.score_pvalue),'o')
#plt.plot(list(bdf.Dx),list(bdf.cos_pvalue),'*')
#plt.plot(list(bdf.Dx),list(bdf.cos_stat),'.')
#plt.plot(list(bdf.Dx),list(bdf.score_stat),'.')
#plt.plot(list(bdf.score_pvalue),list(bdf.cos_pvalue),'.')
#plt.plot(list(cdf.effect),list(cdf.test_st),'o')
#plt.plot(list(cdf.test_N),list(cdf.test_pvalue),'.')

In [319]:
cresTax['C1']['cl_elong_var']

7.8649476230195035

In [320]:
df   = cresTax['C1']['book_cl_elong']
evar = cresTax['C1']['cl_elong_var']

# Effective variance: effect step^2 * Bernoulli variance. (Var[X] = p*(1-p))

df['p']=df['test_Nx']/df['test_N']
df['np']=1-df['p']
df['eff_var']=df['eff2']*df['p']*df['np'] 
df

                        effect        Dx   N      eff2  test_pvalue  test_dX  \
arcpath    lemma
cc>        and       -0.751177  0.002718  13  0.564267      0.03505   -0.631
nmod>case> of         0.729722  0.004417   8  0.532494      0.20712    0.477
nmod>      Hewitson   0.725210  0.001158   1  0.525929      0.25272    1.202
nsubj<     order      0.717932  0.001071   1  0.515427      0.40541    0.875
nmod>case> in         0.702984  0.005788   9  0.494187      0.48678    0.249
cc>        as        -0.698172  0.002902   3  0.487444      0.44919   -0.462
nmod>      Boisduval  0.672279  0.001131   1  0.451959      0.30727    1.073
nmod>case> with       0.668601  0.002075   4  0.447027      0.32006    0.527
           as         0.662159  0.000889   1  0.438454      0.30989    1.068

                      test_Nx  test_N  test_st         p        np   eff_var
arcpath    lemma
cc>        and             13     199    -2.12  0.065327  0.934673  0.034454
nmod>case> of               8     199     1.27  0.040201  0.959799  0.020546
nmod>      Hewitson         1     199     1.15  0.005025  0.994975  0.002630
nsubj<     order            1     199     0.83  0.005025  0.994975  0.002577
nmod>case> in               9     199     0.70  0.045226  0.954774  0.021339
cc>        as               3     199    -0.76  0.015075  0.984925  0.007238
nmod>      Boisduval        1     199     1.02  0.005025  0.994975  0.002260
nmod>case> with             4     199     1.00  0.020101  0.979899  0.008805
           as               1     199     1.02  0.005025  0.994975  0.002192

In [327]:
def cres_clean(cres):
    
    cdf = pd.concat(
        [cres['C%d'%i]['book_cl_elong'].sort_values(by='test_pvalue').assign(cluster=i) for i in range(10) if 'C%d'%i in cres.keys()]
    ).sort_values('test_pvalue')
    cdf=cdf[cdf.test_pvalue<.1]
    cdf=cdf.groupby('lemma').head(1)
    cdf=cdf.groupby('arcpath').head(2)
    cdf['eff ratio']=(cdf['effect']/cdf['test_dX']).round(2)
    
    # Effective variance: effect step^2 * Bernoulli variance. (Var[X] = p*(1-p))
    
    cdf['p']=cdf['test_Nx']/cdf['test_N']
    cdf['np']=1-cdf['p']
    cdf['eff var']=cdf['eff2']*cdf['p']*cdf['np']     
    
    cdf=cdf[['cluster', 'test_Nx', 'test_N',   'test_pvalue', 'test_st',  'eff var', 'eff ratio']]
    cdf.columns=['cl. id', 'Nfeat', 'cl. size',   't test p-value','t test stat', 'eff var', 'eff ratio']
    cdf.sort_values(by='eff var',ascending=False,inplace=True)
    
    return cdf.head(5).sort_values(by=['cl. id'])
    
    #return pd.concat([df for (c,df) in cdf.head(5).groupby('cl. id')])

In [359]:
sets = {'Adaptation':cresAda,
        'Location':cresLoc,
        'Taxon group':cresTax,
        'Topic':cresTop
       }

for title,cdf in sets.items():
    cdf = cres_clean(cdf)
    print("{\\bf       %s }\n"%title)
    cleanlatex(cdf)

{\bf       Adaptation }

\begin{tabular}{llrrrrrrr}
\toprule
arcpath & lemma & cl. id & Nfeat & cl. size & t test p-value & t test stat & eff var & eff ratio \\
\midrule
nmod> case>  & of & 0 & 7 & 114 & 0.00 & 5.18 & 0.036141 & 0.48 \\
nmod> case>  & such & 0 & 3 & 114 & 0.002880 & 3.05 & 0.014053 & 0.47 \\
cc>  & or & 6 & 14 & 592 & 0.000020 & 4.35 & 0.007815 & 0.96 \\
amod>  & other & 8 & 8 & 287 & 0.00 & -5.02 & 0.013205 & 0.71 \\
conj>  & feed & 9 & 5 & 284 & 0.000390 & -3.59 & 0.013245 & 0.37 \\
\bottomrule
\end{tabular}

{\bf       Location }

\begin{tabular}{llrrrrrrr}
\toprule
arcpath & lemma & cl. id & Nfeat & cl. size & t test p-value & t test stat & eff var & eff ratio \\
\midrule
det>  & the & 4 & 7 & 13 & 0.088610 & -1.87 & 0.145010 & 0.38 \\
compound<  & locust & 7 & 21 & 298 & 0.00 & 6.24 & 0.011691 & 0.89 \\
conj>  & marsh & 8 & 13 & 197 & 0.00 & 6.63 & 0.050478 & 0.29 \\
conj>  & grassland & 8 & 5 & 197 & 0.000310 & 3.68 & 0.020155 & 0.30 \\
nsubj:pass< aux:pass>  & be & 9 & 8 & 36 & 0.037910 & 2.16 & 0.010977 & 0.50 \\
\bottomrule
\end{tabular}

{\bf       Taxon group }

\begin{tabular}{llrrrrrrr}
\toprule
arcpath & lemma & cl. id & Nfeat & cl. size & t test p-value & t test stat & eff var & eff ratio \\
\midrule
conj> cc>  & and & 2 & 277 & 2280 & 0.00 & -17.13 & 0.036466 & 0.52 \\
list< list> compound>  & Guinean & 5 & 4 & 5 & 0.015150 & -5.03 & 0.012449 & 0.53 \\
nmod> case>  & in & 7 & 10 & 128 & 0.00 & -4.82 & 0.032643 & 0.18 \\
nmod> case>  & to & 7 & 6 & 128 & 0.000220 & -3.81 & 0.020633 & 0.17 \\
det>  & a & 9 & 63 & 2384 & 0.000020 & -4.23 & 0.021871 & 2.15 \\
\bottomrule
\end{tabular}

{\bf       Topic }

\begin{tabular}{llrrrrrrr}
\toprule
arcpath & lemma & cl. id & Nfeat & cl. size & t test p-value & t test stat & eff var & eff ratio \\
\midrule
amod>  & large & 4 & 42 & 8870 & 0.00 & 6.09 & 0.003613 & 1.59 \\
amod>  & most & 4 & 40 & 8870 & 0.00 & 7.86 & 0.003605 & 1.23 \\
conj>  & hare & 6 & 18 & 2245 & 0.00 & -9.56 & 0.007340 & 0.21 \\
conj>  & carrion & 6 & 14 & 2245 & 0.00 & -9.81 & 0.005482 & 0.18 \\
nmod> case>  & such & 7 & 26 & 1889 & 0.00 & -6.39 & 0.005787 & 0.46 \\
\bottomrule
\end{tabular}

In [340]:
cres_clean(cresAda)

                  cl. id  Nfeat  cl. size  t test p-value  t test stat  \
arcpath    lemma
nmod>case> of          0      7       114         0.00000         5.18
           such        0      3       114         0.00288         3.05
cc>        or          6     14       592         0.00002         4.35
amod>      other       8      8       287         0.00000        -5.02
conj>      feed        9      5       284         0.00039        -3.59

                   eff var  eff ratio
arcpath    lemma
nmod>case> of     0.036141       0.48
           such   0.014053       0.47
cc>        or     0.007815       0.96
amod>      other  0.013205       0.71
conj>      feed   0.013245       0.37

In [341]:
cres_clean(cresLoc)

                                cl. id  Nfeat  cl. size  t test p-value  \
arcpath              lemma
det>                 the             4      7        13         0.08861
compound<            locust          7     21       298         0.00000
conj>                marsh           8     13       197         0.00000
                     grassland       8      5       197         0.00031
nsubj:pass<aux:pass> be              9      8        36         0.03791

                                t test stat   eff var  eff ratio
arcpath              lemma
det>                 the              -1.87  0.145010       0.38
compound<            locust            6.24  0.011691       0.89
conj>                marsh             6.63  0.050478       0.29
                     grassland         3.68  0.020155       0.30
nsubj:pass<aux:pass> be                2.16  0.010977       0.50

In [342]:
cres_clean(cresTax)

                             cl. id  Nfeat  cl. size  t test p-value  \
arcpath             lemma
conj>cc>            and           2    277      2280         0.00000
list<list>compound> Guinean       5      4         5         0.01515
nmod>case>          in            7     10       128         0.00000
                    to            7      6       128         0.00022
det>                a             9     63      2384         0.00002

                             t test stat   eff var  eff ratio
arcpath             lemma
conj>cc>            and           -17.13  0.036466       0.52
list<list>compound> Guinean        -5.03  0.012449       0.53
nmod>case>          in             -4.82  0.032643       0.18
                    to             -3.81  0.020633       0.17
det>                a              -4.23  0.021871       2.15

In [343]:
cres_clean(cresTop)

                    cl. id  Nfeat  cl. size  t test p-value  t test stat  \
arcpath    lemma
amod>      large         4     42      8870             0.0         6.09
           most          4     40      8870             0.0         7.86
conj>      hare          6     18      2245             0.0        -9.56
           carrion       6     14      2245             0.0        -9.81
nmod>case> such          7     26      1889             0.0        -6.39

                     eff var  eff ratio
arcpath    lemma
amod>      large    0.003613       1.59
           most     0.003605       1.23
conj>      hare     0.007340       0.21
           carrion  0.005482       0.18
nmod>case> such     0.005787       0.46